### ISSUE TITLE
Question about setting custom agent states

### ISSUE THREAD

**Issue by aguecida** [amazon-connect/amazon-connect-streams#101]
The documentation for `agent.setState()` gives a simple example for setting an agent to the routable state (i.e. it assumes there is only one state of that type). In the case where a contact center configures multiple custom, non-routable agent states, what is the best way to programmatically select one of these custom states? There is an ARN in the state object, but I'm guessing that's not the best way to search for a state. That leaves the name of the state, but it doesn't seem like best practice to search for a state based on a display name.

Is there any unique ID that can be used to select a custom agent state, or is there any plan to add this in the future?

**Comment by jagadeeshaby** [comment]
I suggest go with the ARN as a ID approach. What it means is clients will have the hash of different state names vs the ARN list,  and while setting through Streams API, filter the getAgentStates result with the intended ARN and use setState to achieve the same. 

```

const AGENT_STATES = {
  coffe: "arn:aws:connect..... coffe",
  available: "arn:aws:connect...available" 
}

connect/agent-states/get-all

```

**Comment by jagadeeshaby** [comment]
I would suggest to go with the ARN as an ID approach (which is unique to the state). What it means is clients will have the hash of different state names vs the ARN list (you can always get this from ADMIN website - https://<<directory-alias>>.awsapps.com/connect/agent-states/get-all),  and while setting through Streams API, filter the getAgentStates result with the intended ARN and use setState to achieve the same. 

Frankly I don't see much benefit of adding an additional ID here,  as you still have to get the info about which custom state you want to move to. 

Would you mind providing the exact use case here like how will you determine which custom state to move to, is there any user interaction involved ?  - if so then you can always consider ARN as a ID and create the UI element and pass in the same for setting the state.

**Comment by aguecida** [comment]
The use case would be when implementing non-phone channels on top of Connect. Using email as an example, we provide the ability to set a channel to be uninterruptible by phone. This means while an agent is working on an email, they will not receive any phone calls. We achieve this by setting the agent's state to Not Routable when they start working on an email. There is no user interaction involved in this flow, but it is required for the business to configure this "uninterruptible" state in our application so we can do the programmatic state changing.

The reason I suggested an additional ID field for this purpose is because this is something that would normally be set by our customers through configuration (i.e. the customer needs to tell us what Connect state they want us to use as their uninterruptible email state). Therefore, a readable identifier that is available in a Connect admin UI would be ideal. Using the endpoint you provided above, the `code` property on the state object was what I was hoping would be made available in the APIs.

We'll definitely consider using the ARN as the ID. I also did some more investigation and realized that the name of the state is enforced to be unique by Connect, so I think that will be another option. Using the name would have an advantage over the ARN because it is available in the Connect admin UI.

**Comment by jagadeeshaby** [comment]
Only downside i see by using name is  - Name field is editable and it can change overtime (also think about localization- non english names, comparison problems )  so i would still suggest to go with ARN as an ID. 

As i mentioned earlier keeping the non routable hash would help . i see something like below snippet makes more sense. 
```
  const STATES =  {
     "coffe" : "arn:aws:connect:us-east-**",
     "email": "arn:aws:connect:us-east-**"
     "default": "arn:**"
   };

 if(AgentGoingToHandleEmail){
    setAgentState("email");
}

function setAgentState(type){
    const agentStateARN = STATES[type]  ||  STATES["default"]
    agent.setState(agent.getAgentStates().filter((state) => state.agentStateARN === agentStateARN)[0])
}

```

**Comment by ctwomblyamzn** [comment]
Hi aguecida@, I think that your question was answered by Jagadeesha. If not, please reopen this issue.
