### ISSUE TITLE
Getting Agent/Queue phone number

### ISSUE THREAD

**Issue by aguecida** [amazon-connect/amazon-connect-streams#104]
I am looking for a way to get the phone number that the customer dialed into (to be used for reporting purposes). What I've tried so far is to get the endpoint of the agent's connection, but the phone number field always seems to be empty (for both inbound and outbound calls). I also see that I am able to get the queue ARN of a contact, but it doesn't seem like there is a way to get the dialed number given the queue ARN.

Is there anyway this data can be retrieved?

**Comment by jagadeeshaby** [comment]
At this point we do not this data readily available on the Agent Side (Streams). as you observed we have only the Queue and Routing profile ARN details which in turn maps to multiple claimed phone number on the instance. 

Will discuss the possibilities of getting this value on the agent side internally and update it here.

**Comment by prosunshining** [comment]
@aguecida  As a trick in combination of Contact flow, I always add Dialed Number of system attribute as contact attribute in contact flow before routing calls to the queue/agent. Then extract dialed number from contact attributes. I hope there comes a direct way with this library later, but that's how I'm making it possible within contact flow and contact attributes.

**Comment by jagadeeshaby** [comment]
Yup that a feasible solution. thank you.

**Comment by CiscoKidxx** [comment]
I don't think you can get the phone numbers in an instance from the Connect API currently either. The Contact flow hack is helpful in some cases only.

**Comment by ijustwannanamewhyitissodifficult** [comment]
Any update on this one?

**Comment by wuzhen1228** [comment]
Any update on this one? T.T
