### ISSUE TITLE
Custom login issue

### ISSUE THREAD

**Issue by KaanBoz** [amazon-connect/amazon-connect-streams#106]
Hello,

I don't know if this is the place to ask this. Sorry if it is not. We are trying to implement amazon connect to our custom solution. The issue is streams is opening a login pop-up for login. Customer does not wants this way of logging in. They want a customized login screen Is there an api or a way for programatic login? Help will be much appreciated.

Thanks

**Comment by aguecida** [comment]
As far as I know there is no way to customize the Connect login screen. You have the option to configure Connect to authenticate against your own SAML identity provider. With this setup Connect will use your IdP's login page, and you can customize your login page if your IdP supports it. See the following link for more details:

https://docs.aws.amazon.com/connect/latest/adminguide/configure-saml.html

**Comment by RathoreKavita** [comment]
We currently don't support customized login screen. We've captured your feedback as a feature request for future.

**Comment by maxprime1** [comment]
Have there any updates for the custom agent login/logout through the streams API?
