### ISSUE TITLE
Agent State ARN not available through agent.getState method

### ISSUE THREAD

**Issue by aguecida** [amazon-connect/amazon-connect-streams#108]
When calling `agent.getState()`, the return object has an "agentStateARN" property, but the value is always null. The `agent.getAgentStates()` method on the other hand populates this property for each agent state. I can get around this temporarily by mapping the name I get from the `getState` object to one of the states returned by the `getAgentStates` method and then retrieving the matching ARN, but it would be nice to have access to the ARN directly from the return object of the `getState` method.

**Comment by ctwomblyamzn** [comment]
Hi aguecida@, we are tracking this on our end now.

**Comment by zxl634** [comment]
Any news?

**Comment by ctwomblyamzn** [comment]
Unfortunately, this has not been prioritized. It is in the team's backlog as of now.
