### ISSUE TITLE
AgentState documentation is inaccurate

### ISSUE THREAD

**Issue by aguecida** [amazon-connect/amazon-connect-streams#109]
When inspecting the result of the `agent.getState` and `agent.getAgentState` APIs, both return `AgentState` objects that have the following properties:

- `agentStateARN`
- `name`
- `startTimestamp`
- `type`

The documentation for these 2 methods does not match what is being returned.

`agent.getState`: https://github.com/aws/amazon-connect-streams/blob/master/Documentation.md#agentgetstate

`agent.getAgentStates`: https://github.com/aws/amazon-connect-streams/blob/master/Documentation.md#agentgetstate

Also, the `AgentState` interface in the type definition file (index.d.ts) is also incorrect. It currently contains the properties `name`, `type`, and `duration`.

**Comment by marcogrcr** [comment]
This is related to #108

**Comment by marcogrcr** [comment]
This has been addressed in #243
