### ISSUE TITLE
How to get called number (dnis) 

### ISSUE THREAD

**Issue by samurai8429** [amazon-connect/amazon-connect-streams#119]
Is there a way to get what number the customer called?
I want to get an incoming number (dnis)

**Comment by AzerinnD** [comment]
Not through the Streams API the last time I checked (they do sneak new things in every so often and this is something that has been requested); however, it is available in the contact flow.  So you could pull it during the contact flow before it gets routed to the agent (available in System->Dialed Number) and set it as a contact attribute via the set contact attribute node.

**Comment by ctwomblyamzn** [comment]
I believe this answers the question. Closing

**Comment by MAsad-Nawaz** [comment]
The contact's phone number without adding a custom attribute in the Contact Flow:
```
contact.onConnecting((c) => {
  const { phoneNumber } = c.getActiveInitialConnection()?.getEndpoint()
})
```
