### ISSUE TITLE
Feature Request: Pass an optional log name to getLogs().download()

### ISSUE THREAD

**Issue by AndrewFairbairn** [amazon-connect/amazon-connect-streams#122]
We have a custom softphone deployed to a call centre that has hundreds of agents.

We have added the ability for agents to download softphone logs so that they can be sent with us when issues are reported.

This has resulted in our developer team receiving multiple log files all named 'agent-log.txt'.

We would appreciate the ability to pass a string to the download() function so that we can more easily identify these logs. For instance we would like to save logs as 'agentName-Timestamp'

This would also mean that if an agent has multiple logs they will not have to navigate agent-log.txt, agent-log(1).txt, agent-log(2).txt etc etc

**Comment by bigsapper** [comment]
Is upvoting a "thing" on GitHub? 
Our org would take advantage of this feature.

**Comment by AndrewFairbairn** [comment]
The change required for this would be something like the following in log.js:

`   Logger.prototype.download = function(logName = 'agent-log') {
      var logBlob = new global.Blob([JSON.stringify(this._rolledLogs.concat(this._logs), undefined, 4)], ['text/plain']);
      var downloadLink = document.createElement('a');
      downloadLink.href = global.URL.createObjectURL(logBlob);
      downloadLink.download = logName + '.txt';
      document.body.appendChild(downloadLink);
      downloadLink.click();
      document.body.removeChild(downloadLink);
   };
`

**Comment by bigsapper** [comment]
You can submit that change. I could do it, but I would need to go thru a certification process with the company I work for, first.

**Comment by ctwomblyamzn** [comment]
PR was merged. Closing.
