### ISSUE TITLE
Question about remote mediaStream / becoming SOFTPHONE master 

### ISSUE THREAD

**Issue by CiscoKidxx** [amazon-connect/amazon-connect-streams#125]
I am wondering if there is a way to become master of the remote-audio mediastream. In the event there are multiple CCP's open in same browser, it seems the first to initialize is the owner of the remote-audio mediastream meaning subsequent CCP's show `active: false` for the remote-audio media stream when a call is active. 

I have tried something like `connect.core.becomeMaster(connect.MasterTopics.SOFTPHONE)` however this does not change the above behavior. 

Thanks!

**Comment by clifwis75** [comment]
For the CCP's that you don't want to deliver audio to, simply flag allowFramedSoftphone: false in your connect.core.initCCP. This will stop any media from connecting to that session, but still allow event subscription and API functions...

**Comment by CiscoKidxx** [comment]
The issue is the custom application / embedded CCP competing with the default CCP (that I cannot control). For example, User A logs into the CCP via https://<Alias>.awsapps.com/connect/ccp#/ and then logs into the custom application. In this scenario, the embedded CCP does not get the media stream for the remote audio.

**Comment by CiscoKidxx** [comment]
@jagadeeshaby - may I bother you for assistance with this?

**Comment by CiscoKidxx** [comment]
@jagadeeshaby, still need your guidance here.

**Comment by CiscoKidxx** [comment]
@jagadeeshaby - please lol?

**Comment by dnovicki** [comment]
@CiscoKidxx - I am thinking I may be able to help you as I recently experienced a similar use case to support. It appears as you mentioned calling `connect.becomeMaster(connect.MasterTopics.SOFTPHONE)` does indeed make a tab the Master, it doesn't seem to stop the call from attempting to connect to that tab before others. A work around I found is to call `connect.ifMaster(connect.MasterTopics.SOFTPHONE)` whenever a call is routed to an agent and ignore the call (and corresponding hooks) if you are not master. This means not creating an `RTCSession`. Connect also appears to auto-resolve to a new Master tab whenever the current Master tab is closed so no additional work needs to be done to handle this.

**Comment by CiscoKidxx** [comment]
@dnovicki - thank yo so much! I will give that a shot.

**Comment by ctwomblyamzn** [comment]
@CiscoKidxx did that resolve your issue?

**Comment by ctwomblyamzn** [comment]
Closing as we have not heard back in a while, and it appears that your question has been answered.
