### ISSUE TITLE
About transfer between agents

### ISSUE THREAD

**Issue by samurai8429** [amazon-connect/amazon-connect-streams#128]
Hi
When transferred to another agent by CCP quick connection,
Is it possible to obtain who transferred using the API and the name of the transfer source agent etc. at the transfer destination incoming event?

**Comment by ctwomblyamzn** [comment]
I'm not sure I fully understand your question. You're asking if, in the streams context of the agent receiving a transfer, you can tell who the original agent that transferred you is?
