### ISSUE TITLE
Notification for user without CCP access

### ISSUE THREAD

**Issue by aguecida** [amazon-connect/amazon-connect-streams#129]
I have an application that is to be accessible by any Amazon Connect user (e.g. Agent or CallCenterManager). By default, users with the CallCenterManager security profile are not granted access to the CCP, and when I try to initialize the CCP within my application for this type of user using Streams, it rightly displays a "You are not authorized" message in the iframe. However, I feel like it should be possible for my application to determine if a user has permissions to use the CCP (without duplicating this configuration in my application), so that it can react appropriately (i.e. by hiding the CCP container div or not calling `initCCP` at all). Is there any Connect API to get the permissions or are there any events on `initCCP` that can notify me if the CCP could not be loaded because the user is not authorized?

**Comment by CiscoKidxx** [comment]
there are not currently.

**Comment by jagadeeshaby** [comment]
``` connect.core.onAccessDenied ``` Handler would be the best fit to handle this use case.  We are tracking this internally and will post an update once available. 

Thanks,

**Comment by ctwomblyamzn** [comment]
This handler is now available. Resolving.
