### ISSUE TITLE
contact.onEnded() not being called for outbound 'hangup'

### ISSUE THREAD

**Issue by camstuart** [amazon-connect/amazon-connect-streams#132]
Hi,

I have inbound calls working correctly, and when either the agent or the caller hangup, `contact.onEnded()` is called as expected.

However, when I make an outbound call `contact.onEnded()` is only called when the agent terminates the call.

If the endpoint being called hangs up first, `contact.onEnded()` does not get called.
Which leaves my dialler in an odd state.

Eventually, after an `agent.onRefresh()` event, everything returns to normal.
But I need to capture this event

**Comment by seiyako** [comment]
Thanks for the feedback. As far as I tested at this point I can't reproduce the issue. This issue should be already resolved.
