### ISSUE TITLE
Change Output Device for Ringtone

### ISSUE THREAD

**Issue by deveddev** [amazon-connect/amazon-connect-streams#134]
I am attempting to use a different hardware device when the phone rings in response to an incoming call (onConnecting).  Then, I want to switch back to the main handset for the conversation (onConnected).

I thought I would just have to pass the deviceId into the following method:
RingtoneEngineBase.prototype.setOutputDevice(deviceId)

But this does not appear to be the case.  Any suggestions?  Thanks.

**Comment by deveddev** [comment]
Cleaner version of API
![image](https://user-images.githubusercontent.com/33138144/62998610-efa04600-be20-11e9-8ae4-0b645f579f86.png)
`/**
      * Change the audio device used to play ringtone.
      * If audio element is not fully initialized, the API will wait _audioPlayablePromise for 3 seconds and fail on timeout.
      * This API is supported only by browsers that implemented ES6 Promise and http://www.w3.org/TR/audio-output/
      * Return a Promise that indicates the result of changing output device.
      */
     RingtoneEngineBase.prototype.setOutputDevice = function(deviceId) {
        if (this._playableAudioPromise) {
           var playableAudioWithTimeout = Promise.race([
              this._playableAudioPromise,
              new Promise(function(resolve, reject){
                 global.setTimeout(function(){reject("Timed out waiting for playable audio");}, 3000/*ms*/);
              })
           ]);
           return playableAudioWithTimeout.then(function(audio){
              if (audio.setSinkId) {
                 return Promise.resolve(audio.setSinkId(deviceId));
              } else {
                 return Promise.reject("Not supported");
              }
           });
        }
  
        if (global.Promise) {
           return Promise.reject("Not eligible ringtone owner");
        }
     };`

**Comment by seiyako** [comment]
Hi, in the 1.6.3 release, we added audio device related APIs such as agent.setSpeakerDevice(), agent.setMicrophoneDevice(), and agent.setRingerDevice(). For embedded CCP users, you can pass a new parameter pageOptions: { enableAudioDeviceSettings: true } to initCCP API, which will add an audio device section to the Settings page.
