### ISSUE TITLE
force 'After Call Work'

### ISSUE THREAD

**Issue by camstuart** [amazon-connect/amazon-connect-streams#135]
Is it possible to force the agent state into `After Call Work`?

I have tried:

```javascript
window.myCPP.agent.setState(connect.AgentStateType.NOT_ROUTABLE, {
      success: () => {
        ...
      },
      failure: () => {
        console.error('! unable to set non routable (after call work) state');
      }
});
```
But as far as I can tell, `NOT_ROUTABLE` is not exactly After Call Work.

**Comment by jagadeeshaby** [comment]
Unfortunately that is not an option - as After Call Work (After Contact Work) state is meant for handling wrap up task after the contact and it's system defined. (also admin can define a timer to auto dismiss)

Alternatively you can always create a custom states (non_routable) using  /connect/agent-states  page on admin website (name it accordingly) and on CCP you can use setState to Choose the same. 

Hope this helps.  I'm curious to understand the use case here.

**Comment by camstuart** [comment]
Ok Thanks;

This is a scenario on my custom dialler where our agents make outbound calls and the target either declines the call or the agent cancels the call (due to error, mistaken dial) and we would have our agent capture an end of call disposition that reflects either of these scenarios.

When in an after call work state, our custom dialler disables the ability to go back to routable until this information is saved (same UI) does that make sense?

**Comment by m66rus** [comment]
What is your auto available setting in the user profile set to as it should not go auto available

**Comment by AlexD1979** [comment]
"auto available setting" where should I find it? Im my user config I did not have any option except the "Auto accept call" checkbox. Is this a new hodden feature?

**Comment by m66rus** [comment]
Sorry in the user management is there a after call work timeout set?

**Comment by AlexD1979** [comment]
no, should be 0 as never ending.  But when the time has elapsed, the status will change from ACW to available. But this settings works only if a contact was acceppted .. if you are in outbound and status and status "connecting" and the customer does not pick up the call and you hang up, you are asap back to "available" im Status as described by the issue owner.

**Comment by old-square-eyes** [comment]
Also to add. If you are using "Desk Phone", or in my case, mobile phones for field agents... and they do not answer... they get permanently stuck in not ready. This is not an after call work status as they never accepted the call. I need to be able to time out this state as well as after call work. THese agents don't use CCP. Yes they could jump on CCP and put themselves on available but that's not what I need.
