### ISSUE TITLE
Can't Disable desktop notification programmatically

### ISSUE THREAD

**Issue by boopathi018** [amazon-connect/amazon-connect-streams#137]
How to block the notification triggered by default CCP programmatically

**Comment by jagadeeshaby** [comment]
Unfortunately we do not have any way to block the notifications triggered by default CCP. Definitely will add this into CCP feature request pipeline.  

Probably Something like below would make sense.

```
initCCP({
   disableBrowserNotifications:  true
})
```

**Comment by sseidel16** [comment]
would also like to see this implemented

**Comment by bkapellusch** [comment]
This is also something I'd really like to see. We want to have our own custom notification, but it looks weird when Amazon's comes first then ours comes.

**Comment by alexgurr** [comment]
This is an issue for us, especially when the embedded CCP doesn't seem to request notifications (but the auth window does) -- it's very unreliable. Would love the ability to turn this off.

**Comment by manojverma086** [comment]
I'm also experiencing the issue described, and it's impacting my use case. Is there any update on the progress or an estimated time of arrival for a fix? Your efforts are much appreciated.Thank you!

**Comment by alexgurr** [comment]
Chiming in on this - we'd also love to be able to turn these off!

**Comment by dmal1922** [comment]
Has there been any progress on this effort? This would be extremely beneficial.
