### ISSUE TITLE
Call Start time to retrieve s3 file name 

### ISSUE THREAD

**Issue by siddiq-syed** [amazon-connect/amazon-connect-streams#141]
Hi.,

Is there any method in the api that give me the call start time and date ? I am using the contact.getContactId() method to get the contact_id to form the file name where the call recordings are stored.

connect/callcenter/CallRecordings/2019/08/29/93755524-32b4-480b-9108-898522aa513f_**20190829T17:11_UTC**.wav

I want to get the timestamp so that I can save the path in my DB for retrieving the call record whenever required.

Is there any method that can return me the call start time ?

**Comment by hfahlbusch** [comment]
Hi,

if this the call start time or the start time of media streaming, when the user accepted to get his call recorded?

For call start time you could check if the `contact.getQueueTimestamp()` matches your needed time.
Second possibility would be to set an extra attribute in your call flow. Setting a contact attribute after the media streaming block allows you to get the start timestamp.
Last possibility would be to check, if you can access it directly. I used some data in a lambda together with media streaming, there was a special block present in the contact data:

`  "MediaStreams": {
                "Customer": {
                    "Audio": {
                        "StartFragmentNumber": "91343852333181432392682062621279895313779700474",
                        "StartTimestamp": "1562277545978",
                        "StreamARN": "arn:aws:kinesisvideo:eu-central-1:018475083538:stream/mailbox-xxxxx-xxxxx-contact-a557455a-3342-4b0e-ac9c-4b77e1d08e90/1562251721736"
                    }
                }
            }
`

Regards,
Helge

**Comment by aguecida** [comment]
I ran into this same issue. As a workaround, I used the S3 GetFiles API to do a wildcard search on files matching the pattern `contactId*`, this way I only had to store a reference to the contactId in my database, which is easily accessible using the Streams API.

**Comment by siddiq-syed** [comment]
I used the Connect Data streaming ... Enable the data streaming and through lambda parse the Kinesis steam where you get the call metadata.

https://docs.aws.amazon.com/connect/latest/adminguide/agent-event-streams.html

When the agents get the call we will have the contact-id and we can use the compare the get the metadata through the stream.
