### ISSUE TITLE
agent.connect() not firing when invoked

### ISSUE THREAD

**Issue by MatthewAlviz** [amazon-connect/amazon-connect-streams#143]
Hello, I'm facing an issue invoking this method. It doesn't return any callbacks from success or failed it just skips this function and no error at the console...

`connect.agent(function (agent){
           			 console.log(agent.getConfiguration());
                 agent.connect(connect.Endpoint.byPhoneNumber("+611800836411"), {
                   		 queueARN: null,
                       success : function(){console.log("Success call!!!!!!")},
                       failure : function(){console.log("Call failed!!!!!!!")}
                });
           			console.log("done");
          });`

**Comment by jagadeeshaby** [comment]
Same code seems to be working fine for me! 

```
connect.agent(function (agent){ 
	console.log(agent.getConfiguration()); 

    agent.connect(connect.Endpoint.byPhoneNumber("+611800836411"), { 
        queueARN: null, 
        success : function(){console.log("Success call!!!!!!")}, 
        failure : function(){console.log("Call failed!!!!!!!")} 
    }); 

  console.log("done"); 
});
```
Could you please elaborate further on how you try to execute this? also could you try this directly on browser console and see if that works.

**Comment by MatthewAlviz** [comment]
Hello, I'm trying to integrate this library on a ServiceNow instance. I did check the browser console. It doesn't trigger anything nor throw an error when invoked. It only logs the "console.log('done')"

**Comment by scoland** [comment]
Hi Matthew, apologies for the late response.

I've also tested the code you posted and was able to successfully invoke both the success and failure callbacks.

I'm going to close this for now, but if you're still experiencing this issue please feel free to reopen.

**Comment by Mohamed-Nasr7** [comment]
I have exactly the same issue. Is there a reason for this, guys?
