### ISSUE TITLE
Agent on Hold while confernce

### ISSUE THREAD

**Issue by abebars** [amazon-connect/amazon-connect-streams#146]
is it possible to put agent connection on hold while a conference between Agent, Inbound, Outbound?

Using this scenario to collection information from the contact through the outbound call then disconnect the outbound and resume the agent connection.

**Comment by camstuart** [comment]
Always happy to help a fellow Gopher out :)

Essentially you can iterate through the active contact "connections" array and call `.hold()` on any you choose.

Having said that, AFAIK, it's the last one in the array, like this:

```javascript
const activeConnections = window.YOUR_CCP.contact.getConnections();
if (activeConnections.length < 1) {
  console.log('nobody to put on hold!')
} else {
  activeConnections[activeConnections.length - 1].hold({
    success: () => { console.log('please enjoy some elevator music') },
    failure: () => { console.error('failed to put the call on hold') }
  })
}
```
