### ISSUE TITLE
Setting Agent status through API

### ISSUE THREAD

**Issue by siddiq-syed** [amazon-connect/amazon-connect-streams#150]
Hi All.,

I am trying to see if there is any API call that I can make to set the Agent Status for the AWS Connect agent.,
I am creating the user with CreateUser API Call with DESK_PHONE as Phone type by passing the phone number.,

The user have manually login to connect to be available.. I am trying to see if I can set those agents status as available so if the calls comes it will go directly to the Desk phone.,

**Comment by camstuart** [comment]
The only way that I know of to set agent status is once the agent is logged in as you pointed out. All of the methods in Connect Streams are for the currently authenticated user.

If I understand your needs correctly, then I think the best approach would be:

1. Maintain the agent's state in a database. This can be done by having a lambda triggered by the agent event kinesis stream (it gets a heartbeat of the status quite often. If there is no data for a given agent inside a minute, you know they are offline)

2. During your call flow, invoke a lambda to check this status, if offline, transfer the call to the desk phone

**Comment by haochi-aws** [comment]
Hi @siddiq-syed, it's currently not possible to set the agent's status to `Available` through an Amazon Connect API call.

However, you can programmatically change the agent's state using the `agent.setState() / agent.setStatus()` method in the [Connect Streams API](https://github.com/aws/amazon-connect-streams/blob/master/Documentation.md#agentsetstate--agentsetstatus).
