### ISSUE TITLE
onHoldToggle event

### ISSUE THREAD

**Issue by nielsenius** [amazon-connect/amazon-connect-streams#151]
The `Agent` class provides an event for `onMuteToggle`. Can an event be added to the `Contact` class for `onHoldToggle`? This would make it easier to implement third-party softphones. My current solution is to provide a success callback in hold/resume APIs; this works, but it's probably cleaner to have an out-of-the-box `onHoldToggle` event.

**Comment by scoland** [comment]
Thanks for the request, I agree that there's a valid use case for adding this convenience method. I flagged it to the team's list of future items to look into.

Also feel free to create a pull request if you'd like!

**Comment by sheltonli** [comment]
Is there any update on this?

**Comment by vs-amzn** [comment]
It’s been a while and we are closing this for now. Please reopen if it’s still an issue
