### ISSUE TITLE
Not populating "Previous Contact Id"

### ISSUE THREAD

**Issue by NBNalluri** [amazon-connect/amazon-connect-streams#152]
Hi All,

As per the below document, "Previous Contact Id" should be populated, while call transferred among multiple agents/queues.

https://docs.aws.amazon.com/connect/latest/adminguide/connect-attrib-list.html

Now it is populating only "Contact Id" and "Original Contact Id" but NOT "Previous Contact Id".

Any reason why streams API is not populating "Previous Contact Id".

Thanks,
NB Nalluri.

**Comment by zesheng-amazon** [comment]
Hi NB,
"Previous Contact Id" is a System attribute of contact flow. I am assuming you are using contact.getAttributes() method to get attributes. StreamsJs only support User-defined attributes for that method. Please check out this doc for how to create User-defined attribute in contact flow. 

https://docs.aws.amazon.com/connect/latest/adminguide/using-contact-attributes.html

Hope this helps!

Thanks,
Zesheng
