### ISSUE TITLE
agent.getAgentStates() does not seem to return all states.

### ISSUE THREAD

**Issue by crewsha** [amazon-connect/amazon-connect-streams#155]
Currently the `getAgentStates()` method returns two different states: "Available" and "Offline" but if you subscribe to `onAgentStateChange()` and step through the process of making or taking a call there's actually more states like CallingCustomer, PendingBusy, Busy, and AfterCallWork.

**Comment by hfahlbusch** [comment]
The states are "selectable" by the agent himself. It's selectable in his CCP. 
The Agent is not able to switch into "PendingBusy" state or the other ones.
I guess these are more "technical" states of the phone and not the agent.

@crewsha Does this help?

**Comment by crewsha** [comment]
Yeah after working with it for a bit this started to make sense. I guess my issue is that it isn't clear that the states of the ccp are different from the connect agent states, and the documentation doesn't help to clarify that.

**Comment by ctwomblyamzn** [comment]
We are working on improving agent state currently. This will be addressed in the future.

**Comment by alim907** [comment]
@ctwomblyamzn @yaminli-aws was this enhancement ever completed? I've noticed that the `agent.getAgentStates()` response still does not seem to include states such as `PendingBusy`, `Busy`, and `AfterCallWork`.

cc @azuruce @cclifford3

**Comment by ctwomblyamzn** [comment]
Hi @alim907 -- the plan was never to expose these system states in the getAgentStates api, as Streams users can't actually switch agent state to any of these system states. To further clarify the difference between states like `PendingBusy`, etc, we have introduced the `agent.getAvailabilityState` api, which will provide the current user-changeable / definable state which the agent is in, even while on a voice contact (even when `agent.getState` returns some other system state. The system states like `PendingBusy` are, in reality, a relic of a time when voice was the only media channel. With media channels like chat and task, which can take more than one contact at a time, displaying contact-specific system states in the agent status does not make sense, but we must continue to do this for legacy reasons for voice contacts.

If you have any questions about this, let me know.

**Comment by ctwomblyamzn** [comment]
It may make sense to rename this api (create an alias for backwards compatible reasons) to something like `agent.getAgentAvailabilityStates`

**Comment by alim907** [comment]
@ctwomblyamzn Thanks for explaining! That context helps clarify the reason behind discrepancies.

**Comment by gamliela** [comment]
So `getAgentStates()` returns only "selectable" states (or "availability" states, if you like), but `getState()` may return any state, including system states. On top of that, there is a (new?) undocumented api called `getAvailabilityState()`. I second @ctwomblyamzn - `getAgentStates` should be renamed to `getAgentAvailabilityStates` (or `getAvailabilityStates`) to reduce confusion. Also PLEASE document `getAvailabilityState` - I spent hours until I accidentally found this API.
