### ISSUE TITLE
Apply Customs Styles to Connect Contact Control Panel

### ISSUE THREAD

**Issue by jiwasz-sav** [amazon-connect/amazon-connect-streams#163]
We have a business requirement to change the colors and icons used in the Contact Control Panel.

Per the documentation:

"CSS styles you add to your site will NOT be applied to the CCP because it is rendered in an iframe."

So, styles can be applied to the div to size the container, but cannot be applied to style the CCP since it uses an iframe that points to:

https://[instancename].awsapps.com/connect/ccp#/

In turn, that iframe references a CSS hosted in CloudFront.

https://d1f0uslncy85vb.cloudfront.net/css/lily_ccp_Prod_ad73d82fd17dee51a3e160b7c84439903d6d59db.gz.css

Are there any capabilities planned for the CCP which allow for custom styling?

**Comment by danbee-park** [comment]
Hi,

Could you specify which style you pursue like just simple overall text color or only state text color  ?

**Comment by mschersten** [comment]
I've thought about this issue for a few different reasons, and I've imagined that just like connect.agent and connect.contact we could have connect.ccp.  Then we could use that for something like connect.ccp.applyStyle(css).

Somewhat unrelated, I would also use that for event listeners, like .onReject().  We've had difficulty knowing when agents are just missing calls or actively rejecting them.  Related to chats, we also will need a way to know which chat is showing in the ccp to control other parts of our application.

**Comment by danbee-park** [comment]
@jiwasz-sav and @mschersten ,
First, we appreciate your feedback and please check my answers below.

Using a js object for style may have security vulnerabilities (we don't know if there is a XSS, so it would lower the initialization speed because of validating the style). Therefore, there is no short term plan now.

For your other questions, we will consider these requests.
