### ISSUE TITLE
connect.getAgentConnection() fails for chat

### ISSUE THREAD

**Issue by i336588** [amazon-connect/amazon-connect-streams#174]
Hi,
I have enabled chat for my connect instance and I can test chat without any error using the test chat url provided by the console. However, when I follow the usage of https://blogs.perficient.com/2019/11/25/whats-new-with-streams-api-v1-4/ to implement my own code. I got the following error when contact.getAgentConnection() is called.
![image](https://user-images.githubusercontent.com/51769945/69794147-b68bb600-1204-11ea-9c23-9d0cf616e2dd.png)
Besides, I have added the required 'region' parameter and changed the ccpUrl to the updated ccp-v2, When calling connect.core.initCCP().
Do I miss some other configuration? What's the problem?

**Comment by mschersten** [comment]
I'll close issue #179, but note here that this also happens on getActiveInitialConnection(), and appears to be coming from src/mediaControllers/chat.js, on lines 26-34.

**Comment by winzig** [comment]
@mschersten Do you work on the AWS Connect team? I'm also having this same issue.

**Comment by zesheng-amazon** [comment]
Please also include ChatJs in your own code. You can follow https://github.com/amazon-connect/amazon-connect-chatjs to get compiled amazon-connect-chat.js.

Let me know if you have any questions.

**Comment by winzig** [comment]
@zesheng-amazon Thanks! I just saw your comment after discovering this myself! ;-) 

Is this explained in the docs anywhere?

**Comment by winzig** [comment]
@zesheng-amazon Actually, I found that I wasn't able to get this working unless I literally included amazon-connect-chat.js into the connect streams Makefile and make it part of my build: https://github.com/aws/amazon-connect-streams/issues/197#issuecomment-570290109

Is this anticipated? If so, why isn't this part of the official Makefile?

**Comment by zesheng-amazon** [comment]
@winzig Chatjs isn’t in the streams Makefile because it is only needed when streams is being used for agent chat. If a customer wants to use it only for softphone, chatjs is not needed. You can include chatjs by using script tag. 

```
<script src="amazon-connect-chat.js"></script>
```

We will update readme file soon to include these information.

Let me know if you have any questions.

**Comment by winzig** [comment]
@zesheng-amazon It doesn't work for me if I try to include it via <script> tag. The only way I could get it to work was to reference it in the connect-streams Makefile and rebuild. See my issue #197 for more details on all that. Thanks.

**Comment by zesheng-amazon** [comment]
I am closing this issue. @winzig We will discuss in your issue [#197.](https://github.com/amazon-connect/amazon-connect-streams/issues/197).

**Comment by nickvargas82** [comment]
I am getting a different error with getAgentConnection().
I have a simple code to send a message upon chat connection.

```
connect.contact(function (contact) {
    contact.onConnected((c) => {
        console.log('CONNECTED');        
        c.getAgentConnection().getMediaController().then(controller => {
            controller.sendMessage({message: "message from agent", contentType: "text/plain"}).then(function(res, req)
            {
                console.log(res.status);
            });
        })                  
    });
});
```

It throws few CORS related errors:

> Access to XMLHttpRequest at 'https://participant.connect.us-west-2.amazonaws.com/participant/connection' from origin 'https://xxxx.xxx' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> VM949:1 POST https://participant.connect.us-west-2.amazonaws.com/participant/connection net::ERR_FAILED

Then it throws this error:
> [ERROR]: ChatClient error when creating connection request 
> Connect Failed with data:  {"_debug":{"reason":"Failed to fetch connectionDetails with createParticipantConnection","_debug":{"type":"NetworkingError","message":"Network Failure","stack":["NetworkingError: Network Failure","    at XMLHttpRequest.<anonymous> (https://xxx.xxx/xxx/js/aws-sdk-2.628.0.min.js:6:3738)"]}},"connectSuccess":false,"connectCalled":true,"metadata":null}

Can anyone please point me to the right direction on how to fix this? Thanks.
