### ISSUE TITLE
ccp-v2 fails first auth and whitelested-origins calls

### ISSUE THREAD

**Issue by mschersten** [amazon-connect/amazon-connect-streams#177]
I'm having some trouble loading the ccp-v2 embedded in an application.  I first thought this had something to do with SAML authentication, but I have confirmed that the below happens both with and without SAML.

When using the ccp-v2 url (.../connect/ccp-v2/) in connect.core.initCCP(), it loads the login page (either Connect or SAML) in a new tab, which then becomes the softphone.  After that, my main page makes requests to .../connect/auth/authorize as well as .../connect/whitelisted-origins.  These both fail with 401 - Unauthorized.  If I then reload the page having already logged into the CCP(v2), the softphone will load successfully embedded in the page.

Another way this works is by using the ccp-v1 url to load the page, and then once that has loaded manually changing the iframe source url to point to v2.  That also allows both requests to return as 200.

It appears that the calls to .../connect/auth/authorize and .../connect/whitelisted-origins are being made by one of the js files loaded from .../connect/ccp-naws/static/js, in my case named "14.4e3b223a.chunk.js".  The calls seem to come from connect.core.authorize and connect.core.verifyDomainAccess.

**Comment by devansvd** [comment]
Facing this issue, can confirm

**Comment by devansvd** [comment]
This occurs only when embedded in http sites. For https it works fine. Hard to test in local development with locally resolved domains

**Comment by mschersten** [comment]
I saw a comment somewhere that this was related to running it locally.  I do test locally by whitelisting localhost sometimes, but I have confirmed that this still happens when running on a real domain, and regardless of SAML or not.

**Comment by ctwomblyamzn** [comment]
Is this still occurring?

**Comment by mschersten** [comment]
We're not using v2 in production yet, but this seems to be fixed from the testing I've done.
