### ISSUE TITLE
Login/Logout callbacks?

### ISSUE THREAD

**Issue by sromocki** [amazon-connect/amazon-connect-streams#19]
Is there a way to perform an action after successful agent login/logout?

**Comment by k1p1l0** [comment]
Hey @sromocki! Did you find the answer?

**Comment by sromocki** [comment]
@k1p1l0 No, I haven't.  Though instead of making a new thread I added a comment on my other login API thread.  Still looking for login/logout callbacks.

**Comment by naresh-talluri** [comment]
@sromocki 
Login ==> i would consider calling agent() from connect object would trigger after successful login, ex: connect.agent(callback);

Logout ==>
let bus = connect.core.getEventBus();
bus.subscribe(connect.EventType.AUTH_FAIL, () => {
//do something 
}

hope this helps!

**Comment by sromocki** [comment]
@naresh-talluri Yea, that's what I did for login.  I haven't tried that logout solution though (just been living without being able to logout), I'll give it a shot.

**Comment by saketag** [comment]
Depending upon what you intend to solve here, the recently launched agent event stream may be handy - http://docs.aws.amazon.com/connect/latest/userguide/agent-event-streams.html

**Comment by sromocki** [comment]
@saketag Just needed callbacks to be able to show in my application that the user is indeed logged in/out of connect and can/cannot place calls.  I'm not sure how I'd do that with the agent event stream, looks like that's more for reporting.

**Comment by sromocki** [comment]
@naresh-talluri I tried your logout strategy, but that AUTH_FAIL event does not appear to be triggered on logout.  I also checked the TERMINATE and CLOSE events but those don't appear to trigger either.

**Comment by pavanrachapudy** [comment]
When I authenticate with my amazon connect credentials on the other page and when i come to my web page, it is taking lot of time to trigger connect.agent(...). Is there something, I am missing. Any help on this would be appreciated.

**Comment by davidjosephhayes** [comment]
I did this:

```
       const bus = connect.core.getEventBus();

        // get the agent init to set logged in
        bus.subscribe(connect.AgentEvents.INIT, this.handleAgentLogin);

        // handle shared worker terminated to set agent logged out
        bus.subscribe(connect.EventType.TERMINATED, this.handleAgentLogout);
```

**Comment by chriys** [comment]
@davidjosephhayes the log out solution is definitely working.
For those using ES5 or a script tag. This can help.
```
// The following lines need to be after the ccp has been initiated `initCCP()`
// Get the event but
var eventBus = connect.core.getEventBus();

// Attach a handler to the login event
// connect.EventType.INIT is a constant containing the name of the event.
eventBus.subscribe(connect.EventType.INIT, function() {
  // whatever you need your code to do here.
  console.log('logged in');
});

// Attach a handler to the log out event
// connect.EventType.TERMINATED is a constant containing the name of the event.
eventBus.subscribe(connect.EventType.TERMINATED, function() {
  // whatever you need your code to do here.
  console.log('logged out');
});
```

**Comment by camstuart** [comment]
On this note, is there a way to trigger a logout? (destroy the session) 

For testing I have set up multiple accounts, but as you probably know, once a session is created, all browser tabs see the session. I would like to be able to logout, so I can log back in again as a different user
