### ISSUE TITLE
'createOutboundContact' API request failed

### ISSUE THREAD

**Issue by rpaulojade** [amazon-connect/amazon-connect-streams#190]
Hi our code worked for a while but then started throwing a 'createOutboundContact' API request failed.
Below is our code:

```
const endpoint = this.connect.Endpoint.byPhoneNumber(phoneNumber);
    activeAgent.connect(endpoint, {
      success: () => {console.log('success')},
      failure: () => {console.log('failures')}
    })
```

**Comment by ctwomblyamzn** [comment]
Hi, your syntax looks right, assuming activeAgent is a valid agent object. 

createOutboundContact could be failing for a number of reasons. Are you able to consistently reproduce this error? If you look in a browser's network logs you might be able to find a more detailed error message.
