### ISSUE TITLE
Agent hangup and hold

### ISSUE THREAD

**Issue by Juzziee** [amazon-connect/amazon-connect-streams#193]
It seems like the examples provided for hanging up a call don't seem to be working.

I am calling a function to hang up a phone call but it seems to returning a subscription event without actually hanging up the call. 

`var c;
connect.contact(function (contact) {
  c = contact;
  connect.agent(async function(agent) {
    if (c) {
      var initialConnection = c.getInitialConnection();
      if (initialConnection) {
        initialConnection.destroy();
      }
    }
  });
});`

Does anyone have any guidance here?

**Comment by scoland** [comment]
Hi @Juzziee,

Are you passing success/failure callbacks to the destroy function as seen here:

https://github.com/aws/amazon-connect-streams/blob/master/Documentation.md#contactdestroy

Which one gets called? If it fails, is there a failure reason passed through?

**Comment by Juzziee** [comment]
Hey Scoland,

Unfortunately, I don't think I am passing through the contact information correctly. 

`function abandonCall(){
        console.log("Agent Abandon called");
        connect.contact(function (contact) {
           contact.destroy({
               success: function() { console.log("Successfully Abandon"); },
               failure: function() { console.log("Failed to Abandon"); }
            });
        });
    }`

Any guidance here would be greatly appreciated.

**Comment by scoland** [comment]
`connect.contact()` subscribes an event handler to be called every time a new contact is detected, so you likely don't want to be calling this inside your `abandonCall` function.

Rather you probably want to pass in the specific contact object you want to abandon like so: `abandonCall(contact)`.

You can get the contact object a few ways, by either storing it from a previous trigger of `connect.contact()` or through the agent API via `agent.getContacts()`.

**Comment by ctwomblyamzn** [comment]
This issue is going to be closed for lack of activity. I hope your question was answered. If you have followup questions, please feel free to reopen!
