### ISSUE TITLE
Login Popup sometimes does not open

### ISSUE THREAD

**Issue by imankurpatel000** [amazon-connect/amazon-connect-streams#195]
https://github.com/aws/amazon-connect-streams/blob/2802651ab46452485bcb178d8d324aaffa4019ba/src/util.js#L413

```
connect.PopupManager.prototype.open = function(url, name) {
    var then = this._getLastOpenedTimestamp(name);
    var now = new Date().getTime();
    var win = null;      
    if (now - then > ONE_DAY_MILLIS) {
       win = window.open('', name);
       if (win.location !== url) {
          win = window.open(url, name);
       }
       this._setLastOpenedTimestamp(name, now);
    }
```

According to the code above. The login popup only opens if one day has passed since the last popup. This seems to create isssues as sometimes the user is not logged in but it won't popup the login window because 1 day has not passed yet since the last popup. Somehow, I don't see this issue mentioned by anyone so may be I am doing something wrong here. 

The following is the only code that I have for now.

```
var ccpUrl = "https://" + instanceAlias + ".awsapps.com/connect/ccp-v2";
connect.core.initCCP(containerDiv, {
        ccpUrl: ccpUrl,
        loginPopup: true,
        loginPopupAutoClose: true,
        softphone: {
            allowFramedSoftphone: true
        }
    });
```
I was wondering if the check `if (now - then > ONE_DAY_MILLIS) {` is really required?

**Comment by winzig** [comment]
Have also experienced this issue.

**Comment by hfahlbusch** [comment]
I don't understand this one day, neither. 
I was clearing this with the following snippet:  
`connect.core.getPopupManager().clear(connect.MasterTopics.LOGIN_POPUP);`

**Comment by jolim24601** [comment]
We clear the timer on ACK_TIMEOUT and ACKNOWLEDGE events, and you can manually clear it by calling `connect.core.getPopupManager().clear(connect.MasterTopics.LOGIN_POPUP)` as @hfahlbusch mentioned. By default if the CCP does not ACK for 10 seconds that will trigger a cleanup call.
