### ISSUE TITLE
How to subscribe to incoming/outgoing message events?

### ISSUE THREAD

**Issue by winzig** [amazon-connect/amazon-connect-streams#197]
I've read the [documentation](https://github.com/aws/amazon-connect-streams/blob/master/Documentation.md) and [cheat sheet](https://github.com/aws/amazon-connect-streams/blob/master/cheat-sheet.md) a few times and searched the issues here, and am not seeing an explanation of how to subscribe to incoming/outgoing message events for CCP. 

I do see this kind of thing in the dev console:

`[2019-12-30T00:32:28.824Z] [INFO]: ContactId-a52e3078-48be-486c-bacf-938e04af6716:  Subscribed successfully to eventName:  INCOMING_MESSAGE`

I am able to hook into this kind of functionality on the [sample chat UI](https://github.com/amazon-connect/amazon-connect-chat-ui-examples), and assumed there would be something similar in the CCP JavaScript?

**Comment by winzig** [comment]
Finally noticed this code on the cheat sheet which seems like what I'm after, but it fails to run when I put it within my `connect.contact(function(contact) { ... });` hook. 

```js
connect.contact(function(contact){
contact.getAgentConnections().forEach(function(connection){
  // chat users
  if(connection.getMediaType() === connect.MediaType.CHAT){
      contact.getConnection().getMediaController()
      .then(function(controller){
          controller.onMessage(function(response){
              console.log("data", response)
          })

          controller.sendMessage({message: "so and so", contentType: "text/plain"})
              .then(function(res, req){
                console.log(res.status)
          });
          
          controller.onDisconnect(function(){
              console.log("on disconnect");
          })
      });
  }
});
```

It looks like the culprit is `contact.getAgentConnections()`, which as near as I can tell, doesn't exist. The closest I find is `contact.getAgentConnection()` (singular), which according to the docs just returns a single connection, but even that is currently failing for me. (I get an error of `[ERROR]: 'contact::init' event handler failed.`)

**Comment by winzig** [comment]
I ran the `contact.getAgentConnection()` method outside the context of the `connect.contact(...)` call, and now I get a more verbose error, though I've not yet figured out the root cause.

```
Uncaught TypeError: Cannot read property 'setGlobalConfig' of undefined
    at createMediaInstance (global.js:20)
    at Object.get (global.js:20)
    at getMediaController (global.js:20)
    at Object.get (global.js:20)
    at ChatConnection._initMediaController (global.js:20)
    at ChatConnection.Connection (global.js:20)
    at new ChatConnection (global.js:20)
    at global.js:20
    at Array.map (<anonymous>)
    at Contact.getConnections (global.js:20)
```

**Comment by winzig** [comment]
Looks like @jagadeeshaby added the above sample code to the cheat sheet on Nov 21. Any idea how to make it work? 😅

**Comment by winzig** [comment]
If I use this PR that @ctwomblyamzn updated 5 hours ago, I can now get past the `setGlobalConfig` error above: https://github.com/aws/amazon-connect-streams/pull/196

(Prior to the update from 5 hours ago, I was still getting that error message.)

However, now the error I see is further down, when `connection.getMediaController()` is called:

```
Uncaught (in promise) Media Controller is no longer available for this connection
```

<img width="602" alt="Screen Shot 2019-12-30 at 11 35 40 AM" src="https://user-images.githubusercontent.com/127062/71597557-8d5a9000-2af8-11ea-91bf-88efba757c3c.png">

This is what my code currently looks like:

```js
connect.contact(function(contact) 
{
    var connection = contact.getAgentConnection();
    console.log("Contact Connected", contact, connection); 

    if (connection)
    {
        if (connection.getMediaType() === connect.MediaType.CHAT)
        {
            connection.getMediaController().then(function(controller)
            {
                controller.onMessage(function(response)
                {
                    console.log("onMessage", response);
                });

                controller.sendMessage({message: "so and so", contentType: "text/plain"}).then(function(res, req)
                {
                    console.log(res.status);
                });

                controller.onDisconnect(function()
                {
                    console.log("on disconnect");
                });
            });
        }
    }
});
```

**Comment by winzig** [comment]
I take it back, even with that PR with the latest check-ins, I am still seeing the `setGlobalConfig` error regularly.

**Comment by winzig** [comment]
Well I figured out the issue I think. I had to include [amazon-connect-chat.js](https://github.com/amazon-connect/amazon-connect-chatjs/blob/master/dist/amazon-connect-chat.js) from the `amazon-connect-chat.js` project. If this is in the documentation somewhere, I'm not seeing it...

**Comment by winzig** [comment]
I'm still getting an error, though I'm not yet sure what it's impacting:

```
Uncaught TypeError: AWS.ConnectParticipant is not a constructor
    at new t (client.js:70)
    at e.value (client.js:34)
    at e.value (client.js:22)
    at t.value (chatSession.js:55)
    at t.value (chatSession.js:36)
    at Object.create (chatSession.js:139)
    at createMediaInstance (global.js:20)
    at Object.get (global.js:20)
    at getMediaController (global.js:20)
    at Object.get (global.js:20)
```

**Comment by winzig** [comment]
So, I now have this working, but I wasn't able to just add amazon-connect-chat.js to my page with a `<script>` tag. Instead, I had to add that .js to my local clone of this repo, and modify the Makefile to actually include it as part of the build:

```
#
# Minimal Makefile for amazon-connect JS.
# Concatenates JS assets in the correct order.
#

VERSION = $(shell git describe --tags)
OUTPUT_JS = 'amazon-connect-$(VERSION).js'

SOURCE_FILES = src/aws-client.js \
					src/sprintf.js \
					src/log.js \
					src/util.js \
					src/event.js \
					src/streams.js \
					src/client.js \
					src/transitions.js \
					src/api.js \
					src/lib/amazon-connect-chat.js \
					src/lib/amazon-connect-websocket-manager.js \
					src/core.js \
					src/ringtone.js \
					src/softphone.js \
					src/worker.js \
					src/mediaControllers/* 

all: $(OUTPUT_JS)

$(OUTPUT_JS): $(SOURCE_FILES)
	cat $^ >$@

clean:
	rm -f $(OUTPUT_JS)

.DEFAULT_GOAL := all

.PHONY: clean css
```

**Comment by zesheng-amazon** [comment]
Here are my test codes.
```
<script src="amazon-connect-1.4.4-1-g2802651.js"></script>
 <script src="amazon-connect-chat.js"></script>
 <script type="text/javascript">
    //replace with the CCP URL for your Amazon Connect instance
    var ccpUrl = "https://my-instance.awsapps.com/connect/ccp-v2/";
    function handleContactConnected(contact){
        if(contact){
            if(contact.getAgentConnection().getMediaType() === connect.MediaType.CHAT){
                contact.getAgentConnection().getMediaController().then(controller => {
                    controller.onMessage(function(response,contentType){
                        console.log(response.data);
                    })
                })

            }
        }
    }
    connect.core.initCCP(containerDiv, {
        ccpUrl: ccpUrl,
        loginPopup: true,
        region: "us-east-1",
        softphone: {
            allowFramedSoftphone: true
        }
    });
    connect.contact(handleContactConnected);
 </script>
```

**Comment by zesheng-amazon** [comment]
@winzig You may want to clone [ChaJs](https://github.com/amazon-connect/amazon-connect-chatjs) repo on your local and build it. Then use amazon-connect-chat.js that you build on your local.

**Comment by winzig** [comment]
@zesheng-amazon Thank you! It turns out it was simply the ordering of the <script> tags. Apparently the `amazon-connect-chat.js` needs to come after the streams JS. 

Should the documentation be updated to provide information about how to integrate ChatJS and the chat functions? At the very least it seems the cheat sheet is outdated.

**Comment by winzig** [comment]
PR #207 addresses the last part of my issue, so closing this, thank you.

**Comment by AlexAsirvathamPersistent** [comment]
@winzig @zesheng-amazon How do we do this in Typescript, I have added the import lines in order still geting the same error 
[https://github.com/amazon-connect/amazon-connect-chatjs/issues/75](url)
