### ISSUE TITLE
Is there any API that we can used to get the remote media stream after agent pick a contact?

### ISSUE THREAD

**Issue by chengkunkang** [amazon-connect/amazon-connect-streams#198]
Is there any API that we can used to get the remote media stream after agent pick a contact?

**Comment by ctwomblyamzn** [comment]
Could you clarify exactly what you need here? Sorry about the long response time! 

By remote media stream, we are assuming this would be the media stream related to the softphone, which is accessible through [rtcjs](https://t.corp.amazon.com/V166848231/overview).

In terms of detecting when an agent has accepted a voice contact, that is certainly doable with Streams. We can use [this Contact.onAccepted API](https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/api.js#L486) to trigger a callback when any contact has been accepted, and then check that the contact's connection(s) are of `MediaType` `SOFTPHONE` with [the Contact.getConnections API](https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/api.js#L546) and [the Connection.getMediaType API](https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/api.js#L920)

**Comment by ctwomblyamzn** [comment]
I am going to close this issue, as I think this has answered your question. If not, please reopen!
