### ISSUE TITLE
Controlling the agent's active customer tab via JS?

### ISSUE THREAD

**Issue by winzig** [amazon-connect/amazon-connect-streams#202]
When an agent is talking to multiple customers, is there a way to control and detect which chat "tab" is currently active? Is there an event to subscribe to that would notify when a chat tab is selected/active? 

It would be desirable for us so that we can, for example, allow changes in our CRM to reflect the active customer chat tab in the agent UI.

**Comment by winzig** [comment]
@ctwomblyamzn @scoland How do we get support from AWS for these SDK-level questions? I've opened several over the past week and have not received much help. I also opened a support request directly at AWS, but when I pointed them at my GH issues, they basically said I need to wait for someone to answer them here?

**Comment by ctwomblyamzn** [comment]
Hi @winzig, are you referencing other issues? This specific question seems to be a streams-level question to me, not an SDK-level question. Sorry that we have been delayed getting back to you.

To answer your question here, this is not implemented at this time. That being said, we have had several requests for this feature, so we are strongly considering adding this. I will reference this issue if/when this feature is released.

**Comment by winzig** [comment]
Thanks @ctwomblyamzn. Sorry, by "SDK-level questions" I guess what I meant was code-level questions related to the AWS Connect GitHub repos, not necessarily specific to the SDK. 

I had also asked a question in the chatjs repo: https://github.com/amazon-connect/amazon-connect-chatjs/issues/6

Thanks

**Comment by marcogrcr** [comment]
@winzig : it seems 7f104fc added two methods that precisely help with what you want:

- `connect.core.onViewContact`: Allows you to subscribe to an event that fires whenever the currently selected contact changes (it passes a `{ contactId: string }` arg).
- `connect.core.viewContact`: Allows you to change the currently selected contact on the CCP. This will also trigger any subscriptions to `connect.core.onViewContact`.

_**Note:** I have tested those methods myself, that's how I figure out their behavior._

It seems like these methods are intended to be a public API (at least for `connect.core.viewContact` according to [cheat-sheet.md](https://github.com/amazon-connect/amazon-connect-streams/blob/master/cheat-sheet.md)), though I would wait for official confirmation.

**Comment by winzig** [comment]
@marcogrcr Thanks for highlighting that. To be honest, I had to bow out of using AWS Connect for now due to some of these shortcomings (and lack of a fully open source chat client that can be configured for it). Ended up creating our own internal chat system from scratch. ¯\_💩_/¯ 

If @ctwomblyamzn wants to close this out it's fine, though perhaps instead someone can confirm your findings for everyone to benefit from?

**Comment by marcogrcr** [comment]
@winzig 

> and lack of a fully open source chat client that can be configured for it

I'm curious what do you mean by that. Does [amazon-connect-chatjs](https://github.com/amazon-connect/amazon-connect-chatjs) not satisfy your needs?

**Comment by winzig** [comment]
It may be different now but when I was looking into it in January, the only thing distributed was the pre-built chat client. So tweaking it’s behavior and styling was really hacky and relied on tweaking things likely to break in follow up releases.

**Comment by marcogrcr** [comment]
#243 Officially documented `onViewContact` and `viewContact`, so this can be closed now.
