### ISSUE TITLE
Transfer call join

### ISSUE THREAD

**Issue by Juzziee** [amazon-connect/amazon-connect-streams#203]
Hi guys,

I am currently setting up transferring calls between agents and queues. 
I was not able to find anything within the API docs regarding joining transferred calls.

I am looking to setup the ability for the agent to disconnect from the call and leave the customer and the new agent/queue to remain active. 

Does anyone have any advice for me?

**Comment by ctwomblyamzn** [comment]
If I understand your question correctly, we do support this behavior. The Contact.prototype.conferenceConnections API called by the agent who transferred the contact to a queue or another agent will allow that agent to join the transferred call, assuming that the call has been connected to another agent. See the description in [Documentation.md](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#contactconferenceconnections) for more information. Once the connections are conferenced, either agent can leave the call in the usual fashion (calling[ Connection.prototype.destroy()](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#contactdestroy) on the relevant connection).  One agent leaving the call will only end their specific connection, and in a conferenced call, there are two agent-side connections, so the other will remain open. 

Let me know if I didn't answer any part of your question properly.

**Comment by Juzziee** [comment]
Thanks for the reply @ctwomblyamzn 

To make sure I am understanding you correctly;

Once the calls are connected using the 'Contact.prototype.conferenceConnections' api, I will then need to physically disconnect from both lines (main and secondary)?

**Comment by ctwomblyamzn** [comment]
Once the calls are connected using the 'Contact.prototype.conferenceConnections` api, you will need to destroy on the first agent's connection and then on the second agent's connection in order to end the call, yes (because we want an agent to be able to leave without ending the call). Note that you may destroy the agent connections in any order, and the call will persist until all agent connections are destroyed.

**Comment by faizaanshah** [comment]
I guess you are talking about blind transfer? All you need to do is to create a new connection and then use getAgentConnection.destroy method. Here is the sample
 
![gq](https://user-images.githubusercontent.com/22859078/73689038-2760ba00-46ef-11ea-89b9-700400169190.PNG)

Similarly there is cold transfer, Where agent stays in call until there is conference.
![gq](https://user-images.githubusercontent.com/22859078/73689205-8a525100-46ef-11ea-8e3a-b107e9a49491.PNG)
 

There is a very detailed blog by [Ivan Bliskavka](https://medium.com/@ibliskavka/how-to-implement-cold-transfer-in-amazon-connect-streams-api-8a06a39c8bac)

**Comment by martin-greenberg** [comment]
@Juzziee did this solution work for you?

**Comment by Juzziee** [comment]
Hi Martin,

It did indeed work for me. 
When attempting to drop out of the call and leave the customer and agent on the line. I used an abandon alternate line script.

`
    connect.agent(function(agent) {
        var thirdParty = window.myCPP.contact.getSingleActiveThirdPartyConnection();
        if(thirdParty) {
            thirdParty.destroy({
                success: function() { 
                    console.log("Abandon successfull");
                },
                failure: function() { console.log("Abandon failed");} 
            });
        } else {
            // Alt line has already been abandon. Revert to standard call state and unmute initial contact. 
            callState("callProgress");
            toggleHold();
        }  
    });
`
