### ISSUE TITLE
Routinely having "login window" open even when logged in

### ISSUE THREAD

**Issue by winzig** [amazon-connect/amazon-connect-streams#204]
I've noticed I'll have a new tab opened to the CCP v2 page that we're using when I reload my custom chat page. The error in the console right before this happens is:

`ACK_TIMEOUT occurred, attempting to pop the login page if not already open`

So instead of popping up a login page, since I'm already logged in, it just loads a new tab with the full screen CCP chat interface, which is not desirable. So it doesn't seem like triggering this based on an ACK_TIMEOUT is working properly?

**Comment by winzig** [comment]
Wouldn't `AUTH_FAIL` be a better event to trigger this behavior on?

**Comment by jagadeeshaby** [comment]
Looks like it's a scenario where CCP could not load within the embedded context with the default CCP_LOAD_TIMEOUT which is 3s https://github.com/amazon-connect/amazon-connect-streams/blob/1c26b7e736db2d92a30e04b6e0a7dbdec4fc5626/src/core.js#L458

You could try using the custom `ccpLoadTimeout` to offset the latency 

```
connect.core.initCCP(containerDiv, {
   ccpUrl:        ccpUrl,        /*REQUIRED*/
   ccpLoadTimeout: 5000
});

```

Also to note if you are using a SAML based Authentication it's preferred to turn off the default login popup option by setting - `loginPopup:    false` on the initCCP method.

**Comment by winzig** [comment]
@jagadeeshaby Thank you, we will try that as a workaround. However, does the logic seem correct? I.e. that a load timeout should trigger a login? Versus only triggering a login when an `AUTH_FAIL` occurs instead?

**Comment by imankurpatel000** [comment]
> Looks like it's a scenario where CCP could not load within the embedded context with the default CCP_LOAD_TIMEOUT which is 3s
> 
> https://github.com/amazon-connect/amazon-connect-streams/blob/1c26b7e736db2d92a30e04b6e0a7dbdec4fc5626/src/core.js#L458
> 
> You could try using the custom `ccpLoadTimeout` to offset the latency
> 
> ```
> connect.core.initCCP(containerDiv, {
>    ccpUrl:        ccpUrl,        /*REQUIRED*/
>    ccpLoadTimeout: 5000
> });
> ```
> 
> Also to note if you are using a SAML based Authentication it's preferred to turn off the default login popup option by setting - `loginPopup: false` on the initCCP method.

@jagadeeshaby So ideally with SAML I should set the `loginPopup: false` but without the login Popup how does the amazon connect authenticate? Because I can't seem to make it work with `loginPopup: false`

**Comment by jagadeeshaby** [comment]
>@jagadeeshaby So ideally with SAML I should set the loginPopup: false but without the login Popup how does the amazon connect authenticate? Because I can't seem to make it work with loginPopup: false. Even though I have already setup the SAML authentication properly I can only make it to work if loginPopup: true.

i missed out on this, Apologies i meant we expect our customers to call initCCP only after they do all SSO login, meaning that SSO would have already set the necessary cookies.  it could be as simple as your agent clicking login to CCP button that would load SSO URL which ultimately loads you custom CCP APP  ( SAML URL has a parameter called destination you can configure that to point to your custom app) and your Custom CCP app would then call InitCCP with loginPopup false and it would just work as you SAML flow would have set cookies already.

That being said you should be able to do this SAML SSO using initCCP loginURL  parameter with login Popup set to true as well
