### ISSUE TITLE
Safari support for CCP v2?

### ISSUE THREAD

**Issue by winzig** [amazon-connect/amazon-connect-streams#205]
Is support planned for Safari browsers for the v2 CCP interface? If so, is there an issue somewhere that I can follow to keep up on this?

**Comment by ctwomblyamzn** [comment]
Unfortunately we do not support Safari browsers at this time, and we have no official plans to do so as of now.

**Comment by winzig** [comment]
This is really disappointing, given the marketshare of iOS devices. It basically means CCP is not usable from iPad, since even third party browsers like Chrome are using Safari's rendering engine on iOS.
