### ISSUE TITLE
Agent started outbound call event?

### ISSUE THREAD

**Issue by VaibhavKakadeHS** [amazon-connect/amazon-connect-streams#208]
Hi, is there any event to know if the agent has started outbound call. So my use case is when the agent types some number in the widget and calls the user, I would want that outbound call started event.

**Comment by ctwomblyamzn** [comment]
We do not have an "onDialling" or "onCallingCustomer" API in streams, nor do we have a "Dialling" or "CallingCustomer" event, but we do have an `onStateChange` API that will trigger for every agent state change. One such agent state change that could happen is any given state to the `CallingCustomer` state. If that happens, it would indicate that the agent attempted to start an outbound call. We will consider an `onCallingCustomer` API as a feature request.

**Comment by VaibhavKakadeHS** [comment]
@ctwomblyamzn Thanks for the reply. I will try out the workaround mentioned.

**Comment by VaibhavKakadeHS** [comment]
@ctwomblyamzn The workaround you mentioned works for my use case. Thanks a lot.
