### ISSUE TITLE
Unusual data being added to endpoint phone number (inbound)

### ISSUE THREAD

**Issue by camstuart** [amazon-connect/amazon-connect-streams#211]
Recently, we have detected the following cruft being prefixed and post fixed to our caller endpoint:

```javascript
const cli = contact.getActiveInitialConnection().getEndpoint().phoneNumber
```
Resulting in:

```
sip:+61406111111@lily-outbound
```

I am stripping this with:

```javascript
cli = str.replace(/^sip\:/i, '').replace(/@lily-outbound$/i, '')
```

**Comment by hfahlbusch** [comment]
@camstuart Have you tried this:
=> [..].getEndpoint().stripPhoneNumber();

**Comment by ctwomblyamzn** [comment]
I am going to close this issue as it appears to have been answered. Thanks @hfahlbusch!
