### ISSUE TITLE
Detecting Agent Hang Ups using Streams

### ISSUE THREAD

**Issue by reyiv** [amazon-connect/amazon-connect-streams#213]
I'm not sure if this has been asked/answered before , I couldn't find it in open issues. If it has been answered, I apologize , please direct me to the answer. 

Is it possible to capture an event that identifies when an agent hangs up a call on the CCP (as opposed to the caller) .   I would like to identify on every call, whether the agent disconnected using the "End Call" button on CCP or if the caller disconnected.   I have searched for this and there doesn't seem to be a clear answer.   AWS has a blog post that refers to log entries in the CCP logs  (SIGNALING state or "Agent disconnected successfully") , however these entries are not seen in the CCP logs when I download them. 
Additionally,  the streams documentation mentions a state called "AgentHungUp" under the Agent States Logging section, however this is also not found in the CCP logs when searching in the downloaded file.  Even if it were, I'm at a loss to figure out how a log entry can be captured within your CCP code. 
Is there an agent state (or some other way) that can be used to capture whether it was the agent that disconnected the call using the "End Call" on the CCP  or  if it was the caller.  If this data can be made available in the contact.onEnded event , then the CTR can be updated with a contact attribute which will indicate who hung up on every call.

**Comment by DillonSykes** [comment]
Subscribe to the contactRefresh Event and you can check whether both connections are still active I don't know if this helps but this is what I have done when implementing warm transfer.

**Comment by ash5g** [comment]
Would also like to be able to subscribe or find out in some way if it was the agent that hung up the call. The agent hang up event is not available in the connect log download. Something like agent.onStateChange but for the AgentErrorStates as well as AgentAvailStates would be very handy.

**Comment by martin-greenberg** [comment]
@reyiv if you've found a solution to this question, is it okay with you if we resolve this issue?
