### ISSUE TITLE
agent.connect success handler

### ISSUE THREAD

**Issue by andersonjohnf** [amazon-connect/amazon-connect-streams#217]
The agent.connect success handler should have the contact object passed as a parameter, or should return the contact object.  Right now the success function is passed an empty object, and you have to jump through a lot of hoops to get the current contact after initiating a new connection via agent.connect

**Comment by ctwomblyamzn** [comment]
We are considering this a feature request. We will look into it in time. If you have a potential solution, feel free to submit a pull request!

Thanks for your suggestion.

**Comment by marcogrcr** [comment]
This is a duplicate of #216
