### ISSUE TITLE
Why would we want to overwrite the baked in AWS SDK found in Streams?

### ISSUE THREAD

**Issue by nmiddleweek** [amazon-connect/amazon-connect-streams#225]
Hello

In the README.md AND Documentation.md it states

> Streams has a "baked-in" version of the AWS-SDK in the ./src/aws-client.js file. Make sure that you import Streams before the AWS SDK so that the AWS object bound to the Window is the object from your manually included SDK, and not from Streams

Does this mean the baked-in AWS-SDK is a cut down version? Or is this note here because the updated version of the AWS-SDK isn't always re-built into Streams?

Thanks
Nick

**Comment by ctwomblyamzn** [comment]
This means the baked-in AWS-SDK is a cut down version built for the needs of Streams only. I will close this, as I think this answers your question. Feel free to reopen if you feel otherwise!
