### ISSUE TITLE
Agent security profile

### ISSUE THREAD

**Issue by Juzziee** [amazon-connect/amazon-connect-streams#226]
Is it possible to query the security profile of an agent using streams?

I would ideally like to make some screen elements that are only available to admin/call centre managers.

**Comment by ctwomblyamzn** [comment]
Good question! We don't expose security profile names in Streams at present, unfortunately. We will discuss the possibility of adding this functionality in the future. Thanks for your suggestion!

Do note that there are other ways of telling what sort of agent is currently using streams. For example, if you associate manager agents with, say, a Routing Profile named "ManagerRoutingProfile" you would be able to see that an agent's Routing Profile was called "ManagerRoutingProfile" by calling the `Agent.getRoutingProfile()` method. I hope that helps.

**Comment by ctwomblyamzn** [comment]
Reopening for visibility.
