### ISSUE TITLE
Not able to get Media Controller for Chat Connection

### ISSUE THREAD

**Issue by vijay-janar** [amazon-connect/amazon-connect-streams#227]
Hi Team,
I am trying to customize the Agent UI for Chat. I tried with the below code snippet given in the page 

**_https://github.com/amazon-connect/amazon-connect-streams/blob/master/cheat-sheet.md_** 

Seems like there is no method called getAgentConnections(), so I tried with getConnections(), getAgentConnection() still I am not getting the ChatConnection. Could you please help me how to get the ChatConnection from the contact object.

_connect.contact(function(contact){
contact.getAgentConnections().forEach(function(connection){
  // chat users
  if(connection.getMediaType() === connect.MediaType.CHAT){
      contact.getConnection().getMediaController()
      .then(function(controller){
          controller.onMessage(function(response){
              console.log("data", response)
          })
          controller.sendMessage({message: "so and so", contentType: "text/plain"})
              .then(function(res, req){
                console.log(res.status)
          });
          controller.onDisconnect(function(){
              console.log("on disconnect");
          })
      });
  }
});_

Thanks
Vijay

**Comment by winzig** [comment]
I had similar issues, check my closed issue to see if it may help: https://github.com/amazon-connect/amazon-connect-streams/issues/197

**Comment by vijay-janar** [comment]
Thanks a lot. It works fine after I created the connect stream js file by including ChatJS in the make file.

**Comment by AlexAsirvathamPersistent** [comment]
@vijay-janar could you post the steps you did to add the chatjs file, i am stuck in the same scenario. thank you
