### ISSUE TITLE
contact.getAgentConnection().getMediaController() throws CORS error and "Failed to fetch connectionDetails with createParticipantConnection" error

### ISSUE THREAD

**Issue by nickvargas82** [amazon-connect/amazon-connect-streams#228]
I am getting an error with getAgentConnection().
I have a simple code to send a message upon chat connection.

```
connect.contact(function (contact) {
    contact.onConnected((c) => {
        console.log('CONNECTED');        
        c.getAgentConnection().getMediaController().then(controller => {
            controller.sendMessage({message: "message from agent", contentType: "text/plain"}).then(function(res, req)
            {
                console.log(res.status);
            });
        })                  
    });
});
```

It throws few CORS related errors:

> Access to XMLHttpRequest at 'https://participant.connect.us-west-2.amazonaws.com/participant/connection' from origin 'https://xxxx.xxx' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> VM949:1 POST https://participant.connect.us-west-2.amazonaws.com/participant/connection net::ERR_FAILED

Then it throws this error:
> [ERROR]: ChatClient error when creating connection request 
> Connect Failed with data:  {"_debug":{"reason":"Failed to fetch connectionDetails with createParticipantConnection","_debug":{"type":"NetworkingError","message":"Network Failure","stack":["NetworkingError: Network Failure","    at XMLHttpRequest.<anonymous> (https://xxx.xxx/xxx/js/aws-sdk-2.628.0.min.js:6:3738)"]}},"connectSuccess":false,"connectCalled":true,"metadata":null}

Can anyone please point me to the right direction on how to fix this? Thanks.

**Comment by Ashutosh257** [comment]
I can help you with that, can you tell me how are you accessing the connect instance?
Are you accessing it through secret access key and access key? or something else

**Comment by nickvargas82** [comment]
I am using this initialization as mentioned in the documentation:

```
connect.core.initCCP(container, {
    ccpUrl: ccpURL,
    loginPopup: false,
    softphone: {
        allowFramedSoftphone: true,
        disableRingtone: false
    }
});
```

I also tried updating the AWS credentials by sending the aws access key, secret access key and session key from connect to the UI via contact attributes but didn't help.

**Comment by nickvargas82** [comment]
Did a little more debugging and it's actually the getMediaController() that throws the error.

> "Failed to fetch connectionDetails with createParticipantConnection"

I can call contactObj.getAgentConnection().getMediaType() successfully which returns "chat".

**Comment by nickvargas82** [comment]
Figured it out! For those who are interested, it was caused by mismatched regions. By default, it's using "us-west-2". If you have a connect instance in "us-east-1", you have to specify it in the initCCP().

```
connect.core.initCCP(container, {
    ccpUrl: ccpURL,
    region: "us-east-1",
    loginPopup: false,
    softphone: {
        allowFramedSoftphone: true,
        disableRingtone: false
    }
});
```
