### ISSUE TITLE
connect-streams-1.4.4 and connect-rtc-1.1.5 causes signalling_handshake_failure

### ISSUE THREAD

**Issue by yeoji** [amazon-connect/amazon-connect-streams#229]
I have found integration issues with using `connect-streams-1.4.4` and `connect-rtc-1.1.5` together. It seems to cause a `signalling_handshake_failure` when we try to make a call with the embedded softphone.

<img width="331" alt="Screen Shot 2020-03-03 at 9 42 33 am" src="https://user-images.githubusercontent.com/8002179/75726293-2d6da900-5d36-11ea-9d98-983cc47234b2.png">

Using `connect-rtc-1.1.3` with `connect-streams-1.4.4` seems to work, but there have been instances when the call is made successfully, but the softphone shows the same error as the image above.

**Code used to init the softphone**
```
<script>
        var softphoneDiv = document.getElementById('softphone');

        // Modify this with your Connect details
        var yourCCPPage = 'https://blabla.awsapps.com/connect/ccp#'

        var softphoneParams = {
            ccpUrl: yourCCPPage,
            loginPopup: true,
            loginPopupAutoClose: true,
            softphone: {
                allowFramedSoftphone: false
            }
        };
        connect.core.initCCP(softphoneDiv, softphoneParams);
        connect.core.initSoftphoneManager({ allowFramedSoftphone: true });
</script>
```

Has anyone else tried to integrate both `connect-streams-1.4.4` and `connect-rtc-1.1.5` together successfully?

**Comment by gargvk10** [comment]
connect-rtc-js version > v1.1.3 and connect stream 1.4.4 version must use CCP V2 endpoint.

<script> var softphoneDiv = document.getElementById('softphone'); // Modify this with your Connect details var yourCCPPage = 'https://blabla.awsapps.com/connect/ccp-v2/' var softphoneParams = { ccpUrl: yourCCPPage, loginPopup: true, loginPopupAutoClose: true, softphone: { allowFramedSoftphone: false } }; connect.core.initCCP(softphoneDiv, softphoneParams); connect.core.initSoftphoneManager({ allowFramedSoftphone: true }); </script>
