### ISSUE TITLE
Agent Queues / Call Agent

### ISSUE THREAD

**Issue by tgxn** [amazon-connect/amazon-connect-streams#230]
Hey, 
I am trying to see if it's possible to establish a voice call (either a transfer, while in a call; or a new contact) with another agent, given some details about them (their username, queueARN, or name).

I have been playing around with the routingProfile's "queues" array, which always contains a queue with `name: null` and an ARN like `arn:aws:connect:ap-southeast-2:AWS_ACCOUNT:instance/CONNECT_INSTANCE/queue/agent/GUID`

Using a custom `Endpoint` I hoped it would be possible to initiate a new contact with the user, similar to how we are creating outbound calls to phone numbers, but I always recieve this error when trying this:
```
...
AWSClient: <-- Operation 'createOutboundContact' failed: {\"message\":\"Only phone number addresses are supported.\",\"code\":\"BadEndpointException\",\"time\":\"2020-03-09T14:32:08.233Z\"
...
```

**Comment by ctwomblyamzn** [comment]
I will see if our co-team can support something like this in the future.

**Comment by Winner244** [comment]
we are still waiting for it

**Comment by tgxn** [comment]
Yes, this is still an issue - being able to create calls direct to other agents is something that we are still looking for.
