### ISSUE TITLE
Can we send DTMF tone via the Streams API?

### ISSUE THREAD

**Issue by starkshaw** [amazon-connect/amazon-connect-streams#231]
I was trying to add DTMF tones to a third-party phone number when I make outbound calls to them as a reference number. However, it seems it's not possible via Streams API.

**Comment by ctwomblyamzn** [comment]
This is possible through the [`VoiceConnection.sendDigits` API](https://sim.amazon.com/issues/LILAX-493). Hope that helps! I'm going to close this as I think this answered your question. Please reopen if it did not!
