### ISSUE TITLE
Agent 1 transfer to Agent 2, can Agent 1 know if the transfer failed

### ISSUE THREAD

**Issue by scyforce** [amazon-connect/amazon-connect-streams#232]
Are there any events on Agent 1 side, can let agent 1 know the transer failed (liked Agent2 is not online, agent 2 rejects the call, call times out on agent 2 side etc.)?

**Comment by scyforce** [comment]
@jagadeeshaby , any idea? today I only see it comes as disconnected, so I can not differentiate if the call is disconnected because agent 2 hangs up or agent 2 doesn't pick up the call.

**Comment by adityajadhavfromblaze** [comment]
Any updates on this question? I have same scenario to handle
