### ISSUE TITLE
Example code in agent.setState is incorrect

### ISSUE THREAD

**Issue by riderchoi** [amazon-connect/amazon-connect-streams#233]
In the example provided in agent.setState:

`
var routableState = agent.getAgentStates().filter(function(state) {
   return state.type === AgentStateType.ROUTABLE;
})[0];
agent.setState(routableState, {
   success: function() { ... },
   failure: function() { ... }
});
`

should be:
`var routableState = agent.getAgentStates().filter(function(state) {
   return state.type === connect.AgentStateType.ROUTABLE;
})[0];
agent.setState(routableState, {
   success: function() { ... },
   failure: function() { ... }
});`

**Comment by ctwomblyamzn** [comment]
Our bad! We would love if you could submit a pull request for this!

**Comment by ctwomblyamzn** [comment]
Update: I updated `Documentation.md` and fixed this issue.
