### ISSUE TITLE
CCP in React.js microphone not accessible

### ISSUE THREAD

**Issue by Chu-CloudHesive** [amazon-connect/amazon-connect-streams#240]
Hi I have a React.js implemenation of the CCP that used to work, but now since the new ccp version it gives me an error that "Microphone is not accessible". I've tried different approaches but still getting it. Does anyone have encountered with this issue?

**Comment by marcogrcr** [comment]
@Chu-CloudHesive I faced a similar issue, and I was able to fix it with the following:

```js
connect.core.initCCP({
  // (...)
  softphone: {
    allowFramedSoftphone: true
  }
});
```

From the [docs](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md):

> Normally, the softphone microphone and speaker components are not allowed to be hosted in an iframe. This is because the softphone must be hosted in a single window or tab. The window hosting the softphone session must not be closed during the course of a softphone call or the call will be disconnected. If `allowFramedSoftphone` is `true`, the softphone components will be allowed to be hosted in this window or tab.

---

You can also use the barebones React setup that I documented on #88 if you want to work backwards from there to see what things specifically on your app/configuration is causing it to break.

If this does not solve your problem, I recommend that you provide a bit more context about your problem (e.g. `amazon-connect-streams` version, browser, React version, args to `connect.core.initCCP()`).

**Comment by Chu-CloudHesive** [comment]
@marcogrcr The issue was in the version of the amazon-connect-streams I was importing. Also I had to use `window.connect` to access the connect variable because it wasn't avalibale. Now it works fine. Thanks for the help.

**Comment by vmgolubev** [comment]
@Chu-CloudHesive How did you solved this issue? We are experiencing the same issue right now and we tried everything, but it looks working only with loginPopup: true and allowFramedSoftphone: true...
