### ISSUE TITLE
Outbound call which doesn't connect transitions agents from non-routable status to available

### ISSUE THREAD

**Issue by benmissionlabs** [amazon-connect/amazon-connect-streams#241]
- Agent is set to a non-routable status e.g. break
- Make an outbound call to a number which isn't answered so times out
- Connect puts the agent into FailedConnectCustomer status
- Immediately the status then reverts to Available rather than the previously selected agent status

We've tested this against CCPv1 and v2 and it seems to be a bug rather than intended behaviour. 
 I'm not sure if it's Streams at fault here or an issue with CCP/Connect

Thanks

**Comment by kvs6rj** [comment]
To clarify does agent go
NonRoutable State -> FailedConnectCustomer -> Available
Or 
NonRoutable State -> FailedConnectCustomer -> ACW -> (Clear Contact) -> Available

**Comment by benmissionlabs** [comment]
Agent goes from...

NonRoutable State -> FailedConnectCustomer -> Available

**Comment by ctwomblyamzn** [comment]
Hi @benmissionlabs this is a long-term bug that we are aware of. It will be fixed soon, but I don't believe I am able to give exact dates. I will try to update this thread once the fix has been pushed out.

**Comment by benmissionlabs** [comment]
No problem....we'll keep an eye on it in any case to see if we notice a fix drop in.  Thanks for your help.

**Comment by ctwomblyamzn** [comment]
With our recent deployment, this should be fixed for all regions. Let us know if you still have problems.
