### ISSUE TITLE
How to reject an incoming call?

### ISSUE THREAD

**Issue by ozkologlu** [amazon-connect/amazon-connect-streams#245]
When a contact is initially connecting, attempting to destroy the contact's connection from the streams api will throw a webrtc error in the CCP iframe.

Is there any possible way to reject an incoming call from within the streams api and clear the contact, so they are once again available and begin waiting for the next incoming call?

Example of code that will cause the CCP iframe to throw a webrtc error:
```
connect.contact((contact) => {
    const initialConnection = contact.getInitialConnection();

    initialConnection.destroy({
        success: () => {
            console.log('successfully rejected call!');
        },
        failure: (error) => {
            console.log(error);
        }
    });

    return;
}
```

**Comment by ctwomblyamzn** [comment]
Hi @ozkologlu, sorry about the long response time. You were very close here. Unfortunately, the `contact.getInitialConnection()` method will always retrieve the customer-side connection, not the agent connection. To get the agent connection, instead use the `contact.getAgentConnection()` method, and then call `connection.destroy()` on that connection. Hope that helps. I'm going to resolve this issue. Please reopen if you have more issues.
