### ISSUE TITLE
Contact onAccepted Handler does not provide contact as parameter

### ISSUE THREAD

**Issue by hfahlbusch** [amazon-connect/amazon-connect-streams#247]
If I register an `on accepted` handler on a contact `c` the callback function does not get the contact data as stated in the api documentation (https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#contactonaccepted)

Code example:

```
c.onAccepted(function(contact) { 
   console.log(contact);
});
```

This logs `null` to the console.

Calling the same callback log function with the onConnecting function (https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#contactonconnecting) returns the contact data correctly. Both function signatures are similar.

Not sure if other contact event handlers are affected too.``

**Comment by tgxn** [comment]
You can access the contact event from within the contact event - There should only be one `contact` with multiple subscriptions.

https://github.com/amazon-connect/amazon-connect-streams/blob/master/cheat-sheet.md
```
var c;
connect.contact(function (contact) {
    c = contact;

    c.onAccepted(function(ignorethis) { 
       console.log(c);
    });
});
```

Some of the subscription handlers have the contact in the callback attribute and some do not.

**Comment by hfahlbusch** [comment]
@tgxn Thanks for your answer. I already have a way to access the contact in the on accepted handler, that's not my biggest issue. 

Due to the documentation bug we lost an hour and nearly implemented a bug in our library, because we tested for some other events that worked. (New users should bump into that)
Would be good to have the right documentation or to implement the handlers in a consistent way. Maybe it's only a bug in the function that calls the event handler.
Do you know which other handlers do not provide the contact in the callback function?

**Comment by ctwomblyamzn** [comment]
This issue has been resolved since June 25th: https://github.com/amazon-connect/amazon-connect-streams/commit/2b3342b5ada4b3eb1756b096c3a090caefbc9eea#diff-e1d62d8c4965edf0e532dfa19da0891fR641. Please upgrade to the latest version of streams to get this fix.
