### ISSUE TITLE
Is there any way to read Agent Email Address ?

### ISSUE THREAD

**Issue by praveshbansal** [amazon-connect/amazon-connect-streams#249]
Currently, there is a method to get Agent Configuration
agent.getConfiguration()

- agentStates: See agent.getAgentStates() for more info.
- dialableCountries: See agent.getDialableCountries() for more info.
- extension: See agent.getExtension() for more info.
- name: See agent.getName() for more info.
- permissions: See agent.getPermissions() for more info.
- routingProfile: See agent.getRoutingProfile() for more info.
- softphoneAutoAccept: Indicates whether auto accept soft phone calls is enabled.
- softphoneEnabled: See agent.isSoftphoneEnabled() for more info.
- username: The username for the agent as entered in their Amazon Connect user account.

Is there any way where I can get the Agent Email Address as well? I have to trigger some mail to the agent using this?

**Comment by jolim24601** [comment]
This isn't currently supported, you will want to maintain your own table for username -> email for now.

**Comment by jolim24601** [comment]
#246 is a duplicate, so closing this one
