### ISSUE TITLE
Random Failure in "agent.getEndpoints" API while transferring using Quick connects

### ISSUE THREAD

**Issue by Harsha453** [amazon-connect/amazon-connect-streams#251]
agent.getEndpoints(
   queuesARNs,
   {
      success: function(data) {
         var endpoints = data.endpoints; // or data.addresses
//transfer using these endpoints 
      },
      failure: function(err) {
      }
   }
);

Hi @haochi-aws , sometimes while transferring using quick connects i am getting failure in getEndpoints Api even after having proper Queue ARN.
[ERROR]: 'getEndpoints' API request failed: [object Object]'

**Comment by Harsha453** [comment]
Hi, @ctwomblyamzn please anyone look into this ASAP as it creating many issues in our product

**Comment by jolim24601** [comment]
Hi @Harsha453,

Could you please provide more information? This will be easier to debug if you could provide the error message, streams version, etc.

**Comment by Harsha453** [comment]
Hi @jolim24601, i got the reason for this, "when we change the routing profile, it won't immediately replicate in agent object which results in a call from previously assigned queue to be routed to agent, but when we do getEndPoints api for this call, it will throw error as contact queue is not configured with agent now".


	'{"type":"InvalidStateException","message":"Exception thrown while retrieving end-points for AgentId 775e663f-e873-4379-a9a3-..........: Invalid contact state.","stack":["InvalidStateException: Exception thrown while retrieving end-points for AgentId 775e663f-e873-4379-a9a3-...............: Invalid contact state.","    ........

**Comment by jolim24601** [comment]
Hi @Harsha453 

Can you give me the list of steps to reproduce this? It sounds like a bug that is happening when you change an agent's configuration while they are Available.

Thanks.

**Comment by Harsha453** [comment]
Hi @jolim24601,
 make a call to agent, then change the routing profile,
So, at this point try using agent.getEndPoints API with contact queue, which will throw this error stating
"{"type":"InvalidStateException"..."
I can see it happening during change in routing profile

**Comment by Harsha453** [comment]
Hi @jolim24601, can you please give me update on this

**Comment by jolim24601** [comment]
Hi @Harsha453 

When calling `agent.getEndpoints` you should also pass in the result of `agent.getAllQueueARNs` to ensure that the proper queues are getting passed in.

**Comment by Harsha453** [comment]
Hi @jolim24601, i am passing proper queue only, but change in routing profile and then using this endpoint API is the problem.
