### ISSUE TITLE
Support for electron App

### ISSUE THREAD

**Issue by imankurpatel000** [amazon-connect/amazon-connect-streams#252]
Hello,

It looks like it won't be possible to use Amazon Connect Streams in an electron app as ideally, the electron apps don't open the website URL, they instead open a local index.html file in the browser. So the document.URL will be a file path instead of some HTTPS URL. And since Amazon connect streams require the URL to be explicitly whitelisted to allow it to embed the CCP, there won't be any way to use it in electron APP unless I open the URL instead of the local HTML file in the electron App.

I would still like to know if there is some way around it to make it work in an Electron App.

Thanks

**Comment by jolim24601** [comment]
Hey @imankurpatel000 please see #166, closing this as it's a duplicate.
