### ISSUE TITLE
Outgoing/Callback missed call

### ISSUE THREAD

**Issue by Juzziee** [amazon-connect/amazon-connect-streams#253]
Hi guys,

When an agent misses a scheduled callback, is there a way to catch this state? 
It appears that contact.onMissed is not flagged in this situation. 

Has anyone else found a solution to capture this?

**Comment by ctwomblyamzn** [comment]
Hi! We currently don't support flagging this state, its on our roadmap though so stay tuned. Please check our documentation, which will have announcements as we make updates.

**Comment by seiyako** [comment]
Hi @Juzziee,
The contact.onMissed() works for queued callback scenario now. You can verify it with the code like this below. 

```
connect.contact((contact) => {
    contact.onMissed(() => {
        console.log('contact.onMissed');
    });
});
```

Also you can check if the missed contact is a queued callback or not by calling `contact.getType()`.
