### ISSUE TITLE
Pause and resume recording through Connect Streams

### ISSUE THREAD

**Issue by DonaldMatthews** [amazon-connect/amazon-connect-streams#254]
Please can you confirm if the ability to pause and resume recording via the Connect Streams API is going to become available.

**Comment by ctwomblyamzn** [comment]
LILAX team is considering this feature for 2021 (planning still in progress). I'm going to mark this closed, as we are already tracking this internally.

**Comment by DonaldMatthews** [comment]
Thanks, we can see that there is a now an Amazon Connect API which we can access via API Gateway.
https://aws.amazon.com/blogs/contact-center/pausing-and-resuming-call-recordings-with-a-new-api-in-amazon-connect/
