### ISSUE TITLE
Monitoring status

### ISSUE THREAD

**Issue by Juzziee** [amazon-connect/amazon-connect-streams#255]
Hey all.

Has anyone had any experience monitoring calls through a custom CCP?
I have been able to initialise the monitoring. I am looking for an event or function that I can query to check if Amazon connect is currently monitoring a call.

Does anyone have any information that might assist me?

**Comment by CiscoKidxx** [comment]
Hey there, I'm curious how you were able to initialize the monitoring from this library? Do you have an example you'd be willing to share?

**Comment by Juzziee** [comment]
> Hey there, I'm curious how you were able to initialize the monitoring from this library? Do you have an example you'd be willing to share?

Investigating the network traffic when trying to perform a call monitor through Connect gives you a link similar to:

https://YOURCONNECTINSTANCE.awsapps.com/connect/manager-listen-in?agentMediaLegId=PHONECONNECTIONID&agentResourceId=AGENTID&token=CSRFTOKEN

You can call this from your site to initialise the call monitor.

**Comment by CiscoKidxx** [comment]
How are you learning the token in your app?

**Comment by Juzziee** [comment]
Unfortunately, I haven't made it that far yet.
I did find that you don't actually need to send the token for the function to work.
A support ticket with Amazon has come back to me advising me that there is currently no support for requesting tokens or monitoring from a custom ccp

**Comment by ctwomblyamzn** [comment]
Hi @Juzziee, I don't believe you can directly initiate monitoring via API right now, however if you initiate it through the Administrator Website's Real Time Metrics page (<instance-alias>.awsapps.com/connect/real-time-metrics), Streams will detect the new contact, just like any other contact. It can be differentiated via `contact.getInitialConnection().getType() === connect.ConnectionType.MONITORING`

**Comment by slugger2410** [comment]
Hi,
I have been trying to monitor an ongoing call, but couldn't make it. 
Will you please help? My issue is described here. #537
