### ISSUE TITLE
Getting the name of the agent that initiated a quick connect

### ISSUE THREAD

**Issue by Darkneon** [amazon-connect/amazon-connect-streams#258]
Hi guys,

I'm trying to add a short message that displays 'Transfer from <Agent Name>' but I can't seem to find the agent name. When I inspect the connections during `onConnecting`, although I see an `name` property it's always null. Is there a way to accomplish this?

Thanks

**Comment by scyzenefits** [comment]
I don't think you can know if the inbound call is transfer or not

**Comment by Christian-Sesta** [comment]
I was wondering if there was any progress on this @ctwomblyamzn ?

This is especially frustrating when it comes to multi party conferences with multiple internal transfers, as there is no way for me to currently identify who is who. The only thing I can think of is to add connection info to my external transfer directory, HOWEVER, the connection IDs are not unique for the contact interaction. The UUIDs for all connections are unique to the connected agent, NOT the contact interaction as a whole. So this will sadly not work :(

**Comment by gjesse** [comment]
this is pretty annoying, as far as i can tell there's still no way to really tell who is who on a multiparty call. sometimes the quick connect name is populated, but often it's just 'INTERNAL-TRANSFER'.

**Comment by Christian-Sesta** [comment]
@ctwomblyamzn Has this progressed at all?

**Comment by Christian-Sesta** [comment]
Love the github actions, its been like this for 90 day's waiting for a response. Can we get a response on this @ctwomblyamzn ?

**Comment by alexgurr** [comment]
Relevant for us too, as we generate quick connects with UUIDs and are unable to differentiate queues or agents, with names. Bump!

**Comment by oharez** [comment]
> Hi guys,
> 
> I'm trying to add a short message that displays 'Transfer from ' but I can't seem to find the agent name. When I inspect the connections during `onConnecting`, although I see an `name` property it's always null. Is there a way to accomplish this?
> 
> Thanks



> Hi guys,
> 
> I'm trying to add a short message that displays 'Transfer from ' but I can't seem to find the agent name. When I inspect the connections during `onConnecting`, although I see an `name` property it's always null. Is there a way to accomplish this?
> 
> Thanks



> Hi guys,
> 
> I'm trying to add a short message that displays 'Transfer from ' but I can't seem to find the agent name. When I inspect the connections during `onConnecting`, although I see an `name` property it's always null. Is there a way to accomplish this?
> 
> Thanks

I'm assuming custom CCP, are you hosting views and such? I can think of a few ways to do this if you have access in your CRM/the CCP host- to the trace records and agent data stream. Could do it from client side when the agent is receiving a contact - contact.onPending() or contact.onConnecting() -  that is a transfer type, use the CID to match to agent data stream, get the previous agent from there. So contact.getInitialConctactId() returns the initial contact id if an internal transfer, lookup that prior contactId in your agent status data, trace record may not have been created- especially if original agent is still in ACW, then the prior contact will still "exist" within Connect, and thus a trace record won't yet have been created.
