### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by boblail** [amazon-connect/amazon-connect-streams#260]
Hello!

Thank you for providing this library, for versioning it, and publishing it on npm!

Would you also maintain a `CHANGELOG.md` document?

It would help us tremendously in all the obvious ways:
- Choosing when to run `yarn upgrade amazon-connect-streams`
- Seeing whether a bug we're experiencing was fixed in a subsequent version
- Knowing when to anticipate API contract changes

Thank you 🙏

**Comment by ctwomblyamzn** [comment]
Hi @boblail we have provided a change log. I will encourage the team to keep it up to date with each minor version release!
