### ISSUE TITLE
How to properly integrate with amazon-connect-chatjs?

### ISSUE THREAD

**Issue by marcogrcr** [amazon-connect/amazon-connect-streams#261]
According to [the documentation](https://github.com/amazon-connect/amazon-connect-streams/blob/1.4.8/Documentation.md#a-few-things-to-note-1), in order to use the chat functionality, you'll need to include `amazon-connect-chatjs`. So far, here's how my code looks:

```js
import "amazon-connect-streams";
import "amazon-connect-chatjs";

connect.contact(contact => {
  if (contact.getType() !== connect.ContactType.CHAT) {
    return;
  }

  contact.onAccepted(async () => {
    const cnn = contact
      .getConnections()
      .find(c => c.getType() === connect.ConnectionType.AGENT);

    if (!cnn) {
      return;
    }

    const { controller } = await cnn.getMediaController();

    // I had to examine the internals of `ChatSession` to figure this out
    // See: https://github.com/amazon-connect/amazon-connect-chatjs/blob/1.0.6/src/core/chatSession.js#L67-L69
    //
    // This works, but I would love to use the publicly documented `.onMessage()` API
    // See: https://github.com/amazon-connect/amazon-connect-chatjs/blob/1.0.6/README.md#connectchatsessioncreate
    controller.subscribe("INCOMING_MESSAGE", data => {
      // do something with `data`
    });
  });
});
```

This works just fine, however `controller` is an [instance of `ChatController`](https://github.com/amazon-connect/amazon-connect-chatjs/blob/1.0.6/src/core/chatController.js#L24) instead of an [instance of `ChatSession`](https://github.com/amazon-connect/amazon-connect-chatjs/blob/1.0.6/src/core/chatSession.js#L62). There are two problems with this:

- The documentation of `amazon-connect-streams` is misleading by [indicating `chatConnection.getMediaController()` obtains a `ChatSession` object](https://github.com/amazon-connect/amazon-connect-streams/blob/1.4.8/Documentation.md#chatconnectiongetmediacontroller).
- `ChatController` is an internal class and implementation detail of `amazon-connect-chatjs`. The only publicly exposed and documented API is `ChatSession`.

It seems it's trivial to obtain a `ChatSession` from a `ChatController` instance. You just [pass it to the constructor as an argument](https://github.com/amazon-connect/amazon-connect-chatjs/blob/1.0.6/src/core/chatSession.js#L63-L65). Unfortunately, this constructor is not publicly exposed. You can only create instance of `ChatSession` by using the [`ChatSession.create()` method](https://github.com/amazon-connect/amazon-connect-chatjs/blob/1.0.6/src/core/chatSession.js#L148).

---

Given this information, what's the appropriate way to integrate with `amazon-connect-chatjs`?

**Comment by ctwomblyamzn** [comment]
After discussing offline with @marcogrcr, looks like the use of `getMediaController` was confusing in our internal implementation, as we assign the return object of `ChatSession.create()` to a variable named `controller`. HOWEVER, this variable represents a `ChatSession` object, not a `ChatController` object. This is definitely misleading, apologies. In summary, `getMediaController` DOES return a `ChatSession`. Your usage is correct, if you replace `const { controller } = await cnn.getMediaController();` with `const session = await cnn.getMediaController();`.
