### ISSUE TITLE
Chat contact missed results in error status rather than missed status

### ISSUE THREAD

**Issue by Christian-Sesta** [amazon-connect/amazon-connect-streams#272]
Currently `contact.onMissed()` is not being fired when a contact chat has been missed.

From my understanding of what I have read `contact.onMissed()` seems to only handle call cases, but it should really handle both voice/ chat. This is because weather a contact is a voice/ chat contact they are a contact that has been missed.

Documentation snippet:

> Subscribe a method to be invoked whenever the contact is missed. This is an event which is fired when a contact is put in state "missed" by the backend, which happens when the agent does not answer for a certain amount of time, when the agent rejects the call, or when the other participant hangs up before the agent can accept.

**Comment by sseidel16** [comment]
This is indeed the behavior, and although I coded my application appropriately, it does not seem right that it should go into error state and not missed state. Can this be fixed/updated?

**Comment by Christian-Sesta** [comment]
Not to sure if the issue is related to the chat contact status being wrong, however it seems that if a chat contact has been missed (currently error status) any event subscriptions setup by `conn.getMediaController()` (chat session) is not cleaned up (i.e. `chatSession.onMessage()`, `chatSession.onTyping()`), even though the session itself has been destroyed. 

I would destroy the subscriptions myself, but the only bit of logic to do that seems to be within the chat session itself which has already been destroyed at this point.

**Comment by Christian-Sesta** [comment]
@sseidel16 Looks like version 1.4.8 that came out the same day as I raised this issue might have resolved the event handler `contact.onMissed()` not firing for chat contacts as its now triggering for me. Let me know if this solves your problem, if so we can close this ticket then.

**Comment by sseidel16** [comment]
@Christian-Sesta I still need to check if `onMissed()` is firing, but after upgrading to 1.4.8 (from 1.4.6), I am using the npm module, a missed chat still enters into the error state `ContactStateType.ERROR`. This seems off since `ContactStateType.MISSED` never seems to occur.

**Comment by sseidel16** [comment]
Confirmed that `onMissed()` is getting called! That behavior is new. The weird part is that it then enters the error state.

**Comment by sseidel16** [comment]
@Christian-Sesta Confirmed that `onMissed()` is getting called! That behavior is new. The weird part is that it then enters the error state. After upgrading to 1.4.8 (from 1.4.6), I am using the npm module, a missed chat still enters into the error state `ContactStateType.ERROR`. This seems off since `ContactStateType.MISSED` never seems to occur.

**Comment by Christian-Sesta** [comment]
@sseidel16 Oh weird. That might explain why a missed chat contact is not cleaning up the subscriptions I previously mentioned. As it triggers `onMissed()` but after that goes into an error state, possibly due to not being able to cleanup the chatSession correctly?

**Comment by sseidel16** [comment]
@Christian-Sesta I do not have much input on that. I designed my app to not subscribe to messages and events until after the chat was accepted so I have never run into the issues you mention above. Very interesting though.

**Comment by Christian-Sesta** [comment]
@sseidel16 fair enough, In our Call contact system we usually show all information about the contact to an agent before they have accept a call so they can respond must faster to a customers query. Was pretty much trying to do the same thing here with chat and showing the current transcript and subsequent messages coming through before accepted.

Since the original issue around `onMissed()` not working has been resolved as part of version 1.4.8 I will be closing this ticket.
