### ISSUE TITLE
Send Message to agent after the chat has ended

### ISSUE THREAD

**Issue by ketsthechanger** [amazon-connect/amazon-connect-streams#275]
Hi,
I want to be able to send a message to the agent once the customer chat has ended (either by agent or customer) but before the agent clicks on "Close contact". 
Is there any custom code that I need to write using Streams API or can I achieve this in Contact Flows using any block?

**Comment by ctwomblyamzn** [comment]
Hi @ketsthechanger. At this time, that is not possible using the Streams API or Contact Flows. Sorry about that! We certainly know that this is a requested feature. Stay tuned.
