### ISSUE TITLE
How to change the default CCP ringtone in Chrome?

### ISSUE THREAD

**Issue by BCSZSZ** [amazon-connect/amazon-connect-streams#276]
I would like to change the default ringtone of my CCP.
I currently refer to the page:

https://github.com/amazon-connect/amazon-connect-streams/blob/master/README.md

the inInitialization part says:

## Initialization
Initializing the Streams API is the first step to verify that you have
everything setup correctly and that you will be able to listen for events.

### `connect.core.initCCP()`
```html
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
  <head>
    <script type="text/javascript" src="amazon-connect-1.4.js"></script>
  </head>
  <!-- Add the call to init() as an onload so it will only run once the page is loaded -->
  <body onload="init()">
    <div id=containerDiv style="width: 400px;height: 800px;"></div>
    <script type="text/javascript">
      var instanceURL = "https://my-instance-domain.awsapps.com/connect/ccp-v2/";
      // initialise the streams api
      function init() {
        // initialize the ccp
        connect.core.initCCP(containerDiv, {
          ccpUrl: instanceURL,            // REQUIRED
          loginPopup: true,               // optional, defaults to `true`
          region: "eu-central-1",         // REQUIRED for `CHAT`, optional otherwise
          softphone: {                    // optional
            allowFramedSoftphone: true,   // optional
            disableRingtone: false,       // optional
            ringtoneUrl: "./ringtone.mp3" // optional
           }
         });
      }
    </script>
  </body>
</html>
```
Integrates with Connect by loading the pre-built CCP located at `ccpUrl` into an
iframe and placing it into the `containerDiv` provided. API requests are
funneled through this CCP and agent and contact updates are published through it
and made available to your JS client code.
* `ccpUrl`: The URL of the CCP. This is the page you would normally navigate to
  in order to use the CCP in a standalone page, it is different for each
  instance.
* `region`: Amazon connect instance region. ex: `us-west-2`. only required for chat channel.
* `loginPopup`: Optional, defaults to `true`. Set to `false` to disable the login
  popup which is shown when the user's authentication expires.
* `loginPopupAutoClose`: Optional, defaults to `false`. Set to `true` in conjunction with the `loginPopup` parameter
  to automatically close the login Popup window once the authentication step has completed.
  If the login page opened in a new tab, this parameter will also auto-close that tab.
* `loginUrl`: Optional. Allows custom URL to be used to initiate the ccp, as in
  the case of SAML authentication.
* `softphone`: This object is optional and allows you to specify some settings
  surrounding the softphone feature of Connect.
  * `allowFramedSoftphone`: Normally, the softphone microphone and speaker
    components are not allowed to be hosted in an iframe. This is because the
    softphone must be hosted in a single window or tab. The window hosting
    the softphone session must not be closed during the course of a softphone
    call or the call will be disconnected. If `allowFramedSoftphone` is `true`,
    the softphone components will be allowed to be hosted in this window or tab.
  * `disableRingtone`: This option allows you to completely disable the built-in
    ringtone audio that is played when a call is incoming.
  * `ringtoneUrl`: If the ringtone is not disabled, this allows for overriding
    the ringtone with any browser-supported audio file accessible by the user.

it looks like no problem to play with ringtoneUrl to satisfy my need but I somehow fail to do it.

I store my CCP html in my S3 like this:

https://MYS3.s3-ap-northeast-1.amazonaws.com/ccp_dir/index.html

It works fine for me with other feature.

And if I change the "disableRingtone" to true, it works and there is no ringtone at all when I receive a call.

However, when "disableRingtone" is set to false and ringtoneUrl is set, it is always the default ringtone.

I store the mp3 file in the same dir with my CCP index.html file,like:

https://MYS3.s3-ap-northeast-1.amazonaws.com/ccp_dir/ringtone01.mp3

my ringtoneUrl is like this:

"https://MYS3.s3-ap-northeast-1.amazonaws.com/ccp_dir/ringtone01.mp3"

"./ringtone01.mp3"

"ringtone01.mp3"

none of them works for me.

Sorry if this turn out to be some stupid question but I really appreciate some help or enlightment.

**Comment by sseidel16** [comment]
I have only been able to make this work by providing the entire URL, not relative, and I have tried many different ways. Just enter the full URL for the audio file location and it should work.
