### ISSUE TITLE
How to get call connecting and Connected status for Outbound calls

### ISSUE THREAD

**Issue by dineshkaruppiaht** [amazon-connect/amazon-connect-streams#277]
Am currently trying to make the Outbound call flow with Agent. Am able to make outbound calls with Streams API.But Unfortunately am unable to hook the Contact states which is Connecting and Connected (Outbound) to display the same accordingly on the Custom UI created. 

Is any one facing this issue ? 

Kindly suggest if any possible way i can try to make to hook the Connecting and Connected states for outbound call.

**Comment by ax2to** [comment]
Try with event subscription

```
connect.contact(function (contact) {
  contact.onAccepted(function (contact) {
	console.log('call is accepted!');
  });

  contact.onConnected(function (contact) {
	console.log('call is connected!');
	let awsConnectId = contact.getAgentConnection().getConnectionId();
	console.log(awsConnectId);
  });

  contact.onMissed(function (contact) {
	console.log('call is missed');
  });

  contact.onEnded(function (contact) {
	console.log('call is ended');
  });
});
```

**Comment by dineshkaruppiaht** [comment]
Thanks for the reply.

Am able to see the call connected status on the console.But now am not able to invoke any functions or methods inside contact method. For example , I have to  change the view of Connecting panel to Connected panel for this i have created two different templates , one for Connecting and another for connected based on the status am trying to enable/disable the fields , but am able to call my internal method to invoke this functionality. I have enclosed my sample code for understanding

contact.onConnected(function (contact) {
	console.log('call is connected!');
	//calling enable component method here
       this.enableconnectedComponent = true; //this line not woring
  });

  contact.onEnded(function (contact) {
	console.log('call is ended');
this.enableconnectedComponent = false; //this line not woring
  });

index.html
------------
<div id="connected_component" *ngIf="enableconnectedComponent"/>

Kindly advise

**Comment by tomsabin** [comment]
This is likely due to the context of `this` being changed when you're within the event handlers. A quick workaround could be to retain the reference of the `this` in another variable to reference again in the event handler:

```diff
+ const that = this;

connect.contact(function (contact) {
  contact.onConnected(function (contact) {
    console.log('call is connected!');
    //calling enable component method here
-    this.enableconnectedComponent = true; //this line not woring
+    that.enableconnectedComponent = true;
  });

  contact.onEnded(function (contact) {
    console.log('call is ended');
-    this.enableconnectedComponent = false; //this line not woring
+    that.enableconnectedComponent = false;
  });
});
```

**Comment by dineshkaruppiaht** [comment]
Thank you so much for the suggesting this works !
