### ISSUE TITLE
IVR input through voice without lex

### ISSUE THREAD

**Issue by tayyabgilani** [amazon-connect/amazon-connect-streams#278]
i just want to know can we take input in IVR through voice without lex in amazon connect. If yes So, How?

**Comment by ctwomblyamzn** [comment]
Hi, this isn't exactly relevant to amazon-connect-streams, but we have two options for collecting customer information in contact flows: DTMF input, and lex. Therefore, if you want the customer to be able to make selections with their voice, you will need to use lex. [See an example IVR survey here](https://aws.amazon.com/blogs/contact-center/building-a-survey-ivr-system-with-amazon-connect/)
