### ISSUE TITLE
Amazon lex Slots break

### ISSUE THREAD

**Issue by tayyabgilani** [amazon-connect/amazon-connect-streams#279]
hi i have 2 slots type in lex one is Membership Number and 2nd is Pin.
i wanted to know in contact flow can we check Membership number from database before moving to second slot which is pin.
mean if we enter wrong membership number it check first if it is wrong ask me again to say membership number (means check each slots 1 by 1 from db). hope so you understand my question.
Thanks

**Comment by tayyabgilani** [comment]
@marcogrcr

**Comment by marcogrcr** [comment]
Hello @tayyabgilani. Unfortunately I am not a member of the Amazon Connect team that maintains this library. I have not personally used Lex integration in Amazon Connect, so I can't provide you with guidance on that matter.

**Comment by magdnede** [comment]
@tayyabgliani, you can check the membership number against a database by using a validation Lambda in Lex. https://docs.aws.amazon.com/lex/latest/dg/ex-book-trip-create-integrate.html

**Comment by martin-greenberg** [comment]
We're going to close this issue because this is not a question related to this library, but please feel free to submit a support request to AWS Support for guidance on how to set up your contact flows.
