### ISSUE TITLE
Error in connect-streams.js: Cannot set property 2011-06-15 of [object Object]

### ISSUE THREAD

**Issue by pijus-r** [amazon-connect/amazon-connect-streams#280]
I have integrated Amazon Connect Streams (through NPM) to Angular 9 project and everything worked as a charm, but after transferring all of the code from child to parent folder and running `ng serve` again I got this error.

 ```
connect-streams.js:20985 Uncaught TypeError: Cannot set property 2011-06-15 of [object Object] which has only a getter
    at Object.push../node_modules/amazon-connect-streams/release/connect-streams.js.107.../apis/connect-2017-02-15.min (connect-streams.js:20985)
    at o (connect-streams.js:4)
    at r (connect-streams.js:4)
    at Object../node_modules/amazon-connect-streams/release/connect-streams.js (connect-streams.js:4)
    at __webpack_require__ (bootstrap:79)
    at Module../src/app/app.module.ts (app.module.ts:1)
    at __webpack_require__ (bootstrap:79)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:79)
    at Object.0 (main.ts:12)

```

Error is caused by this line in connect-streams.js: 
`AWS.apiLoader.services['sts']['2011-06-15'] = require('../apis/sts-2011-06-15.min');
`

    "typescript": "^3.9.6"
    "amazon-connect-streams": "^1.4.9"

**Comment by pijus-r** [comment]
main.component.ts

`import {Component, OnInit} from '@angular/core';
import "amazon-connect-streams";


@Component({
    selector: 'app-main',
    templateUrl: './main.component.html',
    styleUrls: ['./main.component.scss']
})
export class MainComponent implements OnInit {


    constructor() {
    }


    ngOnInit(): void {

        const CCP_URL = "https://biomapas-robsta-test.awsapps.com/connect/ccp-v2/";
        const LOGIN_URL = "https://biomapas-robsta-test.awsapps.com/connect/login/";

        const container = document.getElementById("ccp");
        connect.core.initCCP(container, {
            ccpUrl: CCP_URL,
            loginUrl: LOGIN_URL,
            loginPopup: true,
            loginPopupAutoClose: true,
            softphone: {
                allowFramedSoftphone: true
            }
        })

    }

}
`

**Comment by pijus-r** [comment]
@ctwomblyamzn

**Comment by tecstang** [comment]
Try importing amazon-connect-streams asynchronously in the ngOnInit() method.

`ngOnInit(): void {
    this.initAmazonConnectStreams();
  }

  private initAmazonConnectStreams(): void {
    from(import('amazon-connect-streams/release/connect-streams-min.js')).pipe(
      take(1),
      tap(() => this.initCCP()
    )).subscribe();
  }

  private initCCP(): void {
    const ccpContainer = this.ccpContainer.nativeElement;
    connect.core.initCCP(ccpContainer, this.config);
    this.connectInitState.upadteStateToInitialized();
  }`

This way you avoid the initial TypeError (and possibly a follow-up window reference error).
That's how i got it to work with Angular 9 and Angular 10.

**Comment by martin-greenberg** [comment]
Looks like you were able to get this working, so I'll resolve this.

**Comment by Ibrahimkhattana123** [comment]
I am facing the same issue but couldn't fix it. can you please share the full code of component ts for my reference?

**Comment by Rynxiao** [comment]
Still facing this issue when I import as the `es` way.
```javascript
import 'amazon-connect-streams';
```
So I use `script` to import the sdk directly in the `html`. Worked as expected!
```html
<script src="./node_modules/amazon-connect-streams/release/connect-streams-min.js"></script>
```
