### ISSUE TITLE
onAccept handler not fired on deskphone

### ISSUE THREAD

**Issue by hfahlbusch** [amazon-connect/amazon-connect-streams#281]
I had some logic implemented that should fire, when an agent accepts a call. 
I tested this feature with my softphone and it worked out pretty well, but my customers agents had problems with the functionality until I figured out that they are using deskphones. 
My workaround was to use the onConnected event, but this seems like a bug to me.

**Comment by zesheng-amazon** [comment]
This issue should be fixed. Please let us know if you are still seeing this issue.

**Comment by ataraxg** [comment]
Hi I am re-opening this issue as i am experiencing the exact same issue:
The callback contact.onAccepted() is not triggered if using Deskphone
