### ISSUE TITLE
Contact `getQueue` sometimes returns `undefined`.

### ISSUE THREAD

**Issue by crrice** [amazon-connect/amazon-connect-streams#285]
Hello,

I have noticed a bug in my application caused when the contact object from the streams api returns `undefined` from the `contact.getQueue()` call. I am wondering two things:

* Is it expected behavior that this method will sometimes return `undefined`?
* If so, are you intentionally omitting `undefined` from the possible [return types of `getQueue` in the `index.d.ts` file](https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/index.d.ts#L868)?

Thank you,

**Comment by seiyako** [comment]
Hi @crrice, could you describe how to reproduce the error so that we can look into this?

**Comment by seiyako** [comment]
Closing this ticket because we haven't heard from the issuer for a while. Please reopen this issue when you see the same issue.
