### ISSUE TITLE
iFrame Connection Refused using SAML 

### ISSUE THREAD

**Issue by robertdippolito** [amazon-connect/amazon-connect-streams#286]
Hi All,

I am running into an issue when I attempt to embed the CCP panel on a static web page. I am hosting the static web page via S3/CloudFront. When I navigate to the web page a new tab is opened and the SSO between my IDP/Connect runs successfully. However, in the original tab the browser is refusing to frame my CCP.

I am seeing 'Firefox Can't Open This Page' (https://support.mozilla.org/en-US/kb/xframe-neterror-page?as=u&utm_source=inproduct) and Chrome is simply refusing to connect.

This suggests to me that the browser is restricting the CCP from being displayed. I have whitelisted my CloudFront domain with my Amazon Connect instance and the code below is the init snippet from my launchCCP.js that is attempting to launch the CCP.

`connect.core.initCCP(containerDiv, { `
    `ccpUrl:"https://<my-instance>.awsapps.com/connect/ccp-v2/"`,  
    `  loginPopup: true`,
    `  loginUrl:"<saml-url>"`,
    `  softphone: {`
        `  allowFramedSoftphone: true`
     `}`
`})`;

The code that is initializing and ccp-v2/ is returning a 200 inside the <iframe>. There are no console / network errors so I am at a bit of a loss here. 

<img width="1094" alt="Screen Shot 2020-07-27 at 11 11 48 PM" src="https://user-images.githubusercontent.com/26776061/88614827-9562ba00-d05e-11ea-9e6d-a56226bae67b.png">

**Comment by robertdippolito** [comment]
As these things tend to work I have resolved the issue above. The root cause seems to be due to the fact that my ccpUrl was https://<my-instance>.awsapps.com/connect/ccp-v2/ instead of the appropriate RelayState Url https://<region>.console.aws.amazon.com/connect/federate/<instance-id>?destination=<ccp (encoded)>

Once this was updated i can now see the CCP embedded in the page.

**Comment by aguecida** [comment]
@robertdippolito This seemed to fix the issue in Firefox for me, where before I was getting the "Firefox Can’t Open This Page" error. But in Chrome I'm still getting the error "signin.aws.amazon.com refused to connect." Any ideas?
