### ISSUE TITLE
src/lib/amazon-connect-websocket-manager.js  needs newline at EOF

### ISSUE THREAD

**Issue by slass100** [amazon-connect/amazon-connect-streams#287]
makefile/compiled javascript corrupted because missing newline.

**Comment by ratsirarar** [comment]
This should be fix in the new coming release.

**Comment by martin-greenberg** [comment]
I'll close this as we have merged the temporary fix in the websocket manager file to fix the issue at present, and the issue has been permanently fixed for all our future releases.
