### ISSUE TITLE
Microphone Access in Embedded CCP Not Working (Chrome/Firefox)

### ISSUE THREAD

**Issue by robertdippolito** [amazon-connect/amazon-connect-streams#288]
Hi,

I have embedded my CCP panel in a static webpage hosted by CloudFront/S3 (via Lambda@Edge). I have configured an SAML instance and set up the appropriate connections with my IDP.

When I navigate to the static page I call my `connect.core.initCCP` with the following params:
ccpUrl: https://(region).console.aws.amazon.com/connect/federate/(instance id)?destination=%2Fconnect%2Fccp-v2
loginUrl: (my saml SSO url)
loginPopup: true
region: <region>
softphone: { alllowFramedSoftphone: true }

When the softphone initializes a new page is popped open and it redirects through my IDP to the softphone. The softphone successfully initializes and I am logged in - the browser then asks if it can access my systems speakers/microphone (I click accept). This tab stays open.

In the main tab my softphone initializes as expected. The problem I face is as follows: If I close the second tab my softphone indicates that the Microphone is no longer accessible.

![Screen Shot 2020-07-28 at 3 26 14 PM](https://user-images.githubusercontent.com/26776061/88711779-ae16b280-d0e6-11ea-9337-bcd62956a36c.png)

Even if I manually update the browser settings to allow the microphone it still shows the error above. If I add loginPopupAutoClose it also gives the above error.

I believe this is likely because the iframe that is launching the CCP needs access to the microphone and for some reason it is not taking the instructions from the browser. Has anyone seen an issue like this before? It seems similar to #271 but the behavior I am seeing is more limiting.

**Comment by efh365** [comment]
Hi Robert,

I was successfully able to reproduce what you are experiencing. The issue is with your CCP URL. It should be in the form of "https://${instanceAlias}.awsapps.com/connect/ccp-v2". Please update that value and let me know if that solves your problem.

**Comment by robertdippolito** [comment]
@efh365 thank you. This seems to solve a problem. Once i have updated the CCP URL the iframe is failing to frame the softphone. Per the screenshot below it appears that the content-security-policy does not include the whitelisted domains that I have configured for my instance which is why the iframe is not loading. This appears to be more of a CloudFront related problem but its unclear. 

![Screen Shot 2020-07-29 at 6 20 34 PM](https://user-images.githubusercontent.com/26776061/88859779-74b67380-d1c8-11ea-8d9d-4a485657f96d.png)

**Comment by robertdippolito** [comment]
Closing this issue. The original issue was correctly solved by @efh365 . The iframe denial was due to the fact that my edge lambda for my CloudFront had a Referrer-Policy set to same-origin which (by the looks of things) was preventing information from being sent to the iframe. After removing this header I am able to get the desired results.
