### ISSUE TITLE
Given a contact id, can a manager join an on-going live call? 

### ISSUE THREAD

**Issue by appsmehta** [amazon-connect/amazon-connect-streams#290]
Hello, 

We have an integration wherein we are storing the contactId for every call with a ticket number. Now we want to develop a feature where a manager sees a live call going on for a while and wants to join in the conversation. 

is there an api that allows joining the call if we know the contact id?

**Comment by ctwomblyamzn** [comment]
Hi, I don't think this is possible via API currently. The only way of doing this is to use the real time metrics page in the Connect Administrator website (<instance-url>/home)
