### ISSUE TITLE
Call keeps ringing the only agent in the queue after rejecting, despite being in non-routable state

### ISSUE THREAD

**Issue by runekaagaard** [amazon-connect/amazon-connect-streams#292]
Dear Amazon Connect. What I want to achieve is this:

- The agent receives an incoming call
- She presses a keyboard shortcut
- The call is rejected and she is in a non-routable state, in this case called "Inactive"

I've tried to call agent.setState() and contact.getAgentConnection().destroy() in any combination of agent.onError, contact.missed, contact.ended and agent.onStateChange I can think of but I can't get it to work reliably. Sometimes it works, but other times the agent is stuck in a loop of the same incoming call that she desperately is trying to hang up.

Help!?

**Comment by runekaagaard** [comment]
@scoland A saw you added the enhancement label. Does that mean it's impossible to do on the current version? Thx

**Comment by martin-greenberg** [comment]
I don't think we have enough details here to begin looking into this. Can you describe everything you've tried so far and exactly what the results were for each thing you tried?

**Comment by runekaagaard** [comment]
Hi martin-greenberg

Sorry for the delay, I've been involved with other things. I think you are solving the this exact problem with the upcoming "NextStatus" you have announced. Closing for now. Thanks for you help!
