### ISSUE TITLE
Pause recordings: Resource not found (after agent transfer and queue transfer)

### ISSUE THREAD

**Issue by james-coder** [amazon-connect/amazon-connect-streams#294]
We have Pause Recordings set up according to the custom CCP from CloudFormation in:
https://aws.amazon.com/blogs/contact-center/pausing-and-resuming-call-recordings-with-a-new-api-in-amazon-connect/

From within our Contact Flows we always start recordings for agent+customer and those recordings continue except when the agent pauses the recording to take confidential information.

Scenario: Agent 1 is in BasicQueue and available. Agent 1 receives a call and both sides (agent + customer) of the conversation is correctly recorded. Agent 1 clicks Quick Connect to transfer to another agent (agent transfer), Agent 2. The transfer of the call to Agent 2 is completed and Agent 1 drops off the call. Agent 2 talks to the customer and then presses "Pause" and this error happens: "Failed to PAUSE error: Resource not found". The same error happens when Agent 1 uses a Quick Connect to transfer to another queue (rather than agent).

We see the recorded call with the contact ID showing up in call reports after the calls is completed, so we know the recording is still in progress after the transfer even though we get the error when trying to pause. Pause works fine before a transfer, but fails after a transfer regardless of the actual state of call recording.

**Comment by seiyako** [comment]
Looks like this is not directly related to StreamsJS. We'll pass this issue to the related team.

**Comment by ctwomblyamzn** [comment]
I'm going to close this as this simply has no relevance to streams right now. Please file a support case for this to be addressed.
