### ISSUE TITLE
Rejecting calls

### ISSUE THREAD

**Issue by shaun0024** [amazon-connect/amazon-connect-streams#296]
When there is an incoming contact, the default CCP has an accept and reject button. I see that the contact API has an accept function, is there also a reject function?

Trying to implement a custom CCP UI and got the accept button to work but not reject. I've tried destroy but it doesn't appear to do anything.

**Comment by jolim24601** [comment]
You can use `Contact.prototype.getAgentConnection` and call `Connection.prototype.destroy`. We are working on releasing an API for this use-case and you should see an announcement soon.

**Comment by intptr-t** [comment]
An alternative until the official announcement.

```
connect.core.getClient().call("rejectContact", {
    contactId: contact.getContactId()
}, {
    success: function() {  },
    failure: function(err) { }
});
```
