### ISSUE TITLE
contact.onAccepted not returning connect.Contact

### ISSUE THREAD

**Issue by tylerlot** [amazon-connect/amazon-connect-streams#299]
The contact.onAccepted hook returns a plain JS object with contactId rather than the Connect.contact class with prototype methods, resulting in the inability to access any methods (i.e. getAttributes) using the value passed back into the hook.

**Comment by jolim24601** [comment]
Hi @tylerlot for now you can just instantiate a new `Contact` by calling `new connect.Contact(contactId)`. Will investigate this inconsistency as I believe this only happens when auto-accept is enabled (?) and fix it in a future release.

**Comment by tylerlot** [comment]
I am not using auto-accept, any timeline on which future release will have the fix?

**Comment by intptr-t** [comment]
Seems to have been fixed in Streams API 1.6.2

https://github.com/amazon-connect/amazon-connect-streams/commit/87b5c125951c414671f6ba00c1665b7aac9002de#diff-be21f3913edf585ffabb7db45b3beb835f40d313c713a812c163995f4c155173R22639-R22641
