### ISSUE TITLE
How to implement a custom heartbeat between the shared worker and CCP?

### ISSUE THREAD

**Issue by hernihub** [amazon-connect/amazon-connect-streams#300]
I have a React SPA and some backend services. The SPA relies on the shared worker to make API calls to the Connect instance.
I can't tell right now if it's a bug or not, but when changing states for an agent, I'm getting a InvalidStateException when this "connect heart beat" functionality I have warns when the shared worker is gone. This functionality executes every 30 seconds and invokes the agent.getEndpoints(ARNs[]).

Is there any other way to query or ping the worker and make sure is there? The calls happen inside a React SPA.

**Comment by jolim24601** [comment]
Hi @hernihub can you please share a code sample to better explain what it is you are trying to do?

**Comment by hernihub** [comment]
Thank you much, sorry about leaving that out.
What I'm trying to do is simply be aware of the ConnectShared worker. I have this fragment of code, part of the connect hear beat functionality that pings Amazon Connect instance:
```
beat = () =>
        Promise.race([this.makeRequest(), this.makeAlarm()])
            .then((result) => {
                if (result !== ConnectSuccess) {
                    this.updateState(false);
                    log.error(`Connect Heartbeat - ${result}`, {
                        errorCode: ERROR_CODES.AMAZON_CONNECT_STREAMS_HEARTBEAT_ERROR,
                        username: get(this.props, 'agentUsername'),
                    });
                    return this.props.onError(ConnectHeartbeatErrorMessage);
                }
                this.updateState(true);
                return true;
            })
            .catch(() => {});
```

```
makeRequest = () =>
        new Promise((success) => {
            const agent = this.getAgent();
            agent.getEndpoints(agent.getAllQueueARNs()[0], {
                success: () => success(ConnectSuccess),
                failure: (err) => {
                    const exception = JSON.parse(err).stack.toString();
                    return exception.startsWith(ConnectHeartbeatExpectedExceptionTypeText)
                        ? success(ConnectSuccess)
                        : success(`${ConnectFailure}: ${err}`);
                },
            });
        });
```

```
makeAlarm = async () => {
        await sleep(this.props.config.pollingTimeoutForConnectHeartbeatInMillis);
        return ConnectTimeout;
    };
```

So, after the component is mounted, it starts polling. That polling is simply a periodical heart beat, and if that GetEndpoints fails, it means that there is no connection to the worker.
The GetEndpoints call fails with InvalidStateException, for the Contact. That to me makes no sense, since there is no contact at that moment.
I realize now that even when it throws the exception, it means the worker is there; my whole SPA relies on that and whenever I terminate that worker manually, the SPA becomes completely unresponsive and a browser level refresh is in order.
The purpose of this heart beat is to know the worker is there so a pop-up shows telling the user to refresh the window.
I tried to query the workers through other means, but found none.
I'm silently handling the exception and validating the type of exception.

**Comment by hernihub** [comment]
I've just noticed that the CTIService.GetRoutingProfileQueues fails sometimes with `400 Bad Request - {"message":"Agent does not have access to this resource."}` and the next call is a 200 with the actual response.

**Comment by jolim24601** [comment]
I would not recommend depending on the API to return success to determine if the shared worker is up or down. May I ask why you need to do this? 

We do have a `KeepaliveManager` which you can use to ping the worker, you can call it with `connect.core.keepaliveManager.start()` and subscribe to a timeout with the code `connect.core.getEventBus().subscribe(connect.EventType.ACK_TIMEOUT, function () { ... })`. This flow happens automatically when `initCCP` is called and triggers a refresh of the CCP if it's being embedded in an iframe.

**Comment by hernihub** [comment]
Thanks.
We thought of this because we want to let the user know if a refresh has to happen if, for some reason, the app has lost connection to AC instance.
That might be unnecessary, but that's the reason.
I'll try that and keep this post updated.

I guess what we are trying to do in the end is understanding why is that operation failing.

**Comment by hernihub** [comment]
The issue was reformulated in terms of the worker behaviour.
