### ISSUE TITLE
What is the custom login URL, for SAML authentication ?

### ISSUE THREAD

**Issue by josefyendif** [amazon-connect/amazon-connect-streams#303]
Hi folks,
          my ccp did configured for SAML authentication,
       i have an sso account to use my custom ccp application pages logged in ?
 
            samlLoginURL = ??????????
           connect.core.initCCP(containerDiv, {
                ccpUrl: ccpUrl,	
		loginUrl: samlLoginURL,	      
    });

my question is where can i find the SAML url 

i have implement to testing the SSO to Amazon Connect Working Perfectly 
https://aws.amazon.com/blogs/contact-center/enabling-federation-with-aws-single-sign-on-and-amazon-connect/

**Comment by josefyendif** [comment]
Kindly Reply the answer about my question, there is no support for this

**Comment by GuidoNebiolo** [comment]
following

**Comment by math-ve** [comment]
Hi ! does anyone have an answer to this question ?

**Comment by marktheunissen** [comment]
Did anyone figure it out?

**Comment by marktheunissen** [comment]
@ctwomblyamzn We are still struggling to get AWS SSO working with this loginUrl parameter, this issue has been sitting for a year now without a response, please could you help by providing an example of what this loginUrl should look like, specifically to get this login flow working with AWS SSO?

**Comment by marktheunissen** [comment]
Found this document titled "Optimize your Amazon Connect call audio path": https://aws.amazon.com/blogs/desktop-and-application-streaming/optimize-your-amazon-connect-call-audio-path-with-amazon-appstream-2-0/

It contains the clue for where the AWS SSO url (**loginUrl**) comes from:

```
    connect.core.initCCP(
        container, {
            ccpUrl: "https://CCP-NAME/connect/ccp-v2/",
            loginPopup: true,
            loginPopupAutoClose: true,
            loginUrl: "URL-Gathered-From-SSO-Dashboard",
            softphone: {
                allowFramedSoftphone: false,
                disableRingtone: false
            }
        }
    )
```

Note: `URL-Gathered-From-SSO-Dashboard`. The document describes how to gather this URL as follows:

**_Step 6: Get the AWS SSO Application link_**
  Get the direct link to your AWS SSO application.

- Open the AWS Single Sign-On console.
- Select Applications, then select the Amazon Connect application you created
- Assign the custom Application to at least one test user.
- In the navigation pane, select Dashboard. Note the User portal URL.
- In a separate browser session, open the User portal URL, then login.
- Choose the hyperlink for your Amazon Connect application, and copy the link address. Save this Amazon Connect URL for later.

**Comment by martin-greenberg** [comment]
We're looking at how we can improve the documentation here, but the URL you need to use here will depend on the SSO vendor and would be the URL of the page to which you would send a user to authenticate in your SSO system, which has been configured to provide a SAML response to the Connect federation endpoint mentioned in the Connect documentation linked in the original question. It may not be feasible for us to provide up-to-date documentation on how to find this URL for every SSO vendor, but in every case it will be the same URL you would already be providing to your users to authenticate to your existing systems behind the same SSO. The instructions above should work if your vendor is AWS SSO.
