### ISSUE TITLE
Amazon have forced a CCP upgrade and I have lost functionality in Salesforce 

### ISSUE THREAD

**Issue by Selbo1978** [amazon-connect/amazon-connect-streams#304]
The CCP is no longer 'pinned' in Salesforce and Presence sync has stopped working, also call reasons have been removed from the flow. Can anyone help resolve this?

**Comment by yingdoli** [comment]
Hello, can you explain what you mean by "pinned"? There could be a domain whitelisting issue when upgrading CCP from v1 to v2. Can you check that you whitelist the visualforce url and Salesforce instance url? Please check the latest installation guide on domain whitelisting.

**Comment by Selbo1978** [comment]
The Whitelist was the resolution but the upgrade never mentioned anything about whitelisting. But thank you
