### ISSUE TITLE
Warm transfer make second call

### ISSUE THREAD

**Issue by sivac47123** [amazon-connect/amazon-connect-streams#305]
Warm transfer when we make second call the contact subscription not invoked for the onConnected and onConnecting events call back. 

Unable to identify the second call is connecting or connected. 
Is there any way to find the second call connection state.

**Comment by sivac47123** [comment]
We can use onRefresh to identify all the calls connected to the agent with the connection id.

**Comment by ctwomblyamzn** [comment]
Hi @sivac47123. Sorry this took so long for us to see. A warm transfer is modeled as an additional connection on the same contact, as indicated by the api name: `contact.addConnection`. Therefore, this new connection will reflect the states you are looking for, like going into the connecting and connected states. `contact.onRefresh().getSingleActiveThirdPartyConnection().getState()` will get you the state of the active warm transfer connection on each refresh to the contact object (refreshes will occur on connection state changes, as well as other changes to the contact object). I'm going to close this, as I think that answers your question. Please let me know if that is not satisfactory.
