### ISSUE TITLE
Warm transfer how to differentiate 2 calls connected

### ISSUE THREAD

**Issue by sivac47123** [amazon-connect/amazon-connect-streams#306]
After warm transfer completed we are unable to identify the which call is hold.getActiveinitialConnection.hold will hold the active initial connection. 

If we want to get the connection state in OnRefresh how we can identify which call is hold. First call or second call how do we differentiate the both calls. 

Contact events having the contact I'd which common for all. Connection I'd is unique for 3 connections. 

But we want to know onrefresh of contact state which connection is hold or resume or connecting or connected.

**Comment by sivac47123** [comment]
We can use onRefresh to identify all the calls connected to the agent with the connection id.

**Comment by seiyako** [comment]
Hi @sivac47123,
you can identify which connection is on hold by calling connection.isOnHold() API.
For example,
```
contact.onRefresh((_contact) => {
  const connections = _contact.getConnections();
  connections.forEach((con) => console.log(con, con.isOnHold()));
});
```

Hope this helps. Please reopen the ticket if you have more questions regarding this issue.
