### ISSUE TITLE
When we connected with two call resume all not working

### ISSUE THREAD

**Issue by sivac47123** [amazon-connect/amazon-connect-streams#307]
I have connected with two calls in a contact.
After connected two calls. I have 3 connections in the contact.
1. AgentConnection
2. ActiveInitialConnection
3. SingleActiveThirdPartyConnection

When doing resume all functionality we have invoked the below call

ActiveInitialConnection.resume()  - This will be success
SingleActiveThirdPartyConnection.resume() - This will be failure

Getting the below exceptions

"{"type":"InternalServiceError","message":"Cannot resume connection from hold","stack":["InternalServiceError: Cannot resume connection from hold","    at constructor.extractError (https://rescontactctr-sbx.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:98513)","    at constructor.callListeners (https://rescontactctr-sbx.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:120416)","    at constructor.emit (https://rescontactctr-sbx.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:120126)","    at constructor.emitEvent (https://rescontactctr-sbx.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:113835)","    at constructor.e (https://rescontactctr-sbx.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:109426)","    at r.runTo (https://rescontactctr-sbx.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:147717)","    at https://rescontactctr-sbx.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:147922","    at constructor.<anonymous> (https://rescontactctr-sbx.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:109695)","    at constructor.<anonymous> (https://rescontactctr-sbx.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:113890)","    at constructor.callListeners (https://rescontactctr-sbx.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:120522)"]}"

Thanks in advance for any help.

**Comment by sivac47123** [comment]
For resume all now we used the conference call functionality. Its working as expected.

**Comment by adityajadhavfromblaze** [comment]
@sivac47123  what solution you got working for resuming the third party call? in a conference

**Comment by sivac47123** [comment]
Thanks @adityajadhavfromblaze. Same steps i have tried. Its working fine.
