### ISSUE TITLE
Supported heights of CCP v2 widget does not match the documentation

### ISSUE THREAD

**Issue by runekaagaard** [amazon-connect/amazon-connect-streams#310]
Dear Amazon Connect

Thx for a great product. When switching to v2 CCP and embedding it in an iFrame with a height of 465px and width of 320px as per the documentation, scrollbars appears on some pages:

<img width="219" alt="Screenshot 2020-09-25 115853" src="https://user-images.githubusercontent.com/378464/94254072-84cba480-ff26-11ea-8862-852fac744524.png">

Are the docs wrong?

**Comment by angieyu** [comment]
Hi @runekaagaard can you please link the docs that you are referring to?

**Comment by runekaagaard** [comment]
Sure I'm referring to https://github.com/amazon-connect/amazon-connect-streams/blob/master/README.md and https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md. It reads:


    - The pre-built CCP UI is portrait oriented and capable of contracting horizontally to fit smaller widths. It can expand from a 
    width of 200px to a maximum of 320px based on the size of its container div. If the CCP is placed into a container 
    where it would be sized under 221px in width, the CCP switches to a different layout style with smaller buttons and fonts.
    
    - In its normal larger style, the CCP is 465px tall. In its smaller form, the CCP is reduced to 400px tall.

**Comment by vs-amzn** [comment]
It’s been a while and we are closing this for now. Please reopen if it’s still an issue
