### ISSUE TITLE
How to get number of holds from connect streams api

### ISSUE THREAD

**Issue by sivac47123** [amazon-connect/amazon-connect-streams#311]
We want to get the number of holds details from CTR. We can able to see this details under Agent section of CTR.
Is there anyway to get these details via connect streams api.

**Comment by angieyu** [comment]
CTR's are not available through the Connect Streams API. The Connect Streams API is for handling agent and contact state event. You can view the CTRs in this instance or stream the CTR's to Kinesis. Please see https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-metrics.html.
