### ISSUE TITLE
How to use amazon connect streams in Angular Application with customized User Interface design?

### ISSUE THREAD

**Issue by katrav03** [amazon-connect/amazon-connect-streams#315]
I am using the Amazon Connect Streams to Manage the call setting.
<img width="197" alt="Call" src="https://user-images.githubusercontent.com/68652876/94820204-cfb15480-041d-11eb-9800-847682335dbf.PNG">
 I tried to redesign the uploaded image, but it provides me the document(html document) in iframe tag. Is it possible to customize this iframe document based on my requirement? Please help me to sort out a solution on this.

**Comment by angieyu** [comment]
Hi @katrav03, when I want to modify the CCP to a certain degree, I inject the iframe into a div. Then I target the css classes to modify the styling. On the other hand, you can create a totally custom solution by initializing the CCP, hiding it, then using an app that you build to make the API calls. We are working on launching a custom CCP solution which will be released in the future. Does this answer your question or do you have more specific questions?

**Comment by amicming** [comment]
aws.training (free digital course) has an excellent way to explain. Not in Angular, but if someone knows Angular, it can easily configure. 

Look for `Amazon Connect: Build a Custom Call Control Panel` in https://www.aws.training/.

**Comment by sasidharsaikumar** [comment]
hi @angieyu ,how can i render the agent work space in angular application.is it possible ?if yes how can i do it could you please provide me sources
