### ISSUE TITLE
Coonect varibale not initialize in React app

### ISSUE THREAD

**Issue by indraneelnexright** [amazon-connect/amazon-connect-streams#317]
Connect Variable does not initialize in react app,

**Comment by amicming** [comment]
Can you please share the steps / Code? How you configure Connect? So someone can guide.

**Comment by ashwinisajjan** [comment]
@indraneelnexright, did you find a solution,  what was wrong?? I'm in also in the same situation,  can you please help me if you have got your answer.

**Comment by h3adache** [comment]
This issue doesn't give us enough information to address the issue. Can you please reopen it with more details (preferably a sample project displaying the issue).
