### ISSUE TITLE
app freezes with CHAT (VOICE working)

### ISSUE THREAD

**Issue by amicming** [amazon-connect/amazon-connect-streams#318]
Hello,

We are currently in the process of adding chatJS in our custom CCP (Angular app).  When I'm accepting the incoming chat request, the whole app freezes with no Error message.

Here are the steps I'm doing to initiate a Chat request.

1.  Added amazon-connect-chat.js after connect-streams.js in HTML file 

2. after initCCP, I'm checking if 

    a. contact.getType() is CHAT or VOICE

3. VOICE part working good

4. If CHAT, I'm trying to open a window that has an "Accept" button. If someone clicks on the "Accept" button, it goes to contact.onAccepted. 

If I make VOICE, all the flow is working as expected. If I make a Chat request, I can see the "Accept" dialog, but I cannot click on the Accept button the whole app freezes. 

Here, I'm trying to make **Custom CCP Chat UI for Agent**. I'm using Angular 8+, NodeJS.

Any Idea / Direction on Chat? Are there any steps I missed?

**Comment by seiyako** [comment]
Hi @amicming, sorry for the delayed response. Have you figured out how to resolve the issue you mentioned above? Did you set `region` parameter to initCCP() properly? If the issue still persists, could you share the screen shot / error messages in the developer console (of the tab or the shared worker)?

**Comment by seiyako** [comment]
Closing the ticket for now as there's no response for a month. Please reopen the ticket when you are still having the issue.
