### ISSUE TITLE
Hide pre-built UI 

### ISSUE THREAD

**Issue by amicming** [amazon-connect/amazon-connect-streams#319]
Hello,

We've custom CCP (Angular app). We initiate all calls using InitCCP and stream javascript SDK. 

We noticed when user login to Custom CCP, immediately open pre-built UI. 

We added below CSS code in the respective CSS file, but no help

```
.containerDiv iframe {
  display: none;
}
```

We added the below code in the HTML file, too but no help.

`<div id="containerDiv" style="width: 320px; min-width: 200px; height: 465px; min-height: 400px;display: none; "></div>`

Any idea / Suggestion or Direction to fix this issue?

**Comment by h3adache** [comment]
Hi this is a documentation bug I believe.

Try
```
#containerDiv iframe {
  display: none;
}
```

**Comment by amicming** [comment]
@h3adache , it looks like working now. Thanks

**Comment by h3adache** [comment]
Good to hear!
