### ISSUE TITLE
contact.destroy not working

### ISSUE THREAD

**Issue by karanagarwal17** [amazon-connect/amazon-connect-streams#320]
Hello,

We are creating an agent response app where we are hiding the CCP and using the API to access functionality. 

I am able to accept the incoming call request using contact.accept().
But, the contact.destroy() is not working. I was trying to end the chat using this. 
Afterwards, contact.clear() is also working to close the contact. 

Anything I am missing here/ Any other way to end the chat?

**Comment by amicming** [comment]
@karanagarwal17 , Can you please code snippet ? How do you handle `destroy` call.

**Comment by ctwomblyamzn** [comment]
Hi @karanagarwal17. Our documentation is outdated for this api (being updated very soon). In reality, `connection.destroy()` is how you should end the agent chat connection. Once you have ended it, you can call `contact.clear()`.
