### ISSUE TITLE
How to add custom agent status using connect streams API

### ISSUE THREAD

**Issue by sivac47123** [amazon-connect/amazon-connect-streams#324]
Hi Team,

Is possible to add custom agent status through amazon connect API or Amazon connect streams API.

We have the requirement to add the custom agent status by custom application itself.

Appreciate your help to resolve this.
 
Thanks and Regards
Siva

**Comment by scoland** [comment]
Hi Siva,

Unfortunately we don't currently have APIs for actually creating a new agent status from Streams.

**Comment by sivac47123** [comment]
Thanks @scoland for your response.
