### ISSUE TITLE
How to add, modify and delete quick connect using Amazon connect streams API

### ISSUE THREAD

**Issue by sivac47123** [amazon-connect/amazon-connect-streams#325]
Hi Team,

We have the requirement to add, modify and delete new quick connect using Amazon connect streams API or Amazon connect API.

Is there anyway to do this.

Appreciate your help on this.

Thanks and Regards
Siva

**Comment by scoland** [comment]
Hi Siva,

Unfortunately we don't currently have APIs for these operations in either streams or the Amazon Connect API.

**Comment by sivac47123** [comment]
Thanks @scoland for your response.
