### ISSUE TITLE
initCCP Login Popup on page

### ISSUE THREAD

**Issue by lukeschmidt-wisc** [amazon-connect/amazon-connect-streams#326]
We are implementing the amazon connect streams API on a project and our client doesn't like the additional step of having to open another tab to login.  Is it possible to have the popup login open on the site's page rather than opening a new tab?  I am assuming no due to same origin policy.

**Comment by h3adache** [comment]
A related feature was added in [1.5.1](https://github.com/amazon-connect/amazon-connect-streams/releases/tag/1.5.1)
You can get the login in a new popup vs a new tab by adding [`loginOptions`](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#connectcoreinitccp)

```          loginOptions: {                 // optional, if provided opens login in new window```

There is currently no feature to open in the same page. Does the new window solve your use case?

**Comment by lukeschmidt-wisc** [comment]
Thank you for the response.  In our case it didn't solve the issue since our client wanted to open the screen in the same page. However, we find using the loginPopup, loginPopupAutoClose, and loginOptions help for various testing and production purposes.
