### ISSUE TITLE
Support named imports

### ISSUE THREAD

**Issue by tomsabin** [amazon-connect/amazon-connect-streams#327]
Currently, the Amazon Connect Streams package cannot be imported as a named module, i.e. these do not work:

`import { connect } from 'amazon-connect-streams'`
> TypeError: Cannot read property 'core' of undefined

`import { core } from 'amazon-connect-streams'`
> TypeError: Cannot read property 'initCCP' of undefined

`import * as connect from 'amazon-connect-streams'`
> TypeError: Cannot read property 'initCCP' of undefined

`import connect from 'amazon-connect-streams'`
> TypeError: Cannot read property 'initCCP' of undefined

Instead, the only option that we have is to import the package to the global namespace:

`import 'amazon-connect-streams';`

where it will define a global variable `connect`.

This inflexibility leads to a conflict (and possible confusion) with other packages that are named `connect`, for example the Redux `connect`. But more importantly, it prevents importing only certain parts of the Streams package in various parts of the web app - for example, importing only `ContactEvents` to use in tests.

I'd add the `enhancement` tag to this request, but it doesn't seem as though I can

**Comment by Ibrahimkhattana123** [comment]
i have imported this in my angular 9 projects. I am getting this error: 
Uncaught TypeError: Cannot set property 2011-06-15 of [object Object] which has only a getter
    at Object.push../node_modules/amazon-connect-streams/release/connect-streams-min.js.105.../apis/connect-2017-02-15.min (connect-streams-min.js:1)
    at u (connect-streams-min.js:1)
    at i (connect-streams-min.js:1)
    at Object../node_modules/amazon-connect-streams/release/connect-streams-min.js (connect-streams-min.js:1)
    at __webpack_require__ (bootstrap:84)
    at Module../src/app/ccp/ccp.component.ts (ccp.component.ts:1)
    at __webpack_require__ (bootstrap:84)
    at Module../src/app/app.module.ts (app.module.ts:1)
    at __webpack_require__ (bootstrap:84)
    at Module../src/main.ts (main.ts:1)

**Comment by ChenYangMei** [comment]
I tried to use `const connect = require('amazon-connect-streams')` inside a `if (typeof window !== `undefined`)` block, due to  `navigator is not defined` for SSR in gatsby. However `connect` turned out to be an empty object.

**Comment by SeanGroff** [comment]
> I tried to use `const connect = require('amazon-connect-streams')` inside a `if (typeof window !== undefined)` block, due to `navigator is not defined` for SSR in gatsby. However `connect` turned out to be an empty object.

I have this same issue in Next.js.

Has anyone found a workaround for this issue?

**Comment by tomsabin** [comment]
This may give you some pointers @SeanGroff, we ended up creating another file `app/packages/amazon-connect.ts` with the following contents:

```ts
import 'amazon-connect-streams';
import 'amazon-connect-chatjs';

const amazonConnectStreams = connect;

export default amazonConnectStreams;
```

and then importing Connect from that module instead, e.g. for a component named `app/components/Example/index.tsx`:

```tsx
import connect from 'app/packages/amazon-connect'

export const Example: React.FC = () => {
  const ccpContainerEl = useRef<HTMLDivElement>(null);

  useEffect(() => {
    connect.core.initCCP(ccpContainerEl.current!, {
      ...
    });
  
    ...
  
    return () => {
      connect.core.terminate();
      ccpContainerEl.current!.innerHTML = '';
    };
  }, []);

  return (
    <div ref={ccpContainerEl} />
  )
}
```

**Comment by SeanGroff** [comment]
> ```tsx
> connect
> ```

@tomsabin That worked for you? I still get the same error `navigator is not defined` This doesn't prevent the code from being read server side. Are you using Next.js?

**Comment by IsaacTrevino** [comment]
@SeanGroff  I was able to get `amazon-connect-streams` working on Next.js.

First, specify `amazon-connect-streams` as a precompiled type to be included in your project. 
In you tsconfig.ts:
```typescript
{
  "compilerOptions": {
   // ...other options
    "types": [
      "amazon-connect-streams",
    ],
  }
}
```

Then import your connect streams within your use-effect since navigator is a browser function.

```typescript
/* eslint-disable no-undef */
import { useRef, useEffect } from 'react';

const CCP = () => {
  const ccpContainerEl = useRef(null);

  useEffect(() => {
    require('amazon-connect-streams');

    connect.core.initCCP(ccpContainerEl.current, {
      ccpUrl: 'https://rgv-metro-waste.my.connect.aws/ccp-v2',
      region: 'us-east-1',
      loginPopup: true,
      // loginUrl: 'https://rgv-metro-waste.my.connect.aws/connect/login',
      // loginPopupAutoClose: true,
      loginOptions: {
        autoClose: true,
      },
      softphone: {
        allowFramedSoftphone: true
      },
      pageOptions: {
        enablePhoneTypeSettings: false,
        enableAudioDeviceSettings: true
      }
    });

    return () => {
      connect.core.terminate();
      ccpContainerEl.current = null;
    };
  }, []);

  return (
  <>
    <div
      style={{
        width: '100%',
        height: '100%',
      }}
      id="ccp-container"
      ref={ccpContainerEl}
    />
  </>
  );
}

export default CCP;
```

**Comment by tomsabin** [comment]
> @tomsabin That worked for you? I still get the same error `navigator is not defined` This doesn't prevent the code from being read server side. Are you using Next.js?

Yes, we're using Next.js and imported the component as follows from a page component:

```jsx
import dynamic from 'next/dynamic';

const AmazonConnectChat = dynamic(() => import('../components/AmazonConnectChat'), {
  ssr: false,
});

...
```

(where the path `../components/AmazonConnectChat` leads to the `Example` component above in my earlier example)
