### ISSUE TITLE
Browser refresh drops audio, possible to reconnect it?

### ISSUE THREAD

**Issue by sromocki** [amazon-connect/amazon-connect-streams#33]
If I'm on a call and I refresh the browser and initialize the CCP app again, the call is still "connected" but there is no audio.  Is it possible to reconnect the audio stream?

**Comment by ninjamike54** [comment]
As it currently exists, if the audio stream is terminated, it won't be able to reconnect. We're looking at various ways to improve this, such as being able to reconnect the audio, or at least being honest and disconnecting the call when the audio is definitely lost, but I unfortunately don't have any details about what exactly we will do here (or when it'll happen).

**Comment by CiscoKidxx** [comment]
@ninjamike54 - Any update on this?

**Comment by chrisckchang** [comment]
a current workaround: you can use an agent quick connect or an agent queue to transfer the call back to yourself to recover it. the customer isn't impacted by this as long as you have your transfer to agent and transfer to queue flows set to not play anything. it will look like a new call and will impact reporting, however that *may* be than losing the call.

**Comment by DillonSykes** [comment]
any update on this or any other workarounds?

**Comment by 0-g-r-e-g-0** [comment]
The workaround that @chrisckchang shared works pretty well.
I think that a good long term solution may be to make it possible to configure a flow to handle this situation. That way we can each decide what our customer experience will be when this happens.
In my opinion, the current situation is better than dropping the call though - although honest, the situation is recoverable and termintating the connection sounds harsh.

**Comment by jamesbyars** [comment]
Exactly how does one implement the workaround @chrisckchang mentioned @0-g-r-e-g-0 ?

**Comment by maronov-amzn** [comment]
Apologies for the delay. Unfortunately the only current workaround is the one suggested above to transfer the call back to yourself. We are tracking the issue internally.

**Comment by evilC** [comment]
@ninjamike54 
3 years seems like an awfully long time to not address such an issue. Is there still no ETA on a proper fix?
Also, regarding the "Redirect to yourself" workaround - is there a way to programmatically detect that this has happened and automatically do the redirect?

**Comment by Logesh5** [comment]
any update on this ?

**Comment by tamilmani-m** [comment]
Any update on this ?

Both microphone and speakers are not working, when I refresh the browser during the call.

**Comment by dschueler** [comment]
5 YEARS and this is still being ignored by AWS....pretty sad. Since the call is still there and you can transfer it back and regain it there MUST be a way to handle this in AWS Code. PLEASE Amazon...we're trying to run ENTERPRISE call centers here!

**Comment by MAsad-Nawaz** [comment]
@ninjamike54  Hi, any update on this issue? is there any progress?

**Comment by 0-g-r-e-g-0** [comment]
Re-testing this today has shown that now, even if you transfer the call to a flow that re-transfers it back to the agent, the audio for the remote call is no longer reconnected to the agent audio.
This method for audio reconnection has worked previously.
This is a step backwards that makes this issue more critical.

**Comment by 0-g-r-e-g-0** [comment]
Further testing has shown that the workaround intermittently results in fully connected audio. Sometimes only 1 in 5 tests result in working audio, other times it will recover the audio 4 times in a row, or fail to recover the audio 4 times in a row.

**Comment by MAsad-Nawaz** [comment]
> Further testing has shown that the workaround intermittently results in fully connected audio. Sometimes only 1 in 5 tests result in working audio, other times it will recover the audio 4 times in a row, or fail to recover the audio 4 times in a row.

I'm getting the same error. If I reload (browser reload hit) the page during the call, there is no voice coming, but the connection is live. I have to destroy the connection and make a new call then I will get a voice from the customer. Can you please guide on this?

**Comment by 0-g-r-e-g-0** [comment]
> Further testing has shown that the workaround intermittently results in fully connected audio. Sometimes only 1 in 5 tests result in working audio, other times it will recover the audio 4 times in a row, or fail to recover the audio 4 times in a row.

Following up again.
Initially, I was releasing the agent leg after it got connected to the flow. The problem is that sometimes this released is too soon. Changing this to complete the conference and then leaving it allowed the hand off part to work properly.

**Comment by 0-g-r-e-g-0** [comment]
@jamesbyars  and @MAsad-Nawaz this is a high level description of how I handle it:
1 - Setup contact attribute updates using the AWS API
2 - Write a flow that can receive a transfer, look at a contact attribute and use it as the destination to transfer a call to the queue of the agent identified in the contact attribute.
3 - Setup a quick connect that points to the flow and make it available to your agents
4 - If you login and find an active softphone call in progress, assume that the audio is not connected.
5 - Set the agent ID in the contact attribute and wait until you see this contact attribute get updated in the amazon connect streams events
6 - Conference the call to the quick connect
7 - Wait until you see the new connection for the conference
8 - Release the call
9 - Make your agent available
10 - Answer the incoming call
The audio will work in the returned call.
As you can see, it is not super difficult, but neither is it particularly simple.  It certainly took me a while to get it all going.

**Comment by teleme-coder** [comment]
Hi AWS,

One would think this is a major issue which should be addressed as one cannot control how agents use the CCP (or when they decide to refresh the browser).

Any updates on this essential feature?

**Comment by francismanansala** [comment]
I'm experiencing this issue with the latest version. Has anyone resolved this without the work around mentioned above?

**Comment by vhenessey** [comment]
Has anyone had any new findings on it yet?
Seem to be a withstanding issue still.

**Comment by srikanth2102** [comment]
We are also facing the same issue.
