### ISSUE TITLE
contact.accept() doesn't accept call when agent logs in first time

### ISSUE THREAD

**Issue by faizaanshah** [amazon-connect/amazon-connect-streams#330]
When our agent logs in first time, by calling contact.accept() we never get into contact.OnAccepted(). But when we refresh the browser page, we see that we get inside the onAcceptHandler and things work fine. 

We are not sure if we are missing to subscribe to some event which is causing the issue but not sure. It would be great if someone could point us out to anything that can cause this.

thanks

**Comment by Christian-Sesta** [comment]
Not to sure on your flow, but from what I know the `contact.onAccepted` event should fire on any accepted inbound call. The only time it doesn't fire is if a customer accepts an outbound call. 

Might be worth checking to see if your streams version is up to date. Else something that might solve your issue could be to use the `contact.onConnected` event as that seems to fire for both inbound/ outbound calls once `contact.accept` has fired successfully.

**Comment by faizaanshah** [comment]
Opened a ticket and came to know that updating the browser (chrome 87.x.xxx) should fix it. And yeah by updating the browser it worked.
