### ISSUE TITLE
Log-rotate in Logger::setLogRollInterval() does not work

### ISSUE THREAD

**Issue by shinsaka** [amazon-connect/amazon-connect-streams#331]
Expected behavior:
- Logger._logs copy to Logger._rolledLogs
- empty Logger._logs.
- We can download logs up to 60min logs(_rolledLogs=60mins to 30mins ago, _loglog=max last 30mins ago)

Impremented behavior:
- rotate doesn't work

I thought `global.setInterval()` is a cause, "The this problem" of the following url page.

https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval#The_this_problem

**Comment by martin-greenberg** [comment]
PR merged, closing.
