### ISSUE TITLE
Engines Node ">=12.0.0" value is causing an issue in pipeline that uses node "10.21.0"

### ISSUE THREAD

**Issue by nmiddleweek** [amazon-connect/amazon-connect-streams#333]
UPDATE 18th Nov 3pm: Running ```yarn --ignore-engines``` on the local machine with 10.21.0 works as well and the web application that uses connect streams works as expected.
-

Hello

What part of the connect-streams library is dependant on node version >=12.0.0 ?

This might be a misunderstanding on my part in how the packages are pulled down when calling ```yarn``` on a project that has amazon-connect-streams as a dependancy however I'm trying to understand why the engines, node value is blocking us.

Our pipeline uses Node 10.21.0 - Our Client is struggling to upgrade this due to internal procedures with SecOps.
Connect Streams package is saying it needs >=12.0.0

Does this mean that when the connect-streams is pulled down from the NPM registry, the package is then built on the fly by pipeline before being saved to the node_modules folder and something is checking it?

Or is the connect-streams pre-built before being made available on the NPM registry?

Here's what I've tried locally...

```nvm install 10.21.0
node -v # to confirm 10.21.0 is active
npm install -g gulp
npm install
npm run release
```

I don't get any errors about node engines.

I also know that on another project, I have used the Makefile to generate an amazon-connect-1.5.0.js file which is served from the public/js folder.

Thanks for any help with this.
Nick

**Comment by martin-greenberg** [comment]
We are unable to support older versions of node. Resolving this as it sounds like you were able to find a workaround.
