### ISSUE TITLE
Library is not compatible with JavaScript's STRICT MODE / Salesforce Community

### ISSUE THREAD

**Issue by alecak1** [amazon-connect/amazon-connect-streams#335]
Library is not compatible with JavaScript's STRICT MODE.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode 

This is an issue because this library is not able to run into other cloud Platform such as Salesforce that force javascript secure standards.
The only way to integrate Amazon Connect CTI product with Salesforce Community Technology is to use Amazon Connect Streams SDK . 

Salesforce apply a security Framework, named Lightning Locker, that force external library to run with strict mode.
You can see the error from Salesforce compatibility tool. This issue was confirmed by Salesforce Official Support.
https://developer.salesforce.com/docs/component-library/tools/locker-service-console 

We notice that there are a lot of points into library that are not compliant with Strict mode.

**Comment by nmiddleweek** [comment]
Hi @alecak1 - I'd like to understand this a bit further... Can you share your specific setup so I can reproduce this locally? I'd be keen to understand the impact of forcing Strict.

Are you simply building the connect-streams with the Makefile, then adding "use strict"; to the top of the file to reproduce this?

Thanks
Nick

**Comment by alecak1** [comment]
HI @nmiddleweek , 
we compiled library (stream-connect.js file) with make standard file. After this we ran library into Salesforce Community. Salesforce force "strict mode" for each external js library so result is that library cannot be loaded correctly. With Salesforce support we understood that problem is related to strict mode enforced by Salesforce.
Infact if you run compiled library (stream-connect.js file) with strict mode (test_run_strictmode.png) you have an errror  (test_run_strictmode_error_result.png). You can see the same error if you load compiled library (stream-connect.js file)  into Salesforce Lightning Locker validator (https://developer.salesforce.com/docs/component-library/tools/locker-service-console)  and press “Evaluate” :
:Cannot set property 2011-06-15 of # which has only a getter (LockerError.png).

Thanks
Alessandro

[Attachments.zip](https://github.com/amazon-connect/amazon-connect-streams/files/5590416/Attachments.zip)

**Comment by alecak1** [comment]
HI @nmiddleweek ,
in particular the library into stream-connect project that is not compatible with strict mode seams to be aws-client.js.

Regards
Alessandro

**Comment by alecak1** [comment]
Seams very similar to following issue in terms of error:
https://github.com/amazon-connect/amazon-connect-streams/issues/328

**Comment by anantoghosh** [comment]
Likely related to https://github.com/aws/aws-sdk-js/issues/3555
Also facing this when trying to add streams via [snowpack](https://www.snowpack.dev/).

**Comment by seiyako** [comment]
This was fixed in v2.3.0 with new AWS SDK
