### ISSUE TITLE
onRefresh event not triggering/detecting Third-party connections

### ISSUE THREAD

**Issue by Selva-Guru** [amazon-connect/amazon-connect-streams#339]
Hi, I'm not able to detect agent/contact events when third-party (conference) connection is added to the Agent A. 
```
contact.onRefresh(handleContactRefresh);

function handleContactRefresh(contact) {
	if (contact) {
        logInfoEvent("[contact.onRefresh] Contact is Refresh. Contact state is " + contact.getStatus().type);
        setStatus(contact.getStatus().type, "");
    } else {
        logInfoEvent("[contact.onRefresh] Contact is Refresh. Null contact passed to event handler");
    }
}

```

Conference endpoint connection is established to Agent A successfully. Customer or initial contact is able to hear Hold music. Here, I want to complete conference (merge all connection) based on the third-party connection events. I have code logic to merge all active connections. Can anyone help me on this to handle third-party connection events?

**Comment by seiyako** [comment]
Hi @Selva-Guru, apologies for the delayed response.
When a new connection is added to the contact, callbacks registered to both `agent.onRefresh()` and `contact.onRefresh()` should be invoked.
One way to recognize that a new connection is added to the contact is to count the number of connections like below. Hope this helps.

```
connect.contact((c) => {
  let connNum = 0;
  c.onRefresh((_c) => {
    console.log('@@@ number of connections', _c.getConnections().length);
    console.log('@@@ prev number of connections', connNum);
    if (_c.getConnections().length > connNum) {
      console.log('@@@ a new connection added!');
    }
    if (_c.getConnections().length > 2) {
      if (_c.getConnections()[2].getState().type === connect.ConnectionStateType.CONNECTED) {
        console.log('@@@ third connection is in connected state, ready to call contact.conferenceConnections()');
      }
    }
    connNum = _c.getConnections().length;
  });
});
```
