### ISSUE TITLE
 'agent::update' event handler failed

### ISSUE THREAD

**Issue by SaiThotapalli99** [amazon-connect/amazon-connect-streams#342]
The CCP is initializing, however, it doesn't seem to register to the event handlers, keeps emitting the message "[ERROR]: 'agent::update' event handler failed." Please find the code below. Appreciate if anyone can shed light on this. Thanks.

 `initializeCCP() {
        if (AWSConnect) {
            AWSConnect.core.initCCP(this.containerDiv.current, {
                ccpUrl: CONNECT_INSTANCE_URL,            // REQUIRED
                loginPopup: true,               // optional, defaults to `true`
                loginPopupAutoClose: true,      // optional, defaults to `true`
                loginOptions: {                 // optional, if provided opens login in new window
                    autoClose: true,              // optional, defaults to `false`
                    height: 600,                  // optional, defaults to 578
                    width: 400,                   // optional, defaults to 433
                    top: 0,                       // optional, defaults to 0
                    left: 0                       // optional, defaults to 0
                },
                region: AWS_REGION,         // REQUIRED for `CHAT`, optional otherwise
                softphone: {                    // optional
                    allowFramedSoftphone: true// optional
                }
            });
            AWSConnect.agent(this.subscribeToAgentEvents) //Subscribe to the agent events
        }
    }
    subscribeToAgentEvents(agent) {
        console.log("Inside Subscribe")
        console.log(agent)
        window.myCPP.agent = agent;
        AWSConnect.agent = agent;
       
        agent.onRefresh(this.handleAgentRefresh);
        agent.onRoutable(this.handleAgentRoutable);
        agent.onNotRoutable(this.handleAgentNotRoutable);
        agent.onOffline(this.handleAgentOffline);
        agent.onStateChange(this.handleAgentStateChange);
        agent.onError((agent) => {
            console.log('Error with Agent')
        })
        this.setAgentDataOnState(agent)
    }

    setAgentDataOnState(agent) {
        const currentAgent = {}
        currentAgent.name = agent.getName()
        currentAgent.status = agent.getState().name

        if (this && currentAgent) {
            this.props.addCurrentAgent(currentAgent)
        }
    }

    handleAgentStateChange(agent) {
        console.log('[agent.onStateChange] Agent state changed. New state is ' + agent.newState);

    }
    displayAgentStatus(status) {
        console.log('Agent Status is ' + status)
    }

    handleAgentRefresh(agent) {
        console.log('[agent.onRefresh] Agent data refreshed. Agent status is ' + agent.getStatus().name);
    }

    handleAgentRoutable(agent) {
        console.log('[agent.onRoutable] Agent is routable. Agent status is ' + agent.getStatus().name);
    }

    handleAgentNotRoutable(agent) {
        console.log('[agent.onNotRoutable] Agent is online, but not routable. Agent status is ' + agent.getStatus().name);
    }

    handleAgentOffline(agent) {
        console.log('[agent.onOffline] Agent is offline. Agent status is ' + agent.getStatus().name);
    }
`

**Comment by yaminli-aws** [comment]
Hi, sorry for the confusion. The error should not impact the functionalities, however we recommend to upgrade to the latest Stream version, which will fix the issue. Thanks.
