### ISSUE TITLE
'contact::onViewContact' is not fired when switching to softphone tab in CCP.

### ISSUE THREAD

**Issue by jwelborn-sugar** [amazon-connect/amazon-connect-streams#343]
[The documentation](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#connectcoreonviewcontact) for `connect.core.onViewContact` states that the event is triggered when the CCP User views a contact. When an agent is on a chat and makes an outgoing phone call this event is not triggered. Similarly, when the agent switches tabs between chats and their phone call this event is not triggered.

Is there any way to listen for clicks into the softphone tab, and get the contactId for the phone contact?

**Comment by ctwomblyamzn** [comment]
Hi @jwelborn-sugar. Thank you for pointing out this hole in our "ViewContact" event.  We are going to track this as a feature request going forward. I will try to keep this ticket updated once we have released a solution. 

For now, you can definitely solve the "an agent is on a chat and makes an outgoing phone call" case by registering a callback to one of our event subscription methods, such as `connect.contact`, and checking that the contact is of type `connect.ContactType.VOICE`. See [our documentation on that method](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#connectcontact) and other event subscription methods for more details.

**Comment by jwelborn-sugar** [comment]
@ctwomblyamzn thanks for the reply! We have the case for when the agent initially makes the call solved, but ran into trouble when the agent switches back and forth between their call and chat tabs. If it helps, this is the actual use case:

We're a team building a dashboard with the CCP embedded. The dashboard shows context in our system relevant to the customer the agent is viewing, and automatically updates when the agent switches tabs in the CCP. We noticed after making an outgoing phone call while on chats, they initially get their call context just fine. If they click the chat tab, we surface the chat dashboard as expected. If they switch back to the call tab, we can't find a way to detect this and display the right context for the call.

Our implementation allows them to see the call context if they close their active chat sessions because it will be the only one left, but this isn't ideal.

I appreciate you tagging this enhancement request, and if you need any more details on the use case or what we've tried let me know.

**Comment by seiyako** [comment]
Hi @jwelborn-sugar, sorry for our delayed response, this issue was fixed back in February. Thank you
