### ISSUE TITLE
agent.getState() for missed and rejected queued callbacks is "Default"

### ISSUE THREAD

**Issue by nielsenius** [amazon-connect/amazon-connect-streams#344]
When a queued callback is missed or rejected `agent.getState()` is returning `"Default"` which appears to be a catch-all error. This is a discrepancy with the way inbound missed or rejected calls set agent state to `"MissedCallAgent"` or `"FailedConnectAgent"`. Can you please provide the same handling for queued callbacks as inbound calls?

**Comment by vs-amzn** [comment]
It has been a while and we are closing this for now
