### ISSUE TITLE
Login with API 

### ISSUE THREAD

**Issue by depark** [amazon-connect/amazon-connect-streams#351]
I want to use key to login iframe connect
Now there is no login due to x-frame-option
now I have to login aws-connect console first, then use iframe in my app
so is there any API login using my key ?

**Comment by ctwomblyamzn** [comment]
Currently there is no login API. What are you referring to as your key?

**Comment by yaminli-aws** [comment]
Hi, we don't support login API from Streams, and the login page is by design not able to embed in the iframe like CCP.
