### ISSUE TITLE
Documentation for Initialization for CCP, Customer Profiles, and Wisdom references amazon-connect-1.7.js

### ISSUE THREAD

**Issue by nicholasloek** [amazon-connect/amazon-connect-streams#355]
There's reference to the following file that does not appear to be included in the repository in the latest Documentation file  example for initializing CCP / Customer Profiles / Wisdom
`<script type="text/javascript" src="amazon-connect-1.7.js"></script>`

**Comment by jauzepy** [comment]
It seems to be working with version 1.6.1.xx. May be a typo..

**Comment by seiyako** [comment]
Yes, the lates version at this point is 1.6.x.
