### ISSUE TITLE
Voice ID Preview

### ISSUE THREAD

**Issue by nickvargas82** [amazon-connect/amazon-connect-streams#356]
We are evaluating Voice ID preview to see how it can be implemented. The contact flows are working fine. It's able to detect that a call is not enrolled. However, In the Agent UI, when I call enrollSpeakerVoiceId() method, it returns "enrollSpeaker failed". I make sure there's at least 30 seconds of audio before making the call as well. Here's the sample code:

```
voiceConnection = new connect.VoiceConnection(contactId, connectionId);              
voiceConnection.enrollSpeakerInVoiceId()
.then((response) => {
    console.log(response);
})
.catch((error) => {
    console.log(error);
});
```

I'm using the latest release version of amazon-connect-streams. I'm setting the correct contactId and connectionId when the call is connected. Anything else I might be missing?

**Comment by hartjo** [comment]
> We are evaluating Voice ID preview to see how it can be implemented. The contact flows are working fine. It's able to detect that a call is not enrolled. However, In the Agent UI, when I call enrollSpeakerVoiceId() method, it returns "enrollSpeaker failed". I make sure there's at least 30 seconds of audio before making the call as well. Here's the sample code:
> 
> ```
> voiceConnection = new connect.VoiceConnection(contactId, connectionId);              
> voiceConnection.enrollSpeakerInVoiceId()
> .then((response) => {
>     console.log(response);
> })
> .catch((error) => {
>     console.log(error);
> });
> ```
> 
> I'm using the latest release version of amazon-connect-streams. I'm setting the correct contactId and connectionId when the call is connected. Anything else I might be missing?

Not answer to your question but do you have any sample contact flow for VOICE ID? i always get error on check security

**Comment by hartjo** [comment]
I'm having the same error did you manage to fix it?

**Comment by kaushalgautam** [comment]
@nickvargas82 -  did you manage to solve this? Your answer here could help folks who are stuck

**Comment by nickvargas82** [comment]
> I'm having the same error did you manage to fix it?

It was the region we are using (us-west-2) and I think at that time it wasn't available in that region. I think it only worked in us-east-1.
