### ISSUE TITLE
Connect.agent () is not getting initialized 

### ISSUE THREAD

**Issue by ashwinisajjan** [amazon-connect/amazon-connect-streams#358]
Issue : I'm integrating Amazon Connect CCP panel in my organization's UI. I have integrated CCP and now i want to subscribe to events and perform some actions on trigger of events.  The UI is written in React, the following is the code written to achieve what i'm saying but for some reasons, the events are not getting subscribed and in turn call back functions are not triggering.  The error i'm getting is : 'agent::init' event handler failed.

Additional question : I learnt that till the recent version of streams - 1.6.0, the display of login page in the same iframe as CCP. It would be great if someone can confirm me the same.

import React, {Component} from 'react';
import 'amazon-connect-streams';

class CCP extends Component {
  
  constructor(props) {
    super(props);
    this.containerDiv = React.createRef();
  }

  componentDidMount() {
    connect.core.initCCP(this.containerDiv.current, {
      ccpUrl: 'https://case-callcenter.awsapps.com/connect/ccp-v2#/',
      loginPopup: false,
      loginOptions: {                 // optional, if provided opens login in new window
        autoClose: true,              // optional, defaults to `false`
        height: 600,                  // optional, defaults to 578
        width: 400,                   // optional, defaults to 433
        top: 0,                       // optional, defaults to 0
        left: 0                       // optional, defaults to 0
      },
      region: "eu-central-1",
      softphone: {
        allowFramedSoftphone: true
      },
    });
    connect.agent(subscribeToAgentEvents);
    function subscribeToAgentEvents(agent) {
      logInfoMsg("Subscribing to events for agent " + agent.getName());
      logInfoMsg("Agent is currently in status of " + agent.getStatus().name);
      agent.onRefresh(handleAgentRefresh);
      agent.onStateChange(handleAgentRefresh);
      agent.onRoutable(handleAgentRoutable);
      agent.onNotRoutable(handleAgentNotRoutable);
      agent.onOffline(handleAgentOffline);
    }
    function handleAgentRefresh(agent) {
      logInfoEvent(
        "[agent.onRefresh] Agent data refreshed. Agent status is " +
          agent.getStatus().name
      );
    }
    function handleAgentRoutable(agent) {
      logInfoEvent(
        "[agent.onRoutable] Agent is routable. Agent status is " +
          agent.getStatus().name
      );
    }
    function handleAgentNotRoutable(agent) {
      logInfoEvent(
        "[agent.onNotRoutable] Agent is online, but not routable. Agent status is " +
          agent.getStatus().name
      );
    }
    function handleAgentOffline(agent) {
      logInfoEvent(
        "[agent.onOffline] Agent is offline. Agent status is " +
          agent.getStatus().name
      );
    }
 }

render() {
    return (
      <div className="ccp">
        <div className="container" ref={this.containerDiv} />
      </div>
    );
  }
}

export default CCP;

**Comment by seiyako** [comment]
Hi @ashwinisajjan, the "XXX event handler failed" message means there was an uncaught error thrown within the callback function to XXX event. Adding a try catch block within the callback function should help you debug which line caused an error.

**Comment by fezekilePlaatyi2** [comment]
@ashwinisajjan I am having the same error, did you manage to  find solution to this?
