### ISSUE TITLE
Warm transfer get transferred Agent and Queue

### ISSUE THREAD

**Issue by sivac47123** [amazon-connect/amazon-connect-streams#359]
Hi Team,

How we can get the transferred from agent and transferred from queue details from the connect stream API.

I tried with contact event object but unable to get those details. We can get the initial contact id. 

Is there is any other way to get the details.

Thanks and Regards
Siva

**Comment by magdnede** [comment]
You can set the name of the transferring agent in the transfer queue (or agent) contact flow and you will be able to retrieve it as a contact attribute on the recipient of the transfer. You can do the same for the queue.
