### ISSUE TITLE
Transfer a quick connect call to another quick connect

### ISSUE THREAD

**Issue by bhanuyandraJava** [amazon-connect/amazon-connect-streams#363]
can we transfer a quick connect call to another quick connect. Agent one receives a quick connect call  then --> transfers to agent two using quick connect.

**Comment by magdanedelcu** [comment]
The quick connect is a mechanism for you to transfer a call, it is not the
call itself. Do you mean adding another line or party so when the second
agent gets the customer call they can consult again?

**Comment by bhanuyandraJava** [comment]
I will explain my scenario to give you better picture/understanding.
We have three agents on three different machines logged into CCP:
Agent-1 receives a call then he transfers call to Agent-2 using:

`agent.getContacts(lily.ContactType.VOICE)[0].addConnection(data.endpoints[1], {
      success: function(data) {
      alert("transfer success");
      },..`

Now Agent-2 receives the call and tries to transfer to another endpoint:

`agent.getContacts(lily.ContactType.VOICE)[0].addConnection(data.endpoints[2], {
      success: function(data) {
      alert("transfer success");
      },`

Problem I'm seeing is when Agent-2 tries to transfer:
data.endpoints[] is empty

**Comment by m66rus** [comment]
We found that connect operates slightly differently when your second agent tries to transfer as the contact flow whisper is not triggered as in normal situations so you may be seeing this from a streams api perspective

**Comment by magdanedelcu** [comment]
Understood. Looks like your agent 1 is still on the call so you are asking
if we support more than three lines.
The answer is not at the moment.
