### ISSUE TITLE
TypeScript - Property 'getEventBus' does not exist on type 'Core'.

### ISSUE THREAD

**Issue by rein-chau-nab** [amazon-connect/amazon-connect-streams#365]
I'm not sure if this is the right place to put this issue. I found that the TypeScript type definition on https://www.npmjs.com/package/@types/amazon-connect-streams seems to be outdated. I'm using package `amazon-connect-stream@1.6` with `TypeScript@3.8` and have these errors:

> Property 'getEventBus' does not exist on type 'Core'.
> Property 'EventType' does not exist on type 'typeof connect'.

Please help me to provide the correct typing.
Thank you.

**Comment by SamSchiff** [comment]
Hi @rein-chau-nab, thank you for pointing this out. If you are so inclined, we highly encourage you to publish a PR to add these type definitions. If not, we will look into adding them internally.

**Comment by vfsleeth** [comment]
Will this be fixed anytime soon, is it not possible to access logout event with typescript? Having same issue as ^^. Thanks!

**Comment by ctwomblyamzn** [comment]
Hi, we now have typings for [EventType's enum](https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/index.d.ts#L162). Unfortunately, we are unable to prioritize typescript coverage right now. As @SamSchiff said, we encourage you to publish a PR to further our coverage if you are so inclined.
