### ISSUE TITLE
React, TypeScript - Property 'setEchoLevel' does not exist on type 'Logger'. 

### ISSUE THREAD

**Issue by Seeemba** [amazon-connect/amazon-connect-streams#366]
Hi Team,
I tried to set LogLevel using
```
const rootLogger = connect.getLog();
// Set log level.
rootLogger.setLogLevel(connect.LogLevel.TRACE);
// Set console output level.
rootLogger.setEchoLevel(connect.LogLevel.TRACE);
```

according to documentation - https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#loglevel

and example - https://github.com/amazon-connect/amazon-connect-streams/issues/269
`connect.getLog().setEchoLevel(connect.LogLevel.CRITICAL);`

but got the error "Property 'setLogLevel' does not exist on type 'Logger'."
****
I'm using package amazon-connect-stream@1.6 with **TypeScript**@4

Could you suggest, how to remove logs?

**Comment by alexgurr** [comment]
Logging has been a constant problem since we started using streams **2 years ago**. Any updates on this?

**Comment by IsaacTrevino** [comment]
+1

**Comment by tavisca-mahmad** [comment]
+1

**Comment by CGarces** [comment]
Just look the last two commits.
2fddb141096eebb49b5e085ebec5220d52b91b81
e59f62f22992f7b3a9cb1cfa6fe8e3d33aa25423

Directly from a master branch, hard to track the changes, no description in the PR you need to go to the release notes.

Documentation from #265 is wrong...

I'm not sure if there is someone at the wheel
