### ISSUE TITLE
Make on windows: make: *** No rule to make target `all'.  Stop.

### ISSUE THREAD

**Issue by JamesBromberger** [amazon-connect/amazon-connect-streams#368]
Trying to make on Windows 10 with bash (ubuntu).
Make would abandon, not finding the "all" target.
This post seemed to help:
https://stackoverflow.com/questions/65332680/amazon-connect-makefile-help-makefile-no-rule-to-make-target-all-stop

**Comment by griffisc306** [comment]
There is a typo on the makefile I found.  Where it says DEFAULT_Goal := all it should  just be DEFAULT_GOAL : all. I have a pull request in￼￼￼. You should be able to manually change it on the meantime tho

**Comment by martin-greenberg** [comment]
This issue was fixed by PR #350 in February which added the explicit "all" target. I'm closing this issue but feel free to reopen if you're still having Makefile issues.
