### ISSUE TITLE
Determine if call is being recorded

### ISSUE THREAD

**Issue by CiscoKidxx** [amazon-connect/amazon-connect-streams#369]
Is there an system attribute or API that can tell me if a call is currently being recorded?

I really want to avoid manually setting a contact attribute after each set recording behavior block in the contact flows. It doesn't seem like streams API has anything that would indicate if a call is being recorded and if so, which parties. The Connect API doesn't seem to have a method like getContactRecordingStatus either.

As a bad work around I am calling startContactRecording on the contact to see if it errors with "Request is not allowed in current voice recording state". The down side is if it's not being recorded, there will now be a short recording while the stopContactRecording request is handled. 

Hopefully I'm missing some really easy way to do this. Any help is appreciated!

**Comment by ctwomblyamzn** [comment]
Hi @CiscoKidxx unfortunately right now we do not have any data indicating whether the contact is being recorded in Streams. As such, we will need to try to expose this data to the frontend first. We will track this as a feature request and pass it to a downstream team. I will try to update this ticket if this request gains some traction

**Comment by alexgurr** [comment]
Any further updates on this?

**Comment by alexgurr** [comment]
Bump ☝️
