### ISSUE TITLE
contact.getState() and contact.getStateDuration() Methods not available

### ISSUE THREAD

**Issue by devansvd** [amazon-connect/amazon-connect-streams#37]
The methods contact.getState() and contact.getStateDuration() are not available Instead contact.getStatus() and contact.getStatusDuration() are available. I just wanted to bring this to your attention.

EDIT: Also, connection.getState() and connection.getStateDuration() are not available too, Instead connection.getStatus() and connection.getStatusDuration() are available.

But In Agent API agent.getState(), agent.getStatus(), agent.getStateDuration, agent.getStatusDuration all this FOUR methods are available.

If Possible please update the documentation properly.

Thanks.

Devan

**Comment by ctwomblyamzn** [comment]
This issue is now resolved.
