### ISSUE TITLE
EventBus.prototype.trigger throwing errors for `data.contactId` when `data` is null

### ISSUE THREAD

**Issue by peterkinmond** [amazon-connect/amazon-connect-streams#372]
After upgrading to v1.6.3 we started seeing this error come up in the Chrome dev console for our app which uses `amazon-connect-streams`. It's due to a [recent addition to the `EventBus.prototype.trigger` method](https://github.com/amazon-connect/amazon-connect-streams/pull/354/files#diff-be21f3913edf585ffabb7db45b3beb835f40d313c713a812c163995f4c155173). 

![Screen Shot 2021-02-03 at 4 25 43 PM](https://user-images.githubusercontent.com/779389/106826832-8c215e00-663c-11eb-8498-2195c3361a0c.png)

The `data` object is sometimes null but the code doesn't have any null check.

**Comment by yaminli-aws** [comment]
Hi,

Please upgrade Streams version to 1.6.5+ to pick up the update we have around this.
