### ISSUE TITLE
SAML login working in Firefox but not Chrome

### ISSUE THREAD

**Issue by aguecida** [amazon-connect/amazon-connect-streams#374]
Hello,

I am running Amazon Connect using the SAML 2.0 authentication option with the CCP embedded in an iframe. The integration is working fine in Firefox, where when I login to my app, the CCP will get opened in a new browser tab and automatically close once it finishes loading. In Chrome, the new tab opens, the CCP loads successfully, but the tab does not auto close and I see the following errors in my browser console.

![image](https://user-images.githubusercontent.com/3771301/107395776-1ea57f80-6acb-11eb-97e1-4d2266c96271.png)

Here are the properties I'm setting when calling `initCCP`:

`ccpUrl: https://<my-connect-instance>.awsapps.com/connect/ccp-v2`
`loginUrl`: Here I'm using my ADFS IdPInitiatedSignOn url with a relay state using `connect/federate/<my-connect-instance-id>` and a destination of `connect/ccp-v2` as described in https://docs.aws.amazon.com/connect/latest/adminguide/configure-saml.html.
`loginPopup: true`
`loginPopupAutoClose: true`
`softphone: {
    allowFramedSoftphone: true
}`

**Update**: I've also noticed this issue happen occasionally in Firefox. For example, we had 3 co-workers test it in Firefox, for 2 of them it worked while 1 of them saw the same errors shown above.

**Comment by yaminli-aws** [comment]
The console error "Refused to display 'https://<connect-instance>.awsapps.com/connect/login' in a frame because it set 'X-Frame-Options' to 'sameOrigin'" is expected for our login page setup, which we open the login page in a separate new window/tab for login. After logged in, the CCP in iframe should load successfully.

What's the StreamJS version you're using and faced the issue of not auto-close the login window and the Chrome browser version? We verified with the latest version Streams 1.6.6 and Chrome Version 89.0.4389.128, the workflow is as expected.

**Comment by aguecida** [comment]
I've just tested again now with the latest version of Streams installed:

Streams: `1.6.6`
Chrome: `89.0.4389.128`

One important difference for me is that recently it has been working in a regular Chrome window, but the issue happens consistently when running in an incognito window. Could you see if you can reproduce the issue in incognito mode?

**Comment by yaminli-aws** [comment]
Chrome incognito mode doesn't work because the default Chrome behavior is "Block third-party cookies in Incognito", see your Chrome cookies settings at chrome://settings/cookies.

**Comment by aguecida** [comment]
That was the issue, thanks!

**Comment by CiscoKidxx** [comment]
> Chrome incognito mode doesn't work because the default Chrome behavior is "Block third-party cookies in Incognito", see your Chrome cookies settings at chrome://settings/cookies.

This will soon be the default behavior for chrome in general. Does the Connect team have any comment on how this will be addressed?

https://www.pcmag.com/news/google-effort-to-kill-third-party-cookies-in-chrome-rolls-out-in-april
