### ISSUE TITLE
TypeScript Types Feel Incomplete

### ISSUE THREAD

**Issue by milky2028** [amazon-connect/amazon-connect-streams#375]
Fellow Amazonian here. I'm not able to import types without importing the module itself and creating side effects. For anyone using a TypeScript version greater than 3.8, it's possible to import just types using the `import type { thing } from "somewhere"` syntax, but this fails with `'index.d.ts' is not a module`. This can usually be fixed just by adding an unsightly `export {}` to the bottom of your types file, otherwise TypeScript won't recognize it as a module. This seems like a common problem in a scenario where someone is building an app with NPM and all that, but they've included amazon-connect-streams as a script tag in their HTML.

Beyond just that, there are also some events that appear to be missing, like `AgentEvents`. Enums that are provided for `ContactEvents` don't provide the namespace for events, so `ContactEvents.View = "view"` instead of `"contact::view"`.

What would be super legit is to have something like `ContactEventMap` that maps each event name to that event's type, similar to `WindowEventMap` that TypeScript provides in `lib.dom.ts`.

```typescript
interface WindowEventMap extends GlobalEventHandlersEventMap, WindowEventHandlersEventMap {
    "abort": UIEvent;
    "afterprint": Event;
    "beforeprint": Event;
    "beforeunload": BeforeUnloadEvent;
    "blur": FocusEvent;
    "canplay": Event;
    "canplaythrough": Event;
    "change": Event;
    "click": MouseEvent;
    "compassneedscalibration": Event;
    "contextmenu": MouseEvent;
    "dblclick": MouseEvent;
    "devicelight": DeviceLightEvent;
    // ... more
  }
```

**Comment by ctwomblyamzn** [comment]
Hi @milky2028 thank you for the suggestions. We will certainly look into these improvements. If you are so inclined, we highly encourage you to publish a PR for one or both of the issues described here. If not, we will track them internally.

**Comment by milky2028** [comment]
I'll see what I can do here in the next few weeks or so. Thank you!
