### ISSUE TITLE
Can we connect to agent ARN directly

### ISSUE THREAD

**Issue by sivac47123** [amazon-connect/amazon-connect-streams#378]
Hi Team,

Can we connect agent ARN directly using the below method. Here endpoint would be agent ARN got it from agent.getEndPoints

  this.agent.connect(endpoint, {
  success: function () {    },
  failure: function (err) {  }
Am getting the below error.

logging.service.ts:49 outbound call failed ["{"type":"BadEndpointException","message":"Only pho…eams/connect-streams-min.65e3ad85.js:1:120091)"]}"]

**Note :**agentARN is working when am using contact.addConnection(endpoint). But we need to connect another agent directly.

Thanks for your input.

Regards
Siva

**Comment by Juzziee** [comment]
I agree. 
This would allow us to make agent to agent direct calling without having to do some contact flow trickery.

**Comment by tgxn** [comment]
Please have a look at https://github.com/amazon-connect/amazon-connect-streams/issues/230

**Comment by yaminli-aws** [comment]
Hi @sivac47123, we are still waiting for our co-team to support on this in future.
