### ISSUE TITLE
Recording Control from CCP

### ISSUE THREAD

**Issue by bobbili789** [amazon-connect/amazon-connect-streams#38]
Hi,

Is there a way to start/stop the recording of amazon connect agent conversation with customer from CCP embedded html?

Thanks

**Comment by ibliskavka** [comment]
VoiceFoundry.com has a solution for this.

**Comment by ctwomblyamzn** [comment]
Out of the box, we do not currently offer this feature. We do, however, provide manager listen-in. See more about that feature [here](https://docs.aws.amazon.com/connect/latest/adminguide/monitor-conversations.html). I'm going to close this and mark it as a feature request.

**Comment by ctwomblyamzn** [comment]
Reopening for visibility
