### ISSUE TITLE
AWS CCP cannot be answered.  User is clicking on ANSWER button, but it does not work an eventually user goes into MISSED  state.

### ISSUE THREAD

**Issue by ssarir** [amazon-connect/amazon-connect-streams#386]
After user's PC network adapter goes into suspended mode (for example after PC was put into sleep), first INBOUND call user receives in AWS CCP cannot be answered. User is clicking on ANSWER button, but it does not work an eventually user goes into MISSED  state.

Logs are showing that issue is causing by line 22068 of connet-streams.js. Event handler error: "failed to execute 'addStream' on 'RTCPeerConnection': signallingState is closed"

**Comment by CiscoKidxx** [comment]
We are also experiencing this. What is the suggested ccp / socket recovery process from network changes on the client ?

**Comment by Christian-Sesta** [comment]
Experiencing this as well. We have been having our agents refresh the page every so often once they run into a call they cannot answer, but this is becoming tedious and slowing down their work. Is there plans to improve on this inactivity side of things?

**Comment by seiyako** [comment]
This is an OS-level known issue that closes websocket connection after going into sleep mode. Please utilize [websocket init failure event hook](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#connectonwebsocketinitfailure) or [connection lost event hook](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#connectonwebsocketinitfailure) and show a warning message to encourage agent to refresh the page.

**Comment by Christian-Sesta** [comment]
@seiyako we do not currently use those hooks so we will give it a go, however, I can confirm that refreshing the page does not alway fix this problem.

I have run into this issue myself a few times with a stable connection with no dropouts, its almost like the contact on the other end has gone, however something failed upstream to still think they are there. This leads to a phantom contact the floats around the agent pool until we kill the contact via the aws cli stop contact method.
