### ISSUE TITLE
CCP Logout functionality

### ISSUE THREAD

**Issue by BlackBird-CR7** [amazon-connect/amazon-connect-streams#388]
As mentioned in the amazon connect cheat sheet, i added the window.location.replace to the offline function and i am calling this function in onbeforeunload event. But when i close the webpage and type the ccp url again in a new tab, i am not logged out and i can still see the ccp with my name on the screen.

Ideally when i close the webpage, onbeforeunload functions are triggered and i should have been logged out of CCP. But this is not happening.

![Cheatsheet](https://user-images.githubusercontent.com/8322280/111116121-a8100c00-85b9-11eb-9d88-4114f6ec7da1.png)

**Comment by seiyako** [comment]
Can you try fetch API? It's more reliable in the onbeforeunload event.
`fetch("https://<your-instance-domain>/connect/logout", { credentials: 'include'})`
