### ISSUE TITLE
Cannot determine if contact is in MISSED state - getStatus() returns ERROR

### ISSUE THREAD

**Issue by tjw0051** [amazon-connect/amazon-connect-streams#391]
If I let a contact fall into the `MISSED` state, the CCP red banner shows the contact as `Missed chat`, but if I do:

`contact.getState()` or `contact.getStatus()`

... the returned state is `ERROR`. 
I've also tried:
```
contact.getAgentConnection().getState()
```
which returns `DISCONNECTED` as the state.

How can I determine if a contact is in the `MISSED` state?

**Comment by yaminli-aws** [comment]
Hi,

Unfortunately we doesn't build the contact status in a elaborative way right now, rather we just pass back the contact status from the back end API request, which couldn't easily tell if the contact is in missed state from the single request itself.

You can use the following code snippets to determine if the contact is in missed state:
```
isContactMissed() {
  return contact.getStatus().type === CONTACT_STATUS.ERROR &&
    contact.getInitialConnection().getStatus().type === CONTACT_STATUS.CONNECTED && 
    contact.getAgentConnection().getStatus().type ===  CONTACT_STATUS.DISCONNECTED;
}
```

We'll evaluate to provide such API to Streams as well.

Thanks.

**Comment by tjw0051** [comment]
@yaminli-aws thanks for the response, i'll use the method you suggested for getting missed state.
