### ISSUE TITLE
amazon-connect-streams - c# client

### ISSUE THREAD

**Issue by srivathsah** [amazon-connect/amazon-connect-streams#395]
Hi Team,

I understand there is no availability of clients in languages other than javascript, however for integrating amazon connect with native applications, are there any other options ?

Is it possible for us to port this javascript library into c# ? in this scenario how would the authentication work ?

Could you please guide me into what options I should be exploring

**Comment by martin-greenberg** [comment]
Right now there are no other options for Streams as all of its logic runs client-side. Aside from the AWS SDK clients which would allow you to make Connect API calls from any language in which the SDK is available. You would need to handle authentication yourself, presenting a login page to your agent and reading the authentication cookies set by the successful authentication response (in the case of Connect-managed username/password authentication) or presenting whatever your SSO interface is to the agent and orchestrating the SAML authentication. Streams does not handle any authentication on its own; it relies on redirecting to the existing Connect login webpage to do this.
