### ISSUE TITLE
Update Contact Attributes

### ISSUE THREAD

**Issue by darwinanirudh** [amazon-connect/amazon-connect-streams#397]
Hello Team .,

I am using amazon-connect-1.3.js. Currently we are able to read contact attributes but I would like to know if it is possible to write/update contact attributes.  It would be handy for transfer and conferences as sharing contact attributes is key. 

regards
Darwin

**Comment by intptr-t** [comment]
It looks like the only way is to use the [UpdateContactAttributes](https://docs.aws.amazon.com/connect/latest/APIReference/API_UpdateContactAttributes.html) API as per the following comment
https://github.com/amazon-connect/amazon-connect-streams/issues/187#issuecomment-623734431

**Comment by darwinanirudh** [comment]
Hii ,

Thanks for replying.  Yes I am aware of that API . But i was interested if there any function of amazon-connect-1.3.js , which I can use ?


regards
Darwin

**Comment by martin-greenberg** [comment]
We have taken this as a feature request in #187, but right now the only way to do this is via the API mentioned. I'm going to close this as a duplicate of that issue, but please feel free to +1 issue 187 to help us understand the level of interest for the feature request.
