### ISSUE TITLE
Refused to display `https://<instance-id>.awsapps.com/` in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by asanabria-hc** [amazon-connect/amazon-connect-streams#398]
# Refused to display `https://<instance-id>.awsapps.com/` in a frame because it set 'X-Frame-Options' to 'sameorigin'.

## Description
Even if we add the hosts as the [allowlist documentation](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#allowlisting) states, we are getting this error on the version 1.6.5

**Allowlist example**
![image](https://user-images.githubusercontent.com/77176710/115053902-d9bc1180-9e9c-11eb-99d8-864e6651fc06.png)

**Comment by SamSchiff** [comment]
Hi Andres, thanks for bringing this to our attention. It's a little tough to figure out exactly what might be happening without knowing a bit more info. If it's possible, could you provide us with your ` initCCP()` code (personal info blurred out as needed). It would be helpful to see that code to rule out any possible configuration issues. 

Also, on the off chance you haven't already, I just want to make sure you double-check that your approved origins are the correct scheme host and port. And that this is the instance you're trying to initialize using Streams. These are unlikely the issue but we can't rule it out without seeing the data so it's up to you to verify that.

**Comment by asanabria-hc** [comment]
@SamSchiff 
- We doubled checked that the approved origins are the correct scheme host and port ✅
- The instance is correct. ✅

This is the code we are using with `initCCP()`:

```javascript
const instanceDomain = "<insert-instance-domain>"
const containerDiv = document.getElementById('ccp-container')
window.connect.core.initCCP(containerDiv, {
  ccpUrl: `https://${instanceDomain}.my.connect.aws/ccp-v2/`,
  loginPopup: true,
  loginOptions: {
    autoClose: true,
    height: 600,
    width: 400,
    top: 0,
    left: 0,
  },
  softphone: {
    allowFramedSoftphone: true
  }
})
```

**Comment by CiscoKidxx** [comment]
@asanabria-hc - Check to make sure 3rd party cookies are enabled in your browser. The auth model for the stream lib requires them to be enabled. By default, these are disabled in incognito mode. In a future release of Chrome they will be disabled by default in normal chrome mode as well.

**Comment by asanabria-hc** [comment]
@CiscoKidxx Yes, 3rd party cookies are allowed! My guess is that this is issue is related to the [new connect instances domain](https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-release-notes.html#march21-release-notes). 

- Current: https://[instance name].awsapps.com/connect/
- New: https://[instance name].my.connect.aws/

**We created our instance after this change**. When we try to login I've noticed that the login page still redirects` .my.connect.aws ` to `.awsapps.com` (the old one). It is causing that the login refuses to be displayed in our iframe, so it is forced to open a popup in order to login. **After the login**... the CCP is finally displayed. **What we want is that the login is displayed in the iFrame not the popup.**

![Screen Shot 2021-04-22 at 8 20 50 AM](https://user-images.githubusercontent.com/77176710/115732138-f1841180-a344-11eb-874a-0a4229476b96.png)

![Screen Shot 2021-04-22 at 8 21 11 AM](https://user-images.githubusercontent.com/77176710/115731378-52f7b080-a344-11eb-9f2e-5409fbf96230.png)

**Comment by yaminli-aws** [comment]
Hi,

We don't support login page to be embedded in the iframe, which is as designed.
