### ISSUE TITLE
Domain for new Amazon Connect instance(March 2021)

### ISSUE THREAD

**Issue by ygt1qa** [amazon-connect/amazon-connect-streams#401]
Hi, team

The domain for the Amazon Connect access URL has changed.
https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-release-notes.html#march21-release-notes

so, we have to update amazon-connect-streams's document.

and,

I tried to change new domain, and tried to work amazon-connect-streams.
As usual logged in by loginPopup, redirected to dashboard page of amazon connect in iframe. not ccp page.

How do I redirected to ccp page?

**Comment by yaminli-aws** [comment]
Hi,

Thanks for reaching out!

For redirection to CCP page, you can specify land at place for loginUrl with the `lantat` parameter. like `https://${connect_domain}/connect/login?landat=/connect/ccp-v2`.

**Comment by sachinjabshetty** [comment]
i am also facing the same issue, can you please tell what exactly need to change in the code. i am very new to coding.
