### ISSUE TITLE
Don't work amazon-connect-streams on Nuxt.js

### ISSUE THREAD

**Issue by ygt1qa** [amazon-connect/amazon-connect-streams#404]
Hi,

I created a web application written by nuxt.js, and I try to embed in amazon-connect-streams.
but it doesn't work.

Error is `ReferenceError navigator is not defined` 
in `node_modules/amazon-connect-streams/release/connect-streams.js:21760`

code is simple 
```
index.vue

<template>
  ~ simpel HTML ~
</template>

<script>
import 'amazon-connect-streams'
export default  {}
</script>
```

So, this error is caused when amazon-connect-streams is imported.

who tried and could embed in Nuxt.js?

Thank you.

**Comment by GuidoNebiolo** [comment]
I make it work in a Vue.js app (so without the SSR from Nuxt) putting:
`import 'amazon-connect-streams'` inside main.js
and then `window.connect.core.initCCP(this.$el,{...})` inside the component that contains the softphone

**Comment by ygt1qa** [comment]
@GuidoNebiolo 
Thanks to your solution, my app written Nuxt.js work!
