### ISSUE TITLE
Task contact getQueue() is missing name

### ISSUE THREAD

**Issue by ross-symbee** [amazon-connect/amazon-connect-streams#407]
When we call `getQueue` from our Task contacts the returned object doesn't have the queue name, ex.,
```
    {
        queueARN: "arn:aws:connect:us-east-1:xxx:instance/xxx/queue/xxx", 
        name: "", 
        queueId: "arn:aws:connect:us-east-1:xxx:instance/xxx/queue/xxx"
    }
```
This seems to be happening for all Task contacts. We're using a custom UI, but this can also be reproduced in the CCP. In the CCP source maps, navigate to /js/context/StreamJSContext.js. Place a breakpoint inside the `initContact` method. Place a Task in to the agent and inspect `getQueue()` on the incoming contact.

We need the queue name to key additional functionality in our UI and so far it's been populated well for Voice and Chat. We're using v1.6.5 of streams and v1.1.0 of taskjs.

**Comment by yaminli-aws** [comment]
Thanks for reporting the issue, we are working to fix it.

**Comment by ColoradoKiwi** [comment]
Hi - is there any update on this bug or ETA on a fix?
Thanks

**Comment by CiscoKidxx** [comment]
Also waiting for fix here.

**Comment by CiscoKidxx** [comment]
Hello - Has this been addressed?

**Comment by CiscoKidxx** [comment]
Testing, 123. Is this thing on?

**Comment by marktheunissen** [comment]
@CiscoKidxx Barely... my experience with this project is that the Amazon engineers drop by every so often, maybe once a week, and reply to a select few issues. But they don't maintain this like a traditional open source project with community engagement, support, etc.

You might get lucky and get a response here, but to be honest the way to get help is by opening a support ticket in your AWS console.

**Comment by m66rus** [comment]
I will log a ticket with AWS this morning so it is logged with them and see if this helps.

**Comment by m66rus** [comment]
I raised a ticket with AWS they have just confirm a fix has been rolled out!

**Comment by m66rus** [comment]
I raised a ticket with AWS support on the issue and they have just confirmed a fix has been rolled out to almost all regions!

**Comment by CiscoKidxx** [comment]
> I raised a ticket with AWS support on the issue and they have just confirmed a fix has been rolled out to almost all regions!

Whoa, nice work!

Is the fix in a new connect-streams version or was it fixed in their backend?

**Comment by m66rus** [comment]
I am guessing from their response it must be in the back end
