### ISSUE TITLE
New ringer/speaker/mic settings not persisting

### ISSUE THREAD

**Issue by griffisc306** [amazon-connect/amazon-connect-streams#413]
My settings, ringer specifically, goes back to default whenever I open.  Are thes supposed to persist accross sessions

**Comment by seiyako** [comment]
Hi @griffisc306, thank you for reporting this issue. I was able to reproduce it on my embedded CCP setup and I believe this should be considered as a bug. We'll update here once the fix is made.

**Comment by griffisc306** [comment]
Any update on this bug?

**Comment by seiyako** [comment]
We fixed the issue that the ringer device doesn't persist beyond page reload.
