### ISSUE TITLE
Programmatic way to change the language of the CCP?

### ISSUE THREAD

**Issue by magdanedelcu** [amazon-connect/amazon-connect-streams#414]
I tried using the agent.setConfiguration() using the method and setting the config.locale value to 'fr_FR', but the UI does not change. Is this doable with the current kit?

**Comment by SamSchiff** [comment]
Is this still an issue in the latest Streams version? You should be able to update your language by passing in the locale in the config object similar to the following:

```
const config = { 
  agentPreferences: {
    locale: 'fr_FR'
  }
};
agent.getConfiguration(config, callbacks);
```
That should both update the agent's language and trigger Streams to refresh the agent configuration object

**Comment by antawad** [comment]
I was able to switch language using the following:
**JS/TS**:
```typescript
agent: connect.Agent;
ngAfterViewInit(): void {
    var ccpUrl = "https://xyz.my.connect.aws/connect/ccp#";
    var containerDiv = document.getElementById('containerDiv');

    connect.core.initCCP(containerDiv, {
      ccpUrl: ccpUrl,
      loginPopup: true,
      softphone: {
        allowFramedSoftphone: false,
      }
    });
    connect.agent((agent) => {
      this.agent = agent;
    });
  }
toggleLanguage(lang) {
    const config = this.agent.getConfiguration();

    config.agentPreferences.locale = lang;
    this.agent.setConfiguration(config, {
      success: () => {
        console.log('success setting config');
      },
      failure: (err) => {
        console.warn('failed to set config', err);
      }
    });
  }
```
**HTML:**
```html
<div>
  <button (click)="toggleLanguage('en_US')">Set to English</button>
  <button (click)="toggleLanguage('fr_FR')">Set to French</button>
</div>
<div id="containerDiv" style="width:100%;height:500px;"></div>
```

One caveat to note, if you are using Typescript, the Amazon Connect SDK team has set locale to readonly so it will throw an error until modified. index.d.ts needs to be modified:
```typescript
interface AgentPreferences {
    //readonly locale?: string;
    locale?: string;
  }
```

**Comment by jeve7** [comment]
Hi team, any update regarding the solution of .getConfiguration() returning the local under "LANGUAGE" and .setConfiguration() expecting "locale"? The workaround doesn't work for Typescript as stated by Antoine because the locale is still readonly... I think the "custom" index.d.ts solution is a workaround for development environments but not a good idea for a production workload.
