### ISSUE TITLE
How can I get the Task Connection after a voice call ended?

### ISSUE THREAD

**Issue by derangedgirl** [amazon-connect/amazon-connect-streams#419]
The voice call ended using contact.getAgentConnection().destroy() but I couldn't get the existing Task Connections. Is there a way to still see the ongoing task connections?

**Comment by seiyako** [comment]
Hi, a voice contact and a task contact are two different contacts. To access the task connection, you need to call getAgentConnection on the task contact. 

```
const taskContacts = agent.getContacts().filter((c) => c.getType() === connect.ContactType.TASK);
const taskConnection = taskContacts[0].getAgentConnection();
```

Hope this helps!
