### ISSUE TITLE
How to hide customer phone number in Agent CCP screen on Amazon connect

### ISSUE THREAD

**Issue by anilmatrix** [amazon-connect/amazon-connect-streams#423]
I want to hide the customer phone number like XXXX and in fact only show last 4 digits of the customer number in the agent screen. This is for the security purpose. If they need to call them back they can dial from the list of calls they received from the call list XXXXXXX (last four digits)

**Comment by SamSchiff** [comment]
If you just want to hide the numbers on the frontend, you can use javascript to programmatically set the numbers to "XXXXXXXXXX" upon a call coming in

**Comment by vpogudina** [comment]
I'm closing this issue, please feel free to reopen, or open a new one if your question is still unanswered.
