### ISSUE TITLE
Rtc Metrics in Custom CCp

### ISSUE THREAD

**Issue by teachtocode** [amazon-connect/amazon-connect-streams#424]
I am trying to access the webrtc metrics from the custom ccp . In stock ccp , I am getting values. My goal is to show all the rtc values like latency , audio , jitler etc in realtime (both user and remote stats) . 
I am injecting softphone.js script in the ccp . This is basically a chrome extension that is showing the stats realtime. In stock ccp its working i am getting values from softphone (rtc session), But in custom it's not working. I guess softphone manger has some issues with custom ccp. Any one know how to make it work with custom

**Comment by Christian-Sesta** [comment]
So this is a fun one, you can use this additional connect extension lib:
https://github.com/aws/connect-rtc-js

Follow the steps provided and it should hopefully work for you. If you are using typescript be prepared to setup a `definition.d.ts` file and define the missing type definitions if your build relies on 0 type checking errors to succeed.

**Comment by vpogudina** [comment]
I'm closing this issue, please feel free to reopen, or submit a new one if that solution didn't work for you.
