### ISSUE TITLE
How will amazon-connect-streams work without third-party cookies and state partitioning?

### ISSUE THREAD

**Issue by marcogrcr** [amazon-connect/amazon-connect-streams#425]
With web browsers phasing out third-party cookies (e.g. [Chrome](https://blog.chromium.org/2020/01/building-more-private-web-path-towards.html) / [Firefox](https://blog.mozilla.org/en/products/firefox/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/)) and implementing state partitioning (e.g. [Chrome](https://docs.google.com/document/d/1V8sFDCEYTXZmwKa_qWUfTVNAuBcPsu6FC0PhqMD6KKQ) / [Firefox](https://developer.mozilla.org/en-US/docs/Web/Privacy/State_Partitioning)), if my understanding is correct, the following features of `amazon-connect-streams` will break:

- Authentication via the `lily-auth-prod-iad` and `lily-auth-refresh-prod-iad` third-party cookies for `https://${connect-instance}.awsapps.com`, `https://${connect-instance}.my.connect.aws` (#210).
- Cross-site `SharedWorker` re-usage (e.g. embedding CCP vs loading CCP directly on a new window).

https://github.com/amazon-connect/amazon-connect-streams/blob/057d05f3ccbc0dd947407ddcfc7346021f06d950/src/core.js#L322-L325

I wanted to understand what does this mean for `amazon-connect-streams` in a future where these configurations become the default or only allowed configuration?

**Comment by marktheunissen** [comment]
https://blog.google/products/chrome/updated-timeline-privacy-sandbox-milestones/

> Stage 2 (Starting mid-2023): Chrome will phase out support for third-party cookies over a three month period finishing in late 2023.

**Comment by ctwomblyamzn** [comment]
Hi @marcogrc, we are actively working on our approach for this. I will try to update this issue with any updates we have to share. Thank you for raising this here!

**Comment by adam-b-maurer** [comment]
> Hi @marcogrc, we are actively working on our approach for this. I will try to update this issue with any updates we have to share. Thank you for raising this here!

Hi @ctwomblyamzn ,  we are also very interested in the solution to this issue as well.

Is there any word on a timeline for this (or hopefully a solution)?

**Comment by IdealSystemsMCP** [comment]
Hi @ctwomblyamzn any update on this?

**Comment by apook-aspen-tgi** [comment]
Please tell me this update will include an actual auth flow for the streams API. The current solution of waiting for a second window to set a cookie is really painful.
