### ISSUE TITLE
onEnded() and onDestroy() event is not working to end the call

### ISSUE THREAD

**Issue by satyendragupta** [amazon-connect/amazon-connect-streams#427]
Hi,
Using AWS connect CCP ,onEnded() and onDestroy() event is not working to end the call or is there any direct method to close/end the call

Waiting for response!!

**Comment by martin-greenberg** [comment]
Per the documentation, all onX functions are used to subscribe code to be called in response to ending or destroying the contact. They don't have logic of their own aside from registering your logic and cannot be used to end or destroy a contact. You need to use the connection.destroy() API on the agent's connection to end a live contact.
