### ISSUE TITLE
Agent's losing ability to answer calls

### ISSUE THREAD

**Issue by Juzziee** [amazon-connect/amazon-connect-streams#428]
Hi all,

We have been experiencing issues where our agents will lose the ability answer/initialise a call. 
Refreshing our CCP will always resolve the issue.

This indicates to me that the webRTC connection is failing.

Have any of you experienced this? 
If so have you found a way to check to see if webrtc has died?

Thanks

**Comment by rakesh-eltropy** [comment]
@Juzziee I am facing the similar issue, have you found any solution?

**Comment by Juzziee** [comment]
> @Juzziee I am facing the similar issue, have you found any solution?

Unfortuantely, nothing yet.
We have been advising users to run our CCP in its own browser window. It appears that both chrome and firefox will put the tab into a sleep state when too many tabs are open or it has been inactive for too long.

**Comment by ctwomblyamzn** [comment]
Hi @Juzziee is this issue still occurring?

**Comment by bjm88** [comment]
We have seen agents also having issues getting calls after some time.  A few calls will go well, then over time errors start, so its hard to test and reproduce, but in real life scenarios happening too often!

"Error while accepting an incoming contact"
"ice_collection_timeout title"
"error while accepting an incoming contact"
"Softphone call failed"

**Comment by martin-greenberg** [comment]
Closing as it sounds like the issue has stopped recurring, but feel free to reopen if needed; although this might be a better issue to open a case with AWS Support so we can exchange internal logs and debugging info if needed.

**Comment by saurabh-ketanshah** [comment]
Hello, i have been facing this issue for over few months now across different networks and location. As users mentioned earlier it is intermittent and goes away after restarting the bworser tabs. Do we have any concreate solution to this issue? Its really annying to keep collecting the logs and opening multiple AWS support cases who always says "please validate your company network settings"

**Comment by PrabhakaranPragasam** [comment]
Was anyone able to fix this issue

**Comment by M571544** [comment]
Do we have a fix for this yet ?

**Comment by humzasadiq** [comment]
Do we have a fix for this? This doesnt seem to be a network issue, as our agents report that these connection failures occur intermittently within the same session... they can successfully take multiple calls, and then a subsequent call randomly fails. For example, one agent took 10 calls and the 8th call hit one of these errors.

| # | Error                                                        | Details                                                                                                                                                                                                                                                           |
| - | ------------------------------------------------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 1 | `FailedConnectCustomer`                                      | `streams.contact.missed` with `name: FailedConnectCustomer`. Agent connection `connected`, inbound `disconnected`.                                                                                                                                                |
| 2 | `MissedCallAgent` + WebSocket lost + `microphone_not_shared` | `streams.contact.missed` with `name: MissedCallAgent`, preceded by "WebSocket connection lost". Softphone error: `errorType: microphone_not_shared`, `errorMessage: "Your microphone is not enabled in your browser."` Agent `disconnected`, inbound `connected`. |
| 3 | `Ice Collection Timeout`                                     | `Softphone error {errorType: Ice Collection Timeout}`                                                                                                                                                                                                             |
| 4 | `microphone_not_shared` (standalone)                         | `Softphone error {errorType: microphone_not_shared, errorMessage: "Your microphone is not enabled in your browser."}`                                                                                                                                             |
| 5 | `GUM Other Failure`                                          | `Softphone error {errorType: GUM Other Failure}`                                                                                                                                                                                                                  |
| 6 | `Set Remote Description Failure`                             | `Softphone error {errorType: Set Remote Description Failure}`                                                                                                                                                                                                     |
| 7 | `signalling_handshake_failure` (with endpoint)               | `errorType: signalling_handshake_failure`, `errorMessage: "Handshaking with Signalling Server via endpoint *.transport.connect.<region>.amazonaws.com failed."`                                                                                                   |
| 8 | `Signalling Handshake Failure` (generic)                     | `errorType: Signalling Handshake Failure`                                                                                                                                                                                                                         |
