### ISSUE TITLE
hasOtherConnectedCCPs() and numberOfConnectedCCPs()

### ISSUE THREAD

**Issue by mschersten** [amazon-connect/amazon-connect-streams#429]
I would like to identify if an agent has multiple CCPs loaded, and I see that the softphone in the iframe has methods for this.  Using chrome devtools and the softphone javascript context, I can execute connect.hasOtherConnectedCCPs() and connect.numberOfConnectedCCPs().  Is there a way to do this using the streams API?

**Comment by martin-greenberg** [comment]
These methods are not supported for public use at this time.
