### ISSUE TITLE
Is it possible to prevent duplicate agent login in two different browsers ?

### ISSUE THREAD

**Issue by darwinanirudh** [amazon-connect/amazon-connect-streams#430]
Agent logs into amazon CCP in one browser. 
Same Agent logs into amazon CCP in another browser.

Is it possible to prevent the duplicate agent login in another browser ?

**Comment by martin-greenberg** [comment]
CCP and Streams don't interact directly with authentication or session management so there's no way at present to do this through the Streams API.
