### ISSUE TITLE
Is it possible to get all agent configures?

### ISSUE THREAD

**Issue by nikadoridaisuke** [amazon-connect/amazon-connect-streams#432]
Hi.
I want to get all agent configurations by amazon-connect-stream API.
because of create agent manage dash board that can check all agent configuration.
Is it have method to get all agent configuration?
Best regards.

**Comment by martin-greenberg** [comment]
There's no way to get all agent configurations through the Streams API, it is only possible at present to get configurations for the agent who is currently authenticated.
