### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by aqarain** [amazon-connect/amazon-connect-streams#439]
I am trying to integrate **amazon-connect-streams** in my node application. The node app consists of an `index.html` file containing one div only and one `app.js` file.

I am getting an error when I run my node application.

**Error:** 

```
/home/abc/chat-app/backend/node_modules/amazon-connect-streams/release/connect-streams.js:21794
  var userAgent = navigator.userAgent;
                  ^

ReferenceError: navigator is not defined
    at /home/abc/chat-app/backend/node_modules/amazon-connect-streams/release/connect-streams.js:21794:19
    at Object.<anonymous> (/home/abc/chat-app/backend/node_modules/amazon-connect-streams/release/connect-streams.js:22466:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/abc/chat-app/backend/src/app.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

`app.js`

```
const PORT = process.env.PORT || 3000;

const express = require("express");
const path = require("path");
require("amazon-connect-streams");

const app = express();

app.get("/", function (req, res) {
  console.log(connect);
  connect.core.initCCP(containerDiv, {
    ccpUrl: "https://abcd.my.connect.aws/ccp-v2/chat/",
    region: "eu-central-1",
    softphone: {
      allowFramedSoftphone: true
    }
  });
  res.sendFile(path.join(__dirname, "/index.html"));
});

app.listen(PORT, () => {
  console.log("Server is up on port 3000");
});
```

Can anyone please help me fix this issue? What am I missing here?

**Comment by Christian-Sesta** [comment]
Hey from my understanding `amazon-connect-streams` is a client side only library and wont work at all in NodeJS since its server side javascript that has no relation to the DOM.

I would suggest running `connect.core.initCCP` creating a js script and sourcing it within the index.html file.

You would most likely want the amazon SDK for actions you can perform against your connect instance.

**Comment by ctwomblyamzn** [comment]
Hello, Christian-Sesta is correct, this will not work in a node express script. You'll want to run this `initCCP` script within the `/index.html` file somehow, either in a separate script file or right within a `<script/>` tag within the file, such that it is executed in the browser that the html file will be served to.
