### ISSUE TITLE
Customize CCP UI

### ISSUE THREAD

**Issue by Karlen92** [amazon-connect/amazon-connect-streams#440]
We currently. use CCP in its default UI which is provided by AWS, we embed it into an iframe, and that works just fine.
https://docs.aws.amazon.com/connect/latest/adminguide/agent-user-guide.html 

Now we want to customize the UI of CCP itself (accept calls, access quick connects, perform login and etc. ).

My question is that possible to customize the default CCP, and if yes, is this recommended direction to follow?

Thanks in Advance!

**Comment by ctwomblyamzn** [comment]
Hi @Karlen92 we don't actually allow you to customize the UI of CCP directly. You can embed CCPUI and place elements that visually appear over it in the rendered DOM, though, which may be what you are referring to. Alternatively, you can hide the div that you supply to embed CCP inside of, and that will entirely hide CCPUI, leaving room for a custom UI of your own on the rendered DOM. If that didn't answer your question, please let reopen this.
