### ISSUE TITLE
Not able to host this on S3

### ISSUE THREAD

**Issue by baswma** [amazon-connect/amazon-connect-streams#442]
Hi, 
I am using the below streams js version i.e amazon-connect-1.6.8-2-ga95f3de.js and the index.html file. Uploaded both of them in S3 and made the bucket public. Also, enabled static web hosting on S3. Whitelisted the S3 URL on Connect settings. Still after invoking the URL, it asks for auth and then just displays a blank screen. Same with both Chrome and Firefox.
This setup works well with hosting it on local server. S3 isn't working somehow. Any insight would be appreciated.

Browser logs : 
react-dom.production.min.js:4928 TypeError: Cannot read property 'enumerateDevices' of undefined
    at AudioDeviceContext.js:29
    at ss (react-dom.production.min.js:5012)
    at Nu (react-dom.production.min.js:6336)
    at t.unstable_runWithPriority (scheduler.production.min.js:309)
    at Vo (react-dom.production.min.js:2742)
    at Cu (react-dom.production.min.js:6316)
    at lu (react-dom.production.min.js:5732)
    at react-dom.production.min.js:2776
    at t.unstable_runWithPriority (scheduler.production.min.js:309)
    at Vo (react-dom.production.min.js:2742)

/favicon.ico:1 Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by ctwomblyamzn** [comment]
Hi @baswma, sorry to hear you are ahving this issue. I'm not exactly sure what your setup is after your description. However, if `enumerateDevices` isn't found, it's probably due to one of two things: 

1. You are using Internet Explorer
2. You are using an insecure connection (`http`). [This post](https://stackoverflow.com/questions/43183514/unable-to-get-property-enumeratedevices-of-undefined-or-null-reference) might help you (experimental flags are suggested to fix it).

If you're still having problems, can you further clarify your setup? You are hosting an entire webapp in s3 or just streams? Can you attach a link to your full console log dump?

**Comment by baswma** [comment]
Hello ctwomblyamzn,
Thanks for reaching out. Let me explain my setup.
1. Hosted streams-js on S3 (added only the java script .js file and the html file)
2. Enabled S3 static website on bucket
3. Made S3 bucket public
4. Whitelisted S3 static website URL on Connect console.

Now, when I try to access the S3 URL, it pops up for CCP auth and when I do so, it goes back and stays blank instead of displaying CCP console. During this time, if I see the browser logs, it gives the above errors and also a few more

Errors : 
X-Frame issue pointing to SAMEORIGIN
Microphone access error
Cannot read property 'enumerateDevices' of undefined

I have tried this in both Chrome and Firefox. Havent used IE at all. May be I will post some screenshots soon.

**Comment by baswma** [comment]
yes, at this moment i am using http only. So is that the only reason for this behaviour? is it documented in any amazon official website like streams-js hosting on S3 wont work with http ?

**Comment by ctwomblyamzn** [comment]
Hi @baswma, thanks for the info. Have you definitely whitelisted the s3 static website domain in the Connect Instance's [allow list for integrated applications](https://docs.aws.amazon.com/connect/latest/adminguide/app-integration.html)?

**Comment by baswma** [comment]
Hello ctwomblyamzn@
Yes, I have. As by default the static website will have an http url, is it mandatory to have it as https (using SSL or CloudFront) ?
Will it not work with http itself ? I see the screen blinks with CCP console and then turns on to blank again. If https is required, do we have it documented anywhere?

**Comment by ReeceTrolley-EORI** [comment]
![image](https://user-images.githubusercontent.com/82092493/128635340-c7b1a0fa-30d0-414e-9afb-e586ff609a1a.png)
Taken from https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md

**Comment by ctwomblyamzn** [comment]
I just wanted to loop back on this. The `Allowlisted domains must be HTTPS` requirement does answer this question. Thanks to @ReeceTrolley-EORI for digging that up. On some browsers you can get around the underlying constraint in certain ways, and using localhost on HTTP will work by default on Chrome. 

However, for any production systems we highly recommend that you use HTTPS. Closing this as the question has been answered.
