### ISSUE TITLE
Api for selecting Microphone and speakers

### ISSUE THREAD

**Issue by jakubzeman-acc** [amazon-connect/amazon-connect-streams#45]
I miss in the API a callback which can filter Speaker and Mic devices which the CCP uses for:
- Phone calls
- Ring tones

It can be very simple call back which just returns CONSTRAINTS for `navigator.mediaDevices.getUserMedia()`. Something like:
```
function contactConstraints() {
    return {
        deviceId: {
            exact: [inAudioDevSelected, outAudioDevSelected]
        }
    };
}

function ringConstraints() {
    return {
        deviceId: {
            exact: outRingDevSelected
        }
    };
}

connect.core.initCCP(iframeContainer, {
    ccpUrl: url,
    loginPopup: false,
    softphone: {
        allowFramedSoftphone: true,
        disableRingtone: false
    },
    contactAudioConstraints: contactConstraints,
    ringTonesAudioConstraints: ringConstraints
});
```

**Comment by extmchristensen** [comment]
Yes indeed! Want this too!

**Comment by seiyako** [comment]
Hi, in the 1.6.3 release, we added audio device related APIs such as `agent.setSpeakerDevice()`, `agent.setMicrophoneDevice()`, and `agent.setRingerDevice()`. For embedded CCP users, you can pass a new parameter `pageOptions: { enableAudioDeviceSettings: true }` to initCCP API, which will add an audio device section to the Settings page.
