### ISSUE TITLE
setState() method not update the agent states in backend

### ISSUE THREAD

**Issue by sivac47123** [amazon-connect/amazon-connect-streams#452]
Hi Team,

We have facing intermittent issue in production regarding agent state update. Some times agent state is not updated properly. Sample code updated below. Most of the time it went to success but the states not updated in back end. We have added 1 second timer to verify the state using onstatechange method. Still states are not updated in some scenarios.

       setState(agentState, {
            success: function () {
              resolve(true);
            },
            failure: function () {
              resolve(false);
            }

Thanks in advance for sharing your thoughts.

**Comment by martin-greenberg** [comment]
What does the `agentState` variable represent here and how are you getting it to pass to `setState`?

**Comment by ctwomblyamzn** [comment]
Hi @sivac47123, the `onStateChange` handler will be updated when our agent snapshot api returns the updated state. This is after `setState` is called and succeeds. Therefore, `setState` succeeding simply means that the state will be updated, not that it already is reflected in the system. I suppose sometimes 1 second would not be enough time for the state change to be reflected in the agent snapshot api. 

Assuming that you are using the api correctly ^^, my colleague is wondering about that.
