### ISSUE TITLE
3rd party login / accessing authToken

### ISSUE THREAD

**Issue by alparbartok** [amazon-connect/amazon-connect-streams#453]
Hi guys, I don't know if this is a right place to ask for help but I didn't find any answer to my question. 
I'm working on a project which uses amazon connect. 
We have some issues with the login. Is there a way to make a login in amazon connect from another site? (I found only the CCP login pop-up).
Also after I login with the pop-up is there a way to access the authToken provided by Amazon connect? I tried to use the `/auth/authorize` endpoint with my `instance` but nice it's a no-cors fetch the reponse has type `opaque` and I can't read the response on newer browser (it works on older browsers).

I'd really appreciate  a little help in here, thanks a lot.

**Comment by martin-greenberg** [comment]
The established way to log into Connect by logging into a 3rd party site would be to integrate with the other site as a SAML identity provider if possible; instructions can be found at https://docs.aws.amazon.com/connect/latest/adminguide/configure-saml.html

Currently I'm not aware of a way to do what you're asking but you can use the GetFederationToken API to get an access token for Connect federation: https://docs.aws.amazon.com/connect/latest/APIReference/API_GetFederationToken.html

**Comment by martin-greenberg** [comment]
GetFederationToken will give you an auth token to call Connect APIs. You will not be able to use APIs owned by Connect to get tokens that will allow you to call other AWS services. What you're asking to do is more complicated than we are able to provide support for in this forum and I would suggest working with an AWS solution architect on this.
