### ISSUE TITLE
Is connection.destroy supposed to invoke onEnded/onDestroy of the _contact_ ?

### ISSUE THREAD

**Issue by nisabek** [amazon-connect/amazon-connect-streams#457]
For the voice calls, I assumed the following workflow:

1. Call comes in and is accepted by the agent
2. "On hangup" -> destroy active _connection_
3. put agent into "after call work" state (custom) so they don't receive new calls
4. when the agent is "done" -> call contact.clear()

can you confirm the workflow makes sense?...

if so.. why is calling destroy on the _connection_ cause onDestroy and onEnded being invoked on the contact and how would I keep the contact, while the _voice_ connection is ended?..

from Documentation.md

```
connection.destroy()

conn.destroy({
   success: function() { /* ... */ },
   failure: function(err) { /* ... */ }
});

Ends the connection. This can be used to reject contacts, end live contacts, and clear chat ACW. At this point, it should be used to reject contacts and end live contacts only. We are deprecating the behavior of clearing ACW with this API. To clear ACW for voice and chat contacts, use the contact.clear() API.

Optional success and failure callbacks can be provided to determine if the operation was successful.
```

Thanks in advance,
Nune

**Comment by ctwomblyamzn** [comment]
Hi @nisabek, the flow of calling `connection.destroy` and then `contact.clear()` is right. 

"How would I keep the contact, while the voice connection is ended?" -- The contact remains on the agent object. It is still there, but not a live contact anymore. Ending a contact does not imply that the contact is cleared. Destroying a contact implies that the contact is no longer there (out of ACW), but the contact.onDestroy callback is only called once the contact is cleared for voice contacts.

I think that answers your questions. Please reopen if you're not sure about this.
