### ISSUE TITLE
Refresh after routing profile change

### ISSUE THREAD

**Issue by stephan-pi** [amazon-connect/amazon-connect-streams#459]
Good Morning, 
I wanted to know how to update the CCP widget after sending the routing profile change with the updateUserRoutingProfile API.
I need to send commands to the CCP to reload itself with the new routing profile. How can I do ?

**Comment by Christian-Sesta** [comment]
Just wondering if there as been any progress on this issue?

**Comment by stephan-pi** [comment]
the problem still exists, there is no possibility to refresh the ccp in order to synchronize the new routing profile. It runs at the time these logs are generated.
![peerScreen](https://user-images.githubusercontent.com/82958351/163427112-4f6fe4fa-8f48-4d75-9401-84995e7a97fa.PNG)

This occurs every 30 seconds and there is no way to trigger
