### ISSUE TITLE
AgentAppService.Acs.listIntegrationAssociations FAC.js requests failing

### ISSUE THREAD

**Issue by marktheunissen** [amazon-connect/amazon-connect-streams#462]
We're seeing two errors suddenly appearing in our console logs from Connect streams (this is also happening in the AWS CCP):

`getDomainId failed`
`'AgentAppService.Acs.listIntegrationAssociations' API request failed`

Coming from this file:

https://[CONNECT_INSTANCE].my.connect.aws/connect/ccp-naws/static/js/configs/FAC.js

This FAC.js file is trying to do this:

```
async isFeatureEnabled(featureName) {
    try {
      const endpoint = await this.getFACEndpoint();
      if (!endpoint) return false;
      const response = await fetch(`${endpoint}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
        },
        body: this.getEncryptedFACRequestBody(featureName)
      }); 
      const json = await response.json();
      return _.isEqual(json, {});
    } catch (error) {
      return false;
    }
  }
```

The `POST /ccp-v2/fac` fails with status 400

`:authority: ccp.cell-1.prod.ap-southeast-2.prod.connect.aws.a2z.com.`

The response body: `{"status":400,"message":"Invalid input!"}`

**Comment by Christian-Sesta** [comment]
Was actually just about to raise a ticket on this exact thing. Something I have also noticed in a few random instances is that streams gets in a weird state at with this call and enters a agent user authorisation/ authentication loop. i.e. login url popup keeps appearing and closing in a loop and stealing screen focus. running v1.6.10.

**Comment by seiyako** [comment]
Hi, sorry for the inconvenience, this was probably related to our deployment that changes how to authorize VoiceId api invocations before the GA (general availability) launch on 9/27. 
Are you guys still seeing the same error now? Because the default domain will deprecate soon, you may need to create and associate a domain with your instance. Also please make sure to give the "VoiceId" permission to the agent in the security profile.

**Comment by seiyako** [comment]
Let me clarify one thing, are you a VoiceId preview customer who have been using a default VoiceId domain? If not, please ignore my previous comment as that was only intended to those customers.

I feel those two errors you reported are separate issues.
Getting `'AgentAppService.Acs.listIntegrationAssociations' API request failed` error is expected when the agent has the "Voice ID" permission in the security profile but VoiceId domain is not associated with the connect instance. Please check if the agent has it. Please note that if you login with "emergency login", the agent will automatically have all permissions.

Getting `POST /ccp-v2/fac` error is also expected when your account is not allow-listed for a beta feature. Please ignore this error message.

**Comment by CiscoKidxx** [comment]
Any progress on this ?

**Comment by thtliife** [comment]
Any word on getting this error out of the console?

**Comment by gamliela** [comment]
@marktheunissen can you please consider reopen or report on progress? This error is still happening. Thanks!

**Comment by andrei-at-work** [comment]
Still an issue in 2.4.6 (May 2023). Any progress on this?

![image](https://github.com/amazon-connect/amazon-connect-streams/assets/74427636/c80c1145-cc07-42f4-8b3c-678d55635be1)

**Comment by kevingravel** [comment]
Issue is still happening as of version 2.5.0. Any updates on this issue that was originally opened in 2021? These errors are polluting our browser console logs.
![image](https://github.com/amazon-connect/amazon-connect-streams/assets/136620868/286e2cb1-9853-4cda-a24b-51aa30d3d781)

**Comment by gjesse** [comment]
Why was this closed?
