### ISSUE TITLE
Cannot unset/unqueue next status

### ISSUE THREAD

**Issue by tjw0051** [amazon-connect/amazon-connect-streams#465]
When enqueuing a next status, the action cannot be undone/unset.

**Steps to reproduce:**

1. Connect a new contact to the agent
2. Call `agent.setState(OFFLINE_STATE, {enqueueNextState: true})`
3. Calling `agent.getNextState` will show the offline state has been enqueued.
4. Call `agent.setState(CURRENT_ONLINE_STATE, {enqueueNextState: true})` with the current state.
5. Calling `agent.getNextState` will show the offline state is still enqueued.

**Comment by sseidel16** [comment]
Adding on to this same issue, `onEnqueuedNextState` is also not fired when the next state is cleared, even though the next state is clearly changing. Therefore, if another CCP clears the next state, there is no way to detect this change.

**Comment by vpogudina** [comment]
Hi, do you still see same issue? I tried to reproduce mentioned behavior and I didn't see that issue. We've made some fixes since September that could have improved the behavior.

**Comment by kir25** [comment]
Still reproduce for me with 2.0.0, step for reproducing same ones which were at the beginning. 

{"type":"InvalidStateException","message":"Cannot change agent state: Invalid agent or contact state.","stack":["InvalidStateException: Cannot change agent state: Invalid agent or contact state.",..................
