### ISSUE TITLE
Unable to setMicrophoneDevice or other audio devices

### ISSUE THREAD

**Issue by webfactorymatt** [amazon-connect/amazon-connect-streams#467]
Issue

When trying to use the setMicrophoneDevice method the device does not change. 
 
Tried using the deviceId directly and passing the audio device array item from getFrameMediaDevices result as has been suggested elsewhere. Nether seem to have any impact.

In addition only the event onSpeakerDeviceChanged seems to fire when changing a device in the CCP (Framed)

UPDATE:
It appears that the devices can only be changed when in an active call. When in a call the on device change events all fire correctly and setting the device via the device ID works. Note also that the selects in the CCP settings tab do not update as per the changes you make via the code

**Comment by shishkev** [comment]
Thanks for the find. We are working on a fix.

**Comment by stevenasi** [comment]
We are also experiencing this. Any updates? It's a critical issue for our customers.

**Comment by seiyako** [comment]
This is a known issue that mic/speaker devices can only be changed when in an active call. We're working on fixing this. As a workaround, you can listen to the contact.onConnected event for a voice contact and call setMicrophoneDevice or setSpeakerDevice with a deviceId.
