### ISSUE TITLE
Error clearing rejected task

### ISSUE THREAD

**Issue by AzerinnD** [amazon-connect/amazon-connect-streams#474]
Hello,

I am trying to implement tasks in our custom desktop and running into an issue when trying to clear a rejected task.

If I have a Task contact in the reject state and try to call clear I get an error and digging in I see this error message:
"InvalidStateException: Cannot clear contact: invalid state REJECTED"

Looking at the documentation for the contact.clear method it states:
This is a more generic form of contact.complete(). Use this for voice, chat, and task contacts to clear the contact when the contact is no longer actively being worked on (i.e. it's one of ERROR, ACW, MISSED, **REJECTED**). It works for both monitoring and non-monitoring connections.

So it seems like this should work; however, it obviously does not.

How can I clear a rejected task?

If it is the only contact I can just change the agent state; however, I can't do that when I have multiple tasks open and just want to clear the one rejected task.

Thank you

**Comment by SamSchiff** [comment]
We're working on updating `contact.clear` to work for the rejected case. But for now you should use `contact.complete` for rejected contacts

**Comment by vpogudina** [comment]
I've tested the contact.clear for the rejected case and it is functioning as expected now. Please feel free to reopen the issue if problem persists.
