### ISSUE TITLE
How to programmatically determine which tab is active chat or softphone?

### ISSUE THREAD

**Issue by Ruslan1992** [amazon-connect/amazon-connect-streams#476]
Hello everyone!
Can I in any way determine which tab in CCP I am in a chat or softphone? Depending on the given tab, I need to display this or that information

**Comment by Christian-Sesta** [comment]
`contact.getType()` should return you one of the following types defined in this link below. From that you will be able to determine the type of info to display.

https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#contacttype

**Comment by Ruslan1992** [comment]
Unfortunately, this does not work. It is not always possible to determine which contact is currently displayed. (When using the onViewContact method, when we have no active calls and there is one active chat, it fires only once)
