### ISSUE TITLE
CCP Always Using Microphone

### ISSUE THREAD

**Issue by owaink** [amazon-connect/amazon-connect-streams#478]
Several of our support staff have noticed that the embedded CCP is always using their microphone as indicated by the red dot on the tab in Chrome. This is relatively recent with our earliest report coming in in mid September. Our support staff use a Bluetooth headset that drops its audio quality when the microphone is enabled because of shared bandwidth, so they are currently dealing with permanently degraded audio. This is reproduceable on Windows and Mac, all web browsers. Other pages that use the microphone do not have this issue and only use the microphone when it is necessary.

It looks like the responsible code is in `softphone.js` in the `setMicrophoneDevice` function. It looks like when the audio device is set up a stream is opened for it and that single stream is used for the duration of the life of the device instead of starting and stopping a stream for each phone call. 

If this could be addressed our entire staff would greatly appreciate it!

**Comment by mschersten** [comment]
We are also experiencing this.  Not really an issue except that with the red dot always on they can't use it as an indicator that they are on an actual call.

**Comment by Christian-Sesta** [comment]
Experiencing this as well

**Comment by marcin-m** [comment]
Same thing (always on microphone) is now a case for default CCP in EU Frankfurt (seems to start in November 2023). Agents report it a problem - at least one of them says there is constant "click-like" sound which strains the ears.

**Comment by Solomon-m** [comment]
Hello
We are also experiencing this issue with custom CCP.

**Comment by jindalvikas11** [comment]
Our agents also reported same issue

**Comment by maik-idealo** [comment]
we have the same issue

**Comment by andywang219** [comment]
Hi, this is due to a feature we introduced called EarlyGUM. This feature helps us capture a fresh user media before setting up a voice contact and this also helps reduce the latency when setting up the RTC session. 

You can disable this by setting `allowEarlyGum` to false in your initCCP params.
Please see: https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#:~:text=initSoftphoneManager(%7B%20VDIPlatform%3A%20%22CITRIX%22%20%7D)-,allowEarlyGum,-%3A%20If%20true%20or

**Comment by ColoradoKiwi** [comment]
Hi - one question on this...
What are the negatives if we do set allowEarlyGum to false. You mentioned the positives above (which I get) - just wanting to know, if we find we have to go to false, what the impacts would be. Is 'false' essentially the old/previous behavior prior to this option being introduced?  Just wanting to understand the scenario's / recommendations, as there's not much about it in the docs.

Thanks for any further insight.

**Comment by andywang219** [comment]
> Is 'false' essentially the old/previous behavior prior to this option being introduced?
This is correct, you will just revert back to the previous behavior. This will mean that media will be captured before the call is connected, which would introduce some latency in setting up the call.

**Comment by criostre** [comment]
@andywang219 do you know when 'allowEarlyGum' feature was introduced in amazon-connect-streams ?

**Comment by bretticus-mc** [comment]
EarlyGUM was released in October 2023. Closing the issue as there is an option to disable this feature.
