### ISSUE TITLE
Make second call is not working after disconnect the first call

### ISSUE THREAD

**Issue by sivac47123** [amazon-connect/amazon-connect-streams#479]
Hi Team,

We made a conference call. After some time we end the first call. Now try to add new call. System throws an error. We are unable to make second call. Suppose if we disconnect the second call then we can able to make another call.

Issue persist only when disconnect the first call.

Steps:

1. Make out bound call
2. Make second call and conference the call
3. Disconnect the first call
4. Try to add new call

Regards
Siva

**Comment by shishkev** [comment]
When the initial (customer) call is disconnected, new connections cannot be added to the call. For now, this is a server side limitation.
