### ISSUE TITLE
onViewContact() callback is getting called endlessly

### ISSUE THREAD

**Issue by komal-j-khadse** [amazon-connect/amazon-connect-streams#480]
We are using, amazon-connect-streams version 1.6.0 inside an angular 9 application.

We are calling connect.core.viewContact() on a item's click event. The callback connect.core.onViewContact() is getting called endlessly.

**Comment by SamSchiff** [comment]
We are deploying an update to CCP that should reduce the number of calls. Expect that to be out within the next month

**Comment by SamSchiff** [comment]
This should be fixed now
