### ISSUE TITLE
Need information about API methods

### ISSUE THREAD

**Issue by Ruslan1992** [amazon-connect/amazon-connect-streams#488]
Hi There,

Interested in the possibility of adding api methods:

1. The method by which we can get the information entered by the agent on the onTyping event
2. A method in which we can programmatically insert text content into the typing field in CCP

Is it possible to implement these methods with the current functionality, or do you need to write a custom solution?

Thank you for your support!
@jagadeeshaby @jolim24601 @kvs6rj 
 
Best Regards
Ruslan Andreichikov

**Comment by seiyako** [comment]
For the onTyping event handler, could you post the feature request in [ChatJS repository](https://github.com/amazon-connect/amazon-connect-chatjs/issues)? 
bbolek's suggestion should work for the second question.
