### ISSUE TITLE
Update Contact Attributes

### ISSUE THREAD

**Issue by vamsive** [amazon-connect/amazon-connect-streams#49]
Is there any API method to update the contact attributes?  If not, any instructions on how to update the contact attributes

**Comment by mschersten** [comment]
The only way to set contact attributes is from within a contact flow using a "set contact attributes" block.  They can be set to a fixed value, or set dynamically from the results of a Lambda function.

**Comment by vamsive** [comment]
Is it not possible to update from amazon-connect-stream API and not from contact flow block as we have a requirement to update from custom softphone client

**Comment by mschersten** [comment]
Can you describe your use case some more?  Do you want to use these contact attributes for branching in a contact flow?  That could be useful in transferring, but generally once an agent gets a hold of a contact in the softphone client, the contact flow branching has ended.

This could also be useful for reporting or some other non-flow purpose.  Either way, if you really want this you probably need to do some workarounds.  I can imagine the custom client writing a record to some external database, keyed from the contact ARN, and then having a contact flow use a lambda function to get that database record and pull the attributes from there.

Getting that lambda function to execute is a little tricky, as I don't think anything executes in contact flows when the agent and caller are connected.  Maybe set this up as an agent hold flow, and run the lambda function and give a success message, maybe reading the attributes out, to the agent that way.  I haven't used agent hold flows before, though, so I'm not sure.

**Comment by AndySteel-kcom** [comment]
This is seriously needed. An agent may want to update call attributes before transferring the call onto another team for example. Also may want to make a call into another part of the business, setting certain attributes as part of the call initialisation ideally or possibly upon call being routed to the agent.

**Comment by mike-rodriguez** [comment]
This is a need as well, being as for inbound or outbound calling, I would like to be able to log the call result. As an example, for outbound calling, we would like to log if the call was a no answer, a not interested, a lead or a left message. 

Would this be possible through the AWS Connect CCP or with the Streams API in the near future?

**Comment by ffalanga** [comment]
Hi All, 
any news about this topic?
I think that update the Contact attributes, is the main function for any serious CTI.
Please let me know if and when it will be added.
Thanks

**Comment by ffalanga** [comment]
Hi,
I tried to call this API, but without success.
In other words I created the “Connect” instance:
	var x = new AWS.Connect({

Created the “params”, and called the API:
	x.updateContactAttributes(myparams, function(err, data) {
            if (err) 
                console.log(err, err.stack);
            else
                console.log(data);
          });

I receive the following CORS error:
index-sdk.html:1 Access to XMLHttpRequest at 'https://connect.eu-central-1.amazonaws.com/' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

But I don’t know where configure the Cross-Origin.
I tried in any sections ("Application Integration”, “S3”, etc….), without success.


Please can you help me?

Thanks in advance
Francesco

**Comment by NBNalluri** [comment]
We have an use case to update Contact attributes (Call related Information ), before the call is getting transferred to another agent or Queue.

Is it possible through streams api ?

**Comment by ctwomblyamzn** [comment]
Sorry about the long wait. Updating contact attributes is not currently possible through the streams api. We are tracking this internally. I'm marking this issue as an enhancement for now.

**Comment by darwinanirudh** [comment]
any update on the issue ?
