### ISSUE TITLE
After Reject: how can i transfer this call to another agent.

### ISSUE THREAD

**Issue by WangBank** [amazon-connect/amazon-connect-streams#491]
As the title, when a call come in and i reject, the call will come in again, I want transfer this call to another auto, what should i do?  thank you.

**Comment by mschersten** [comment]
In general when one agent rejects a queued call it will be sent along to the next available agent in the queue.  If it is going back to the same agent after rejecting then it's likely that there is no other agent available in the queue.  This can come up often in testing, but in a production environment with many agents available you should see calls being routed to different agents after rejection.

**Comment by WangBank** [comment]
we use a other func to implement that, before transfer in agent, we use lambda and a loop( check the call status in our app) send info to our app, and reminder user choice reject or accept with a custom page.
