### ISSUE TITLE
Get all connected agents status

### ISSUE THREAD

**Issue by stephan-pi** [amazon-connect/amazon-connect-streams#496]
it would be useful to receive from the listAgentStatuses api not only the routable offline custom statuses but also the activity statuses (busy, pending busy, missed ... etc) to know in real time the status of the other connected agents

**Comment by SamSchiff** [comment]
Amazon Connect Streams tries to be scoped down to information one agent wherever possible. The information you requested should be available through the Admin Website at `{connect-url}/home`

**Comment by souvmaju-us** [comment]
Are there any plans for an API interface to retrieve this information in real-time? The following response back in 2018 references something similar about a different API.

https://github.com/amazon-connect/amazon-connect-streams/issues/34#issuecomment-362356016

**Comment by jtbaldwiT** [comment]
Following up from late 2023, are there any plans to retrieve this data through an API without navigating to the Connect website and viewing it manually? Even if it's an API as a part of [the Client Connect SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-connect/) or somewhere else, it'd be useful to have that data available.
