### ISSUE TITLE
OnMissed contact event not getting triggered

### ISSUE THREAD

**Issue by fkhan439** [amazon-connect/amazon-connect-streams#497]
While using onMissed event, the event doesn't seem to get triggered. Let me know the workaround for this

**Comment by SamSchiff** [comment]
I'm seeing that function working as intended in the latest version of Streams. In what scenario exactly are you not seeing the function being triggered?

**Comment by fkhan439** [comment]
In case when an inbound call is not received by the agent, the state changes to Missed, I am just using alert for onMissed event but it seems that event never triggers which doesn’t pop up my alert.

**Comment by SamSchiff** [comment]
Can you send a snippet of your code and let us know what version of Streams you're using?

**Comment by fkhan439** [comment]
window.myCPP = window.myCPP || {};

    //replace with the CCP URL for the current Amazon Connect instance
    var ccpUrl = "xxxxxxxxxxxxxx";
	
    connect.core.initCCP(containerDiv, {
        ccpUrl: ccpUrl,
	    loginPopup: true,
		loginPopupAutoClose: true,
		loginOptions:{
			autoClose: true
		},
        softphone: {
            allowFramedSoftphone: true
        }
    });
   
    connect.contact(subscribeToContactEvents);
	
   function subscribeToContactEvents(contact) {
	    contact.onConnected(handleContactConnected);
		contact.onConnecting(handleContactConnecting);
        contact.onMissed(handleMissed);
   		contact.onEnded(handleEndCall);
		contact.onACW(handleACW);
		contact.onIncoming(handleOnIncoming(contact.getAttributes()));
        
        	
    }
	
	 function handleContactConnected(contact) {
        if (contact) {	
        document.getElementById("State1").style.display = "none"
        document.getElementById("State2").style.display = "none"
        document.getElementById("State3").style.display = "table"
        } else {
            logInfoEvent("[contact.onConnected] Contact connected to agent. Null contact passed to event handler");
        }
    }
	
	function handleContactConnecting(contact) {
        if (contact) {	
        document.getElementById("State1").style.display = "none"
        document.getElementById("State2").style.display = "none"
        document.getElementById("State3").style.display = "table"
        } else {
            logInfoEvent("[contact.onConnected] Contact connected to agent. Null contact passed to event handler");
        }
    }
    
	
	
	
   function handleACW(){
	    
		document.getElementById("State1").style.display = "none"
        document.getElementById("State2").style.display = "table"
        document.getElementById("State3").style.display = "none"
        document.getElementById('containerDiv').style.pointerEvents = 'none';  
        document.getElementById("authStatus").innerHTML = "";
		document.getElementById("callerNumber").innerHTML = "";
		document.getElementById("policyNumber").innerHTML = "";
		document.getElementById("dob").innerHTML = "";
		document.getElementById("ssn").innerHTML = "";		
		runOnMissed="false";
    }
	
	function handleMissed(contact){
	    alert('onMissed Event');
		document.getElementById("State1").style.display = "table"
        document.getElementById("State2").style.display = "none"
        document.getElementById("State3").style.display = "none"
	}
	
	 function handleEndCall(){
	  
		document.getElementById("authStatus").innerHTML = "";
		document.getElementById("callerNumber").innerHTML = "";
		document.getElementById("policyNumber").innerHTML = "";
		document.getElementById("dob").innerHTML = "";
		document.getElementById("ssn").innerHTML = "";		
		
		document.getElementById("State1").style.display = "table"
        document.getElementById("State2").style.display = "none"
        document.getElementById("State3").style.display = "none"		
		
                     
    }


function handleOnIncoming(msg){
	    
        document.getElementById("State1").style.display = "none";
        document.getElementById("State3").style.display = "table";
		document.getElementById("authStatus").innerHTML = msg.Status.value;
		document.getElementById("callerNumber").innerHTML = msg.CustomerNumber.value;
		document.getElementById("policyNumber").innerHTML = msg.PolicyNumber.value;
		document.getElementById("dob").innerHTML = msg.DOB.value;
		document.getElementById("ssn").innerHTML = msg.SSNNumber.value;
        
}


Version: AWS SDK for JavaScript v2.553.0

**Comment by seiyako** [comment]
Hi, were you able to resolve the issue? The code snippet looks fine, but does any other event handlers get triggered? Are you seeing any event handler errors in your console?
