### ISSUE TITLE
NPM package support

### ISSUE THREAD

**Issue by sromocki** [amazon-connect/amazon-connect-streams#5]
Are there any plans to turn this into an NPM package?

**Comment by ninjamike54** [comment]
I'm not aware of any plans currently, but it looks like this is a popular request, so I'll kick something off to track it. We'll update this when we have more details

**Comment by Droogans** [comment]
Do you have any updates on this? Is there a reason you aren't publishing this package as an npm dependency?

**Comment by jagadeeshaby** [comment]
Here we go - https://github.com/aws/amazon-connect-streams/pull/61

Included the NPM package system with the Mocha unit tests!

**Comment by sromocki** [comment]
Sorry, I didn't mean only use NPM for building the application.  I meant have it as a package hosted by NPM publicly.  So in my package.json I can just have a:
```
"dependencies": {
    "amazon-connect-streams": "1.2.1"
  }
```

**Comment by lacivert** [comment]
I think it is a must now. "building" the project may be an option but not a requirement.

**Comment by jose-bernard-receeve** [comment]
any updates on this?

**Comment by marcogrcr** [comment]
Both [amazon-connect-streams](https://www.npmjs.com/package/amazon-connect-streams) and [amazon-connect-chatjs](https://www.npmjs.com/package/amazon-connect-chatjs) are now available as `npm` packages on [npmjs.com](https://www.npmjs.com/)!

This issue can be closed now.
