### ISSUE TITLE
Chrome: Remove Usage of Notifications from iFrames - Chrome Platform Status

### ISSUE THREAD

**Issue by tom-huguenard** [amazon-connect/amazon-connect-streams#50]
According to https://www.chromestatus.com/feature/6451284559265792, the following code in streams library is suspect. Please advise.
`connect.NotificationManager.prototype.requestPermission = function() {
      var self = this;
      if (!("Notification" in global)) {
         connect.getLog().warn("This browser doesn't support notifications.");
         this.permission = NotificationPermission.DENIED;

      } else if (global.Notification.permission === NotificationPermission.DENIED) {
         connect.getLog().warn("The user has requested to not receive notifications.");
         this.permission = NotificationPermission.DENIED;

      } else if (this.permission !== NotificationPermission.GRANTED) {
         global.Notification.requestPermission(function(permission) {
            self.permission = permission;
            if (permission === NotificationPermission.GRANTED) {
               self._showQueued();

            } else {
               self.queue = [];
            }
         });
      }
   };`

**Comment by ctwomblyamzn** [comment]
I don't believe this causes a bug. We handle the case where we do not get permission gracefully.
