### ISSUE TITLE
“X-Frame-Options“ directive set to “self“ on staging server.

### ISSUE THREAD

**Issue by Patrikmulato** [amazon-connect/amazon-connect-streams#500]
Hello!
We are currently facing an issue that our implementation works on https://localhost:3000/ but when we deploy it to a stage server we receive this error:
`Refused to frame '<URL>' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".`
Our setup:
```
{
    ccpUrl: https://INSTANCE_NAME.awsapps.com/connect/ccp-v2,
    loginPopup: true,
    loginPopupAutoClose: true,
    loginUrl: https://eu-central-1.console.aws.amazon.com/connect/federate/INSTANCE_ID?destination=%2Fconnect%2Fccp-v2,
    softphone: {
      allowFramedSoftphone: true,  // tried with false also
    },
 }

connect.core.initSoftphoneManager({ allowFramedSoftphone: true });
```

- We are not using the prebuilt ccp we built our own one with connect-rtc-js and we hid the prebuilt ccp iframe with CSS. we use REACT.
- We are using SAML authentication and it seems to be working both on local and staging we are successfully logging in to the app when we start to use amazon connect.
- We added both the localhost and staging URL to the allowed origin list on the AWS console page.
**HEADERS on the localhost:**
```
GENERAL:
Request URL: https://INSTANCE_NAME.awsapps.com/connect/ccp-v2
Request Method: GET
Status Code: 200 
Referrer Policy: strict-origin-when-cross-origin     **// different**
RESPONSE HEADERS: 
content-security-policy: img-src 'self' data: https: ; script-src 'self'; style-src 'self' 'unsafe-inline'; object-src 'none'; frame-ancestors 'self' https://OUR_STAGING_SERVER https://localhost:3000 **// different**
pragma: no-cache
referrer-policy: strict-origin-when-cross-origin
server: CloudFront
x-cache: Miss from cloudfront
x-content-type-options: nosniff
REQUEST HEADERS: 
:authority: AWS_URL
:method: GET
:path: /connect/ccp-v2
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
referer: https://localhost:3000/    **// missing on staging**
```
**HEADERS on the staging:**
```
GENERAL:
Request URL: https://INSTANCE_NAME.awsapps.com/connect/ccp-v2
Request Method: GET
Status Code: 200 
Referrer Policy: same-origin
RESPONSE HEADERS: 
cache-control: no-cache, no-store, must-revalidate
content-encoding: gzip
content-security-policy: img-src 'self' data: https: ; script-src 'self'; style-src 'self' 'unsafe-inline'; object-src 'none'; frame-ancestors 'self'
content-type: text/html; charset=UTF-8
referrer-policy: strict-origin-when-cross-origin
server: CloudFront
x-cache: Miss from cloudfront
REQUEST HEADERS: 
:authority: AWS_URL
:method: GET
:path: /connect/ccp-v2
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
sec-fetch-dest: iframe
```

Thanks for the answers!

**Comment by SamSchiff** [comment]
You'll want to set whatever url is iframing CCP as an approved origin for your connect instance. You'll find the approved origins tab in the Connect console page for you instance

**Comment by SamSchiff** [comment]
You also should make sure you're using the correct Connect url. You have https://INSTANCE_NAME.awsapps.com/connect/ccp-v2. But your instance may be on the new domain which would make it: https://INSTANCE_NAME.my.connect.aws/ccp-v2

**Comment by Patrikmulato** [comment]
@SamSchiff Thanks for your answer we double-checked and we still have the old URL
![Screenshot 2021-11-29 at 11 21 08](https://user-images.githubusercontent.com/34235392/143850609-58d8ecb3-35f0-47af-a9a6-23ac4a367332.png)
and we also added all the URLs to the approved origins.
For the interesting fact we can also see those URLs in the localhost response headers:
![Screenshot 2021-11-29 at 11 25 46](https://user-images.githubusercontent.com/34235392/143851588-01c5b779-4b86-4564-b30c-5ba46b6094b8.png)
I was thinking that it might have a problem with the URL because we have multiple domains in it
https://sitename-sit.nonprod.sg.sg.sg.com/
What do you think about that?

**Comment by SamSchiff** [comment]
It could be. You'll want to allowlist all of the possible domains in approved origins then

**Comment by jbflow** [comment]
Don't suppose you ever solved this? Having same issue with django. I think it's because the URL is missing from referer so connect can't verify that it's coming from one of the approved frame-ancestors, but unsure how to fix.

**Comment by jbflow** [comment]
OK yes I can confirm the Referrer-Policy needs to be set to "strict-origin-when-cross-origin".

For me with nginx I had to set `add_header Referrer-Policy "strict-origin-when-cross-origin"` in the config file to get it to work.

**Comment by Patrikmulato** [comment]
@jbflow Thank you it was our issue also that we didn't set Referrer-Policy correctly. 
Anyone checking this ticket to resolve this issue check if the Referrer-Policy is "strict-origin-when-cross-origin"
