### ISSUE TITLE
initCCP not working after terminate

### ISSUE THREAD

**Issue by sseidel16** [amazon-connect/amazon-connect-streams#501]
Our custom CCP has an option for agents to update their ringtone. It seems that ringtone can only be provided on init, so I think I would need to call terminate and then init again when they switch their ringtone preference. The problem is that calling terminate seems to break init from ever being called again. After the second init, no new chats or new messages are received.

Am I probably doing something wrong? Is init expected work again after terminate? Can init / terminate be fixed so that one can work after the other any number of times?

Note: I am removing the iframe after terminate is called. The second init successfully creates this iframe again, but the above issues with new chats and messages persist.

Using stream 1.7.4

**Comment by jeonglee** [comment]
Hi. `initCCP` should work even after terminate. Testing this with 1.7.4 I am able to initCCP and receive chats after terminate and removing the original iframe.
