### ISSUE TITLE
Where to find the instance URL for a newly created instance?

### ISSUE THREAD

**Issue by kbokarius** [amazon-connect/amazon-connect-streams#502]
Our Overview page in the AWS Connect console shows a Login URL but no Instance URL.

The Login URL is in the form of: https://<instance>.my.connect.aws - when we try to use this we see the X-Frame-Options error when loading on https://localhost:3000 (with that URL added as an Approved Origin).

When we try to load https://<instance>.awsapps.com/connect/ccp-v2# we see the "This application has not been enabled for your directory" error.

Exactly which URL should we be using when the `connect.core.initCCP` method? And is there anything else obvious that we're doing wrong?

**Comment by kbokarius** [comment]
Anyone? Seems like a straightforward and easy question to answer.

**Comment by martin-greenberg** [comment]
As of March 2021, newly created instances do not support the awsapps domain; you must use the my.connect.aws domain with instances created after this date.

https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-release-notes.html#march21-release-notes
