### ISSUE TITLE
setLogLevel and setEchoLevel have no effect

### ISSUE THREAD

**Issue by andrei-at-work** [amazon-connect/amazon-connect-streams#503]
INFO level messages are still written to the console even after calling connect.getLog().setLogLevel(connect.LogLevel.ERROR) and connect.getLog().setEchoLevel(connect.LogLevel.ERROR).

![image](https://user-images.githubusercontent.com/74427636/142644781-f8af5556-5eaa-46de-9f7c-cf2f94c5ddfb.png)

**Comment by jeonglee** [comment]
The logs in the screenshot above are from the embedded CCP, which has a separate logging context than that of the outer streams code embedding the CCP. Currently there is no way to communicate to the embedded CCP to disable X level logs.

**Comment by shahpay** [comment]
@andrei-at-work Have you found a way to disable logs?

**Comment by alexgurr** [comment]
4 years later and we still can't turn down the 100's of log message in the console. It certainly doesn't make development easy.
