### ISSUE TITLE
Autofill Number Pad

### ISSUE THREAD

**Issue by gigamike** [amazon-connect/amazon-connect-streams#504]
Hi,

Is it possible to pass a parameter (via JS or URL) that will autofill Number Pad?

Thank you

**Comment by SamSchiff** [comment]
At the moment, there is not. Using Javascript you should be able to populate the number pad programmatically yourself, but there isn't a function that we vend to do it for you

**Comment by gigamike** [comment]
thank you @SamSchiff

**Comment by gigamike** [comment]
Hi @SamSchiff ,

Related to this issue/feature, we saw this post https://forums.aws.amazon.com/thread.jspa?threadID=324220. Its related to https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#contactaddconnection. I tried contact.addConnection but its not working, any ideas? seems related as well to https://github.com/amazon-connect/amazon-connect-streams/issues/353

Thanks in advance

**Comment by SamSchiff** [comment]
`contact.addConnection` will add a new participant to an already ongoing call. It requires an open contact so it can't just dial a new number from a non-contact state. But, I did come across a function I had missed last time. https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#agentconnect. `agent.connect` should do the trick for you. Let us know if that works

**Comment by fiyadeleon** [comment]
> At the moment, there is not. Using Javascript you should be able to populate the number pad programmatically yourself, but there isn't a function that we vend to do it for you

Hi Sam! I came across this while exploring the option of auto filling the number pad using javascript. Any chance that you have any documentation how this can be done using JS? Appreciate your response thank you
