### ISSUE TITLE
Create outbound call and pass attributes or parameters for Contact Flow to read.

### ISSUE THREAD

**Issue by nept47** [amazon-connect/amazon-connect-streams#505]
Hi,

Is there the option pass attributes or parameters when do an outbound call (agent.connect(..)...), so I can read them on the Contact Flow?

The scenario is the following:
I have a multi-brand environment. On CCP before calling the customer the agent has to select the **country** and **brand**.
Then on the Contact Flow I will set them as Contact Attributes for statistical reasons and I will also set the outgoing caller Id (using Lambda & DynamoDB)

thank you in advance!

**Comment by jonatandmapser** [comment]
any news about this?
Thanks!

**Comment by ajspetner** [comment]
No explanation? It's a commonly requested feature. It would be nice to have some feedback other than just have the issue closed.

**Comment by jonatandmapser** [comment]
does anyone else have the same problem?
