### ISSUE TITLE
Event listener - When a third party (Transfer) disconnects

### ISSUE THREAD

**Issue by Juzziee** [amazon-connect/amazon-connect-streams#506]
Hey all,

Has anyone come across an elegant way to track if the third party of a call has left?
Ideally, we want to put our agent back into a 'call in progress' UI state when this happens.

 Thanks,

J

**Comment by Christian-Sesta** [comment]
@Juzziee This might be what you are after if you only support 3 way connections (customer, agent, third party contact)? I use it in my current project to cleanup some bespoke transfer logic when the third party connection drops off.

https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#contactgetsingleactivethirdpartyconnection
