### ISSUE TITLE
Ability to remove Logout button from CCP

### ISSUE THREAD

**Issue by bbolek** [amazon-connect/amazon-connect-streams#507]
Hello;

We are using CCP with SSO. And our users use logout button on our application to log out from user, and we are logging out from CCP when user logs out. 

But there is a logout button in CCP. When user clicks that it logs out from CCP but user is still logged in our application. 

So is there any way to remove Logout link on CCP?

![image](https://user-images.githubusercontent.com/1146456/144075173-f59e5fd2-b85e-48ed-a837-af3f354f45a3.png)

Thanks

**Comment by SamSchiff** [comment]
At the moment, there's no supported way to do that. But if you want a workaround you could add an event listener to the logout button that will trigger your application logout flow. Or you could programmatically hide that button using javascript

**Comment by bbolek** [comment]
Hey,
Below event works fine.

Thank you
```
const eventBus = connect.core.getEventBus();
            eventBus.subscribe(connect.EventType.TERMINATED, () => {
                utils.logout();
            });
```
