### ISSUE TITLE
Cannot hear the call response through speaker on outbound calls

### ISSUE THREAD

**Issue by pvranjana** [amazon-connect/amazon-connect-streams#508]
This is my code for making the outbound call and setting the speaker. The outbound call goes through successfully. But I am not able to hear any audio for the outbound call through the speaker. 

```
   
agent.connect(endpoint, {
            success: function () {
                console.log("outbound call connected");
            },
            failure: function (err) {
                console.log("outbound call connection failed");
                console.log(err);
            }
        });
```
        
        //Device id is being selected from a menu which is pre-populated with the device id values.  
        function changeOutputDevice() {
            var deviceId = document.getElementById("outputDevicesMenu").value;
            try {
                window.myCPP.agent.setSpeakerDevice(`${deviceId}`);
            } catch (err) {
                console.log(err);
                try {
                    connect.setSpeakerDevice(`${deviceId}`);
                } catch (error) {
                    console.log(error);
                }
            }
    }

**Comment by ctwomblyamzn** [comment]
Hi pvranjana@ everything looks correct here. Can we have some more details as to how this is failing? Are you sure you have interacted with the window before expecting to hear audio? Are there any console errors occurring?
