### ISSUE TITLE
Unable to terminate CCP without maintaining previous context

### ISSUE THREAD

**Issue by omkarv** [amazon-connect/amazon-connect-streams#51]
I am using the amazon-connect-streams JavaScript library to create a web portal for an agent, for a  audio teleconference solution for the application, and am looking for assistance on how to terminate the connect session correctly to support a 'logout' function of my app.  My issue is related to an existing Github issue [1].

I’ve been able to reproduce a bug consistently where I see a `multiple ccp windows open` error message in the console despite only one tab being open. I strongly suspect the issue I'm running into is related to my web application not terminating the CCP client correctly – since an initial load of CCP (using connect.core.initCCP) in the application in an incognito window never surfaces the error described. 

I only see the issue if an Agent logs out and then logs back in the same tab, even if it is an incognito window / tab. When an Agent relogs back into the app, I re-initialize the CCP by using the connect.core.initCCP method and see the `multiple ccp windows open` error message when the Agent has accepted an inbound call. I am currently using the function “connect.core.terminate" in core.js of the amazon-connect-streams js library [2] on logout to terminate CCP. 

Can you please provide some guidance about how to terminate the app correctly? I'd like to be able to detach the iframe and to clear any state in the web worker / local storage stored by the Connect SDK.

[1] https://github.com/aws/amazon-connect-streams/issues/13
[2] https://github.com/aws/amazon-connect-streams/blob/5fc44af68939a2016cc1c6fd...

**Comment by marcogrcr** [comment]
Is this still an issue?

It seems like the `connect.core.terminate()` method has come a long way since this issue was created:

**v1.2.0 (latest version in apr/2018)**

```js
connect.core.terminate = function() {
  connect.core.client = new connect.NullClient();
  connect.core.masterClient = new connect.NullClient();
  connect.core.eventBus = new connect.EventBus();
  connect.core.initialized = false;
};
```

**v1.4.7 (latest version as of today)**

```js
connect.core.terminate = function () {
  connect.core.client = new connect.NullClient();
  connect.core.masterClient = new connect.NullClient();
  var bus = connect.core.getEventBus();
  if (bus) bus.unsubscribeAll();
  connect.core.bus = new connect.EventBus();
  connect.core.agentDataProvider = null;
  connect.core.softphoneManager = null;
  connect.core.upstream = null;
  connect.core.keepaliveManager = null;
  connect.agent.initialized = false;
  connect.core.initialized = false;
};
```

This seems to cover `connect.agent.initialized = false` as well as the subscriptions concerns raised by @phm200.

The only thing that still has to be manually performed is to remove the `<iframe>` element. Currently `amazon-connect-streams` does not keep track of the container passed as an argument to `connect.initCCP()` or the `<iframe>` element itself, so that's probably why it's not removed.

**Comment by sseidel16** [comment]
This still seems to be broken, particularly for chats. If initCCP is called, the terminate, then initCCP is called again, the CCP breaks and does not receive any additional chats or messages.
