### ISSUE TITLE
on change Agent Status

### ISSUE THREAD

**Issue by gigamike** [amazon-connect/amazon-connect-streams#510]
Hi Guys,

I'm integrating amazon connect streams to our CRM. I'm looking for a way that when an agent changes its status i.e. from Available to offline or Available to On Break (Custom agent status) to trigger an ajax to sync the status with our CRM. I'm not sure if I'm doing it right but connect.agent seems now working. I'm using amazon-connect-v1.7.5.js and this is my code below

```
var containerDiv = document.getElementById("container-div-amazon-connect");
var instanceURL = amazonConnectCCPURL + '/ccp#/';
// initialize the streams api
function amazon_connect_init() {
    // initialize the ccp
    connect.core.initCCP(containerDiv, {
        ccpUrl: instanceURL, // REQUIRED
        loginPopup: true, // optional, defaults to `true`
        loginPopupAutoClose: true, // optional, defaults to `false`
        loginOptions: { // optional, if provided opens login in new window
            autoClose: true, // optional, defaults to `false`
            height: 600, // optional, defaults to 578
            width: 400, // optional, defaults to 433
            top: 0, // optional, defaults to 0
            left: 0 // optional, defaults to 0
        },
        region: awsRegion, // REQUIRED for `CHAT`, optional otherwise
        softphone: { // optional, defaults below apply if not provided
            allowFramedSoftphone: true, // optional, defaults to false
            disableRingtone: false, // optional, defaults to false
            ringtoneUrl: "./ringtone.mp3" // optional, defaults to CCP’s default ringtone if a falsy value is set
        },
        pageOptions: { //optional
            enableAudioDeviceSettings: false, //optional, defaults to 'false'
            enablePhoneTypeSettings: true //optional, defaults to 'true' 
        },
        ccpAckTimeout: 5000, //optional, defaults to 3000 (ms)
        ccpSynTimeout: 3000, //optional, defaults to 1000 (ms)
        ccpLoadTimeout: 50000 //optional, defaults to 5000 (ms)
    });

    connect.agent(function(agent) {
        agent.onRefresh(function(agent) {
            alert("onRefresh");
            $.ajax({
                type: "POST",
                url: baseUrl + "connect/ajax-crm-status",
                data: {},
                beforeSend: function() {},
                success: function(data) {}
            });
        });

        agent.onStateChange(function(agentStateChange) {
             alert("onStateChange");
            $.ajax({
                type: "POST",
                url: baseUrl + "connect/ajax-crm-status",
                data: {},
                beforeSend: function() {},
                success: function(data) {}
            });
        });
    });
}
```
Is it possible or I'm using the wrong API?

Thanks in advance

**Comment by gigamike** [comment]
Hi Guys,

I guess I'm wrong here. The "agent.onStateChange" is not for the agent status i.e. Available, Online or custom break but for when an agent profile is updated. Is there any way we can trigger an event when an agent in CCP change its status i.e. from Available to Break.

Thanks in advance

**Comment by bbolek** [comment]
Hello;

We are using _agent event streams_ for this purpose. It is much more complicated but works :)

https://docs.aws.amazon.com/connect/latest/adminguide/agent-event-streams.html

Thanks

**Comment by gigamike** [comment]
Hi @bbolek ,

Thank you so much for the help, ill check it out.

**Comment by gigamike** [comment]
Hi,

Just want to share what I did on this one. I just follow this one https://docs.aws.amazon.com/connect/latest/adminguide/agent-event-streams-enable.html
1. In your Amazon Connect Instance enable data streaming. Amazon Connect >> Instance >> Data streaming
2.  Enable data streaming, select Kinesis Stream for Contact Trace Records. (This requires the creation of Kinesis Stream)
3. Create Lambda. Add trigger Kinesis. make sure the lambda permission is allowing reads to Kinesis. 
4. The following events trigger your lambda (LOGIN, LOGOUT, STATE_CHANGE and HEART_BEAT).
5. In your lambda you can set an endpoint or script to update something.

Hope this helps. Closing ticket
