### ISSUE TITLE
Enable save button in Custom CCP setting: Product imporvement request

### ISSUE THREAD

**Issue by ChiragDXC** [amazon-connect/amazon-connect-streams#511]
Hi Team,

This is not a feature request but a product improvement request.

We have custom CCP setup and we turn on Audio Device setting in custom softphone but there is no save button enabled to save the settings. Save button is grey out.

This seems like an issue with the product as after changing the setting, save button should be there to confirm on the changes are saved. Please see attached screen shot and help fix the issue.
![Custom CCP save button](https://user-images.githubusercontent.com/95731327/145142535-85d347cb-86e5-4ef5-8831-e0aa7cdeb333.jpg)

**Comment by bkapellusch** [comment]
Your audio settings actually are saved when you pick a new selection in the dropdown. The save button is just for the Language dropdown I believe.

Yeah, it's an odd design choice. They should maybe group those settings into sections so it's a little less confusing.
