### ISSUE TITLE
The Notification permission may only be requested in a top-level document or same-origin iframe.

### ISSUE THREAD

**Issue by gigamike** [amazon-connect/amazon-connect-streams#512]
Hi,

I often get this error "The Notification permission may only be requested in a top-level document or same-origin iframe.".

I already added my domain to my amazon connect instance Approved origins.

Any ideas?

Thanks in advance

**Comment by SamSchiff** [comment]
Requesting notifications permission isn't going to be allowed if called inside the iFramed CCP. The approved origins aren't related to this. Are you trying to get this permission yourself or using Connect's notification system?

**Comment by francoisauclair911** [comment]
@SamSchiff can't we add the notification permission to the allow attributes of the iframe?
I'm having similar issues where I need to allow the microphone. Is there a way to modify the allow attributes of the generated iframe ?
