### ISSUE TITLE
Refreshing page with embedded CCP fails to re-establish contact voice channel

### ISSUE THREAD

**Issue by andrei-at-work** [amazon-connect/amazon-connect-streams#513]
If you are connected to a contact on the voice channel and you initiate a page refresh, the CCP appears to reconnect (see log below) but the voice channel is broken. How can we re-establish the voice channel connection after a page refresh?

Console log from embedded CCP after page refresh:
![image](https://user-images.githubusercontent.com/74427636/146068462-d735a65a-2994-4786-bbee-804bde0e5450.png)

**Comment by vpogudina** [comment]
Hi @andrei-at-work unfortunately at this point that is expected behavior, however there is a workaround described here: 
https://github.com/amazon-connect/amazon-connect-streams/issues/33 by **chrisckchang**
