### ISSUE TITLE
Errors in Connect task while try to reject , complete and transfer.

### ISSUE THREAD

**Issue by kirubha-mahesh** [amazon-connect/amazon-connect-streams#515]
Hello,
I am trying to implement tasks in our application and running into an issue when trying to reject,decline,
close the contact and transfer the task.

contact.reject({
success: function() { /* ... */ },
failure: function(err) { /* ... */ }
});

likewise we tried with complete,clear and onended,

ERROR TypeError: Cannot read properties of undefined (reading 'create')
at createMediaInstance (connect-streams.js:28400)

How can I resolve this issue ?

Thank You

**Comment by vpogudina** [comment]
Hi kirubha-mahesh,
I was able to successfully reject and clear contact (complete is deprecated, so please avoid using it)

Can you please provide more context on how exactly you were using it? 
I've tested it by calling:
let agent = new connect.Agent();
let contact = let contact = agent.getContacts()[0]
contact.reject({
success: function() { /* */ },
failure: function(err) {  /* */  }
});

**Comment by kirubha-mahesh** [comment]
@vpogudina 
Calling is working fine i can able to accept,reject and transfer the call
but for connect tasks not working, i can able to accept the task but can't able to reject the task  by using this functions
contact.reject({
success: function() { /* */ },
failure: function(err) {  /* */  }
});
and also tried with destroy function not working
Reference:
[1]https://github.com/amazon-connect/amazon-connect-streams

**Comment by vpogudina** [comment]
Hi @kirubha-mahesh I'm sorry for the confusion. I was testing the functionality of the connect tasks by "using" (calling) the code snippet I've provided 
```
let agent = new connect.Agent();
let contact = let contact = agent.getContacts()[0]
contact.reject({
success: function() { /* */ },
failure: function(err) {  /* */  }
});
```
Can you please provide more context on how exactly you were using it? Maybe a code snippet?

**Comment by vpogudina** [comment]
Also I believe the destroy function has been deprecated, so it is expected it will not work. https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#contactdestroy
you should be using contact.clear instead

**Comment by kirubha-mahesh** [comment]
@vpogudina 
I tried the function you provided to reject the task 
let agent = new connect.Agent();
let contact = let contact = agent.getContacts()[0]
contact.reject({
success: function() { /* */ },
failure: function(err) {  /* */  }
});
but i got these error
[ERROR]: 'rejectContact' API request failed: Error
ERROR @ lily_ccp_Prod_98a0d7aaffc75e98bc1c7192a12f097c5db25888.js:32748
connect-streams.js:21313 [2022-01-11T05:49:57.550Z] [ERROR] [6c31cd45-1169-4c0b-a6b7-3fd6cddad48c]: 'rejectContact' API request failed: Error

this is my actual snippet getting same error
    window.myCPP.contact.reject({
      success: function () {
        _this.unSubscribeTimerEvents()
        _this.dialingFlag = false
        console.log("Success")
      },
      failure: function () {
      }   })
      
   May I know in what version you were tested ? and also please share clearcontact method.
