### ISSUE TITLE
*on methods should return a subscription object

### ISSUE THREAD

**Issue by anantoghosh** [amazon-connect/amazon-connect-streams#518]
The document specifically mentions this.
https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#event-subscription
> on*() event subscription methods are provided with callbacks which are called when events occur on those specific objects. These return subscription objects, which for contacts are automatically cleaned up when those contacts no longer exist. Users can also manually unsubscribe from events by calling sub.unsubscribe() on the subscriptions returned by these methods.

But most of the **agent** and **contact** *on methods do not return anything
https://github.com/amazon-connect/amazon-connect-streams/blob/d136b26ab04630aa544392ffa326e21bafcee72f/src/api.js#L332-L335
https://github.com/amazon-connect/amazon-connect-streams/blob/d136b26ab04630aa544392ffa326e21bafcee72f/src/api.js#L682-L685

A few methods do https://github.com/amazon-connect/amazon-connect-streams/blob/d136b26ab04630aa544392ffa326e21bafcee72f/src/api.js#L2142-L2145
https://github.com/amazon-connect/amazon-connect-streams/blob/d136b26ab04630aa544392ffa326e21bafcee72f/src/api.js#L2147-L2154

The only way to get to the unsubscribe method without the subscription object is to utilise the event bus directly, but it would be far more straightforward to just use the `on` methods.

Thank you for your work.

**Comment by SamSchiff** [comment]
This is a good callout. We'll put a ticket to fix this in our backlog
