### ISSUE TITLE
Dead Air before FailedConnectCustomer error

### ISSUE THREAD

**Issue by Christian-Sesta** [amazon-connect/amazon-connect-streams#519]
Hey,

I have run into a few scenarios and issues where for a disconnected number or a call resulting in "Your call could not be connected" that the agent is presented with dead air and then the call drops out with the `FailedConnectCustomer` agent state error. This has lead to some confusion for our agents around how they should finalise the calls CRM record before calling their next number. Is this a bug in the system as I could have sworn these errors used to come through as audio for the call i.e. "Your call could not be connected", "The number you have called is not connected"?

I was also just wondering if there was any existing information within streams to give us more information on what led a call to fall under the `connect.AgentErrorStates.FailedConnectCustomer` state.

**Comment by jhleung** [comment]
@Christian-Sesta were you ever able to figure this issue out? i'm seeing the same thing
