### ISSUE TITLE
Is there any status to judge whether ccp is logged in in our system?

### ISSUE THREAD

**Issue by JXZ201606** [amazon-connect/amazon-connect-streams#523]
Is there any status to judge whether ccp is logged in in our system?

**Comment by andywang219** [comment]
Hi @JXZ201606, if I am understanding the question correctly, you're asking if there is a way to judge if an user has successfully logged in. If so, you can use `connect.core.onAuthorizeSuccess()` (https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#connectcoreonauthorizesuccess). This allows you to subscribe to when an agent is logged in
