### ISSUE TITLE
CCP Container style always 100% 

### ISSUE THREAD

**Issue by ccaldron** [amazon-connect/amazon-connect-streams#530]
Can't seem to figure out why it won't take the specified width for the CCP, but will take it for customer profiles and wisdom. Code:

`<!DOCTYPE html>
<meta charset="UTF-8">
<html>
  <head>
    <script type="text/javascript" src="connect-streams-min.js"></script>
  </head>
  
  <body onload="init()">

    <main>
    <h1> Totally Terrible Agent Panel </h1>
    <h2> Someday it will look better </h1>
      <div id="ccp-container"></div>
      <div id="customerprofiles-container"></div>
      <div id="wisdom-container"></div>
    </main>
    <script type="text/javascript">
      function init() {
        const connectUrl = "https://instance.my.connect.aws";
        connect.agentApp.initApp(
            "ccp", 
            "ccp-container", 
            connectUrl + "/ccp-v2/",
            { style: "width:600px !important; height:800px;" }
        );
        connect.agentApp.initApp(
            "customerprofiles", 
            "customerprofiles-container", 
            connectUrl + "/customerprofiles-v2/",
            { style: "width:1200px; height:1200px;" }
        );
        connect.agentApp.initApp(
            "wisdom", 
            "wisdom-container", 
            connectUrl + "/wisdom-v2/",
            { style: "width:1200px; height:1200px;" }
        );
}
    </script>
  </body>
</html>`

**Comment by jeonglee** [comment]
Hello, I can confirm this is a bug - I've cut a ticket to address this. In the meantime please style the CCP Container directly like so 
```
<div id="ccp-container" style="width: 600px; height: 800px;"></div>
```

**Comment by oharez** [comment]
any updates on this? I feel like I've had this issue as well, though could be my Iframe. Only on init, after being hidden and then shown again, it fits the frame as designed.
