### ISSUE TITLE
Failed to fetch routing profile queues list

### ISSUE THREAD

**Issue by DanielHuelse** [amazon-connect/amazon-connect-streams#532]
Hello, we have a use-case where an agent can switch their routing profile between calls. We utilised the AWS SDK `UpdateUserRoutingProfile` method to update the agents routing profile. In the Amazon Connect Console the change takes place imminently, but the softphone sometimes didn't recognized that the agents routing profile has changed. 

We see the following Error: `Failed to fetch routing profile queues list` in the Dev Console. 
Then the agents needs to reload the whole custom ccp to get working again.

Do you have any suggestions how this can be fixed?

**Amazon Connect Streams Version:** 1.7.0

**Comment by AlexD1979** [comment]
Hello, The current error stack trace you can find here:
![grafik](https://user-images.githubusercontent.com/25854347/152491589-42fca805-52dd-4e32-a036-1279a4bc0fea.png)

**Comment by libinjohn05** [comment]
Hi, Please could you confirm if there was any solution for this issue?

**Comment by DanielHuelse** [comment]
We solved this internally by adding a check, to prevent too many routing profiles changes in a short amount of time.
