### ISSUE TITLE
Wisdom doesn't load corrrectly in FRA region with the new connect URL pattern

### ISSUE THREAD

**Issue by juaestiv** [amazon-connect/amazon-connect-streams#535]
I am facing an issue in eu-central-1 region with wisdom-v2. 

For CCP I am using the **new URL format** of connect   connectUrl = "https://instance.my.connect.aws/ccp-v2"; (otherwise it will give an error like -The URL for your instance has changed. Please contact your administrator.-).

But if I use the same format for wisdom https://instance.my.connect.aws/wisdom-v2 I receive "**Please authenticate through CCP in order to use Wisdom!**". This URL works well directly in the browser but not embedded in my code. 
The only way that I have found is to use the **old style for wisdom url** https://instance.awsapps.com/connect/wisdom-v2. 

Any suggestion?
Thanks in advance!

**Comment by juaestiv** [comment]
It is already solved. Apologize, I forgot to comment. One week after posting the issue was working.

**Comment by kvs6rj** [comment]
No problem - thank you for confirming.
