### ISSUE TITLE
Microphone not shared detection

### ISSUE THREAD

**Issue by Juzziee** [amazon-connect/amazon-connect-streams#536]
Hey all,

Lately, we have been having increased support requests advising that agents aren't able to accept phone calls.
After digging into their agent logs, it appears we are getting a lot of microphone_not_shared softphone errors.

These are ranging from an hour since the previous call to straight after the previous call.
Due to the above, I suspect there might be some browser resource-saving processes going on. 
Micro access returns to normal when the page is reloaded.

Is there a way to detect when microphone access is lost and then automatically reinitialize it without having to refresh the page for the agent? 

Look forward to seeing what solutions others have come up with.

Thanks

**Comment by CiscoKidxx** [comment]
We are also seeing this. Do you use connect-rtc as well ?

**Comment by Juzziee** [comment]
No we're not. We are using the AC web app. 
At the moment, it appears to be relating to the browser trying to save system resources and killing off the rtc access. 
We've noticed our busier queues don't appear to have these issues and it is only the areas that may only take a dozen or so calls a day.

**Comment by Christian-Sesta** [comment]
I am seeing this issue too in one of my companies instances. Not sure if it is related, but the browser ends up in a crashing state while this is going on.
