### ISSUE TITLE
Keep hitting the rate limit for concurrent chats

### ISSUE THREAD

**Issue by jbflow** [amazon-connect/amazon-connect-streams#538]
We have a situation where we are hitting the rate limit very quickly during teating. We are using the CCP and the chat widget for customer side. I have tried clearing the contact using onMissed and other callbacks but still the connection remains open. This is also causing the customer chat widget to error after a few tries, causing a page refresh. Is there any way to resolve this?

**Comment by ranfisfrancisco** [comment]
You can request an increase in Concurrent Chats from the Amazon Service Quota page 

https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-service-limits.html#connect-quotas
