### ISSUE TITLE
Errors in Connect task while try to reject call.

### ISSUE THREAD

**Issue by Akhtar1997** [amazon-connect/amazon-connect-streams#539]
We are trying to create a function to reject a incoming call using amazon connect streams v2.0 but it is giving error.

[ERROR]: 'rejectContact' API request failed: Error

we are using this code...

```
function rejectCall()
{  
  let agent = new connect.Agent();
  let contact = agent.getContacts()[0]
  contact.reject({
    success: function() {console.log("success") },
    failure: function(err) {  console.log("Error") }
  });
}
```

**Comment by ctwomblyamzn** [comment]
Hello, when are you trying to reject the contact? If the contact has already been connected, the rejected operation will fail with a 4xx error.

**Comment by Akhtar1997** [comment]
We are trying to create a function to reject a incoming call using amazon connect streams v1.0 they work properly.
we are using destroy() method like below.

```
function rejectCall()
{
  var initialConnection = agentContact.getInitialConnection();
  var thirdParty = agentContact.getSingleActiveThirdPartyConnection();
  if (initialConnection) {
    initialConnection.destroy();
  }
  if (thirdParty) {
    thirdParty.destroy();
  }  
}
```
