### ISSUE TITLE
Unable to find sourcemap

### ISSUE THREAD

**Issue by ajitid** [amazon-connect/amazon-connect-streams#541]
I could see the following issue being logged when I install this library in create-react-app [version 5](https://github.com/facebook/create-react-app/releases/tag/v5.0.0):

```
WARNING in ./node_modules/amazon-connect-streams/release/connect-streams.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/zlksnk/mytmp/my-app/node_modules/amazon-connect-streams/release/amazon-connect-websocket-manager.js.map' file: Error: ENOENT: no such file or directory, open '/home/zlksnk/mytmp/my-app/node_modules/amazon-connect-streams/release/amazon-connect-websocket-manager.js.map'
 @ ./src/App.tsx 7:0-32
 @ ./src/index.tsx 7:0-24 11:33-36
```

## To reproduce
1. Clone [this repo](https://github.com/ajitid/issue-connect-streams-sourcemap) 
2. Run `yarn` to install dependencies (uses yarn 1, but you could use any package manager you want)
3. Run `yarn start`

While the repo uses latest v2 of connect streams, I originally reproduced it with v1.6.11.

## Expected behavior

Sourcemap must be present

## Actual behavior

We see the issue mentioned at the top of the ticket

**Comment by osky9913** [comment]
Are there any solutions temporary? @ctwomblyamzn  Thanks for replying
