### ISSUE TITLE
Errors in Connect task while try to set agent status

### ISSUE THREAD

**Issue by Akhtar1997** [amazon-connect/amazon-connect-streams#545]
We are trying to create a function to set agent status using amazon connect streams api v2.0 but it is giving error. I want to set a agent status(Online, Offline ) using this function.

In other case when we are try this code in previous version like v1.0 then this code work properly. But i want to use this in latest version like V2.0 .

[ERROR]: 'setContact' API request failed: Error

we are using below code:
```
`function goAvailable()
{
  var state = agent2.getAgentStates()[0];
  console.log("state",state)
  agent2.setState(state, {
    success: function() { console.log("success") },
    failure: function(err) { console.log("Error",err) },
   },  
   );
}` 
```

**Comment by seiyako** [comment]
Hi, I'd need error details to say anything about the possible causes, but one issue in this code is that the function is written with an assumption that the response from the `agent.getAgentStates()` API always has the "available" state at index 0, which is not true. 

Please refer to the cheat sheet to filter the states
https://github.com/amazon-connect/amazon-connect-streams/blob/master/cheat-sheet.md
