### ISSUE TITLE
Cannot make a call when another call on hold

### ISSUE THREAD

**Issue by bbolek** [amazon-connect/amazon-connect-streams#557]
Hello,

Here is the scenario:

- Agent starts a voice call.
- Agents gets voice call on hold.
- Agent clicks Number pad
- Agent enters number
- There is no dial button here.

But this scenario works:
- Agent starts a voice call.
- Agents gets voice call on hold.
- Agent clicks Quick Connects
- Agent clicks Number pad
- Agent enters number
- Agent can dial.

![image](https://user-images.githubusercontent.com/1146456/161909707-bc6b396d-d192-4659-bebc-8b9aad640fb9.png)

Is there any reason why there is no dial button on Numberpad?

Thank you

**Comment by bbolek** [comment]
Hey
Any news? Anyone checking these?

Thank you

**Comment by martin-greenberg** [comment]
The dial pad you're bringing up during the call without selecting Quick Connects first is for entering DTMF tones during the call, not for dialing a new number. You need to click Quick Connects and hit the dial pad, as you described, in order to add a new call.
