### ISSUE TITLE
Failed /fac requests 

### ISSUE THREAD

**Issue by alexgurr** [amazon-connect/amazon-connect-streams#558]
Hi,

We've been observing this for a while from connect streams lib. These requests are **not** triggered by our application but somewhere internally in the library.

We see a collection (7) failed POST requests to `https://ourinstance.awsapps.com/connect/ccp-v2/fac`/. This seems to only happen around the time the CCP is initialised/authed. https://puu.sh/ITfJ9/ec3ab2f7f7.png

Any ideas? There doesn't seem to be any observed impact.

This is the error response:
```
{"status":400,"message":"Invalid input!"}
```

Payload (string values obfuscated):

```
accountId: "ID"
featureName: "ID"
instanceId: "ID"
```

**Comment by CiscoKidxx** [comment]
Experiencing same behavior

**Comment by martin-greenberg** [comment]
This behavior is expected and can be ignored.

**Comment by bml1g12** [comment]
@martin-greenberg  I have to agree, errors are by definition not expected...if it's expected, then it should not be an info or warning level log
