### ISSUE TITLE
Handling Missed Calls

### ISSUE THREAD

**Issue by gigamike** [amazon-connect/amazon-connect-streams#559]
Hi guys,

I hope you can help me. I'm using the click to call feature of Amazon Connect i.e. StartOutboundVoiceContact(). Now sometimes it will start to call/ring but there is a delay to the customer, hence chances the customer will not answer. Then after 8 to 10 rings in the customer (after the missed call), it will start to ring in the Agent CCP/Amazon Connect Stream.  Is there a way we can catch this so that it won't ring in CCP/Amazon Connect Stream for missed calls? It's a little annoying for an Agent to answer a call that is already dropped. The worst case, in the CTR, its an AGENT_DISCONNECT rather than CUSTOMER_DISCONNECT
How do you handle this?

Thanks in advance,

Mik

**Comment by oharez** [comment]
Following this... I feel there should be an added function to look for elongated handoffs and not generate missed calls so soon.
