### ISSUE TITLE
amazon-connect-streams is not compatible with javascript strict mode

### ISSUE THREAD

**Issue by wanlimaa** [amazon-connect/amazon-connect-streams#565]
TypeError: Cannot set property 2011-06-15 of #<Object> which has only a getter

We received this error when importing stream library into stencilJS component for building custom CCP. This issue is because the Library is not compatible with JavaScript's STRICT MODE. StencilJS  requires strict mode when importing external library: https://stenciljs.com/docs/module-bundling#strict-mode

The root cause in the source code is in aws-client.js.

In aws-client.js, on line 2869, '2011-06-15' is defined as a property of apiLoader.services['sts'] with a getter but no setter. On line 21104, there is an attempt to set the property. As it stands now, defining the property on line 2869 is pointless as it's value is guaranteed to be overwritten,  commenting out the latter can resolve this issue. Please provide fix for this issue.

**Comment by martin-greenberg** [comment]
Streams 2.3.0 has just been released which should fix this issue.
