### ISSUE TITLE
Fetching the Total Time of a single user for a particular status

### ISSUE THREAD

**Issue by chavannikhil802** [amazon-connect/amazon-connect-streams#571]
I am new to Amazon Connect and I want to fetch the total time for which a single user was in a particular state.

Eg:

1 - After logging in, for how much time the user was in "Available" state?

2 - After logging in, for how much time the user was in "Offline" state?

3 - Suppose there is a state named as "Tea Beak", then for how much time the user as in "Tea Break" state?

Are there any API Calls to fetch these times for a single user?

Please help.

**Comment by YusukeSasaki0620** [comment]
https://docs.aws.amazon.com/connect/latest/adminguide/historical-metrics-definitions.html
