### ISSUE TITLE
Conference Failure 

### ISSUE THREAD

**Issue by Solomon-m** [amazon-connect/amazon-connect-streams#572]
Hello Guys, 
I am trying to conference together with the active connections of the conversation by following lines. But I am getting `InvalidStateException` sometimes. Please need help on this.  Thank you

Sample Code : 
```
  contact.conferenceConnections({
            success: () => {
                console.log('conference success');
            },
            failure: (e) => {
                console.log('conference failure', e);
            }
    })
```
Exception : 
```
 conference failure  : {"type":"InvalidStateException","message":"Cannot conference connections: Invalid contact state.",
	"stack":["InvalidStateException: Cannot conference connections: Invalid contact state."]}'
```
![conference failure_ InvalidStateException](https://user-images.githubusercontent.com/8034514/172183610-8688d0a8-ec7d-496b-9c29-37f5a6c40cbf.png)

**Comment by Solomon-m** [comment]
Hi @ctwomblyamzn 
Good Day. Any suggestion on this issue would be helpful for us.

Thank you

**Comment by erikohlin12** [comment]
I am also getting this error. Any luck/solution found?

**Comment by Solomon-m** [comment]
Hello, 
Good Day. Any update on this issue?

**Comment by erikohlin12** [comment]
Hey @Solomon-m did you ever find a resolution to this? The issue is still occurring for me.
