### ISSUE TITLE
Custom init `CCP` in iframe but blocked by `aws login`

### ISSUE THREAD

**Issue by genffy** [amazon-connect/amazon-connect-streams#576]
## normal use case
In general use `connect` like [connectcoreinitccp](https://github.com/amazon-connect/amazon-connect-streams#connectcoreinitccp)
- get instanceURL from `ccp console`
- popup iframe input username/pwd for auth
- auto close iframe back to softphone page 
- do biz things      

In this normal case, that works, and `Approved domains` config list worked. [DOC](https://docs.aws.amazon.com/connect/latest/adminguide/upgrade-ccp-streams-api.html)    

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/1506972/175931356-16424b06-5c2e-4c32-8cb0-d3735f7170e8.png">

if set `connect.core.initCCP` params `loginPopup` to `false`, the iframe will get error with `Refused to display '<URL>' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`      

<img width="760" alt="image" src="https://user-images.githubusercontent.com/1506972/175930030-ac756473-f28b-4a3d-a359-6f8fe4c81af3.png">
<img width="687" alt="image" src="https://user-images.githubusercontent.com/1506972/175929791-97cdc37d-744a-4071-a6a5-96465c81b73d.png">     

The `Approved domains` config list not worked.      

<img width="798" alt="image" src="https://user-images.githubusercontent.com/1506972/175930383-1e22df7b-a08a-463e-8fa3-d1622e25b49f.png">
<img width="829" alt="image" src="https://user-images.githubusercontent.com/1506972/175930469-ef3d6f1e-61a1-4897-8cb3-4954cedcc053.png">    
so, i want to know where can i config the login redirect `content-security-policy`.     

## custom use case
<del>Another use case is that user visit a page with a iframe which with one url, that server side will deal auto login and get dynamic instanceURL redirect to client.</del>

<del>our sever side was implemented auto login and instanceURL with reference to [Mujina](https://github.com/OpenConext/Mujina).
but iframe also get error.</del>

<del>but the more detail can provide after reproduce this error</del>

the related issues and comments: 
https://github.com/amazon-connect/amazon-connect-streams/issues/398#issuecomment-845350755

**Comment by genffy** [comment]
[help wanted] tag

**Comment by cythiaY** [comment]
Same problem.

Will you support login page to be embedded in the iframe?

**Comment by martin-greenberg** [comment]
Login page cannot be embedded in the iframe due to same origin restrictions. You need a valid Connect auth cookie for the Connect instance domain in order to see your allowlisted domains in the CSP header. If you don't have a valid Connect auth cookie for your instance, there will be no cases under which the CSP header returned will allow CCP to be embedded; having a valid cookie is a prerequisite.

**Comment by sennz** [comment]
> Login page cannot be embedded in the iframe due to same origin restrictions. You need a valid Connect auth cookie for the Connect instance domain in order to see your allowlisted domains in the CSP header. If you don't have a valid Connect auth cookie for your instance, there will be no cases under which the CSP header returned will allow CCP to be embedded; having a valid cookie is a prerequisite.

How can we get a Connect auth cookie?

**Comment by martin-greenberg** [comment]
You would get a Connect auth cookie by authenticating to Connect, either via the Connect login page if you have Connect-managed authentication or via your SSO/SAML flow for an instance using SAML authentication.

**Comment by sennz** [comment]
> You would get a Connect auth cookie by authenticating to Connect, either via the Connect login page if you have Connect-managed authentication or via your SSO/SAML flow for an instance using SAML authentication.

Thank you, is there a document i can refer how to implement?

**Comment by martin-greenberg** [comment]
To implement what specifically, authentication to Connect via SAML/SSO? You can refer to [this AWS blog post](https://aws.amazon.com/blogs/contact-center/enabling-federation-with-aws-single-sign-on-and-amazon-connect/), or [this page](https://docs.aws.amazon.com/connect/latest/adminguide/configure-saml.html) in the AWS documentation.

**Comment by sennz** [comment]
> To implement what specifically, authentication to Connect via SAML/SSO? You can refer to [this AWS blog post](https://aws.amazon.com/blogs/contact-center/enabling-federation-with-aws-single-sign-on-and-amazon-connect/), or [this page](https://docs.aws.amazon.com/connect/latest/adminguide/configure-saml.html) in the AWS documentation.

thank you
