### ISSUE TITLE
How to add Custom button in CCP.

### ISSUE THREAD

**Issue by System-Integrator** [amazon-connect/amazon-connect-streams#581]
Hi Team,

Kindly let me know the possibilities of adding custom button near to Task and End Chat button in Chat windows.

Best Regards,

Sujan

**Comment by bbolek** [comment]
Hello,
With default CCP you cannot do this. But we added an extra layer next to ccp. We can add whatever we want.

You can see an example below.
![image](https://user-images.githubusercontent.com/1146456/185569450-e65be550-25fd-4f4c-95c4-7f19fc2f46e0.png)

Thanks
