### ISSUE TITLE
contact.onIncoming() not triggering

### ISSUE THREAD

**Issue by Juzziee** [amazon-connect/amazon-connect-streams#582]
Hi all,
We have recently started having issues with the contact.onIncoming() not triggering on a customer callback.
When a callback contact is delivered to the agent, the onIncoming function is not triggered. 

When I query the contact type, I get 'queue_callback'. Has something changed with the onIncoming function on Amazon's end?
We are still using version 1.7.5 for the streams sdk.

**Comment by Christian-Sesta** [comment]
I have noticed a few times with older versions of streams breaking when they chance contracts on their backend. Might be worth updating to the latest version if possible

**Comment by seiyako** [comment]
Hi, thanks for sharing the issue.
We're not aware of any model changes made to queue_callback contacts and Streams should trigger contact.onIncoming() when there's a contact whose type has turned to incoming state. ([ref](https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/core.js#L1809-L1811))

These steps might be helpful for the troubleshooting:
- Check if there are any errors thrown in your console from your event handler for contact.onIncoming event
- Try registering a simple callback that logs a console message to the onIncoming event and see if it's triggered 
- Try upgrading the Streams version to the latest to see if it resolves the issue

**Comment by JhonFuenzalida** [comment]
@Juzziee  you should use onRefresh function and inside take out contact.isInbound() and contact.getStatus.type === connect.ContactStateType.CONNECTING, with that you get the incoming calls
