### ISSUE TITLE
contact.onConnected() not triggering

### ISSUE THREAD

**Issue by rizwan5922** [amazon-connect/amazon-connect-streams#584]
Hi all,
We are facing the issue, that sometimes contact.onConnected() is not triggered on voice contact.
We have through logs and identified that contact.onAccepted() callback is properly received but contact.onConnected() is not received. Sometimes it throws an error signalling_handshake_failure and sometimes no error is received.

We are using version 2.2.0 for the streams SDK.
Following are the logs

`[2022-08-05T15:09:50.992Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]: [ContactService.acceptContact()] Accepted contact via Streams
​ [2022-08-05T15:09:48.709Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  [Softphone Manager] softphone manager initialization has begun
​ [2022-08-05T15:09:48.719Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  Contact exist in the snapshot. Reinitiate the Contact and RTC session creation for contactIdf150db0a-ad5c-4f2f-b809-c5eb9643555e agent connectionId 88ddeeb5-bf98-4eba-8705-c07cb5515cc0
​ [2022-08-05T15:09:48.720Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  Contact detected: contactId f150db0a-ad5c-4f2f-b809-c5eb9643555e agent connectionId 88ddeeb5-bf98-4eba-8705-c07cb5515cc0
​ [2022-08-05T15:09:48.727Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  Softphone call detected: contactId f150db0a-ad5c-4f2f-b809-c5eb9643555e agent connectionId 88ddeeb5-bf98-4eba-8705-c07cb5515cc0
​ [2022-08-05T15:09:48.754Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SESSION null => GrabLocalMediaState
​ [2022-08-05T15:09:49.086Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SESSION GrabLocalMediaState => CreateOfferState
​ [2022-08-05T15:09:49.095Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SESSION CreateOfferState => SetLocalSessionDescriptionState
​ [2022-08-05T15:09:49.097Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SESSION LocalSD [object RTCSessionDescription]
​ [2022-08-05T15:09:49.100Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SESSION SetLocalSessionDescriptionState => ConnectSignalingAndIceCollectionState
​ [2022-08-05T15:09:49.102Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SIGNALING null => PendingConnectState
​ [2022-08-05T15:09:49.103Z] [LOG] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SESSION onicecandidate {"candidate":"candidate:364264959 1 udp 41819904 10.4.1.71 59270 typ relay raddr 0.0.0.0 rport 0 generation 0 ufrag +zIO network-id 2 network-cost 10","sdpMid":"0","sdpMLineIndex":0}
​ [2022-08-05T15:09:49.104Z] [LOG] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SESSION Pending signaling connection
​ [2022-08-05T15:09:49.104Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SIGNALING PendingConnectState => PendingInviteState
​ [2022-08-05T15:09:49.104Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SESSION ConnectSignalingAndIceCollectionState => InviteAnswerState
​ [2022-08-05T15:09:49.105Z] [LOG] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SIGNALING Sending SDP v=0

​ [2022-08-05T15:09:49.106Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SIGNALING PendingInviteState => PendingAnswerState
​ Active agents Array(4)
​ Object
​ [2022-08-05T15:09:54.124Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SIGNALING PendingAnswerState => FailedState
​ [2022-08-05T15:09:54.124Z] [ERROR] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SESSION Failed handshaking with signaling server Timeout
ERROR @ connect-streams-min.38499a86.js:1
​ [2022-08-05T15:09:54.124Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SESSION InviteAnswerState => FailedState
​ [2022-08-05T15:09:54.124Z] [ERROR] [327418fb-df8c-4848-91d7-ab65eac98d89]:  Softphone error occurred :  signalling_handshake_failure Handshaking with Signalling Server wss://rtc.connect-telecom.eu-central-1.amazonaws.com/LilyRTC failed. 
ERROR @ connect-streams-min.38499a86.js:1
​ [2022-08-05T15:09:54.127Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SIGNALING closing virtual connection
​ [2022-08-05T15:09:54.178Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  sendSoftphoneReport success{"callStartTime":"2022-08-05T15:09:48.736Z","callEndTime":"2022-08-05T15:09:54.124Z","gumTimeMillis":332,"initializationTimeMillis":364,"iceCollectionTimeMillis":3,"signallingConnectTimeMillis":3,"handshakingTimeMillis":null,"preTalkingTimeMillis":null,"talkingTimeMillis":null,"cleanupTimeMillis":null,"iceCollectionFailure":false,"signallingConnectionFailure":false,"handshakingFailure":true,"gumOtherFailure":false,"gumTimeoutFailure":false,"createOfferFailure":false,"setLocalDescriptionFailure":false,"userBusyFailure":false,"invalidRemoteSDPFailure":null,"noRemoteIceCandidateFailure":null,"setRemoteDescriptionFailure":null,"softphoneStreamStatistics":[{"softphoneStreamType":"audio_input"},{"softphoneStreamType":"audio_output"}]}
​ myWebSocket message from server  Object
​ [2022-08-05T15:09:54.124Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SIGNALING PendingAnswerState => FailedState
​ [2022-08-05T15:09:54.124Z] [ERROR] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SESSION Failed handshaking with signaling server Timeout
ERROR @ main.c6a37f9….js:1
​ [2022-08-05T15:09:54.124Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SESSION InviteAnswerState => FailedState
​ [2022-08-05T15:09:54.124Z] [ERROR] [327418fb-df8c-4848-91d7-ab65eac98d89]:  Softphone error occurred :  signalling_handshake_failure Handshaking with Signalling Server wss://rtc.connect-telecom.eu-central-1.amazonaws.com/LilyRTC failed. 
ERROR @ main.c6a37f9….js:1
​ [2022-08-05T15:09:54.127Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  f150db0a-ad5c-4f2f-b809-c5eb9643555e SIGNALING closing virtual connection
​ [2022-08-05T15:09:54.178Z] [INFO] [327418fb-df8c-4848-91d7-ab65eac98d89]:  sendSoftphoneReport success{"callStartTime":"2022-08-05T15:09:48.736Z","callEndTime":"2022-08-05T15:09:54.124Z","gumTimeMillis":332,"initializationTimeMillis":364,"iceCollectionTimeMillis":3,"signallingConnectTimeMillis":3,"handshakingTimeMillis":null,"preTalkingTimeMillis":null,"talkingTimeMillis":null,"cleanupTimeMillis":null,"iceCollectionFailure":false,"signallingConnectionFailure":false,"handshakingFailure":true,"gumOtherFailure":false,"gumTimeoutFailure":false,"createOfferFailure":false,"setLocalDescriptionFailure":false,"userBusyFailure":false,"invalidRemoteSDPFailure":null,"noRemoteIceCandidateFailure":null,"setRemoteDescriptionFailure":null,"softphoneStreamStatistics":[{"softphoneStreamType":"audio_input"},{"softphoneStreamType":"audio_output"}]}`

**Comment by martin-greenberg** [comment]
The onConnected handler is not firing because your contacts are not connecting successfully -- your RTC connection with the softphone backend is not setting up successfully. This is not a Streams issue; you will need to reach out to AWS Support for troubleshooting with your network to identify the issue you're having connecting from your network to the RTC endpoints.
