### ISSUE TITLE
An extra +1 is added when not necessary for Agent.Connect()

### ISSUE THREAD

**Issue by jhleung** [amazon-connect/amazon-connect-streams#586]
For numbers that aren't already prefixed with a +, the streams api seems to automatically prepend the us country code +1 to the phone number. For example - when calling agent.connect from the agent API with the phone number endpoint, 1123456789, the call is made to +11123456789. Is there any way around this?

**Comment by Christian-Sesta** [comment]
Normalise the number on your end before hitting the agent.connect action. Give this lib a go: https://www.npmjs.com/package/libphonenumber-js
