### ISSUE TITLE
Multiple CCP on different iframes 

### ISSUE THREAD

**Issue by vivekkwatra** [amazon-connect/amazon-connect-streams#587]
We are planning to use connect stream API on two separate applications running on different domain and both the application would be loaded in a single application under an two iframes. Hence we want to know if this is supported by Amazon Connect and can work without any issues?

**Comment by marcingrabda** [comment]
It's not supported:

"Multiple calls to initCCP will no longer append multiple embedded CCPs to the window, and only the first call to initCCP will succeed. Please note that the use-case of initializing multiple CCPs has never been supported by Streams, and this change has been added to prevent unpredictable behavior arising from such cases."

**Comment by vpogudina** [comment]
Thanks for the response, marcingrabda. That's correct, multiple iframes with ccp are not supported.
