### ISSUE TITLE
Version 2.3.1 has wrong version string

### ISSUE THREAD

**Issue by gamliela** [amazon-connect/amazon-connect-streams#593]
Packaging of the latest release (2.3.1) was done with a wrong version number.
If you load softphone and type "connect.version" in the console you'll get 1.7.5 instead of 2.3.1.

![image](https://user-images.githubusercontent.com/8337169/188029584-570dd4f8-75e4-4509-9854-e0b990fb9189.png)

**Comment by seiyako** [comment]
Thank you for the report. The wrong version issue was fixed at 2.3.2.
