### ISSUE TITLE
Incorrect URL Generated (old domain)

### ISSUE THREAD

**Issue by m66rus** [amazon-connect/amazon-connect-streams#595]
I have a new customer instance ready to go live but had issues with a custom CCP whereby the login popup would not work because of a frame-ancestors issue. I spent alot of time trying to debug this issue and finally decided to build a very basic CCP from scratch when it dawned on me that the URL that it was complaining about was not one I had provided, but the old alias.awsapps.com instead of alias.my.connect.aws.

So I may be wrong but I would have expected the embedded CCP to be from alias.my.connect.AWS than awsapps.com as if I select this url in a browser alias.awsapps.com it opens up workdocs. Now, this is a fresh account so workdocs has not been used.

Have I found a bug ?

**Comment by andedavd** [comment]
Hello m66rus, we are not able to reproduce this issue. I would double check on the URLs you are providing both for your CCP initialization and your login URL. Redacting sensitive information as needed, would you be able to provide your CCP init values? You may also need to double check that you've correctly allowlisted your origins.

**Comment by m66rus** [comment]
Thanks for looking into this. I had support look at this as well, and in
the end, i recreated the CloudFront distribution layer and so far so go.
Not sure what was blocking the domains as the CFD was recreated with the
same terraform script
