### ISSUE TITLE
Wrong voiceConnection.updateVoiceIdSpeakerId in streams API documentation.

### ISSUE THREAD

**Issue by MHamza8070** [amazon-connect/amazon-connect-streams#602]
Instead of updateVoiceIdSpeakerId, the documentation showing deleteVoiceIdSpeaker in amazon connect streams documentation.
![image](https://user-images.githubusercontent.com/93217480/195052738-7ce118ac-c1b8-43d7-ab00-211fd2f06c78.png)

**Comment by vpogudina** [comment]
Documentation has been updated https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#voiceconnectionupdatevoiceidspeakeridstring
