### ISSUE TITLE
 CCP fails to access microphone after login popup in Firefox

### ISSUE THREAD

**Issue by ionutivan1** [amazon-connect/amazon-connect-streams#604]
Hello,
I'm embedding CCP into my page and I've stumbled across the following issue when using Firefox. 

### Issue
After authenticating, the login popup shows up and authenticates the user in Amazon Connect. It then displays the standard CCP and asks for microphone rights before closing and allowing the embedded CCP to start. The main page with embedded CCP will then also ask for microphone permissions.

![image](https://user-images.githubusercontent.com/5451467/196140484-a45ba917-453a-49c3-814a-5dd3df755ea8.png)

If the user does not choose 'Allow' on the prompt inside the popup, then it is possible to get 'Local media initialization failed GumTimeout' messages in the console: 

![image](https://user-images.githubusercontent.com/5451467/196141268-11409187-b776-43d8-bbbb-7928965c44b7.png)

If this happens, the user cannot place an outbound call since the embedded CCP thinks it has no microphone access. Instead it will default to a missed call state. 

I have whitelisted my domain into 'Approved origins' section of the Connect instance settings.
When initializing CCP, I am using 'allowFramedSoftphone: true' option.
I am aware that Firefox has a strict browsing mode and I have allowed cookies and pop-up windows for my domain. 
I could not reproduce the issue in Chrome. 

### Steps to reproduce:

1. Open Mozilla Firefox.
2. Initialize CCP app with login popup. Wait for the popup to ask for microphone permissions. 
3. Either let to login popup close without choosing anything or click 'Block'.
4. Let the main window with the embedded CCP ask for microphone permissions. 
5. Place an outbound call.
6. CCP stays on "Connecting" for sometime and then eventually says "Missed Call".

**Comment by seiyako** [comment]
Hi, it is expected that CCP can't connect to a call if the agent doesn't give the browser to access microphone. Do you give the permission at step 4 `Let the main window with the embedded CCP ask for microphone permissions.`? It's also recommended to check "Remember this decision".

**Comment by ionutivan1** [comment]
I am already granting permissions to the main browser window. It seems granting permissions to the popup window before it closes might solve the issue

**Comment by ionutivan1** [comment]
Hello, 
I'm still having this issue.  I found out that in Firefox, CCP seems to lose the microphone rights if the browser is not currently  selected. The use case seems to be that you initiate an outbound call and immediately switch to another program, leaving Firefox minimized.  The OS is Windows 10 (up to date), Firefox is latest version(114.0).

Steps to reproduce:
1. Open Mozilla Firefox.
2. Initialize CCP app with login popup. Wait for the popup to ask for microphone permissions. 
3. Allow all microphone rights  and click on 'Remember this decision'
4. Perform an outbound call and as soon as you press 'Call' button, minimize Firefox or alt+tab to another program. 
5. The CCP will try to call the number, but fail to get microphone rights. The phone call will not start and the agent enters 'Missed call' state
This is the browser console showing the error:
![Untitled](https://github.com/amazon-connect/amazon-connect-streams/assets/5451467/351f2bc1-d9cc-47ee-9091-0d47c4624eba)
