### ISSUE TITLE
Uncaught ReferenceError: connect is not defined

### ISSUE THREAD

**Issue by carbonefederico** [amazon-connect/amazon-connect-streams#607]
Hello team, I just started looking at the SDK and deployed the sample page provided in the section Initialization - connect.core.initCCP(). I installed Streams via NPM `npm i amazon-connect-streams`. The browser loads the javascript but I see the error `Uncaught ReferenceError: connect is not defined` in console.

Any suggestions? 

Thank you

**Comment by jagadeeshaby** [comment]
this appears when streams library isn't loaded successfully. could you double check that streams js loaded as part of your app?

it could also be that you trying to reference the library even before its getting loaded (timing issue). so please make sure the library is loaded on the window scope and then try the same.

**Comment by SukheshEV** [comment]
Hi everyone, I am also experiencing the same. Is there any solution found?
