### ISSUE TITLE
agent.setState not working  

### ISSUE THREAD

**Issue by Sh0bhaTripathi** [amazon-connect/amazon-connect-streams#614]
Tried to change the state of the agent with the below code:
```
agent.setState() / agent.setStatus()
var state = agent.getAgentStates()[0];
agent.setState(state, {
success: function() { /* ... / },
failure: function(err) { / ... */ },
},
{enqueueNextState: false}
});
```

and I got this error:
`{"type":"UnexpectedParameter","message":"Unexpected key 'enqueueNextState' found in params","stack":["UnexpectedParameter: Unexpected key 'enqueueNextState' found in params",.....`

By tracking the error I got to know that `enqueueNextState: options && !!options.enqueueNextState` is causing the problem in src/api.js at line 555.
 ```
Agent.prototype.setState = function (state, callbacks, options) {
    var client = connect.core.getClient();
    client.call(connect.ClientMethods.PUT_AGENT_STATE, {
      state: connect.assertNotNull(state, 'state'),
      enqueueNextState: options && !!options.enqueueNextState
    }, callbacks);
  };
```
Then I just commented out this line and the agent status got updated. while I had read in the document that **enqueueNextState** is supported in the latest version. 
Please let me know if this is the correct workaround or I am missing anything in agent.setState api call.

**Comment by Christian-Sesta** [comment]
In your example you have an extra `}` before the closing `)` give that a fix and see if it helps.

**Comment by vpogudina** [comment]
I assume since we didn't hear back everything worked out. Just in case here is documentation link https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#agentsetstate--agentsetstatus
