### ISSUE TITLE
Sandbox - Login pop up issue

### ISSUE THREAD

**Issue by dynamicscrmguy** [amazon-connect/amazon-connect-streams#619]
Hello,
I am trying to embed the CCP in sandboxed MS Dynamics environment. The login pop up appears & when I enter the credentials, it gives the below error : Warp Drive Console-14.js:1937 Unsafe attempt to initiate navigation for frame with URL 'XXXXXX' from frame with URL 'XXXXX'. **_The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set._** 
I tried to add sandbox = allow-top-navigation in my container div tag in the CCP html but this does not help. The pop up window should auto-close & then ccp should initiate.

Below is my CCP code -  connect.core.initCCP(
                                    document.getElementById("container-div"), {
                                    ccpUrl: customParams.ccpUrl, 	// REQUIRED
                                    loginPopup: true,				// optional, defaults to `true`
                                    loginPopupAutoClose: true,		// optional, defaults to `false`
                                    loginOptions: {                 // optional, if provided opens login in new window
                                        autoClose: true,              // optional, defaults to `false`
                                        height: 600,                  // optional, defaults to 578
                                        width: 400,                   // optional, defaults to 433
                                        top: 0,                       // optional, defaults to 0
                                        left: 0                       // optional, defaults to 0
                                    },
                                    region: customParams.region,         // REQUIRED for `CHAT`, optional otherwise
                                    softphone: {                    // optional, defaults below apply if not provided
                                        allowFramedSoftphone: true
                                    },
                                    pageOptions: {                  // optional
                                        enableAudioDeviceSettings: true, // optional, defaults to 'false'
                                        enablePhoneTypeSettings: true // optional, defaults to 'true'
                                    },
                                    ccpAckTimeout: 5000, //optional, defaults to 3000 (ms)
                                    ccpSynTimeout: 3000, //optional, defaults to 1000 (ms)
                                    ccpLoadTimeout: 10000 //optional, defaults to 5000 (ms)
                                });

**Comment by jagadeeshaby** [comment]
have you tried allow listing the sandboxed MS Dynamics environment within connect using - https://docs.aws.amazon.com/connect/latest/adminguide/app-integration.html ?

**Comment by dynamicscrmguy** [comment]
Yes. It is allowlisted.

**Comment by jagadeeshaby** [comment]
would you be able to post the `path` of the url which is being blocked by browser? 

If it's /login path then it probably means that the you are not yet logged into Connect and the message is expected as Connect assumes you going to login via a popup window.   See if this message goes away once you login to Amazon connect within the popup.

**Comment by dynamicscrmguy** [comment]
The message appears after I enter the credentials in the login pop-up. Below is the path details -


WarpDriveConsole-14.js:1938 Unsafe attempt to initiate navigation for frame with URL 'https://amazon-demo-instance-msd365.awsapps.com/auth/?client_id=564fda62f107a665&redirect_uri=https%3A%2F%2Famazon-demo-instance-msd365.my.connect.aws%2Fauth%2Fcode&state=AQICAHjcvzFwvKFB2p2q__1WSwl99CAdMJy1aUP5P6YzPs-15gFTYiLadWdPAkJWZNIUQ_WdAAAApjCBowYJKoZIhvcNAQcGoIGVMIGSAgEAMIGMBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDDkg-8bBaHcWEBETigIBEIBf2YTonzSR5_3hXcCZgR6Zj7C9yiRnGF5X1wbadKzTybm6oMKJGossWjOQAOYfYqcUdrb2ibR9wXnXXzmix0FAOyRstS5Bo1XQO6a87sFGtjfkn_vzo3MsE-3hVrk2-BY=' from frame with URL 'https://amazon-demo-instance-msd365.awsapps.com/auth/?client_id=564fda62f107a665&redirect_uri=https%3A%2F%2Famazon-demo-instance-msd365.my.connect.aws%2Fauth%2Fcode&state=AQICAHjcvzFwvKFB2p2q__1WSwl99CAdMJy1aUP5P6YzPs-15gFTYiLadWdPAkJWZNIUQ_WdAAAApjCBowYJKoZIhvcNAQcGoIGVMIGSAgEAMIGMBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDDkg-8bBaHcWEBETigIBEIBf2YTonzSR5_3hXcCZgR6Zj7C9yiRnGF5X1wbadKzTybm6oMKJGossWjOQAOYfYqcUdrb2ibR9wXnXXzmix0FAOyRstS5Bo1XQO6a87sFGtjfkn_vzo3MsE-3hVrk2-BY='. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

**Comment by jagadeeshaby** [comment]
I tried to reproduce the same on one of my Connect instance and the popups work just fine on the latest chrome.  Could you elaborate more on the `sandboxed MS Dynamics environment` is that an Iframed application which is set with Sandbox options? 

It's most likely tied with the parent app which is invoking `initCCP` call as the login popup is opened from the same parent app scope.  so please check of the parent app iframe restrictions and follow the chrome recommendation fix the same -  if so please do follow the recommendations here to allow popup navigations - https://developers.google.com/apps-script/guides/html/restrictions

**Comment by dynamicscrmguy** [comment]
Hello, As mentioned in the issue description I tried to add **sandbox = allow-top-navigation** in my **container div tag in the CCP html** but this does not help. The issue would not be reproduced in a standalone connect instance. I am using a parent application which is sandboxed. I have embedded the softphone HTML in a sandboxed parent app which is Dynamics CRM in this case.

**Comment by jagadeeshaby** [comment]
yeah the catch here is, the parameter you mentioned above has to be set on the parent Iframe not on the container Div where CCP is supposed to be loaded. 

Sandbox restrictions are enforced from the Dynamics CRM in this case, so see if there are settings that you can control the same or else please reach out the CRM team to support for this use case. 

I found this which seems to be related see if that helps - https://community.dynamics.com/crm/f/microsoft-dynamics-crm-forum/152041/iframe-issue-sandbox-allow-same-origin-allow-scripts-allow-popups-allow-forms

**Comment by dynamicscrmguy** [comment]
Okay. Thanks for your input. Would check with the Dynamics CRM product team.
