### ISSUE TITLE
contact.onEnded being called twice

### ISSUE THREAD

**Issue by mschersten** [amazon-connect/amazon-connect-streams#62]
I'm using something like the following code to handle the end of a contact:

```
function subscribeToContactEvents(contact) {
  contact.onEnded(handleContactEnded)
}
function handleContactEnded(contact) {
  var endType = contact.getStatus().type
  if (endType == 'ended') {
  	console.log('Contact Ended')
  }
}
```

This is called once, immediately after the contact ends (by agent or caller disconnecting).  The contact status persists for about 13-15 seconds after this, and then the function is called again.  It still returns 'ended' status when the function is called, but getStatus() returns an error if you try to call it again after that.

I find this in the streams file:

```
Contact.prototype.onEnded = function(f) {
   var bus = connect.core.getEventBus();
   bus.subscribe(this.getEventName(connect.ContactEvents.ENDED), f);
   bus.subscribe(this.getEventName(connect.ContactEvents.DESTROYED), f);
};
```

So it appears to be called on ended, and again on destroyed.  I'm checking the contact status type to trigger actions only when a call ends, not when it is missed.  Is there some way I can determine when a contact is ending and when it is being destroyed?

**Comment by mgidea** [comment]
You can call a try/catch block in your code when checking the status of the contact - capturing the error if it takes place and executing your code other wise.

The destroy event seems to happen when the agent becomes routable again

Seems a little ridiculous that there is no way to handle the contact object when the destroy event fires

**Comment by scyforce** [comment]
@jagadeeshaby , Is there a way to identify these two onEnded events instead of relying on Try/Catch?

**Comment by mgidea** [comment]
You can check the constructor of the object

**Comment by DillonSykes** [comment]
We had a similar issue which we solved in angular by unsubscribing from the events on ngDestory. Idk if this will help

**Comment by jolim24601** [comment]
You can use `contact.onDestroy`

**Comment by jolim24601** [comment]
You can call `getContactStatus` and check if it's `ended`

**Comment by scyzenefits** [comment]
@jolim24601 this is not true, contact.getStatus() always gives you "ended"

**Comment by scyzenefits** [comment]
> You can call `getContactStatus` and check if it's `ended` or `destroyed`

@jolim24601  this is not true, contact.getStatus() always gives you "ended"
