### ISSUE TITLE
AUTH_FAIL event triggered on regular interval 

### ISSUE THREAD

**Issue by Solomon-m** [amazon-connect/amazon-connect-streams#622]
Hello guys, 
I'm embedding CCP into Electron.js based application (which uses the Chromium browser engine ). I've stumbled across the following issue.  
   - Users are getting `AUTH_FAIL` event from Connect at regular intervals. For example for every hour user gets AUTH_FAIL event. 
   
Sample code : 
```
     let bus = connect.core.getEventBus();
     bus.subscribe(connect.EventType.AUTH_FAIL, () => {
                console.error('ERROR : AUTH_FAIL', new Date());
             // We get Auth_fail event from connect for every hour for a few users. 
     });
```
Any suggestion or comments on the above issue is much appreciated. Thanks in advance.

![auth_fail](https://user-images.githubusercontent.com/8034514/208363293-f8a46731-9b84-4788-8949-3967f6c43a9f.png)

**Comment by Solomon-m** [comment]
Hi @jagadeeshaby 
Good day, Can you help us with this? If someone looks into this or guides us to the problem it will be much appreciated.

**Comment by Solomon-m** [comment]
Hello, 
Good Day. Any update on this issue ?

**Comment by andywang219** [comment]
Hi, this is because the auth cookie expires every hour and needs to be refreshed

**Comment by andywang219** [comment]
Please reopen if you have any questions
