### ISSUE TITLE
Entire team getting missed calls

### ISSUE THREAD

**Issue by dblkbox42** [amazon-connect/amazon-connect-streams#625]
Entire team getting a lot of missed call after upgrading the custom CCP. Where should I start looking. They were fine prior to the upgrade.

**Comment by hxgnZO** [comment]
We have had issues as well with ours- eliminated a bunch of them by being more specific about the incoming call callbacks on the contact ob. Most of them were resolved by being a bit more specific with handling the onContact object. The rest have all been browser/system related "microphone issues". Are you able to get logs from them when they miss calls/run endpoint test utility? Our biggest issue seems to be that Chrome idles their tab with microphone permissions, and even though they have permissions, AWS isn't able to see them and won't let them take a call, sometimes it just doesn't ring. (I suspect if it happens to mic perms, it does to audio at the same time as well.)

**Comment by jagadeeshaby** [comment]
some of the relevant articles 

- https://aws.amazon.com/premiumsupport/knowledge-center/connect-not-displaying-incoming-calls/
- https://docs.aws.amazon.com/connect/latest/adminguide/common-ccp-issues.html
- https://kb.force.com/s/article/Amazon-Connect-Agent-sees-Missed-Call

If possible please do share the agent log file , this can be downloaded by ` connect.getLog().download()` command on the browser console to investigate further and  recommend next steps
