### ISSUE TITLE
Use Amazon Connect Streams API in AWS Lambda

### ISSUE THREAD

**Issue by gsanjeev432** [amazon-connect/amazon-connect-streams#629]
I am developing an IVR bot where I am calling from Amazon Connect and sending the required DTMF inputs/digits. 

So, I want to make an outbound call and then send digits or DTMF input during the call programmatically. 

Can I use amazon connect streams in Lambda or without having a UI or human intervention?

Please help.

**Comment by fezekilePlaatyiAbsa** [comment]
I believe you don't need Streams API, but just the Core Amazon Connect API. I found for you a function which I think would be used to implement your scenario with link here for [Amazon Connect JavaScript SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Connect.html#startOutboundVoiceContact-property) then you will simple direct to Contact Flow with integration to lambda function and be able to send your DTMF inputs/digits.

Tell me if that helps, I am also not Amazon Connect Expert but I believe that might be helpful!

**Comment by gsanjeev432** [comment]
@fezekilePlaatyiAbsa But how can I send dtmf input from the lambda? Can you please elaborate?

**Comment by fezekilePlaatyiAbsa** [comment]
Check Lambda integration to Contact Flow. Check these links:-

[AWS Official Documentation](https://docs.aws.amazon.com/connect/latest/adminguide/connect-lambda-functions.html)
[Youtube Search all the first 4 videos can be helpful](https://www.youtube.com/results?search_query=aws+connect+lambda+integration)

**Comment by fezekilePlaatyiAbsa** [comment]
If you need a Architecture design for this contact me on fezekileplaatyi<@>gmail.com

**Comment by vs-amzn** [comment]
Closing, this cannot be done with Streams. You will likely need to use the Connect SDK to integrate with lambdas. If there are any other concerns pertinent to Streams here, please feel free to re-open.
