### ISSUE TITLE
Call function before logout?

### ISSUE THREAD

**Issue by mschersten** [amazon-connect/amazon-connect-streams#63]
Previous issues have dealt with login/logout callbacks, or controlling logouts via SSO or SAML.  I'm looking for the ability to call a function (specifically to change the agent's status to offline) before they are logged out.  I have handled this for agents closing the page while still logged in by changing their status onunload or onbeforeunload.  A logout callback, if it existed, would not work because they need to be logged in while their status is changed.  Is there any way we could create a connect.onLogout() or agent.onLogout() function?

**Comment by mschersten** [comment]
A comment on another post about a login/logout callback led me to dig around in the Streams code.  I think I could hack into this and set the agent to offline before terminating.  Thoughts?


>    /**-------------------------------------------------------------------------
>     * Uninitialize Connect.
>     */
>    connect.core.terminate = function() {
>       // PRE-LOGOUT FUNCTION HERE
>       connect.core.client = new connect.NullClient();
>       connect.core.masterClient = new connect.NullClient();
>       connect.core.eventBus = new connect.EventBus();
>       connect.core.initialized = false;
>    };

**Comment by 0-g-r-e-g-0** [comment]
I managed to acheive this with the following javascript:
`var bus = connect.core.getEventBus();`
`if (bus) bus.subscribe(connect.EventType.TERMINATED, ctx.ccpTerminating);`
Where `ctx.ccpTerminating` is a function.
In your termination function you need to do this if you are going to attempt to re-login:
`connect.core.initialized = false;`
`connect.agent.initialized = false;`
You will of course then need to call `initCCP` again when you do try to login back in.
