### ISSUE TITLE
Best practice to use CCP authentication (token) for other APIs

### ISSUE THREAD

**Issue by maddoxd** [amazon-connect/amazon-connect-streams#636]
Writing a complex custom softphone based on streams will in many cases involve calling other APIs for config etc, not just using the connect client-side javascript methods/subscriptions. 

Is there any recommendations for the best way to leverage the CCP authentication to authenticate to other AWS services ? i.e. to an AWS API GW.  If we could get access to the Connect Session token in the front-end and somehow pass & validate that at the back-end this would seem to work, but unclear if this is actually possible.  I see in CloudTrail the Amazon Connect Service assuming the service-account role, with temp credentials - ASIA..... etc, but can't see a way to tie that to an individual Connect/Streams authenticated user.

Any advice?
Thanks

**Comment by thtliife** [comment]
Some advice from AWS on this would be amazing...
Imagine a world where we don't have to have users authenticate to multiple services to use a single app! :)

**Comment by jagadeeshaby** [comment]
This isn't something Amazon Connect Streams library support today, but I'll make sure to track this as a feature request, and update this when we know more.

Closest i could recommend is to make use of AWS Amplify to interact with other AWS REST/graphQl services -  https://docs.amplify.aws/lib/restapi/getting-started/q/platform/js/

**Comment by bml1g12** [comment]
> This isn't something Amazon Connect Streams library support today, but I'll make sure to track this as a feature request, and update this when we know more.
> 
> Closest i could recommend is to make use of AWS Amplify to interact with other AWS REST/graphQl services - https://docs.amplify.aws/lib/restapi/getting-started/q/platform/js/

@jagadeeshaby I see thank you, it's a shame there's no official route here but please could you clarify how we could authenticate with AWS Amplify after logging into AWS Connect's CCP via SAML?

I'd be interested to hear anyone's solutions for this issue of how to authenticate with other APIs from the CCP using the CCP authentication
