### ISSUE TITLE
When an outbound call is forwarded Connect.getType() of the agent receiving the transfer becomes "inbound"

### ISSUE THREAD

**Issue by intptr-t** [amazon-connect/amazon-connect-streams#639]
## What up?

The transferred "outbound" contact becomes an "inbound" contact.

## Expected value

Connection.getType() of the transferred contact is "outbound"

## Question:
Q1: Is it a specification that when an outbound call is transferred, Connect.getType() of the agent receiving the transfer return value "inbound"?

Q2: Can we any way to get the transferred initial contact to be "outbound" purely using the Streams API?

## Operation

1. Agent A outbound to customer "+8170xxxxyyyy".
2. Customer responds.
3. Agent A transfer to Agent B using quick connect.
4. Agent B responds.

## Sample codes and logs

```js
// Agent A
connect.contact((contact1) => {
    contact1.onConnecting((contact) => {
        const conn = contact.getInitialConnection();
        console.log(conn.getType()); // print "outbound"
        console.log(JSON.stringify(conn.getAddress()));
    });
});
```

**Agent A: output log**
```
'outbound'
'{"endpointARN":null,"endpointId":null,"type":"phone_number","name":null,"phoneNumber":"+8170xxxxyyyy","agentLogin":null,"queue":null}'
```

---

```js
// Agent B
connect.contact((contact1) => {
    contact1.onConnecting((contact) => {
        const conn = contact.getInitialConnection();
        console.log(conn.getType()); // => print "inbound"
        console.log(JSON.stringify(conn.getAddress()));
    });
});
```

**Agent B: output log**

```
'inbound'
'{"endpointARN":null,"endpointId":null,"type":"phone_number","name":null,"phoneNumber":"+8170xxxxyyyy","agentLogin":null,"queue":null}'
```

**Comment by vpogudina** [comment]
Regarding your Q1 - it is by design, that when call is transferred the value will change to inbound.

Regarding Q2 - there is a possibility that InitiationMethod on the contact object can be used, but currently it is always null, so we will need to look into it to find out why it is not being populated.

**Comment by intptr-t** [comment]
@vpogudina Thank you for your reply.
I found that I had to use Attribute to solve it.
I think the problem without InitiationMethod is a different problem, so I'm closing this issue.
