### ISSUE TITLE
SAML login window is delayed and not closing

### ISSUE THREAD

**Issue by zhangyuezhong** [amazon-connect/amazon-connect-streams#642]
I have below code setting
``````````
            const ccpConfig = {
                ccpUrl: "https://XXXXXXXXXX.my.connect.aws/ccp-v2/", // REQUIRED
				// from Azure SSO Basic SAML Configuration Relay State  
                loginUrl: "https://myapps.microsoft.com/signin/c90cc4b0-40f3-4d1e-8bfd-0db749aXXXXXX?tenantId=XXXXXXX-a629-4769-908d-ff92d7d3323d&RelayState=https://ap-southeast-2.console.aws.amazon.com/connect/federate/XXXXXX-30db-4431-8c5a-f628fceXXXX?destination=%2Fconnect%2Fccp-v2",
                loginPopup: true, // optional, defaults to `true`
                loginPopupAutoClose: true, // optional, defaults to `false`
                loginOptions: {
                    // optional, if provided opens login in new window
                    autoClose: true, // optional, defaults to `false`
                    height: 600, // optional, defaults to 578
                    width: 400, // optional, defaults to 433
                    top: 0, // optional, defaults to 0
                    left: 0, // optional, defaults to 0
                },
                region: "ap-southeast-2", // REQUIRED for `CHAT`, optional otherwise
                softphone: {
                    // optional, defaults below apply if not provided
                    allowFramedSoftphone: true, // optional, defaults to false
                    disableRingtone: false, // optional, defaults to false
                    ringtoneUrl: "./ringtone.mp3", // optional, defaults to CCP’s default ringtone if a falsy value is set
                },
                pageOptions: {
                    //optional
                    enableAudioDeviceSettings: true, //optional, defaults to 'false'
                    enablePhoneTypeSettings: true, //optional, defaults to 'true'
                },
                shouldAddNamespaceToLogs: false, //optional, defaults to 'false'
                ccpAckTimeout: 5000, //optional, defaults to 3000 (ms)
                ccpSynTimeout: 3000, //optional, defaults to 1000 (ms)
                ccpLoadTimeout: 10000, //optional, defaults to 5000 (ms)
            };
`            const ccpConfig = {
                ccpUrl: "https://lifeblood-ictservicedesk.my.connect.aws/ccp-v2/", // REQUIRED
				// from Azure SSO Basic SAML Configuration Relay State  
                loginUrl: "https://myapps.microsoft.com/signin/c90cc4b0-40f3-4d1e-8bfd-0db749a9f1dd?tenantId=957b3627-a629-4769-908d-ff92d7d3323d&RelayState=https://ap-southeast-2.console.aws.amazon.com/connect/federate/f00fef56-30db-4431-8c5a-f628fce563d0?destination=%2Fconnect%2Fccp-v2",
				//loginUrl: "https://myapps.microsoft.com/signin/c90cc4b0-40f3-4d1e-8bfd-0db749a9f1dd?tenantId=957b3627-a629-4769-908d-ff92d7d3323d",
                loginPopup: true, // optional, defaults to `true`
                loginPopupAutoClose: true, // optional, defaults to `false`
                loginOptions: {
                    // optional, if provided opens login in new window
                    autoClose: true, // optional, defaults to `false`
                    height: 600, // optional, defaults to 578
                    width: 400, // optional, defaults to 433
                    top: 0, // optional, defaults to 0
                    left: 0, // optional, defaults to 0
                },
                region: "ap-southeast-2", // REQUIRED for `CHAT`, optional otherwise
                softphone: {
                    // optional, defaults below apply if not provided
                    allowFramedSoftphone: true, // optional, defaults to false
                    disableRingtone: false, // optional, defaults to false
                    ringtoneUrl: "./ringtone.mp3", // optional, defaults to CCP’s default ringtone if a falsy value is set
                },
                pageOptions: {
                    //optional
                    enableAudioDeviceSettings: true, //optional, defaults to 'false'
                    enablePhoneTypeSettings: true, //optional, defaults to 'true'
                },
                shouldAddNamespaceToLogs: false, //optional, defaults to 'false'
                ccpAckTimeout: 5000, //optional, defaults to 3000 (ms)
                ccpSynTimeout: 3000, //optional, defaults to 1000 (ms)
                ccpLoadTimeout: 10000, //optional, defaults to 5000 (ms)
            };
``````````

First, it shows the iframe refused (i have add the domain to Amazon Connect) 

![image](https://user-images.githubusercontent.com/23203638/219261531-3e571828-7816-41c2-9ab7-6e8c31d074d7.png)

the log shows  
Refused to display 'https://XXXXXXXXX.my.connect.aws/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Second, it takes about 8 seconds for the login screen pop up. 
![image](https://user-images.githubusercontent.com/23203638/219259749-658261dc-d8ce-42a1-839a-bea31cdd720d.png)

Third, the Login window is not closed.
![image](https://user-images.githubusercontent.com/23203638/219259982-66f1f7a5-5079-426b-8b97-1034b40d36ad.png)

i think this because, the custom ccp try to open a url (Microsoft) with different domain, it does not have the window reference and cannot close the window..

**Comment by jagadeeshaby** [comment]
>First, it shows the iframe refused (i have add the domain to Amazon Connect)

Looks like you got an answer to this one. yes you need enable your custom domain to load the CCP. - follow the guide here - https://docs.aws.amazon.com/connect/latest/adminguide/app-integration.html


> Second, it takes about 8 seconds for the login screen pop up.

It could be because of the SSO flow taking longer time to complete. please verify the same by accessing login URL on a new tab and see how long that process takes.   

> Third, the Login window is not closed.

By the looks of the screenshot, it seems like an outcome of of the first issue. try this again after fixing the first issue by allow listing your app domain within Amazon connect.

**Comment by zhangyuezhong** [comment]
> . try this again after fixing the first issue by allow listi

HI [jagadeeshaby](https://github.com/jagadeeshaby),    
Thank you for reply,

I have already added the add my custom domain in CCP, it still refused to display (before agent actual login, it works fine after agent login, it may need display a temporary page rather than a broken icon), 
Refused to display 'https://XXXXXXX.my.connect.aws/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.


To resolve the close of popup issue, i created a login.html, the loginUrl points to http://customdomain/login.html,  so it popup in the same domain, it can hold a window ref,    so later connect.core.loginWindow.close();  

then in the login.html page, i quickly redirect to  "https://myapps.microsoft.com/signin/c90cc4b0-40f3-4d1e-8bfd-0db749aXXXXXX?tenantId=XXXXXXX-a629-4769-908d-ff92d7d3323d&RelayState=https://ap-southeast-2.console.aws.amazon.com/connect/federate/XXXXXX-30db-4431-8c5a-f628fceXXXX?destination=%2Fconnect%2Fccp-v2".

Now, login pop is working and automatically close (4 seconds after login).  it just a little bit slow. 

Notes, when we use 
var winRef = window.open("https:// xxx")
winRef will null if open a different domain,
winRef will not be null if open the same domain.

**Comment by jagadeeshaby** [comment]
>before agent actual login, it works fine after agent login, it may need display a temporary page rather than a broken icon

make sense, alternatively you could probably start by hiding the ccp container with some default message to say loading.. and you can listen to `connect.core.onInitialized(function() { /* ... */ });` and show the container for better customer experience?

**Comment by jagadeeshaby** [comment]
looks like we have a resolution here so moving the issue to be closed. feel free to reach out to us if you are still facing issues.
