### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by jjwilliams42** [amazon-connect/amazon-connect-streams#644]
When importing connect streams, it keeps saying Invalid token.

I've nailed it down to these lines in connect-streams.js:
Line 28215:
```
  var LoggedException = function (e) {
    this.type = (e instanceof Error) ? e.name : e.code || Object.prototype.toString.call(e);
    this.message = e.message;
    this.stack = [];
    if (e.stack){
      try {
          if (Array.isArray(e.stack)) {
              this.stack = e.stack;
          } else if (typeof e.stack === 'object') {
              this.stack = [JSON.stringify(e.stack)];
          } else if (typeof e.stack === 'string') {
              this.stack = e.stack.split('\n');
          }
      } catch {} // <--------- HERE
    }
  };
```

Line 25500:
```
                        if (err.stack){
                           try {
                               if (Array.isArray(err.stack)) {
                                   error.stack = err.stack;
                               } else if (typeof err.stack === 'object') {
                                   error.stack = [JSON.stringify(err.stack)];
                               } else if (typeof err.stack === 'string') {
                                   error.stack = err.stack.split('\n');
                               }
                           } catch {} // <----- HERE
                        }
```
It seems it doesn't like the catch without the parentheses and identifier. 

If I change it to

```
catch (err) {}
```

It works fine

**Comment by jagadeeshaby** [comment]
Could you post the actual error you getting, trying to understand what's causing this issue.

**Comment by SukheshEV** [comment]
I am getting the below error while compiling the application with Webpack
 
ERROR in ./node_modules/amazon-connect-streams/release/connect-streams.js 108:32
Module parse failed: Unexpected token (108:32)
You may need an appropriate loader to handle this file type.
|     }
|     const iframeIdSelector = `iframe[id='${appName}']`;
>     const iframe = containerDOM?.querySelector(iframeIdSelector) ||
|       document.getElementById(appName) ||
|       window.top.document.getElementById(appName);
 @ ./app/Dashboard/Dashboard.js 14:0-32
 @ ./app/Dashboard/index.js
 @ ./app/routes/asyncLoad.js
 @ ./app/routes/routes.js
 @ ./app/routes/index.js
 @ ./app/components/App/App.js
 @ ./app/components/App/index.js
 @ ./app/app.js
 @ multi ./node_modules/react-app-polyfill/ie11.js webpack-hot-middleware/client?reload=true ./app/app.js

**Comment by ammmarr** [comment]
> I am getting the below error while compiling the application with Webpack
> 
> ERROR in ./node_modules/amazon-connect-streams/release/connect-streams.js 108:32 Module parse failed: Unexpected token (108:32) You may need an appropriate loader to handle this file type. | } | const iframeIdSelector = `iframe[id='${appName}']`;
> 
> > ```
> > const iframe = containerDOM?.querySelector(iframeIdSelector) ||
> > ```
> 
> | document.getElementById(appName) || | window.top.document.getElementById(appName); @ ./app/Dashboard/Dashboard.js 14:0-32 @ ./app/Dashboard/index.js @ ./app/routes/asyncLoad.js @ ./app/routes/routes.js @ ./app/routes/index.js @ ./app/components/App/App.js @ ./app/components/App/index.js @ ./app/app.js @ multi ./node_modules/react-app-polyfill/ie11.js webpack-hot-middleware/client?reload=true ./app/app.js

I am facing the same issue, did you find a solution for that?
