### ISSUE TITLE
Amazon connect CCP URL Redirect to Login URL 

### ISSUE THREAD

**Issue by SaqibOctave** [amazon-connect/amazon-connect-streams#645]
I am using Amazon connect streams in my angular project. I call in the InitCCP method and gave all the necessary detail there when I try to login it redirect me to 
`https://XXXX.my.connect.aws/login` 
from
`https://XXXX.my.connect.aws/ccp-v2`
I don't know the reason If someone has any clue please guide me  
because of the above redirection, it opens the home dashboard of amazon connect instead of opening CCP window. 
here is my full configuration:
```
connect.core.initCCP(
      this.connectDiv.nativeElement as HTMLElement,
      // this.connectService.getInitConnectOption(),
     {
        ccpUrl: "https://xxxxx.my.connect.aws/ccp-v2#",            // REQUIRED
                 // REQUIRED
        loginPopup: false,               // optional, defaults to `true`
        loginPopupAutoClose: true,      // optional, defaults to `false`
        region: "eu-central-1",         // REQUIRED for `CHAT`, optional otherwise
        softphone: {                    // optional, defaults below apply if not provided
          allowFramedSoftphone: true,   // optional, defaults to false
          disableRingtone: false,       // optional, defaults to false
          ringtoneUrl: "./ringtone.mp3" // optional, defaults to CCP’s default ringtone if a falsy value is set
        },
        // shouldAddNamespaceToLogs: false, //optional, defaults to 'false'
        // ccpAckTimeout: 5000, //optional, defaults to 3000 (ms)
        ccpSynTimeout: 500, //optional, defaults to 1000 (ms)
        ccpLoadTimeout: 100000 //optional, defaults to 5000 (ms)
      }
    );
```

**Comment by jagadeeshaby** [comment]
The redirection to login page is expected if you haven't logged into Connect already and you should rather see a browser xframe error in such cases. 

also i do see that you setting`loginPopup`  false explicitly this does indicates that you going to login before calling initCCP.  so please make sure you login first using separate browser tab or window and then call initCCP.  Else try setting `loginPopup` to true,  it will try to popup the login screen for you and auto close depending on the settings and loads the CCp successfully.

**Comment by oharez** [comment]
This is still an issue for me. The redirect no longer works in our deployment. Is it something within the built CCP app? streams initializes, logs in, but loadTimeout triggers, refuses to display x-frame bla bla. Browser console shows errors and re-attempts to login. What's the deal? There was a chrome update this week, but more likely due to the new link for logging in to the CCP. I haven't changed anything in our client script which loads the CCP in an Iframe, literally mid shift and our help desk is shut down.
