### ISSUE TITLE
How to barge in?

### ISSUE THREAD

**Issue by andrei-at-work** [amazon-connect/amazon-connect-streams#646]
I see no way to barge in through the CCP (see screenshot below) despite calling the [MonitorContact API](https://docs.aws.amazon.com/connect/latest/APIReference/API_MonitorContact.html) with AllowedMonitorCapabilities set to BARGE. Has barge in been implemented yet? How do I barge in? Thanks.

![image](https://user-images.githubusercontent.com/74427636/220429002-70b1d2b5-0701-43aa-aafe-a4098b49e1a2.png)

**Comment by jagadeeshaby** [comment]
See if this helps - https://docs.aws.amazon.com/connect/latest/adminguide/monitor-barge.html

Screenshot you provided above indicates that you probably still on the monitoring mode so please follow above link to check how to enable the same on CCP.  if you still facing issues please reach out to AWS support with specific account and instance details to further assist you on this request

**Comment by andrei-at-work** [comment]
Thank you very much. Regards,Andrei --     Andrei Pancu SENIOR SOFTWARE DEVELOPERt 613.596.2533 x6220  |  m 613.851.2152 e ***@***.***  |  w www.taske.com     From: jagadeeshabySent: Tuesday, February 21, 2023 9:40 PMTo: amazon-connect/amazon-connect-streamsCc: andrei-at-work; AuthorSubject: Re: [amazon-connect/amazon-connect-streams] How to barge in? (Issue #646) See if this helps - https://docs.aws.amazon.com/connect/latest/adminguide/monitor-barge.htmlScreenshot you provided above indicates that you probably still on the monitoring mode so please follow above link to check how to enable the same on CCP. if you still facing issues please reach out to AWS support with specific account and instance details to further assist you on this request—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
