### ISSUE TITLE
Uncaught ValueError: containerDiv must be provided

### ISSUE THREAD

**Issue by anssaif** [amazon-connect/amazon-connect-streams#648]
hi am getting this error 
Uncaught ValueError: containerDiv must be provided
    at new t.ValueError (connect-streams-min.js:1:450668)
    at t.assertTrue (connect-streams-min.js:1:445913)
    at t.assertNotNull (connect-streams-min.js:1:445973)
    at t.core.initCCP (connect-streams-min.js:1:345122)
    at init (ccpIndex.html:14:26)
    at ccpIndex.html:43:13

however the DIV is already set on the html page , 

<!DOCTYPE html>
--
  | <html>
  |  
  | <head>
  | <meta charset="UTF-8">
  | <script type="text/javascript"
  | src='https://cdn.jsdelivr.net/npm/amazon-connect-streams/release/connect-streams-min.js'></script>
  | <script type="text/javascript">
  | var containerDiv = document.getElementById("container-div");
  | var instanceURL = "https://xxx(removed for privacy ).my.connect.aws/ccp-v2/";
  | // initialize the streams api
  | function init() {
  | // initialize the ccp
  | connect.core.initCCP(containerDiv, {
  | ccpUrl: instanceURL,            // REQUIRED
  | loginPopup: true,               // optional, defaults to `true`
  | loginPopupAutoClose: true,      // optional, defaults to `false`
  | loginOptions: {                 // optional, if provided opens login in new window
  | autoClose: true,              // optional, defaults to `false`
  | height: 600,                  // optional, defaults to 578
  | width: 400,                   // optional, defaults to 433
  | top: 0,                       // optional, defaults to 0
  | left: 0                       // optional, defaults to 0
  | },
  | region: "xxx(removed for privacy )",         // REQUIRED for `CHAT`, optional otherwise
  | softphone: {                    // optional, defaults below apply if not provided
  | allowFramedSoftphone: true,   // optional, defaults to false
  | disableRingtone: false,       // optional, defaults to false
  | ringtoneUrl: "./ringtone.mp3" // optional, defaults to CCP’s default ringtone if a falsy value is set
  | },
  | pageOptions: { //optional
  | enableAudioDeviceSettings: false, //optional, defaults to 'false'
  | enablePhoneTypeSettings: true //optional, defaults to 'true'
  | },
  | shouldAddNamespaceToLogs: false, //optional, defaults to 'false'
  | ccpAckTimeout: 5000, //optional, defaults to 3000 (ms)
  | ccpSynTimeout: 3000, //optional, defaults to 1000 (ms)
  | ccpLoadTimeout: 10000 //optional, defaults to 5000 (ms)
  | });
  | }
  | // add a script load event listener
  | window.addEventListener("load", function () {
  | init();
  | });
  | </script>
  | </head>
  |  
  | <body>
  | <div id="container-div" style="width: 400px; height: 800px;"></div>
  | </body>
  |  
  | </html>

**Comment by seiyako** [comment]
Hi, can you double check if the element with the id exists in the document the containerDiv is not null? I guess you should call getElementById inside init() function.

**Comment by hxgnZO** [comment]
I believe I set my container before the fx is called, IE: 
<script>{
var divvy = document.getElementById("container-div");
init(params)
{ 
someOptions: values
container: divvy
}

}

If you dig into the streams files, might be a typescript thing
