### ISSUE TITLE
Queue Priority in Routing Profile

### ISSUE THREAD

**Issue by aossey** [amazon-connect/amazon-connect-streams#65]
The routing profile exposed by Agent.getConfiguration().routingProfile and Agent.getRoutingProfile(), does not provide the priority assigned to each queue contained in the routing profile.  Is there a way to obtain this priority information from the routing profile assigned to the agent?

**Comment by ctwomblyamzn** [comment]
Hi aossey@, unfortunately currently there is no way of doing this. We will consider this feature request and prioritize it accordingly. Thanks for the feedback.
