### ISSUE TITLE
No puedo colgar la llamda

### ISSUE THREAD

**Issue by jesussales** [amazon-connect/amazon-connect-streams#652]
este es mi codigo 

   var containerDiv = document.getElementById("container-div");
      var instanceURL = "https://xxxxx.my.connect.aws/ccp-v2/";
      // initialize the streams api
      function init() {
        // initialize the ccp
        connect.core.initCCP(containerDiv, {
          ccpUrl: instanceURL,            // REQUIRED
          loginPopup: true,               // optional, defaults to `true`
          loginPopupAutoClose: true,      // optional, defaults to `false`
          loginOptions: {                 // optional, if provided opens login in new window
            autoClose: true,              // optional, defaults to `false`
            height: 600,                  // optional, defaults to 578
            width: 400,                   // optional, defaults to 433
            top: 0,                       // optional, defaults to 0
            left: 0                       // optional, defaults to 0
          },
          region: "eu-central-1",         // REQUIRED for `CHAT`, optional otherwise
          softphone: {                    // optional, defaults below apply if not provided
            allowFramedSoftphone: true,   // optional, defaults to false
            disableRingtone: false,       // optional, defaults to false
            ringtoneUrl: "./ringtone.mp3" // optional, defaults to CCP’s default ringtone if a falsy value is set
          },
          pageOptions: { //optional
            enableAudioDeviceSettings: false, //optional, defaults to 'false'
            enablePhoneTypeSettings: true //optional, defaults to 'true' 
          },

          authTokenRefreshed: function(authToken) {
          // Una vez que se haya autenticado el usuario, haz una llamada saliente a un número específico.
         window.token=authToken;
        },

          shouldAddNamespaceToLogs: false, //optional, defaults to 'false'
          ccpAckTimeout: 5000, //optional, defaults to 3000 (ms)
          ccpSynTimeout: 3000, //optional, defaults to 1000 (ms)
          ccpLoadTimeout: 10000 //optional, defaults to 5000 (ms)

         });
      }

      function Llamar( phoneNumber) {
    
        var endpoint = connect.Endpoint.byPhoneNumber(phoneNumber);
        var agent = new connect.Agent();

        agent.connect(endpoint, {
          success: function() { console.log("Llamando..."); },
          failure: function(err) {
            console.log("Llamada fallida...");
            console.log(err);
          }
        });
    }

con esto se me abre el popup, si llamo a la funcion llamar('+34*********'), hace la llamada sin problemas, pero no encuentro la manera de colgar la llamada, necesitoi ayuda por favor

**Comment by JhonFuenzalida** [comment]
Hola @jesussales yo utilizo las siguientes funciones, espero te funcionen

	 /** Clear active Call */
	function clearCall(contact: connect.Contact): void {
	  contact?.clear({
	    success: function () {
	      console.log(`Cleared contact via Streams`)
	    },
	    failure: function () {
	      console.log(`Failed to clear contact via Streams`)
	    },
	  })
	}
	 /** Destroy call if active or clear if not active */
	function endCallConnect(): void {
	  //TODO: save in history
	  const contact = getContact()
	  if (!haveCall(contact)) {
	    clearCall(contact)
	    return
	  }
	  const initialConnection = contact.getInitialConnection()
	  if (initialConnection) {
	    initialConnection.destroy({
	      success: function () {
	        clearCall(contact)
	      },
	      failure: function (err) {
	        console.log(`Failed to end call`, err)
	      },
	    })
	  }
	}
