### ISSUE TITLE
Can we send a tabular format to lex so that we can get the details from the user such as Payment info?

### ISSUE THREAD

**Issue by Rahulsingh0007** [amazon-connect/amazon-connect-streams#659]
Hi Team,

By any chance can anyone help me to get the details about how can we send the tabular format from lambda to lex using amazon connect UI,
Need to capture User info , please find the attachment below

Kindly repsond
<img width="413" alt="Form Input" src="https://user-images.githubusercontent.com/48233043/228751867-12163de3-4580-453e-83a2-f2fd7b3cfc60.PNG">

**Comment by vpogudina** [comment]
What exactly are you using here? Doesn't look like Streams.js functionality to me, can you clarify where did you get snapshots from?
