### ISSUE TITLE
Bugs after latest merge 

### ISSUE THREAD

**Issue by extmchristensen** [amazon-connect/amazon-connect-streams#66]
The latest mergred PR by @jagadeeshaby was great but introduced a few minior issues (in no partiuclar order):

1) Gulp step won't work unless you also have gulp installed globally. Better to add this section to package.json and ask users to run "npm run gulp" instead.
"scripts": {
"gulp": "gulp"
}

2) The documentation file still mentions the absolete make file at the top under "Downloading Streams"

3) The produced stream api file by gulp is misspelled and missing a verson identifier in the filename like the old file.

**Comment by ctwomblyamzn** [comment]
I believe all of these bugs have since been resolved.

**Comment by ctwomblyamzn** [comment]
Correction, we still have some makefile references in our docs. We will track this and remove these references eventually.

**Comment by ctwomblyamzn** [comment]
Fixed with https://github.com/amazon-connect/amazon-connect-streams/pull/402
