### ISSUE TITLE
X-Frame-Options sameorigin - For Auth Redirect URL this time

### ISSUE THREAD

**Issue by old-square-eyes** [amazon-connect/amazon-connect-streams#661]
Have spent a couple of very late nights trying to get this to work.

I appreciate there is an old thread https://github.com/amazon-connect/amazon-connect-streams/issues/10

But it is ancient and the solutions don't work for me.

Still seems an issue in 2023. I followed [the guide](https://aws.amazon.com/blogs/contact-center/perform-an-external-screen-pop-with-amazon-connect/) to the letter, and it seems out of date. Browsing to my cloudfront address https://xxxx.cloudfront.net/simple_screen_template.html, my browser has a fit with the SAME ORIGIN issue. Yes I have set the cloudfront address as an approved origin in Connect. It seems to get upset with the auth redirect url. I added that too for good measure. Do I have to add something in cloudfront/S3? I'm not even sure why it's wanting me to auth. It does it if I'm already logged in too.

I feel like this is nothing to do with my CRM link. I don't appear to be able to even load the wrapped CCP which makes me think it's related to the bucket somehow. I tried adding a wildcard CORS policy in the bucket and no joy. Also I noticed the login url it tries to navigate to has a 302 redirect to xxxx.awsapps.com/auth/?client_id=xxxxx. So things have probably changed.

Super stuck here and would love some help.

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/25760491/229789199-ee13fd3c-9eac-4762-abdd-b0cd07631709.png">

**Comment by flaviut** [comment]
I'm run into exactly the same issue. It seems like this is caused by [Total Cookie Protection](https://blog.mozilla.org/en/mozilla/firefox-rolls-out-total-cookie-protection-by-default-to-all-users-worldwide/) and similar anti-tracking initatives. The fix is to turn off tracking protection for this domain:


![2023-04-17-154955_528x491_scrot](https://user-images.githubusercontent.com/5213469/232595115-76f9bdac-e11e-47ca-bee9-9c1cc2987aa2.png)

---

The reason this happens is that AWS connect uses cookies to store login state. With Total Cookie Protection, each site has it's own cookie jar: https://support.mozilla.org/en-US/kb/total-cookie-protection-and-website-breakage-faq#w_what-is-total-cookie-protection

This means that even though you're logged in on `my.connect.aws`, you're not logged in under `example.com -> my.connect.aws`, since `example.com` has its own cookie jar.

I've made a bug report at Mozilla for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1828518

Fix would be for AWS Connect to loosen it's same-origin policy inside the iframe for login pages so that the user can log in again.

**Comment by old-square-eyes** [comment]
> Fix would be for AWS Connect to loosen it's same-origin policy inside the iframe for login pages so that the user can log in again.

Seems like this is a glaring omission?

**Comment by flaviut** [comment]
They probably set it up intentionally like this--this cookie privacy thing is new, and there are probably valid security reasons to prevent your login page from being iframed.

**Comment by Trikolon** [comment]
This may also break in Chrome soon, see their timeline for phasing out 3rd-party cookies: https://privacysandbox.com/intl/en_us/open-web/#the-privacy-sandbox-timeline

**Comment by vtrofin** [comment]
Hi there, I'm having the same issue with connect streams api as @old-square-eyes mentioned in the closed issue #10 . In fact this is how i arrived on this issue page, after initially posting my comment in that (closed) issue. Did anyone figure out a workaround for it? 

Same as the above mentioned, the error says: 
 > Refused to display 'https://`<your-instance-name>`.awsapps.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
<img width="661" alt="Screen Shot 2023-06-30 at 17 26 55" src="https://github.com/amazon-connect/amazon-connect-streams/assets/18513968/7e66e21e-5d62-4707-9b64-62ec699152b8">
 
 - browser: Chrome Version 114.0.5735.133 (Official Build) (arm64)
 - app: React 18 and Vite js; I'm running the app on `https://localhost:3000` and I have the domain in the list of approved domains
 
<img width="1112" alt="Screen Shot 2023-06-30 at 17 26 05" src="https://github.com/amazon-connect/amazon-connect-streams/assets/18513968/8465bc26-dcb9-4265-8663-ad3354f898e2">


 - dependencies:
```
 "dependencies": {
    "amazon-connect-streams": "^2.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.14.0",
    "zod": "^3.21.4"
  },
```
- I basically followed this [example implementation](https://github.com/aws-samples/ccp-react-dashboard-example/blob/1b79b6e0d925b2c712db041948e698e6c63ce6bc/ccp-ui/src/components/ConnectCCP.jsx#L11-L42)
- My code:
```ts
// App.tsx
import { useCallback } from "react"

import "./App.css"
import ConnectCCP from "@components/core/ConnectCCP"

function App() {
  // Avoid re-rendering ConnectCCP
  const CCP = useCallback(() => <ConnectCCP />, [])

  return (
    <div>
      <h1>Vite + React</h1>
      <CCP />
    </div>
  )
}

export default App

```

```ts
// ConnectCCP.tsx
import { useConnectCCPHook } from "./hook"
import { memo } from "react"

const ConnectCCP = () => {
  const { ref } = useConnectCCPHook()

  return (
    <div ref={ref} className={"w-full h-full min-w-[400px] min-h-[480px]"}>
      test connect container
    </div>
  )
}

export default memo(ConnectCCP)

```

```ts
// hook.ts
import { useRef, useEffect, MutableRefObject } from "react"
import { config } from "@config/index"

import "amazon-connect-streams"

interface ConnectCCPType {
  ref: MutableRefObject<HTMLDivElement | null>
}

const useConnectCCPHook = (): ConnectCCPType => {
  const ref = useRef<HTMLDivElement | null>(null)

  const ccpUrl = `https://${config.connectInstanceAlias}.my.connect.aws/connect/ccp-v2`

  useEffect(() => {
    try {
      window.connect.core.initCCP(ref.current as HTMLElement, {
        ccpUrl,
        region: config.connectInstanceRegion,
        loginPopup: false,
        loginPopupAutoClose: true,
        loginOptions: { autoClose: true },
        softphone: { allowFramedSoftphone: true },
        pageOptions: {
          enableAudioDeviceSettings: true,
          enablePhoneTypeSettings: true,
        },
        ccpAckTimeout: 5000,
        ccpSynTimeout: 3000,
        ccpLoadTimeout: 10000,
      })
    } catch (err) {
      console.log("err --->", err)
    }

    return () => {
      // handle React 18 double mount of useEffect in dev mode
      window.connect.core.terminate()
      if (ref.current?.children) {
        const targetNode = ref.current.children.namedItem("Amazon Connect CCP")

        if (targetNode) {
          ref.current?.removeChild(targetNode)
        }
      }
    }
  }, [])

  return { ref }
}

export { useConnectCCPHook }

```

**Comment by vtrofin** [comment]
Worth noting that I get the same issue in Firefox even though i've disabled  tracking protection for this domain

<img width="1332" alt="Screen Shot 2023-06-30 at 17 55 59" src="https://github.com/amazon-connect/amazon-connect-streams/assets/18513968/484b89c7-d860-4afa-beda-e1a0c2ff0665">


I got a similar error 
> The loading of “https://`<your-instance-name>`.awsapps.com/auth/?client_id=`<client-id>`&redirect_uri=https%3A%2F%2F`<your-instance-name>`.my.connect.aws%2Fauth%2Fcode&state=AQICAHj7lmrrt7vvzqxba3_B6jDCXE69z-6kg8r2GqdkkqX9VQE-xhO5gJEnWHCGm5UXbkffAAAApjCBowYJKoZIhvcNAQcGoIGVMIGSAgEAMIGMBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDIIPr3Y1KTxzi9FKpgIBEIBfbBJCJKiy4kSsmEuaysM8zr7Nns5xNBPGwFlgdwCS2N90nW2hMPjfbv3Wk0cIcgJJ9ILBFwoSGe2hW2IxQubVKuWxVdTBQLy45agxYkSDjMLvg5EsbTetWELifOz0fyw=” in a frame is denied by “X-Frame-Options“ directive set to “SAMEORIGIN“.

**Comment by vtrofin** [comment]
Based on the response I got from the AWS tech support it looks like the auth flow will not work in the iframe, which is by design. See [here](https://github.com/amazon-connect/amazon-connect-streams/issues/398#issuecomment-845350755)

**Comment by This-Is-Not-Brad** [comment]
I have am having this experience also, trying to embed into a React Application.

My Initialisation code:

```typescript   
const loadConnectStreams = async () => {
      try {
        connect.core.initCCP(containerRef.current!, {
          ccpUrl: 'https://XXX-connect-XXX-dev.my.connect.aws/ccp-v2/',
          loginPopup: true,
          loginOptions: {
            autoClose: true,
            height: 600,
            width: 400,
            top: 0,
            left: 0,
          },
          loginPopupAutoClose: true,
          softphone: { allowFramedSoftphone: true },
        });
        setInitialized(true);
      } catch (error) {
        console.error('Error initializing AWS Connect Streams:', error);
      }
    };

    if (!unmounted) {
      loadConnectStreams();
    }

    return () => {
      unmounted = true;
      connect.core.terminate();
    };
```

and always get the error

```
chrome-error://chromewebdata/:1 Refused to display 'https://XXX-connect-XXX-dev.awsapps.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

As the above people have mentioned. By using a custom chrome extension you can bypass this, but the issue appears to be with the login/auth window. So adding the 'Approved Origins' doesn't do anything. I cannot get a popup to display so it's outside the iFrame.

As anyone found a way around this? Alternatively can we automatically pass credentials\token to bypass this auth window?

**Comment by arozwalak** [comment]
Just got to the same issue and was wondering if anyone has a solution up to date?

**Comment by Solomon-m** [comment]
Hi 
We are facing this issue. Has anyone found a way to fix this?

**Comment by squifpa** [comment]
Facing the same issue, any solution available?
