### ISSUE TITLE
how to init agent workspace 

### ISSUE THREAD

**Issue by AnilSonix** [amazon-connect/amazon-connect-streams#664]
is there a way to init **agent workspace** similar to ccp ?

**Comment by maria-rossi** [comment]
Hi Anil! you mean having Customer profile/Case/etc tabs and not only the cpp embedded on a web page? Check [connect.agentApp.initApp()](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#connectagentappinitappname-containerid-appurl-config)  

The only problem I've found with that, is that is not possible to use SAML for suthentication :/

**Comment by AnilSonix** [comment]
> Hi Anil! you mean having Customer profile/Case/etc tabs and not only the cpp embedded on a web page? Check [connect.agentApp.initApp()](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#connectagentappinitappname-containerid-appurl-config)
> 
> The only problem I've found with that, is that is not possible to use SAML for suthentication :/

Thanks for replying. I will try that out

**Comment by zhangyuezhong** [comment]
I tried the following 
 ```
 const connectUrl = "https://futurebankcc.my.connect.aws";
  connect.agentApp.initApp(
    "customerprofiles",
    "customerprofiles-container",
    connectUrl + "/customerprofiles-v2/",
    { style: "width:800px; height:600px;" }
  );
  connect.agentApp.initApp(
    "cases",
    "cases-container",
    connectUrl + "/cases/agent-app/",
    {
      style: "width:800px; height:600px;",
    }
  );
```
the customer profiles is working, however, the cases is displayed, but cannot create a case even though I'm on an active call and profile is associated.

![image](https://github.com/amazon-connect/amazon-connect-streams/assets/23203638/7eeb869d-7d20-4cb7-a0a4-d7f2edc6ddfd)

![image](https://github.com/amazon-connect/amazon-connect-streams/assets/23203638/172ae929-584e-4d46-b164-97a9e0ee56ff)

**Comment by AnilSonix** [comment]
Thanks, the above snippet worked
