### ISSUE TITLE
connect.agentApp.initApp for 3 inits (CCP, Wisdom, CustomerProfiles) results in warning "there are 3 connected CCPs in this tab ..."

### ISSUE THREAD

**Issue by Ra100NZ** [amazon-connect/amazon-connect-streams#667]
By default, there is no any issue (when allowFramedSoftPhone: true).
We would like to use allowFramedSoftPhone: false (to be able to use 3rd party noise reduction component). 
The CCP is showing a red error: The microphone is not accessible

If we remove connect.agentApp.initApp for Wisdom and CustomerProfiles (we init only CCP) - no error / it works.

![image](https://user-images.githubusercontent.com/53541746/234006895-f6553d58-2d21-4008-b6c5-3dd75813bf3b.png)

**Comment by Ra100NZ** [comment]
Thanks a lot. It works now correctly.

**Comment by maddoxd** [comment]
Hello - related to this - and the fact that each additional agentapp has a hidden CCP.. It seems that each time a new agentapp is initialised, it ties that CCP to the master CCP.  And if that additional Agent App div is removed - i.e. Q/Wisdom is on another tab that gets closed, it causes an AckTimeout on the main CCP.

However, the Amazon Connect Salesforce adapter seems to be able to embed the Q/Wisdom control on any form, and presumbly that div is unmounted when the Salesforce task page is closed for instance.

Any guidance on this?

Thanks
