### ISSUE TITLE
Tree-shaking support

### ISSUE THREAD

**Issue by flaviut** [amazon-connect/amazon-connect-streams#669]
I've written an app using the API, and my bundle looks like this:

![image](https://user-images.githubusercontent.com/5213469/235186123-58fcbb16-6281-4272-8e98-04b1924e0b94.png)

This seems to be because this project includes a full version of the AWS SDK: https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/aws-client.js

I understand some folks use this library as `<script src=...`, and for them this is helpful (although I'd suggest that best practice for them would be to include their own AWS SDK version as well), but when using this from npm, I would prefer this project only include the code that it actually uses.

**Comment by flaviut** [comment]
Looks like this would require switching to aws-sdk v3: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-connect/#v2-compatible-style

> The client can also send requests using v2 compatible style. However, it results in a bigger bundle size and may be dropped in next major version

**Comment by cesargdm** [comment]
Still an issue
