### ISSUE TITLE
What is the CCP URL, for SAML authentication ?

### ISSUE THREAD

**Issue by yuuta31** [amazon-connect/amazon-connect-streams#670]
## What
SAML authentication must be new CCP instance URL ?
When use old CCP URL, succeed SAML federation and redirect to my custom page which isn’t authenticated in iframe
But new CCP URL is authenticated in my custom page

```
old: https://＜instanceName＞.awsapps.com/connect/
new: https://＜instanceName＞.my.connect.aws/
```

## Detail
Old CCP URL is also passing SAML authentication and redirect to my custom page
But iframe in my custom page isn’t authenticated after SAML authentication is succeed
And then retry to sign-in SAML authentication again because iframe in my custom page isn’t authenticated
And more sign-in loop again …

- SAML authentication setting
https://aws.amazon.com/jp/blogs/contact-center/configure-single-sign-on-for-amazon-connect-using-okta/
https://aws.amazon.com/jp/blogs/news/configure-single-sign-on-for-amazon-connect-using-okta/

- Federation setting
https://docs.aws.amazon.com/connect/latest/adminguide/configure-saml.html#destination-relay

### Failed init

```js
connect.core.initCCP(containerDiv, {
  ccpUrl: "https://<connectInstanceName>.awsapps.com/connect/ccp-v2#",
  loginUrl: "https://XXXXXXXXXX",
  loginPopup: true,
  loginPopupAutoClose: true,
  softphone: {
    allowFramedSoftphone: true,
  },
})
```

### Succeed init

```js
connect.core.initCCP(containerDiv, {
  ccpUrl: "https://＜instanceName＞.my.connect.aws/",
  loginUrl: "https://XXXXXXXXXX",
  loginPopup: true,
  loginPopupAutoClose: true,
  softphone: {
    allowFramedSoftphone: true,
  },
})
```

**Comment by vpogudina** [comment]
From a quick glance it seems your ccpUrl: "https://<connectInstanceName>.awsapps.com/connect/ccp-v2#", has an extra # at the end, have you tried with just "https://<connectInstanceName>.awsapps.com/connect/ccp-v2"?
