### ISSUE TITLE
Pass Attributes when Initiating an outbound Call

### ISSUE THREAD

**Issue by asharma99** [amazon-connect/amazon-connect-streams#671]
Is there any way to pass attributes/parameters when making an outbound call ?(connect.agent ). 

We have a use case where the customer agents are a part of multiple queues all of which have a different caller ID (multi Organizations support). The business wants to ensure the agent calls to customers always carry the correct caller ID based on the queue the agent selects. I can get the agent queue real time selection work and pass it to my outbound function but any contact/custom attributes are not passed making it impossible to set the caller id in real time based on queue selection. 

Is there any other way to achieve this ? I know the startOutboundcontactAPI is there but that does not ensure the call gets back to the same agent who initiated it ? Any help is appreciated.

**Comment by mschersten** [comment]
I think this particular case can be solved by assigning the number as the default outbound number of the queue, and then supplying the queue ARN when making the outbound call with connect.agent.  That's how we're doing it now, however we answer for many different numbers that all go into a few inbound queues, so we have had to create separate queues for each number that we answer for. This is time consuming and error-prone, but the main issue is that we recently hit our service limit for queues per instance. It would be great to be able to assign a caller ID to the outbound call through Streams API the way that we can with the startOutboundcontactAPI.

**Comment by ajspetner** [comment]
This is still an issue...

**Comment by p24-max** [comment]
Facing same issue.
@seiyako any plans to add this?
