### ISSUE TITLE
Multi-Party Conference Join from the originating party dropping the originating party

### ISSUE THREAD

**Issue by hamishcross** [amazon-connect/amazon-connect-streams#674]
Definitions:

Agent A = Originating Agent
Agent B = Conferenced in Agent
Customer = Outbound call to Customer

Scenario:
Agent A calls customer. Agent A attempts 3 step transfer to Agent B using quick connect. Agent A attempts to join all 3 parties together.

Expected Result: 
All 3 parties are joined together

Actual Result:
Agent A is dropped, Agent B + Customer are connected.

This is only impacting environments where Multi-Party Calling is enabled

Has anyone else encountered this issue?

**Comment by gjesse** [comment]
i tried this using contact.conferenceConnections() and it worked for me today.

**Comment by hamishcross** [comment]
Thanks @gjesse . We'll close this card.
