### ISSUE TITLE
Error: Cannot set properties of undefined (setting 'md5')

### ISSUE THREAD

**Issue by erikohlin12** [amazon-connect/amazon-connect-streams#675]
I am trying to use amazon-connect-streams (v2.4.6 but the same issue happens on all versions after 2.3.1) in my Salesforce application (which runs in strict mode). The library is throwing the following error as soon as I import the module:

`Error: Cannot set properties of undefined (setting 'md5')`

@stackasaur helped me resolve a similar issue a few months ago [in this thread](https://github.com/amazon-connect/amazon-connect-streams/pull/574#issuecomment-1187517861), so maybe a similar fix is needed for this.

Any help would be much appreciated as this is blocking me from using this.

**Comment by vs-amzn** [comment]
It’s been a while and we are closing this for now. Please reopen if it’s still an issue
