### ISSUE TITLE
A problem that the mute function does not work properly when the value of 'allowFramedSoftphone' is set to false

### ISSUE THREAD

**Issue by kimhanmiru** [amazon-connect/amazon-connect-streams#677]
We are developing a softphone (ccp).

In accordance with the vdi environment guided by AWS, in the custom ccp of the vdi environment, the value of allowFramedSoftphone is set to false in the initCCP function.

So, I set it to media less.

However, clicking the mute button in ccp does not take effect.

How should I solve it?

**Comment by vpogudina** [comment]
Mute button will not have effect in medialess ccp, the only way to mute is have medai-full ccp open and use mute there.

**Comment by vpogudina** [comment]
The "workaround" is to click the mute button in the CCP external to the VDI (which is what is expected to do). Please see our recommended practice here: https://docs.aws.amazon.com/connect/latest/adminguide/using-ccp-vdi.html
_If your agents connect to a remote endpoint and operates in that environment, we recommend either rerouting audio to an external E.164 endpoint or connecting the media through the local device and then signaling through the remote connection._
