### ISSUE TITLE
access the values of agent.onSoftphoneError

### ISSUE THREAD

**Issue by electronicalias** [amazon-connect/amazon-connect-streams#678]
I'm trying to subscribe to [agent.onSoftphoneError](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#agentonsoftphoneerror) with the following code:

 ```
agent.onSoftphoneError(handleSoftphoneError);
...
function handleSoftphoneError(error) {
    console.log("######### [agent.onSoftphoneError] Softphone Error Type: " + error.getErrorType);
    console.log("######### [agent.onSoftphoneError] Softphone Error Message: " + error.getErrorMessage);
    console.log("######### [agent.onSoftphoneError] Softphone Error End Point URL: " + error.getEndPointUrl);
}
```

In my log I see:

```
2023-05-27T08:04:36.316Z] [ERROR] [22cfc840-99eb-4083-a03b-8367f70701d5]:  Softphone error occurred :  signalling_handshake_failure Handshaking with Signalling Server wss://rtc.cell-1.prod.eu-west-2.prod.connect.aws.a2z.com/LilyRTC failed. 
```

But the handler gives me the following:
```######### [agent.onSoftphoneError] Softphone Error Type: undefined```
```######### [agent.onSoftphoneError] Softphone Error Message: undefined```
```######### [agent.onSoftphoneError] Softphone Error End Point URL: undefined```

If I use the method as suggested in the documentation by appending `()` to each method, so `getErrorType()`, the handler fails. 

I assume I should get the log message above broken down into 
`Error Type: signalling_handshake_failure`
`Error Message: Handshaking with Signalling Server wss://rtc.cell-1.prod.eu-west-2.prod.connect.aws.a2z.com/LilyRTC failed.`
`Error End Point URL: wss://rtc.cell-1.prod.eu-west-2.prod.connect.aws.a2z.com/LilyRTC`

It is my lack of knowledge, but I didn't find the documentation clear.

**Comment by vpogudina** [comment]
Hi electronicalias, thanks for pointing that out, we didn't take into account that posting the event will trim all the functions - [cloning functions is not supported](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#error_types) I'll be updating our documentation to reflect the correct usage:
```

agent.onSoftphoneError(handleSoftphoneError);
...
function handleSoftphoneError(error) {
   console.log("######### [agent.onSoftphoneError] Softphone Error Type: " + error.errorType);
   console.log("######### [agent.onSoftphoneError] Softphone Error Message: " + error.errorMessage);
   console.log("######### [agent.onSoftphoneError] Softphone Error End Point URL: " + error.endPointUrl);
}
```
