### ISSUE TITLE
Softphone tab closes without clicking "leave" on pop-up in active call

### ISSUE THREAD

**Issue by stallingerl** [amazon-connect/amazon-connect-streams#685]
**Starting situation:** If you have an active call with the softphone and try to close the tab with the active call, a pop-up starts, asking the user if they really want to close the tab.

**Issue**: Even without confirming you want to close the tab, the tab closes automatically after a couple of seconds, leading to an unwanted disconnect of the call. 

**Expected behaviour:** The tab remains open until you click "close" on the pop-up and does **not** close automatically.

**Comment by ranfisfrancisco** [comment]
Hey,

Thanks for reaching out. I haven't been able to reproduce the issue in Chrome, Firefox or Edge. Which browsers did this work in?
