### ISSUE TITLE
Error: agentID is EMPTY

### ISSUE THREAD

**Issue by metarama** [amazon-connect/amazon-connect-streams#689]
I am using the version 2.5.0. I see this error in the console log soon after SAML login.

[CCP] [2023-06-17T17:02:15.400Z] [ERROR] [a4c61afb-253e-4b24-a33a-6bc3094274e0]: cannot decide clientApp config status from DB due to error: cannot get current agent AppConfig setting due to DB error {"stack":"Error: agentID is EMPTY\n    

at https://<myinstance>.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:870410\n    
at f (https://<myinstance>.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:863657)\n    
at Generator.<anonymous> (https://<myinstance>.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:865013)\n    
at Generator.next (https://<myinstance>.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:864020)\n    
at qs (https://<myinstance>.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:869669)\n    
at a (https://<myinstance>.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:869873)\n    
at https://<myinstance>.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:869934\n    
at new Promise (<anonymous>)\n    
at https://<myinstance>.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:869813\n    
at https://<myinstance>.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:870678",
"message":"agentID is EMPTY"}

**Comment by gustavololli** [comment]
any update?

**Comment by beallc** [comment]
Hello. We are aware of the issue and working to resolve it. Are you experiencing any direct impact or just reporting an error you see in the logs?

**Comment by metarama** [comment]
@beallc, in general, errors in the console log bother me. Plus CCP logs are excessively verbose. So much so that stuff gets lost in the noise.  Whenever I find a pearl like the error I reported above I relish it to see what side affect it's causing. So much is broken around CCP login that I do not know what is causing what.

I hope the SAML login can be smooth experience some day. At present, the login popup does not close fast enough after successful login. It sits there longer than desired displaying the entire CCP in the login dialog! Imagine how ugly it looks - the login box showing the CCP. I can change the target url after SAML login but what do I choose? CCP with the two smiling faces is best of the options. Is there something else I can choose that simply conveys 'successful login'?

**Comment by gjesse** [comment]
I have noticed this as well in non-saml login usage on v2.5.0

**Comment by electronicalias** [comment]
I'm seeing this too, although the use case isn't using SAML and it's a containerised custom CCP.

```{
    "level": "SEVERE",
    "message": "https://myconnect.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.4208d2dc.js 0:425189 \"[2023-06-28T11:12:22.573Z] [ERROR] [22cfc840-99eb-4083-a03b-8367f70701d5]: cannot decide clientApp config status from DB due to error: cannot get current agent AppConfig setting due to DB error {\\\"stack\\\":\\\"Error: agentID is EMPTY\\\\n    at https://myconnect.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:870754\\\\n    at f (https://myconnect.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:864001)\\\\n    at Generator.\\u003Canonymous> (https://myconnect.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:865357)\\\\n    at Generator.next (https://myconnect.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:864364)\\\\n    at qs (https://myconnect.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:870013)\\\\n    at a (https://myconnect.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:870217)\\\\n    at https://myconnect.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:870278\\\\n    at new Promise (\\u003Canonymous>)\\\\n    at https://myconnect.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:870157\\\\n    at https://myconnect.my.connect.aws/connect/ccp-naws/static/client-app-interface.js:1:871022\\\",\\\"message\\\":\\\"agentID is EMPTY\\\"}\"",
    "source": "console-api",
    "timestamp": 1687950742587
}```

This is impacting my ability to build a product because I can't currently place calls.
