### ISSUE TITLE
FAC.js:44     POST https://<InstanceAlias>.my.connect.aws/ccp-v2/fac 400

### ISSUE THREAD

**Issue by metarama** [amazon-connect/amazon-connect-streams#690]
I see this error 7 times in the console log after each login to CCP.

**Comment by hxgnZO** [comment]
Same, has been that way since I've started working on it. It hasn't ever caused an issue that I'm aware of. I tracked it down somewhere but it's too minor for me to have given much time to it. If you search through previous issues and google it you'll see it's common. Out of curiosity- are you using federated authentication?

**Comment by vpogudina** [comment]
FAC 400 errors are expected, and not affecting anything.

**Comment by gjesse** [comment]
I agree, if it's expected, it's not an error, and shouldn't be logged as such. at the least, it's a drag on development.

**Comment by hxgnZO** [comment]
> Why was this issue closed? At a minimum, if FAC errors are expected then do not write to the log as error. Just report it as info that a certain feature is not enabled/available. Ideally make the logs less verbose by default. At present there is not a decent way to mute these logs.
> 
> @vpogudina - Only ERRORS should be logged to the console. If it's not causing a problem then why log it as an error?
> 
> @hxgnZO - I am using SAML login. Finally, after lot of struggle I was able to get the SAML login to work. But, now I wonder if I should have gone with Twilio. The CCP login and logs are horrible!

I second this - I'll have to dig into it again sometime, I forget exactly what it was, I want to say it was an API gateway thing. If you are familiar with AWS resources/have good access, dig into the full application configuration for connect and how it is built. Might be something you can figure out. I think it was something to do with waiting for federated login basically- definitely would be nice to handle it. It's frustrating explaining to my boss/customer "yeah those *errors* are normal".

**Comment by gjesse** [comment]
Just to be clear, this happens with non-federated login as well

**Comment by hxgnZO** [comment]
> Just to be clear, this happens with non-federated login as well

Thank you for that. I was curious about that. Whatever it is it only happens before the use authenticates *shrug*
