### ISSUE TITLE
task option does not exists on InitCCPOptions

### ISSUE THREAD

**Issue by rizwan5922** [amazon-connect/amazon-connect-streams#692]
Hi, 
I am unable to disable ringtone for task. 

 connect.core.initCCP(containerDiv, {
      ccpUrl: `${this.config.ccpUrl}/ccp-v2/`,
      loginPopup: false,
      softphone: softphone,
      chat: {
        disableRingtone: true
      },
      **task:{
        disableRingtone: true
      }**,

![image](https://github.com/amazon-connect/amazon-connect-streams/assets/1834993/5ba5603c-6cee-463d-92b3-6d8fa10cf9f2)

**Comment by vs-amzn** [comment]
Streams does not currently support disabling ringtones for tasks. Thank you for sharing this concern.

**Comment by manojverma086** [comment]
We are also looking for this option. It would be great if this is available.
