### ISSUE TITLE
'resume' muted connection failing 

### ISSUE THREAD

**Issue by hausermatt** [amazon-connect/amazon-connect-streams#694]
this was happening last week (6/15, 6/16). cannot reproduce with native CCP or in my application through streams API.

### repro:
_multi party mode enabled
multiple connections_
- mute connection
- hold the same connection
- resume connection

### result:
the connection actually gets unmuted when resumed but the mute icon still appears muted and no longer works on subsequent clicks.

did not notice any errors in the log at the time.

**Comment by hausermatt** [comment]
does not seem directly related but some general instability with the APIs using multi party mode https://github.com/amazon-connect/amazon-connect-streams/issues/693

**Comment by vpogudina** [comment]
Can you share your code that you are using to mute, hold and resume? Where was it happening, how can we reproduce it to debug?

**Comment by hausermatt** [comment]
> Can you share your code that you are using to mute, hold and resume? Where was it happening, how can we reproduce it to debug?

I'm using `unmuteParticipant()/muteParticipant()`, and  `hold()/resume()`. in this scenario the mute was working fine. it was just when I resumed it broke.

to repro:
> repro:
> multi party mode enabled
> multiple connections
>
> mute connection
> hold the same connection
> resume connection

I'm not sure my code is all that relevant as this was also happening with the native CCP. but here's an example:

```ts
const contact = new connect.Agent().getContacts()[0];
const connection = contact.getConnections()[0];

// mute connection
connection.muteParticipant();

// hold connection
connection.hold();

// resume connection
connection.resume() <----- breaks here

**Comment by Juzziee** [comment]
I'd like to confirm that I am experiencing the same issue using version 2.5.0
Appears to be working correctly in version 2.4.5.

Similar results where holding the call works fine but when you attempt to unhold the call, you hear the audible beep and nothing happens. 

When you initially press resume, streams reports that the unhold was successful. Click resume again will give you an error that 'resumeConnection' API request failed

**Comment by vpogudina** [comment]
Hi again. I tried to reproduce the behavior that you are describing, but what I'm seeing is different -
in the scenario
agent1 accept customer call,
agent1 adds agent2 to the call,
agent1 mutes agent2,
agent1 puts agent2 on hold,
agent1 resumes agent2
agent2 now cannot unmute himself (agent1 is not supposed to be able to unmute agent2 btw)

Is that different from your experience? 
Can you please provide instance arn, contact id and timestamp of when it happened (preferably recent one, we don't have visibility over the contacts longer than a month ago)

**Comment by waqar2418** [comment]
I am encountering a similar issue in both the CCP and our Amazon Connect-integrated application. Below are the steps to reproduce the issue:

1- An agent receives an inbound call from a customer.
2- A supervisor initiates monitoring and then barges into the ongoing call.
3- The agent disconnects, leaving the supervisor and the customer connected.
4- The supervisor mutes their microphone and places the customer on hold.
5- The customer hears the hold music as expected.
6- When the supervisor attempts to resume and taking the customer off hold, an error is thrown.

As a result, the supervisor is unable to remove the customer from hold.
