### ISSUE TITLE
Disconnect event not working in multiparty mode

### ISSUE THREAD

**Issue by laranceas** [amazon-connect/amazon-connect-streams#697]
There are three parties: the customer, agent 1, and agent 2. They are in connected multiple-party mode.

In this case, when a call is connected, we receive two call connected events: one is the call connected event of the customer, and the second is agent 2's call connected event.

### Issue:
 If the agent2 or customer (any one) disconnects the call, we don't receive any kind of contact end event from the agent1's stream.

### Requirement : 
We need to show contact end notification in the CCP of Agent 1 even if only one party disconnects the call. We have tried with **onEnded** event but this is event is triggered only if all parties are disconnected.

**Comment by laranceas** [comment]
Hi, I'm still facing this issue. can anyone please tell us any suggestions?

**Comment by laranceas** [comment]
hi

**Comment by ChristineHarbour** [comment]
maybe related to https://github.com/amazon-connect/amazon-connect-streams/issues/695 ?
