### ISSUE TITLE
Get Agent ARN from the Connect Stream.

### ISSUE THREAD

**Issue by vdineshmca** [amazon-connect/amazon-connect-streams#70]
Hi,

We know the 'Username' we are retrieving with help of agent.getConfiguration().username using the Connect Stream.

Similarly, Is there any way to retrieve the Agent ARN through the Connect Stream?

**Comment by ninjamike54** [comment]
There isn't currently, but we're aware of the need and are already tracking it on our side.

**Comment by prosunshining** [comment]
Hi @ninjamike54 , is there any update on this issue? 🤔

**Comment by CiscoKidxx** [comment]
Any update on this issue?

**Comment by ctwomblyamzn** [comment]
Sorry for the long wait time. We are still tracking this issue on our end.

**Comment by intptr-t** [comment]
I have an alternative that until the official API will be released.

The [Sample agent event stream](https://docs.aws.amazon.com/connect/latest/adminguide/sample-agent-event-stream.html
) says that the "name" of the agent queue is null.
> This queue has a name of "null" because it's an agent queue, and agent queues don't have names.

And the ID part of the agent queue is the same as the agent's ID.(For now...)

```javascript
const AGENT_QUEUE_PATTERN = new RegExp('arn:aws:connect:([\\w|\\-]+):(\\w+):instance/([\\w|\\-]+)/queue/agent/([\\w|\\-]+)');

connect.agent((agent) => {
  const agentQueue = agent.getConfiguration().routingProfile.queues.filter(queue => queue.name === null)
  // group[0] all
  // group[1] region
  // group[2] AWS AccountID
  // group[3] Amazon Connect InstanceID
  // group[4] AgentID
  const groups = AGENT_QUEUE_PATTERN.exec(agentQueue[0].queueARN);
  const agentArn = `arn:aws:connect:${groups[1]}:${groups[2]}:instance/${groups[3]}/agent/${groups[4]}`;

  console.log(agentArn);
}
```

**Comment by syJSdev** [comment]
Also, for all `Id`s such as `queueId` and `contactId`, It's actually `Arn`.
![image](https://github.com/amazon-connect/amazon-connect-streams/assets/51244659/f01f08b7-e374-479d-bf84-44db3b1d8c73)

**Comment by gjesse** [comment]
Can we get this fixed? can't understand why this has been open for 5 years now.

**Comment by seiyako** [comment]
agentARN should be always present in the object returned from agent.getConfiguration(). It'd be appreciated if you could share the repro steps for the empty agentARN scenario. 
Meanwhile, let us fix the typing issue.

**Comment by hngan** [comment]
getAgentARN API has been added to the newest update in Streams!

https://github.com/amazon-connect/amazon-connect-streams/releases/tag/v2.13.1
