### ISSUE TITLE
Contact state type not reporting ACW

### ISSUE THREAD

**Issue by hausermatt** [amazon-connect/amazon-connect-streams#700]
https://github.com/amazon-connect/amazon-connect-streams/blob/932ad6a50f107b57b9e66a8b58c79dcd5eb0c22e/src/index.d.ts#L644C1-L645C1 -> I can never get my contact to return this type when we are in fact in ACW.

streams version: `2.5.0`

flow: incoming call -> accept call -> end call (here we don't get ACW state type)

code repro:
```.ts
// place call
    // ... ring ring

//answer call
contact.accept();

// end call
const agentConnection = contact.getAgentConnection();
connection.destroy();

// print type
const contactStateType = contact.getState().type;
console.log(contactStateType); // <- repeatedly returns "ended" but never changes to "acw".
```

**Comment by vpogudina** [comment]
There is no direct contact state 'ACW', I'll update documentation to avoid confusion.

A better way to detect ACW state would be subscribing to contact.onACW event
https://github.com/amazon-connect/amazon-connect-streams/blob/932ad6a50f107b57b9e66a8b58c79dcd5eb0c22e/Documentation.md#contactonacw

**Comment by hausermatt** [comment]
> There is no direct contact state 'ACW', I'll update documentation to avoid confusion.
> 
> A better way to detect ACW state would be subscribing to contact.onACW event https://github.com/amazon-connect/amazon-connect-streams/blob/932ad6a50f107b57b9e66a8b58c79dcd5eb0c22e/Documentation.md#contactonacw

yes I am familiar with that event. I'm simply stating your model has a property that never seems to be used: https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/index.d.ts#L644

so it's more than updating docs right?

**Comment by vpogudina** [comment]
Yes, we will update the model as well.
