### ISSUE TITLE
Agent attachments fail with 403

### ISSUE THREAD

**Issue by ciulic** [amazon-connect/amazon-connect-streams#707]
Hi guys,

We have enabled the attachments functionality:
https://docs.aws.amazon.com/connect/latest/adminguide/enable-attachments.html and also enabled the CORS.
Within a connection between a customer and an agent, the customer can upload/attach a file, but when the agent is uploading we get a 403 error:
![image](https://github.com/amazon-connect/amazon-connect-streams/assets/839736/28f2b28b-a4fd-40e3-860d-44624a0145a9)

Please guide us with this error.

**Comment by ozthekoder** [comment]
Investigating. In the mean time could you share the CORS policy you attached to the S3 bucket?

**Comment by SaqibOctave** [comment]
@ozthekoder  i am also facing the same issue here is the CORS policy that i attached to the S3 bucket
```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "POST",
            "PUT",
            "HEAD",
            "DELETE"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]
```
