### ISSUE TITLE
Reporting Error Types and Messages

### ISSUE THREAD

**Issue by mschersten** [amazon-connect/amazon-connect-streams#71]
I would like to collect error reports externally, and I'm looking for a way to access the error types and messages that are being logged.

I can trigger these events by on agent.onError() and agent.onSoftphoneError(), but how can I include the type of error in my report?

**Comment by ctwomblyamzn** [comment]
This has been fixed since: https://github.com/amazon-connect/amazon-connect-streams/commit/509487f2ff57aa2e15f977eba7fc759e04e1bab2
