### ISSUE TITLE
Allow customisation of CCP_IFRAME_REFRESH_LIMIT via initCCPParams

### ISSUE THREAD

**Issue by SangaGit** [amazon-connect/amazon-connect-streams#711]
When we call initCCP() in angular application(we are not using login pop up with this integration as user will log in to ccp using aws ccp connect UI itself. but we need some data to pull and show on our application-agent uses aws ccp connect UI to connect with the customers), we experienced that after 6 Iframe retry attempts,  iframe failed to load. This is due to the CCP_IFRAME_REFRESH_LIMIT being set to 6 by default and there is no customisation through initCCPParams. We have a situation where we need to continue this retry process as many as we can(Until agent logs in to AWS CCP connect panel itself at some point). Is there a way to increase an Iframe reties or can we refresh the initCCP() (ex: connect.core.refresh()) when trigger connect.core.onIframeRetriesExhausted() or any workaround for this situation?
Obviously we don't want to refresh the UI. This was working fine with v1.6.6 as iframe was keep retying. After we update in to v2.5.1 we are having this issue.

```
connect.core.initCCP(containerElement, {
            ccpUrl: https://instance.name.my.connect.aws/ccp-v2/softphone,
            loginPopup: false,
            softphone: {
                allowFramedSoftphone: true
            }
        });
```

### Suggested solution
Would be better to have following options via initCCPParams:
1) CCP_IFRAME_REFRESH_LIMIT - can be used to increase or decrease the limit. Default value can be 6.
2) Enable/disable CCP_IFRAME_REFRESH_LIMIT - if disabled(false) this will allow iframe to unlimited retries. Default value can be true (enable)

**Comment by SangaGit** [comment]
@vpogudina can you please help to take a look in to my PR(please feel free to add any changes) as this feature is quite urgent for us.

**Comment by jagadeeshaby** [comment]
could you expand more on your use case?  having infinite refresh is not an viable option here as it could potentially put more load on CCP infrastructure and hence we limited this option to 6.

**Comment by SangaGit** [comment]
@jagadeeshaby simply we have 2 applications opened in 2 browser tabs. AWS CCP connect soft phone UI to connect with customer & internal web application(angular) to handle their requests. We need to pull some information from CCP connect soft phone UI in to angular application. E.x: to show agent’s status(busy, available, unavailable, etc) on our angular application, etc.

We are calling initCCP() within our angular application to communicate with CCP connect soft phone UI to make the bridge between applications with the following code snippets.
```
connect.core.initCCP(containerElement, {
            ccpUrl: https://instance.name.my.connect.aws/ccp-v2/softphone,
            loginPopup: false,
            softphone: {
                allowFramedSoftphone: true
            }
        });
```

We have a situation where we need to continue/increase this retry process more than 6 times as we don’t know when agent is going to log in to AWS CCP connect soft phone UI itself using another browser tab. However some agents don’t have CCP connect account, so we don’t want to show login pop up with this integration.

Problem arises when agent logs in to Angular application first then later CCP connect soft phone UI after some time, like let’s say after 15-20mins. In this case 6 iframe retries is exhausted before logs in to CCP connect soft phone UI and won’t be able to make the bridge between applications. So agent has to manually refresh the Angular application tab to restart iframe retries again which we don’t want to do. Now we need a way to increase this retry mechanism more than 6 times as we don’t know which point agent will logs in to CCP connect soft phone UI with different tab.
As a workaround for this situation if we try to use `connect.core.onIframeRetriesExhausted()` we need to remove iframe from the DOM and recall `connect.core.initCCP()` after each 6 retries I believe, which is not good for our angular application performance(this is not working as expected either).
Hope above explanation helps you understand the situation. We need some control over retry limit not to retry infinite but should be able to increase (customisable) through initCcpParams, rather than removing/adding iframe to the DOM or refreshing the angular application itself.
Any workaround for this situation without doing all above will be great.
