### ISSUE TITLE
Send attachment throw error that signature does not match 

### ISSUE THREAD

**Issue by SaqibOctave** [amazon-connect/amazon-connect-streams#712]
Hi All,
I try to invoke the sendAttachment method of the streams API, but when i pass the Attachment to Send Attachment API it through an error that signtaure does not match

```
controller.sendAttachment({
                    attachment: file
                  }).then((res)=>{
                    console.log(res);
                  })
```
the First API runs successfully like this
![image](https://github.com/amazon-connect/amazon-connect-streams/assets/110086158/d2900a95-b117-48cb-a0fc-888ca713ad8f)
and the response of the start-attachment-upload API is exact match like in the documentation

```
{
    "AttachmentId": "a9ac98ec-c936-4441-a124-9d7a88debfce",
    "UploadMetadata": {
        "HeadersToInclude": {
            "x-amz-meta-contact_id": "3dff5a86-2f3a-4bf3-aa47-d82871671096",
            "x-amz-meta-initial_contact_id": "3dff5a86-2f3a-4bf3-aa47-d82871671096",
            "x-amz-acl": "bucket-owner-full-control",
            "Content-Disposition": "attachment; filename=\"56102_file.txt\"",
            "x-amz-meta-account_id": "747926693930",
            "Content-Length": "9",
            "Content-Type": "text/plain",
            "x-amz-meta-organization_id": "84ecefa9-184a-400f-babf-3288d7c8fd04"
        },
        "Url": "URL",
        "UrlExpiry": "2023-08-03T08:15:46Z"
    }
}
```
but when it goes to complete attachment upload part it gives the error:
![image](https://github.com/amazon-connect/amazon-connect-streams/assets/110086158/9cae061e-8bab-41c0-87df-f1b1788dadb7)
Please Help me to resolve if anyone have any idea about that:

**Comment by seiyako** [comment]
Could you open an issue in [ChatJS repository](https://github.com/amazon-connect/amazon-connect-chatjs/issues)? Thank you.
