### ISSUE TITLE
Refused to display 'https://xxx.awsapps.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by Jabezq** [amazon-connect/amazon-connect-streams#718]
when i click logout，i would auto pop login screen，at this time i close the pop login screen，it will error like what my title said.
i want to reload the website, and the login pop screen will auto pop~
![image](https://github.com/amazon-connect/amazon-connect-streams/assets/89257586/d86106bd-a58d-4469-98c0-ef0deae7faef)
![image](https://github.com/amazon-connect/amazon-connect-streams/assets/89257586/8609b6ed-f91d-4c8f-8d99-2c960db0f5ba)

**Comment by jagadeeshaby** [comment]
This is an expected behavior before the login.  Please do login using the popup and the error should disappear.

**Comment by Jabezq** [comment]
> This is an expected behavior before the login. Please do login using the popup and the error should disappear.

thanks u
