### ISSUE TITLE
updateMonitorParticipantState(connect.MonitoringMode.SILENT_MONITOR) how to use in practice?

### ISSUE THREAD

**Issue by hausermatt** [amazon-connect/amazon-connect-streams#719]
we have this API but how can we use it for a contact we may not have? Assuming the agent performing this API call is a supervisor/manager, how will they call this on a given contact ...if they don't have a contact yet. From what I found, there was no way for a supervisor/manager agent to retrieve ongoing contacts currently in the same instance.

**Comment by vpogudina** [comment]
This API is intended to be used after silent_monitoring has been initiated from real time metrics page in admin console. After silent_monitoring has been initiated - updateMonitorParticipantState(connect.MonitoringMode.BARGE) can be used, if that feature is enabled, and after that if supervisor wants to return back to monitoring - updateMonitorParticipantState(connect.MonitoringMode.SILENT_MONITOR) can be used in that case. 

I hope that helps. Feel free to reopen the issue, if you still have remaining questions.

**Comment by gjesse** [comment]
Just to be clear @vpogudina - you are saying that the *only* way to initiate silent monitoring is from the real time metrics page? I'm having a little trouble what use case is envisioned for this API if it requires using your interface to initiate it. We're building a fully custom control panel and were hoping to integrate the monitor/barge functions in our existing product. Requiring our customers to go to the real time metrics page and then come back to our product seems like a less than ideal user experience.

**Comment by vpogudina** [comment]
There is a public API to initiate monitoring that you can use to initiate silent monitoring. https://docs.aws.amazon.com/connect/latest/APIReference/API_MonitorContact.html

updateMonitorParticipantState API is intended to be use to _update_ current monitoring state, when you have more than one [AllowedMonitorCapabilities](https://docs.aws.amazon.com/connect/latest/APIReference/API_MonitorContact.html#API_MonitorContact_RequestSyntax)

**Comment by vpogudina** [comment]
And possibly this https://docs.aws.amazon.com/connect/latest/APIReference/API_GetCurrentUserData.html API can help getting contacts, but I haven't tried myself.

**Comment by vpogudina** [comment]
Just to clarify - https://docs.aws.amazon.com/connect/latest/APIReference/API_MonitorContact.html this can be used to initiate monitoring, and after that updateMonitorParticipantState(connect.MonitoringMode.BARGE) / updateMonitorParticipantState(connect.MonitoringMode. SILENT_MONITOR) should be used to initiate barge, return back to monitoring same contact.

**Comment by hausermatt** [comment]
> Just to clarify - https://docs.aws.amazon.com/connect/latest/APIReference/API_MonitorContact.html this can be used to initiate monitoring, and after that updateMonitorParticipantState(connect.MonitoringMode.BARGE) / updateMonitorParticipantState(connect.MonitoringMode. SILENT_MONITOR) should be used to initiate barge, return back to monitoring same contact.

right understood. that's what I'm trying now, however I'm experiencing an error when I initiate monitoring via API_MonitorContact and then the subsequent `updateMonitorParticipantState(connect.MonitoringMode.BARGE)` via streams API call fails. I can open up a new issue for this
