### ISSUE TITLE
typo in type file SLIENT -> SILENT

### ISSUE THREAD

**Issue by hausermatt** [amazon-connect/amazon-connect-streams#725]
https://github.com/amazon-connect/amazon-connect-streams/blob/4da7e360f51be6b93a5ccf02e45ed668dcee1e1e/src/index.d.ts#L726

**Comment by hausermatt** [comment]
can we get this fixed? causing comparator issues in our project

**Comment by vpogudina** [comment]
Thanks so much for pointing it out, just merged the fix.
