### ISSUE TITLE
How to Transfer the call in amazon ccp

### ISSUE THREAD

**Issue by psawant311c1** [amazon-connect/amazon-connect-streams#728]
Hello All
We are using Amazon Connect-Stream js in one of our project.
Customer is talking to an agent (A). during the conversation, the agent (A) needed help and want to transfer the call to agent B
We are looking for a stream function which will transfer the call to agent B and agent A should automatically leave the call 

Is there any function for the same, 
Your help is highly appreciated.

Regards
Pravin Sawant

**Comment by jagadeeshaby** [comment]
see if this helps - https://github.com/amazon-connect/amazon-connect-streams/blob/master/cheat-sheet.md#transfer-to-a-quick-connect
