### ISSUE TITLE
Customize CCP UI to masking the customer phone numbers

### ISSUE THREAD

**Issue by RJ261995** [amazon-connect/amazon-connect-streams#739]
Hi,
I am using the default CCP panel provided by the AWS which is working fine.  Now I want to mask the customer phone numbers on CCP UI due to privacy and security.

**Comment by vs-amzn** [comment]
Using the default, out-of-the box CCP, there is no way to do this. If you need to not display the numbers, you could do that via a custom CCP.

If there are any other concerns about this, please do re-open on the ticket
