### ISSUE TITLE
'boolean' misspelt as 'boolan' in index.d.ts

### ISSUE THREAD

**Issue by djsing** [amazon-connect/amazon-connect-streams#753]
Source:
https://github.com/amazon-connect/amazon-connect-streams/blob/9a8950d95012b7fa545fa3c8eb385b2c550c5ab8/src/index.d.ts#L98

Incorrect spelling of this line is causing the following error on compilation:

![image](https://github.com/amazon-connect/amazon-connect-streams/assets/40138027/c1c62a7b-876f-460d-ba8d-9ab427eccbba)

Steps to reproduce:
- `ng new` and follow default prompts.
- `npm install amazon-connect-streams`
- `npm start`

Version: 2.6.3

**Comment by jagadeeshaby** [comment]
Thank you for raising the issue. this has been fixed.
