### ISSUE TITLE
Always connected delayed ~16 sec when its voice mail

### ISSUE THREAD

**Issue by peter-wd-1** [amazon-connect/amazon-connect-streams#757]
I'm using SAML and CCP-v2. Whenever an outbound call is made from the AWS-SDK Node server, it takes time to actually connect from CCP on the browser, and I cannot hear the voicemail instruction. Normally, you should be able to hear something like, "The dial you made is currently not available; please leave a message after the tone." 

However, CCP almost always loses that first part and connects after 16 seconds. Meaning, you will never know if the call is actually connected to the recipient or connected to an answering machine (voicemail). How can I connect to voicemail immediately if the outbound call is missed?

**Comment by hngan** [comment]
Hey, can you explain how you are starting an outbound call with the AWS-SDK and how the flow is connected with CCP here? Streams APIs support creating outbound calls which may help here. https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#agentconnect
