### ISSUE TITLE
Uncaught (in promise) GumTimeout: Local media has not been initialized yet.

### ISSUE THREAD

**Issue by OctaveIdeas** [amazon-connect/amazon-connect-streams#779]
I have developed a custom CCP using amazon connect streams. I works on local environment but when i deploy the streams and and my custom ccp code it throughs the error "Uncaught (in promise) GumTimeout: Local media has not been initialized yet.", Can somebody help me to resolve the issue ?

**Comment by andywang219** [comment]
Is the issue still occurring for you?

Which browser are you using? For Firefox, GetUserMedia does not resolve unless the Firefox window is visible and in focus. If you click away and switch to another application, GetUserMedia will not resolve until you give Firefox focus.

**Comment by Juzziee** [comment]
I have also experienced this issue with one of our users. 
We have found that after near exactly after 10.2 seconds of the inbound call ringing, firefox/connect will report a softphone error with the error "Uncaught (in promise) GumTimeout: Local media has not been initialized yet".

When the agent answers the call within that 10.2 seconds, the softphone will initalise correct 95% of the time.
