### ISSUE TITLE
how to handle multi channels like: voice, chat at the same time in custom CCP?

### ISSUE THREAD

**Issue by OctaveIdeas** [amazon-connect/amazon-connect-streams#781]
I have embedded the Streams API and created a custom CCP to manage voice chats or tasks. It works well for a single channel. However, if an agent is in a chat session with a customer and the same customer calls at the same time, and the agent accepts the call, clicking on the disconnect button disconnects the voice connection only. If we attempt to disconnect the chat from the same button, it displays the following error.

![image](https://github.com/amazon-connect/amazon-connect-streams/assets/126852001/5b236aac-8444-4cc3-ac6b-cc9f2e664af2)

**Comment by andywang219** [comment]
Have you configured your routing profile to handle contacts on multiple channels at the same time?

Please see the following documentation:
1. https://docs.aws.amazon.com/connect/latest/adminguide/channels-and-concurrency.html
2. https://docs.aws.amazon.com/connect/latest/adminguide/routing-profiles.html#example-routing-concurrency
3. https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-connect-agents-calls-chats-tasks/
