### ISSUE TITLE
Issues with implementing 3P Cookie phaseout update

### ISSUE THREAD

**Issue by glemin5011** [amazon-connect/amazon-connect-streams#782]
Hi there,

I am working on updating our Agent app that has a custom CCP to get it ready for the 3P cookie phaseout, but I am struggling with properly implementing and testing the behavior of the new RSA banner. 

I followed the instructions on implementing the 3P phaseout update in the documentation ([here](https://docs.aws.amazon.com/connect/latest/adminguide/admin-3pcookies.html)) and my browser has the following flags turned on:

<img width="742" alt="image" src="https://github.com/amazon-connect/amazon-connect-streams/assets/59791512/48ab3d49-f52f-42db-88a0-bb655d346ba8">

I tested the RSA banner by disabling 3P cookies in my browser settings:

<img width="692" alt="image" src="https://github.com/amazon-connect/amazon-connect-streams/assets/59791512/9c141c75-32ee-4720-a5b8-10ce2840100f">

This way, I was able to trigger the RSA banner in my app:

<img width="815" alt="image" src="https://github.com/amazon-connect/amazon-connect-streams/assets/59791512/bcae5fe6-2799-4567-a589-05b9e1e37edc">

However, whenever I click on the 'Grant Access' button, it simply turns into the deny RSA banner: 

<img width="614" alt="image" src="https://github.com/amazon-connect/amazon-connect-streams/assets/59791512/9fccb3b6-4995-4caa-adeb-16b2d0d090ce">

Also, as I was updating this yesterday, I was still probably signed in to my session from the older version on my local machine. However, when I am trying to sign in today, with the 3P cookies setting turned on (**so that 3P cookies are allowed**), **I am now unable to sign in at all**,  and the blue RSA banner asking me to Grant Access shows up, but the same issue occurs - the banner just changes to the deny (yellow one) and I can't sign in. This is what shows up in my logs:

<img width="564" alt="image" src="https://github.com/amazon-connect/amazon-connect-streams/assets/59791512/9cfddfaf-0346-4195-80d5-c41c6814c38c">

Fyi this is the configuration of my CCP:

```typescript
 const ccpConfig: connect.InitCCPOptions = {
    ccpUrl: app.ccpUrl,
    loginUrl: app.loginUrl,
    loginPopup: true,
    loginPopupAutoClose: true,
    loginOptions: {
      autoClose: true,
      height: 600,
      width: 400,
      top: 0,
      left: 0,
    },
    softphone: {
      allowFramedSoftphone: true,
    },
    storageAccess: {
      canRequest: true,
      mode: 'custom',
    },
  };

```

Any ideas on how to fix this issue with the banner and how to test the functionality of the 3P cookie phaseout before it goes live?

**Comment by MHamza8070** [comment]
@glemin5011, I am also implementing 3P Cookie phaseout update and facing same issue, thanks for posting let's see.

**Comment by orihika0123** [comment]
@glemin5011  @MHamza8070 

I will provide feedback on two points that I have noticed:

1. I too encountered same issue where denial occurred when I pressed the RSA banner authorization button without restarting Chrome after enabling its experimental features. Therefore, I recommend restarting Chrome.

2. Regarding the settings to block third-party cookies, the latest procedure (https://docs.aws.amazon.com/connect/latest/adminguide/admin-3pcookies.html) doesn't seem to provide specific instructions. Here's what my actual settings screen looks like (apologies for the text in Japanese).

![スクリーンショット 2023-10-10 16 38 29](https://github.com/amazon-connect/amazon-connect-streams/assets/34177860/471db06d-2afc-4e42-a331-606c7ec33cb0)

**Comment by andywang219** [comment]
Closing ticket, please open if you have any further questions

**Comment by andywang219** [comment]
@glemin5011. In addition, we are aware of the "Request denied because the embedded..." error and are working on a fix for that.

**Comment by MHamza8070** [comment]
@andywang219  "Request denied because the embedded..." when we can expect the fix of this issue?

**Comment by jwal1414** [comment]
If you embed the CCP via streams (for example, in Salesforce) and your agents never log in directly to the Connect site, you'll run into the "request denied because the embedded" issue. We found a workaround, which is to have the agent log in at least once to Connect directly. After that, the third party workflow in the embedded CCP works as expected.

It's not a great work-around, but unsure how you can deal with this at a code-level as it sort of makes sense that Chrome wouldn't take a third party cookie for site the end user hasn't interacted with at top level, but I'm not a expert. Good luck and looking forward to a fix.

**Comment by jwal1414** [comment]
> @glemin5011. In addition, we are aware of the "Request denied because the embedded..." error and are working on a fix for that.

@andywang219 is there an update or timeline with respect to resolution of this issue?

**Comment by agroblervf** [comment]
Referring to @jwal1414 comment, as a temporary workaround for "Request denied because the embedded..." error we’ve implemented an approach where a Connect console will pop up in a separate browser tab and we will instruct the agents to interact with that page (a click anywhere on the page is sufficient), then close that tab before proceeding onto the approval banner and subsequent browser’s Allow/Block popup.
Here’s a draft code example of this implementation:

```
    let requestStorageTimeout;
    const waitForGrantedStatus = 2000; // (ms) to receive storageAccess onGrant event

    connect.storageAccess?.onRequest({
        onInit: (event) => {
            // if onGrant event doesn't trigger within the timeout, 
            // we need to refresh the top-level context cookie
            // and show the banner within the CCP container
            requestStorageTimeout = window.setTimeout(() => {
                // open the Connect console a new, separate tab, so it gets a top-level context
                // note: user needs to click anywhere in the page
                window.open(getConnectUrl(), "_blank");
            }, waitForGrantedStatus);
        },
        onDeny: () => {
            // after the agent denied the permission
            logger.warn(logStamp("storageAccess - user denied permission"));
            window.clearTimeout(requestStorageTimeout);
        },
        onGrant: () => {
            // after the agent allowed the permission
            logger.log(logStamp("storageAccess - user granted permission"));
            window.clearTimeout(requestStorageTimeout);
        }
    });
```
Although this approach works and the agent would only need to perform it once every 30 days we were wondering if there’s a better way of doing it? @andywang219 , is there something you’re working on to include this top-level interaction flow?

**Comment by csesta-tsa** [comment]
> @glemin5011. In addition, we are aware of the "Request denied because the embedded..." error and are working on a fix for that.

Wondering how this fix is coming along?

**Comment by Christian-Sesta** [comment]
> @glemin5011. In addition, we are aware of the "Request denied because the embedded..." error and are working on a fix for that.

Just wondering how this fix is progressing?
