### ISSUE TITLE
[Urgent] CCP automatically un-muting Agents

### ISSUE THREAD

**Issue by alexgurr** [amazon-connect/amazon-connect-streams#785]
**This is an _urgent_ issue. The agent impact here is very high as agents don't realise they've been unmuted. There is no obvious workaround at the moment and we're having to notify customers as we have no control over the CCP version embedded in the iframe**

---

It appears the CCP has pushed a release that has now impacted all application using connect streams, with an embedded CCP using `initCCP`. This has been tested in our app, a barebones app with just `initCCP` and even using the browser console/window connect with the `awsapps.com` CCP directly.

**Problem**
The CCP automatically unmutes the Agent, several seconds after a call to mute the agent using `agent.mute()`.

**Steps to Reproduce:**

- Init the CCP
- Use the connect streams method `agent.mute()`
- Observe in the console + visually in the CCP that the agent becomes unmuted after a few seconds

**Trying to find the issue:**
_Nothing in any of our app source code calls unmute, as mentioned above, this is reproducible on the AWS connect website directly._

Overriding minified files (the main.js chunk in the CCP react app), I've tracked down the following method calling unmute in the `SoftphoneContactService` file (minified):

```
 syncLocalAndRemoteMute() {
    const e = this.getContactContext()
      , t = e.currentContactState.isOnMute
      , n = e.currentContactState.isSoftphoneEnabled
      , a = this.getAgentConnection();

    a && a.isMute !== t && (n ? this.service.muteToggle(a.isMute) : this.updateContactContext({
        isOnMute: a.isMute
    }))
}
```

This consistently calls `this.service.muteToggle(false)` as the connection mute status is always `false` and the local mute status is `true`.

Interestingly in an old copy of the CCP source code this method looked like this:

```
  syncLocalAndRemoteMute() {
        if (this.isMultiparty()) {
            const context = this.getContactContext();
            const isOnMute = context.currentContactState.isOnMute;
            const isSoftphoneEnabled = context.currentContactState.isSoftphoneEnabled;
            const agentConnection = this.getAgentConnection();
            if (agentConnection && agentConnection.isMute !== isOnMute) {
                if (isSoftphoneEnabled) {
                    this.service.muteToggle(agentConnection.isMute);
                } else {
                    this.updateContactContext({
                        isOnMute: agentConnection.isMute
                    });
                }
            }
        }
    }
```

It looks like the check for multi party has been removed and this method now runs far more often, including throughout normal calls.

**Comment by alexgurr** [comment]
Interestingly the above `if (this.isMultiparty()) {` line of code seems to have made its way back in to the latest CCP version, fixing the issue.

**Comment by andywang219** [comment]
@glemin5011 Are you still experiencing this issue?

**Comment by andywang219** [comment]
Please reopen ticket if you are still experiencing this issue

**Comment by MHamza8070** [comment]
@andywang219  I am facing same issue, I have even upgraded to latest streams version. My scenario is I do a conference and during conference if i mute the agent, I am getting unmute event after sometime from amazon connect streams in agent events.

**Comment by MHamza8070** [comment]
@alexgurr  can you please reopen because I am facing the same behavior during conference agent unmuted automatically as we are getting unmute events in agent events amazon connect streams.
