### ISSUE TITLE
Rejecting a contact doesn't trigger onMissed, onEnded or onError

### ISSUE THREAD

**Issue by alexgurr** [amazon-connect/amazon-connect-streams#792]
As per the docs for `onMissed`:

```This is an event which is fired when a contact is put in state "missed" by the backend, which happens when the agent does not answer for a certain amount of time, when the agent rejects the call```

Our current implementation has to rely on `contact.onRefresh` to determine whether a contact is rejected, which is now beginning to cause issues. None of the callbacks on a contact are called after a contact is rejected.

Is this a bug or is there another way to get a callback for rejected? We are rejecting by calling `contact.reject()`.

**Comment by alexgurr** [comment]
Note, rejected calls seems to trigger `onMissed`, but have an "error" state so it's impossible to know whether they are rejected or missed.

If you look at the CCP, rejecting an incoming call triggers a softphone error and missed state incorrectly.

**Comment by hngan** [comment]
Hey, for CCP, we use the ``onMissed`` API for both missed and rejected contacts. Inside the callback that we pass to ``onMissed`` we check if the contact status is MISSED or REJECTED and determine following actions from there. You can check the contact's status [here](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#contactgetstate--contactgetstatus)

**Comment by alexgurr** [comment]
The state of the contact is always "error" when our `onMissed` handler is called.

**Comment by tannera926** [comment]
You are correct that the contact status is error in some cases when a contact is rejected / missed.

The status for the different contacts are as follows:
1. Missed call: contact status is error, agent connection status is disconnected
2. Rejected call: contact status is error, agent connection status is disconnected
3. Missed chat: contact status is error, agent connection status is disconnected
4. Rejected chat: contact status is error, agent connection status is rejected
5. Missed task: contact status is missed
6. Rejected task: contact status is rejected

If you are handling chat or task contacts, you can differentiate between rejected and missed, however for calls, right now there is no way of differentiating. I will investigate why this is the case and see if a fix can be made.

**Comment by tannera926** [comment]
It looks like this has been the behavior since launch. I will create a backlog task for this, closing the issue in the meantime unless there are other questions.
