### ISSUE TITLE
getAgentConnection().isOnHold() returns false when another agent silently monitors them

### ISSUE THREAD

**Issue by hausermatt** [amazon-connect/amazon-connect-streams#799]
### issue
when an agent is on hold with another connection (caller) and they another agent silently monitors them, the API `getAgentConnection().isOnHold()` will return false.

#### repro
agent 1 receives an inbound call.
put "call" on hold
`contact?.getActiveInitialConnection().hold()`
get hold status
`const isAgentOnHold = contact.getAgentConnection().isOnHold()`
log hold status
`console.log(isAgentOnHold)` -> shows `true`

agent 2 (supervisor) initiates monitoring (we do this using the public API https://docs.aws.amazon.com/connect/latest/APIReference/API_MonitorContact.html)
_agent 2 (supervisor) is now listening in_
from agent 1 CCP/session
`console.log(isAgentOnHold)` -> shows `false`
#### result
agent 1 is still indeed on hold, CCP shows they are on hold, the agent hears the hold music, it's just the API incorrectly returns false

**Comment by hausermatt** [comment]
additionally if an agent (agent 1) is on a multi party call with two other participants (one single third party connect, and agent 1 puts themself on hold, once a supervisor barges in. the call controls change for agent 1 as if they are no on hold but really their connection is still on hold

**Comment by MrBroadie** [comment]
Hiya - I am also experiencing this issue and have raised it with Amazon Connect support. Did you find a fix for this? I have re raised it as an issue on here too. https://github.com/amazon-connect/amazon-connect-streams/issues/836.

**Comment by hausermatt** [comment]
> Hiya - I am also experiencing this issue and have raised it with Amazon Connect support. Did you find a fix for this? I have re raised it as an issue on here too. #836.

I do not believe this was resolved, no.

**Comment by MrBroadie** [comment]
Okay. Thanks for coming back to me. Will see what I can do getting this raised with the AWS Support team as this is blocking our customers now.
