### ISSUE TITLE
connection.getMonitorCapabilities() returns undefined

### ISSUE THREAD

**Issue by hausermatt** [amazon-connect/amazon-connect-streams#800]
### issue
`getMonitorCapabilities` according to the docs and type definition should return `MonitoringMode[]`. Instead I am getting undefined, causing undefined errors, and _more importantly_, not returning capability enums that the agent **does** have

#### repro
this reproduction is fairly easy. calling this function will return undefined **unless** you are on an actively monitored or barged-in call. 

ex:
```ts
const agentConnection = contact.getAgentConnection() as connect.VoiceConnection;
const capabilities = contact.getMonitoringCapabilities();
const findSilentMonitor = capabilities.find((c) => c === connect.MonitoringMode.SILENT_MONITOR); /* -> THROWS EXCEPTION CANNOT perform .find() of undefined*/
```

### expected result
first off it should never return undefined as the API is not typed that way.

furthermore, as long as you have an active contact, thus an active agent connection, it should return the monitoring capabilities of that agent, regardless if they are monitoring or barged in. after all, it seems a little counterintuitive that the function to get the agents capabilities is only available _after_ they have performed the action pertaining to the permission.

### other suggestions
it would be very helpful/useful to have an function on the agent API so that capabilities could be fetched without a contact present.

**Comment by hngan** [comment]
Yes, it seems like either this API is named incorrectly/misleading (in other words we only show capabilities based on active state) or we should provide all possible monitoring capabilities of a given agent. We'll look into an update.

**Comment by hausermatt** [comment]
> Hi,
> 
> Thank you for bringing that to our attention. Monitoring capabilities are a property of a connection, not an agent, so we can't have this function on the agent API. As for the `undefined` - The first thing that I noticed is that in your example you have `getMonitoringCapabilities` instead of `getMonitorCapabilities` API. As the correct one is the latter that would explain why you are getting undefined. Can you please confirm that you are calling the right API?
> 
> Another thing I want to mention is that you are using it on the contact, although in documentation we are suggesting using it on `voiceConnection` rather than the contact. My guess is that is the reason you may be getting `undefined`
> 
> Please see [this](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#voiceconnectiongetmonitorcapabilities) for reference.
> 
> Also, I would recommend using [isSilentMonitorEnabled](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#voiceconnectionissilentmonitorenabled) and [isBargeEnabled](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#voiceconnectionisbargeenabled) APIs to check whether agent(supervisor) is allowed to change the monitoring mode to one or another state.

I've confirmed we're using the correct function on the correct API. my example is just a typo. we're using typescript, so the ide/compiler is enforcing this anyways
```ts
const agentConnection = contact.getAgentConnection() as connect.VoiceConnection;
const capabilities = agentConnection.getMonitorCapabilities();
const findSilentMonitor = capabilities.find((c) => c === connect.MonitoringMode.SILENT_MONITOR); /* -> THROWS EXCEPTION CANNOT perform .find() of undefined*/
```

I was indeed getting undefined though. at this point it'd just be a smaller fix for your team as that should not return undefined, rather an empty array. or update the type definition so it returns `connect.MonitoringMode[] | undefined`.

**Comment by vpogudina** [comment]
Thank you, we will be updating the type definition with `connect.MonitoringMode[] | undefined`. Meanwhile I'll close this issue, feel free to open a new one if you have questions remaining.
