### ISSUE TITLE
Embedding customer profiles does not set iframe permissions to allow clipboard-write

### ISSUE THREAD

**Issue by ColinMorris83** [amazon-connect/amazon-connect-streams#803]
When embedding the customer profiles in a custom app, all of the copy to clipboard actions don't work, as the iframe is not being configured with the correct permissions.

`Uncaught (in promise) DOMException: The Clipboard API has been blocked because of a permissions policy applied to the current document.`

**Comment by hngan** [comment]
It looks like agent app iframes does not allow Clipboard APIs. Will talk to team to see if this can be added.

**Comment by hngan** [comment]
Added to our latest update in Streams!

https://github.com/amazon-connect/amazon-connect-streams/releases/tag/v2.13.1
