### ISSUE TITLE
" microphone_not_shared" error on macOS Sonoma (Version 14) Causing Missed Calls in Softphone

### ISSUE THREAD

**Issue by SuruthiFruma** [amazon-connect/amazon-connect-streams#805]
**Issue Summary:**

- Following the recent update to macOS Sonoma version 14, some of our users have reported encountering  "microphone_not_shared" error within the softphone application. 
- We also confirmed that microphone is enabled for them in their device as well as in their site settings of the browser .
- This issue is having a major impact on the user experience, leading to incoming calls being automatically categorised as missed calls.
- Also, few of our users are experiencing significant audio choppiness, adversely affecting the overall communication experience.

**Additional Information:**
![Screenshot 2023-11-14 at 7 36 49 PM](https://github.com/amazon-connect/amazon-connect-streams/assets/118813322/5dd41a5d-7352-4ee8-8ce3-61026cc1f863)

We request to provide a possible fix or workaround for this issue

**Comment by Solomon-m** [comment]
Hi @jagadeeshaby 
Good day. 
We are also facing this issue. Any suggestion on this issue would be helpful for us.

**Comment by hantaliu** [comment]
+1, we've seen this error too

**Comment by SuruthiFruma** [comment]
**Update** 
Our users have ceased encountering the issue in MacOS Sonoma 14.2.1.
However, it has resurfaced with the release of version 14.3.1.
