### ISSUE TITLE
Barge In Live Monitoring

### ISSUE THREAD

**Issue by jcnovoa** [amazon-connect/amazon-connect-streams#816]
Based on guidance provide here:
https://github.com/amazon-connect/amazon-connect-streams/issues/646
I am calling the [MonitorContact API](https://docs.aws.amazon.com/connect/latest/APIReference/API_MonitorContact.html)
From Lambda, but I get this error (which normally happens when initiating live monitoring from the "real-time metrics" interface if the supervisor is not logged via the CCP)
Response
{
  "errorType": "ServiceQuotaExceededException",
  "errorMessage": "Service quota has been exceeded",
  "trace": [
    "ServiceQuotaExceededException: Service quota has been exceeded",
    "    at de_ServiceQuotaExceededExceptionRes (/var/runtime/node_modules/@aws-sdk/client-connect/dist-cjs/protocols/Aws_restJson1.js:13686:23)",
    "    at de_MonitorContactCommandError (/var/runtime/node_modules/@aws-sdk/client-connect/dist-cjs/protocols/Aws_restJson1.js:10400:25)",
    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "    at async /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24",
    "    at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20",
    "    at async /var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46",
    "    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26",
    "    at async file:///var/task/index.mjs:16:18"
  ]
}

I assume is because it can't correlate the request with the supervisor attempting to barge-in/live-monitor and the agent (user id) for that interaction (contact id)
Is there / will there be a way to add a "UserId" parameter for the supervisor initiating the monitoring here?
const input = { // MonitorContactRequest
  InstanceId: "STRING_VALUE", // required
  ContactId: "STRING_VALUE", // required
  UserId: "STRING_VALUE", // required
  AllowedMonitorCapabilities: [ // AllowedMonitorCapabilities
    "SILENT_MONITOR" || "BARGE",
  ],
  ClientToken: "STRING_VALUE",
};

the scenario is that live monitoring could be programatically queued by a processor vs needing to be initiated by the supervisor form the CCP.
Almost as if queueing the live-monitoring for supervisors, based on volume of calls.
Perhaps we could enhace this by adding a queue id instead and initiate the request to live monitoring that way

**Comment by tannera926** [comment]
This is an issue with the AWS SDK, please reach out to AWS Support if this is still an issue.

To answer your other questions, UserId is a parameter being passed in to the monitorContact API, see here: https://docs.aws.amazon.com/connect/latest/APIReference/API_MonitorContact.html.
