### ISSUE TITLE
Chrome "third-party cookies: limited" status detection

### ISSUE THREAD

**Issue by uhanchar** [amazon-connect/amazon-connect-streams#823]
Recently Google Chrome started testing Third-party cookies allowing removal from Chrome. As far as I'm concerned, Amazon Connect Streams API doesn't detect this option (it detects that Third-party cookies are blocked or not, but not limited), preventing login into the application. 

<img width="314" alt="image" src="https://github.com/amazon-connect/amazon-connect-streams/assets/75665492/a951f779-6e80-47d9-806c-cc3eb54f4ecf">

How can I detect this Third-party cookies option (limited)? 
If Amazon Connect Streams API does not support it, it would be great to add support for detecting this status.

**Comment by hngan** [comment]
Hey our team is already aware and are tracking the third party cookie deprecation issue with Chrome. Can you explain what exactly you're experiencing here?

Reference: https://docs.aws.amazon.com/connect/latest/adminguide/admin-3pcookies.html

**Comment by bretticus-mc** [comment]
Closing as we're actively tracking Chrome's third-party cookie deprecation
