### ISSUE TITLE
When embedding both customer profiles + cases, the connect case button does nothing 

### ISSUE THREAD

**Issue by alexgurr** [amazon-connect/amazon-connect-streams#824]
A profile is matched and the current call is selected in connect streams. However, clicking the button highlighted in red below doesn't do anything. There are no errors or logs specific to this interaction. Any ideas?

```
connect.agentApp.initApp(
  "customerprofiles", 
  "customerprofiles-container", 
  connectUrl + "/customerprofiles-v2/"
);

connect.agentApp.initApp(
  "cases", 
  "cases-container", 
  connectUrl + "/cases/agent-app/"
);
```

<img src="https://puu.sh/JYpfb/7f4d9510ef.png" width=500 height="auto" />

**Comment by alexgurr** [comment]
I can appreciate the above, but when showing customer profiles (which is supported) isn't having a button that does nothig extremely confusing to users? There appears to be no way of hiding it. Our customers don't know cases is supported. 

Any ideas?

**Comment by tannera926** [comment]
Can you test this without cases enabled? Does the connect case button still show up in Customer Profiles without cases enabled?

**Comment by alexgurr** [comment]
Yes, you are correct, the connect case button is hidden when cases is not enabled, although the cases tab/section remains there.

**Comment by markrusell-wr** [comment]
Is there any plans to support cases via streams in the near future?
