### ISSUE TITLE
Embedded Cases App - Add Case Button Is Always Disabled

### ISSUE THREAD

**Issue by alexgurr** [amazon-connect/amazon-connect-streams#825]
Even with an active contact, the create case button is always disabled. This works fine in the v2 agent workspace, but when embedding these modules/widgets in our overlay, we experience the above behaviour. There are no errors or logs specific to this interaction. Any ideas?

```
  connect.agentApp.initApp(
	"customerprofiles", 
	"customerprofiles-container", 
	connectUrl + "/customerprofiles-v2/"
);

connect.agentApp.initApp(
	"cases", 
	"cases-container", 
	connectUrl + "/cases/agent-app/"
);
```

![](https://puu.sh/JYpzJ/2a266c75eb.png)

**Comment by tannera926** [comment]
Cases is not supported by Streams, references to cases were mistakenly added to the documentation and are being removed. Our recommendation to use cases is to call the public API directly.
