### ISSUE TITLE
Swapping between participants on hold when a manager is monitoring

### ISSUE THREAD

**Issue by MrBroadie** [amazon-connect/amazon-connect-streams#836]
When in a conference call with two agents and a customer and a manager is monitoring I am unable to press the swap button to swap between the customer and the other agent as pressing the button more than once brings every participant into the call OR does nothing at all.

Steps to recreate ->  
1:
 - Customer is on hold as I have transferred to another agent.
<img width="319" alt="Screenshot 2024-01-24 at 10 11 41" src="https://github.com/amazon-connect/amazon-connect-streams/assets/80988130/3b25d615-c69b-42bb-bd90-1514dca268f4">

<img width="312" alt="Screenshot 2024-01-24 at 10 11 55" src="https://github.com/amazon-connect/amazon-connect-streams/assets/80988130/20f8a4a9-c863-4334-a10c-76608b829dc0">

<img width="282" alt="Screenshot 2024-01-24 at 10 12 02" src="https://github.com/amazon-connect/amazon-connect-streams/assets/80988130/1ddd334d-4d71-48d4-a45b-8eedc6ddda51">

2:
 - As an agent I press swap to bring the customer off hold and put the other agent on hold.

<img width="319" alt="Screenshot 2024-01-24 at 10 13 08" src="https://github.com/amazon-connect/amazon-connect-streams/assets/80988130/588925f6-f092-4bb2-b39b-68f8976ace0c">

<img width="318" alt="Screenshot 2024-01-24 at 10 13 16" src="https://github.com/amazon-connect/amazon-connect-streams/assets/80988130/825d0c67-dc2c-4a2b-9277-777e66f80408">

<img width="283" alt="Screenshot 2024-01-24 at 10 13 23" src="https://github.com/amazon-connect/amazon-connect-streams/assets/80988130/619d8697-1316-4f06-88a2-600a5c291dc8">

At this point one of two things will happen if I press the swap button again. The first is all users will be brought off of hold and placed into the connected state, the other is nothing, the user on hold will stay on  hold.

**Comment by hngan** [comment]
I was able to reproduce the issue and it does appear to be a bug. I'm going to bring this up to internal teams and see how quickly we can resolve this issue. Is this issue a huge blocker?

**Comment by MrBroadie** [comment]
It is a blocker. A customer has raised this as an issue with the connect team so hopefully there will be visibility for this bug internally.
