### ISSUE TITLE
CHANGELOG.md not updated

### ISSUE THREAD

**Issue by karl-mentzer-vf** [amazon-connect/amazon-connect-streams#840]
Hi AWS Team,

The CHANGELOG.md does not appear to have been updated since release 2.4.5 and Streams is now on release 2.13.1. 

Can this please be updated and maintained please as a standard practice?

I am having to go through all the releases to try find where "allowEarlyGum" was added in the init CCP method, which appears to be 2.9.0 from the notes on the release itself.

**Comment by tannera926** [comment]
Thanks for flagging this, we just updated the CHANGELOG.md, so it should match the release log.
