### ISSUE TITLE
AfterContactWork Status triggers an infinite loop of errors

### ISSUE THREAD

**Issue by DanielHuelse** [amazon-connect/amazon-connect-streams#844]
Hi, we have implemented a custom ccp. On entering the after-contact state an infinite loop of errors is generated. Can you give guidance what the cause is?

amazon-connect-streams: v2.13.1

![error_message](https://github.com/amazon-connect/amazon-connect-streams/assets/42340264/6a6b0cbe-2183-4a1c-8e40-b864a3fab882)

**Comment by hngan** [comment]
Sorry, but there's nothing that I can gather from this... Where is the error coming from (stack trace would be nice)? What Streams APIs were you calling here? Can we get CCP logs for this? Sorry, I can't draw anything from a screenshot.

**Comment by DanielHuelse** [comment]
I get these errors when entering the After Contact Work state after successfully connecting to an incoming call. What changed from the original post is, that the error occurs at least not infinte anymore, but I get still ~4 errors per call.

The issue is also present when using the native softphone that is embedded in the Amazon Connect Console itself, therefore I would assume this has nothing to do with calling any API methods.

The source of the error is originated in a script that is delivered with the embedded iframe:
![error-source](https://github.com/amazon-connect/amazon-connect-streams/assets/42340264/bcf0ad73-fb14-4c06-9eb8-ca56ab087059)

**Comment by tannera926** [comment]
Could you add exact reproduction steps in both the native environment as well as in your custom environment? Additionally, a video of the reproduction in the native environment would be helpful, as well as HAR files in both cases and CCP logs.

**Comment by DanielHuelse** [comment]
Originally, the steps to trigger this was to make an inbound call, and then close the contact to enter after-contact work. Then the browser console showed the errors mentioned in the first post. 

But testing this again today, I was not able to reproduce this anymore. Both custom and native phone working as intended. So, I guess it was fixed?

Therefore, I will close this issue for now.

**Comment by DanielHuelse** [comment]
Originally, the steps to trigger this was to make an inbound call, and then close the contact to enter after-contact work. Then the browser console showed the errors mentioned in the first post. 

But testing this again today, I was not able to reproduce this anymore. Both custom and native phone working as intended. So I guess it was fixed?

Therefore, I will close this issue for now.
