### ISSUE TITLE
Chat drops after browser refresh

### ISSUE THREAD

**Issue by SaqibOctave** [amazon-connect/amazon-connect-streams#846]
I have embedded the amazon connect streams in my angular project. I have deploy the custom UI for the messages using amazon connect streams and amazon connect chat-js. 
![image](https://github.com/amazon-connect/amazon-connect-streams/assets/110086158/eaf4b496-5119-48ad-b252-ca15671fe4a0)
Everything works perfect i can send messages and receive messages through streams. But When i Refresh my browser the chat drops automatically. Can anyone help me where i am doing wrong ?

**Comment by AnilSonix** [comment]
It started happening recently, earlier the only the Voice channels ended on browser refresh, Chat channel used to work fine after refresh.
