### ISSUE TITLE
No typedef for connect.core.getEventBus()

### ISSUE THREAD

**Issue by jpeckAMC** [amazon-connect/amazon-connect-streams#847]
Hey Amazon Connect Team!

I'm attempting to migrate our `amazon-connect-streams` dependency from version 1 to 2 (currently using `2.13.1`). In version 1, we would access the `EventBus` by calling `connect.core.getEventBus()`, but after migrating to version 2, the compiler complains that the function is not defined. 

Is there any documentation or other resources that can explain why this was changed and what new usage is expected, or does it just need to be added to the types file for TypeScript compatibility?

**Comment by peckjj** [comment]
Apologies, I see that there is a PR that has been awaiting reviewal for some time now (#666 ). I can work around the issue with some type casting for now and will close the issue!
