### ISSUE TITLE
Custom Views is not working in Cutsom CCP

### ISSUE THREAD

**Issue by nayabrasool4910** [amazon-connect/amazon-connect-streams#849]
I am trying to use Views in Custom CCP but I am getting Loading View as shown in below image after call connecting to agent. Need to change anything in the code. Advance Thanks.
![views](https://github.com/amazon-connect/amazon-connect-streams/assets/52395438/6681b9d4-9edd-43b9-b5b5-c56498e776e5)

`connect.agentApp.initApp(
      "customviews",
      "customviews-container",
      connectUrl + "/stargate/app",
      { style: "width:650px; height:600px;" }
    );`

**Comment by vvgoyal** [comment]
Hi @nayabrasool4910 
We introduced the new stuff in the recent release. here is the documentation to load view with new stuff https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#connectagentappinitappname-containerid-appurl-config.
