### ISSUE TITLE
login popup doesnt always open

### ISSUE THREAD

**Issue by AnilSonix** [amazon-connect/amazon-connect-streams#852]
Most of the time login pop works and ccp panel gets mounted.
But sometimes, I encounter this issue where login pop doesn't open
. In console, errors are shown that iframe can't be mounted due x frame options, even though it's added in approved origins.

Sometime , I clear cookies then it works and sometime it doesnt.
Not sure why it happens

**Comment by tannera926** [comment]
This is most likely due to the browser getting refreshed before the agent has logged in, which is explained here: https://github.com/amazon-connect/amazon-connect-streams/issues/858.

We are actively working on a fix for this.

**Comment by bretticus-mc** [comment]
Hello, this issue is resolved with the latest version of Streams (2.14.1).
