### ISSUE TITLE
Issue with Amazon Connect Quick Connects functionality

### ISSUE THREAD

**Issue by lucas-capriata-ctr** [amazon-connect/amazon-connect-streams#854]
I am encountering an issue with the functionality of Amazon Connect Quick Connects, and I require assistance in resolving it.

When utilizing the CCP iframe and selecting a contact to transfer using the "quick connect" button, the "end call" button becomes disabled, accompanied by a banner indicating "You cannot end chat...". However, when employing the Amazon Connect Streams API method `contact.addConnection()`, neither the button is disabled nor is there any banner displayed. Consequently, agents are permitted to terminate the chat while the quick connect logic remains active in the background.

Could you please advise if there are additional steps or configurations required to ensure proper functionality in this scenario?

Thank you for your attention to this matter.

**Comment by flaviut** [comment]
UI while transferring via Connect UI:

![image](https://github.com/amazon-connect/amazon-connect-streams/assets/5213469/f8e889e3-3a5a-45bb-a46c-078dfa473365)

UI while transferring via amazon connect streams API, you can still click the end chat button while the transfer is in progress:

![image](https://github.com/amazon-connect/amazon-connect-streams/assets/5213469/e9d29c32-5942-4b76-8b96-b6903922049b)

**Comment by tannera926** [comment]
We disable the end chat button during a transfer in the CCP UI to avoid a race condition between ending the chat and transferring it (which could potentially cause a chat to be ended before it is transferred).

When using Streams APIs to customize your CCP experience (such as `contact.addConnection()`) it is up to the customer how they want to implement these APIs and if they want to put additional safeguards around them, such as the safeguard we added to our out of the box UI to avoid ending a chat during a transfer.

You can add a check in your custom logic after you call `contact.addConnection()` to disable the end chat button until the contact has state `ended`. This can be done by checking if `contact.getState().type === 'ended'`.

**Comment by lucas-capriata-ctr** [comment]
@tannera926 Thanks for your response. And what would be the method to disable the end chat button? Cause I'm not talking about a custom CCP implementation
