### ISSUE TITLE
Warnings popup when running 3rd party applicaiton locally

### ISSUE THREAD

**Issue by jiaxin-liu-webjet** [amazon-connect/amazon-connect-streams#859]
We have added our own application as 3rd party application instance and it is currently running without any warning. We can successfully open the tab in agent workspace and access to the page that our application redirects to. 
However, when we run it locally and also add it as another 3rd party application, when we open the application in agent workspace or open the url in local browser, there is always some warnings related to Amazon Connect node_module. The warnings (warnings.txt) and the main part of our code is also attached (TsaOpener.txt). Just want to know if it is something we can ignore, or there is indeed something that we need to change? The 
Contact Center Instance ARN: arn:aws:connect:ap-southeast-2:975050157807:instance/8eebd28b-8b67-4c0a-b2cb-a8b6779ec1a2
Please select the Integration: Other

**Comment by vs-amzn** [comment]
It sounds like you're using the Amazon Connect SDK... is that right? If so, please open up an issue with that repo.

https://docs.aws.amazon.com/agentworkspace/latest/devguide/what-is-service.html
https://github.com/amazon-connect/AmazonConnectSDK

**Comment by bretticus-mc** [comment]
Sounds like this is for an issue with the Connect Agent Workspace. You can open a [support ticket ](https://github.com/amazon-connect/amazon-connect-streams/issues/894) and we can route it to the Agent Workspace team.
