### ISSUE TITLE
[Question] CCP for device settings

### ISSUE THREAD

**Issue by kimhanmiru** [amazon-connect/amazon-connect-streams#861]
You want to change the device in the softphone settings. You want to set the ringer to the speaker and the customer's voice to the headset.
I'm developing a custom ccp, and the ccp doesn't give me an error when I get the device id,

In the custom ccp, I get an error because the device IDs don't match.
Error message in developer mode 
"RingtoneEngineBase.setOutputDevice failed: audio.setSinkId() failed with error NotFoundError: Requested device not found"

I think the deviceId is in error, if you have any guide that can help, please share.

(Additionally) When I compare, I see that the device ID from which I get the device list from custom ccp is different from the device ID I get from stream.js.

Is there any function to get the deviceList using stream.js ?

**Comment by kimhanmiru** [comment]
When I compare, I see that the device ID from which I get the device list from custom ccp is different from the device ID I get from stream.js.

Is there any function to get the deviceList using stream.js ?

**Comment by vs-amzn** [comment]
In your custom CCP, before you set the set your audio devices, you should validate that the device you intend to set is indeed available to use. One way you can do that is by using `navigator.mediaDevices.enumerateDevices()`. This will return all devices available for use. You can check if the device you want to set is in that list and if it is, then you can set it.

**Comment by seiyako** [comment]
Hi @kimhanmiru , have you tried [connect.core.getFrameMediaDevices()](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#connectcoregetframemediadevices) API? 

The deviceId is expected to be unique per document/frame (see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo)), so you must capture the device list from the context that handles the softphone. If you allow CCP iframe to handle softphone, use the connect.core.getFrameMediaDevices() API. If you use RTCJS and handles softphone on your website context, use navigator.mediaDevices.enumerateDevices().
