### ISSUE TITLE
[Errors] When a supervisor is monitoring a call with multi party enabled, if an agent tries to swap or transfer to a quick connect, it fails

### ISSUE THREAD

**Issue by alexgurr** [amazon-connect/amazon-connect-streams#862]
This occurs in the CCP directly, as well as when we try to do this in our overlay product.

Reproduce by:

- Agent one is in a call
- Supervisor monitors the call from the connect console
- Agent one tries to transfer to a new quick connect or "swap" the connection.

Transferring to a new quick connect/adding an additional conference party member:

```
connect-streams-min.5d6049a5.js:1 
 [2024-04-11T01:46:27.679Z] [ERROR] [af21a16b-5a80-48c6-b7c9-df1faa536474]: Failed to Transfer voice
connect-streams-min.5d6049a5.js:1 
 [2024-04-11T01:46:27.674Z] [ERROR] [af21a16b-5a80-48c6-b7c9-df1faa536474]: 'createAdditionalConnection' API request failed
connect-streams-min.5d6049a5.js:1 
 [2024-04-11T01:46:27.674Z] [ERROR] [af21a16b-5a80-48c6-b7c9-df1faa536474]: 'createAdditionalConnection' API request failed
connect-streamf52e47…ae57d44d4b.js:17148 
 [2024-04-11T01:46:27.674Z] [ERROR]: 'createAdditionalConnection' API request failed
```

This also fails when swapping (`toggleActiveConnection`) with similar errors.

<img width="317" alt="Screenshot 2024-04-11 at 9 46 59 am" src="https://github.com/amazon-connect/amazon-connect-streams/assets/4161867/dfcb29f8-0db3-4031-acc3-635d7122af5a">

Consistently reproducible.

**Comment by vvgoyal** [comment]
Hi @alexgurr, Can you provide the CCP logs?

**Comment by alexgurr** [comment]
[agent-log (11).txt](https://github.com/amazon-connect/amazon-connect-streams/files/14973105/agent-log.11.txt)

**Comment by tannera926** [comment]
I'm confused about what's happening here. Looking at the logs and the agent snapshot, it looks like there are 3 participants on this call and none of them are in monitoring mode. Could you send a video of what this looks like?

**Comment by stevenasi** [comment]
@tannera926 I've attached a video of the issue. 

Uploading Screen Recording 2024-05-14 at 11.00.37 am.mov…

**Comment by stevenasi** [comment]
@tannera926 I've attached a video of the issue. 

https://github.com/amazon-connect/amazon-connect-streams/assets/35161418/9a6afe1f-c378-47c1-a105-b1e4b5b57bad
