### ISSUE TITLE
contact.onRejected is not available

### ISSUE THREAD

**Issue by thavamm** [amazon-connect/amazon-connect-streams#863]
as per the latest update from AWS document, we will be receiving callback method for "Reject", but there is no onRejected method available in this current version 2.14.1

Can you please when this feature will be available?

**Comment by tannera926** [comment]
The callback method from "Reject" is still onMissed. Is there documentation that explicitly states we were adding an onRejected method? If so, could you please link it?

This thread explains how to differentiate between rejected and missed for different contact types: https://github.com/amazon-connect/amazon-connect-streams/issues/792
