### ISSUE TITLE
Agent mute button is stuck and wrongly showing unmute agent when agent is in a conference and silently monitored by a supervisor 

### ISSUE THREAD

**Issue by stevenasi** [amazon-connect/amazon-connect-streams#865]
When an agent is in conference and a supervisor starts silently monitoring the conference, the agent mute button is stuck and can't be toggled and even that it's showing the agent as unmuted, it's muted and can't be heard by any other participants. 

Trying to toggle the button will return a success action but it's not doing anything. Video attached with agent logs 

https://github.com/amazon-connect/amazon-connect-streams/assets/35161418/59f293ab-ab82-4d25-bb1d-948138b53813
[agent-log (2).txt](https://github.com/amazon-connect/amazon-connect-streams/files/15021381/agent-log.2.txt)

**Comment by alexgurr** [comment]
Hi connect team -- this to me is a P1. Agents cannot be heard by customers and the agent does not know they are being monitored understand what's happening.

**Comment by hngan** [comment]
We're able to reproduce this issue from our end. Will need to sync across teams to do a deeper investigation. Will come back with an update when we find more details/potential fixes

**Comment by andywang219** [comment]
We have a team that is aware of this issue and are actively working on a fix. They expect to have the changes rolled out to all regions by 07/31.

The issue is seen when silent monitoring is initiated on an agent who is already muted during a conference call.

**Comment by Studodge** [comment]
Comment at https://github.com/andywang219 stated this would be resolved by 07/31 but was auto closed without any further comments prior to this. Has this issue been resolved?
