### ISSUE TITLE
Request to add Contact.getChannelContext to index.d.ts

### ISSUE THREAD

**Issue by 9bits** [amazon-connect/amazon-connect-streams#866]
The current [index.d.ts](https://github.com/amazon-connect/amazon-connect-streams/blob/ae2a7c06cb326d611a5b29c34c1891e7831ffdf1/src/index.d.ts#L1474) does not contain Contact.getChannelContext even though it is usable and released.

Current Implementation:
* https://github.com/amazon-connect/amazon-connect-streams/blob/ae2a7c06cb326d611a5b29c34c1891e7831ffdf1/src/api.js#L983-L985

Documentation:
* https://github.com/amazon-connect/amazon-connect-streams/blob/ae2a7c06cb326d611a5b29c34c1891e7831ffdf1/Documentation.md?plain=1#L1495

Changelog (Added in v2.2.0):
* https://github.com/amazon-connect/amazon-connect-streams/blob/ae2a7c06cb326d611a5b29c34c1891e7831ffdf1/CHANGELOG.md?plain=1#L21

**Comment by hngan** [comment]
Ahhh yes, looks like this was a miss from our end. We will add this to our list of changes for our next Streams version.
