### ISSUE TITLE
WebRTC - Failing to join video session - AudioJoinedFromAnotherDevice

### ISSUE THREAD

**Issue by Juzziee** [amazon-connect/amazon-connect-streams#867]
We're having when integrating video calling into our customer interface. 
Shortly after video input begins in the webrtc call, the agent is removed from the chime session with the error "AudioJoinedFromAnotherDevice".

As far as I can tell this is because the default CCP is joining the meeting as well.
Has anyone found a proper work around for this? 

We are initialising the session using the below;

```
var videoConnection = await contact
  .getAgentConnection()
  .getVideoConnectionInfo();
const logger = new ChimeSDK.ConsoleLogger(
  "ChimeMeetingLogs",
  ChimeSDK.LogLevel.INFO
);
var chimeMap = new Map();
meetingSession = await new ChimeSDK.DefaultMeetingSession(
  new ChimeSDK.MeetingSessionConfiguration(
    videoConnection.meeting,
    videoConnection.attendee
  ),
  logger,
  new ChimeSDK.DefaultDeviceController(logger)
);

await meetingSession.audioVideo.start();
```

       
A work around I've found is to check the session code on the audioVideoDidStop event. If the code matches "AudioJoinedFromAnotherDevice", then you can simply start the audioVideo session again. 

```
audioVideoDidStop: (sessionStatus) => {
  console.log("AudioVideoDidStop: " + sessionStatus);
  if (sessionStatus == "The attendee joined from another device.") {
    WriteLog(
      "error",
      "Chime: AudioVideoDidStop: The attendee joined from another device. - Restarting session",
      null
    );
    meetingSession.audioVideo.start();
  }
}
```

Has anyone else run into the same issue and if so, did you find a better solution?

**Comment by hngan** [comment]
Did you set `allowFramedVideoCall` to false in `initCCP`? This should prevent CCP from handling the video call logic. [reference](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#connectcoreinitccp)

**Comment by Juzziee** [comment]
You're totally right here. Turns out I had it enabled. 
Disabling the framed video fixed the issue. 

Thanks @hngan !
