### ISSUE TITLE
OnRefresh is invoked after a contact has ended showing both the initial and third party connections as active

### ISSUE THREAD

**Issue by paolo-botta-salesforce** [amazon-connect/amazon-connect-streams#868]
I recorded a video demonstrating the issue
https://drive.google.com/file/d/1Hk75gZZE_bvqNVIF0VNmvljCPX1KmHav/view?usp=drive_link
This is impacting Salesforce's integration. Please prioritize it accordingly.

**Comment by hngan** [comment]
Who did you end the call for here? I assume that this is normal behavior because in the scenario where customer (initial party) calls agent and agent creates conference call with agent 2 (third party), when the original agent ends the call, they are the only one that disconnects from the conference call, both the third party and the initial party can still be connected after agent leaves (leaving both initial and third to be considered active).

**Comment by paolo-botta-salesforce** [comment]
@hngan Ok but then how can we tell that the agent left the call? Event contact.getAgentConnection().isActive() returns true

**Comment by andywang219** [comment]
Could you not use the contact state as a way to check if the agent is connected? For example, if the contact state is  `ENDED`, then that would mean the agent is no longer handling it.

**Comment by paolo-botta-salesforce** [comment]
I added that check as a well for now. I still think it's a bug that all connections are marked active

**Comment by vpogudina** [comment]
<img width="1503" alt="Screenshot 2024-05-13 at 1 19 03 PM" src="https://github.com/amazon-connect/amazon-connect-streams/assets/87140518/bfa915b5-7f3b-4199-b2bb-c2d21a436ace">
I've tried to reproduce that behavior and I can't get what you are describing. I've checked the connections and as I can see in three party call - agent connection on the side of the agent disconnected from the call is correctly marked disconnected, on the remaining agent side - correctly marked 'connected', and the agent that has disconnected (represented as outbound connection) correctly marked 'disconnected'
As you can see on the screenshot - contact.getAgentConnection().isActive() returns true for active agent and false for the disconnected agent. 
Please give us more details, so I can investigate further if it is intended behavior or not.

**Comment by paolo-botta-salesforce** [comment]
I just reproduced the issue again. Is the multi-party toggle enabled in the instance you're using to test? Also which version of streams are you using? I believe I tested on 2.3.7
