### ISSUE TITLE
Adjusting audio output and input level

### ISSUE THREAD

**Issue by voipnewb** [amazon-connect/amazon-connect-streams#87]
I wanted to adjust the volume sound for the ringtone or any audio source, but currently the available api I found is mute, is there a way I could set the volume level for microphone and speaker?

**Comment by mschersten** [comment]
I would be interested in this as well.  We have a few agents that could use a louder ring, and I handled this by downloading the ringtone and amplifying it in audio editing software, then using that as ringtoneUrl in the init.  We're still workshopping it, and if we decide it's too loud/soft I'll need to make a new file.  A simple ringVolume parameter or something would be great.

**Comment by hfahlbusch** [comment]
There is at least an api for the audio element where you can control the volume property. This allows value [0, 1]. I guess you cannot amplify it more than 100% volume, but if you have a louder ringtone you can reduce the volume if not needed.

**Comment by camstuart** [comment]
I am also getting requests for louder volume during 'in call' conversations, can that be adjusted
