### ISSUE TITLE
Unable to Login with amazon connect Streams (Periority High)

### ISSUE THREAD

**Issue by SaqibOctave** [amazon-connect/amazon-connect-streams#871]
I have embeded the amazon connect with amazon connect streams API, And i am using popup to login in amazon connect. 
But when i Access my EC2 instance URL it sows me the following Error 
![image](https://github.com/amazon-connect/amazon-connect-streams/assets/110086158/490092d1-6859-4dd8-8019-01875ec46958)
I have enter my EC2 instance URL in the approved origins. but still i am facing the same error
Kindly help me to solve this. Its priority is very high

**Comment by bretticus-mc** [comment]
This is looks like it's because the domain you're trying to embed CCP in is not added to the approved origins. Please reference the following [instructions](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#allowlisting).

**Comment by bretticus-mc** [comment]
This is looks like it's because the domain you're trying to embed CCP in is not added to the approved origins. Please reference the following [instructions](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#allowlisting).

**Comment by bretticus-mc** [comment]
Please re-open if that doesn't fix your issue.

**Comment by SaqibOctave** [comment]
@bretticus-mc 
I am using proxy server to make my ec2 URL as a secure URL, When we direct login using the EC2 instance public URL it redirect to the dashboard page but when we go through that proxy server it give me the above errors

**Comment by bretticus-mc** [comment]
If I understand your setup correctly, you need to add the proxy server url you're trying to view embedded CCP in. 

The error is a [CSP frame-ancestors violation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors). CCP gets its CSP frame-ancestors from the approved origins allowlist I mentioned above. That means CCP is being embedded in a page that you have not explicitly allowed and the browser is throwing the error.

**Comment by TheBearF8** [comment]
I show that ccp-v2 returns with Response header Content-Security-Policy:  frame-ancestors  'self' and all approved domains set in AWS Connect.
but when authorize returns the response header Content-Security-Policy:  frame-ancestors is only 'self'
