### ISSUE TITLE
Amazon connect Task flow stopped working

### ISSUE THREAD

**Issue by clarists** [amazon-connect/amazon-connect-streams#874]
I created inbound flow where i added create Task block with Sample Lambda function integration ... before 2 days it was partially working but now it routes to error message.

**Comment by vs-amzn** [comment]
What is the behavior / UX that you're seeing on your custom ccp? What in streams is surfacing the error?

**Comment by vvgoyal** [comment]
@clarists Can you share the error message you are seeing?

**Comment by vvgoyal** [comment]
Thanks for the update. I will close the ticket.
