### ISSUE TITLE
amazon instance integrate with SAML  popup window can not close

### ISSUE THREAD

**Issue by beiyue** [amazon-connect/amazon-connect-streams#875]
I use as follow method to handle IDP login request and finally login successful. Even though I have set the parameters include as 'loginPopup:true' and 'loginPopupAutoClose: true' and 'loginOptions:{autoClose: true}'  but popup window continue keep on popup status and can not auto close.  I don't know how to resolve it.

 try {
          // initialize the ccp
          connect.core.initCCP(containerDiv, {
            ccpUrl: "", // REQUIRED
            loginUrl:"https://d-xxxxx.awsapps.com/start/#/saml/default/Amazon%20Connect%20Agent/ins-xxx",
            loginPopup: true, // optional, defaults to `true`
            loginPopupAutoClose: true, // optional, defaults to `false`
            loginOptions: {
              // optional, if provided opens login in new window
              autoClose: true, // optional, defaults to `false`
              height: 600, // optional, defaults to 578
              width: 400, // optional, defaults to 433
              top: 0, // optional, defaults to 0
              left: 0, // optional, defaults to 0
            },
            region: instanceRegion, // REQUIRED for `CHAT`, optional otherwise
            softphone: {
              // optional, defaults below apply if not provided
              allowFramedSoftphone: true, // optional, defaults to false
              disableRingtone: false, // optional, defaults to false
            },
            pageOptions: {
              //optional
              enableAudioDeviceSettings: false, //optional, defaults to 'false'
              enablePhoneTypeSettings: true, //optional, defaults to 'true'
            },
            ccpAckTimeout: 60000, //optional, defaults to 3000 (ms)
            ccpSynTimeout: 3000, //optional, defaults to 1000 (ms)
            ccpLoadTimeout: 10000, //optional, defaults to 5000 (ms)
          });
        } catch (err) {
          console.error(logStamp("initCCP"), err);
        }

**Comment by AdithSandeza** [comment]
Hi,

i am facing a issue with the same topic. My login window or tab pops up asking for credentials, when i enter the credentials and authwnticate, the login page freezes. Could you please help me if i am missing some thing. 

This is my issue link:
https://github.com/amazon-connect/amazon-connect-streams/issues/879

Thanks in advance

**Comment by beiyue** [comment]
hi gays, if you use identity center for SAML and then I suggest setting as follows:
1. firstly both of loginUrl and ccpUrl parameters must be set value.
2. ccpUrl parameter must keep on "https://xxx/ccp-v2/"
3. loginUrl parameter must keep on "https://d-xxxxx.awsapps.com/start/#/saml/default/[YOUR NAMED]/ins-xxx" , if you don't know how to get this url,  when you enter username and pwd based on SSO and page will auto redirect to an new link, you must copy rapidly from browser address bar, the copy content is your loginUrl value. 
5. connect instance for original approval need to add your endpoint domain or IP for approval.
If you all done and pop up windows will auto close..

**Comment by bretticus-mc** [comment]
Hello, is this still occurring? We had an issue with an upstream dependency that sounds like it is related to the problem you're describing.

**Comment by bretticus-mc** [comment]
This sounds like it's related to an already resolved issue. Please re-open if this issue is still occurring.
