### ISSUE TITLE
connect.BaseConnection.getEndpoint() does not provide proper details of endpoint

### ISSUE THREAD

**Issue by SanketK-25** [amazon-connect/amazon-connect-streams#876]
I'm adding an additional connections via Quick Connect to the initial Connection, Trying to get the Endpoint details but getting this instead for type AGENT and QUEUE
`{
    "endpointARN": null,
    "endpointId": null,
    "type": "phone_number",
    "name": null,
    "phoneNumber": "INTERNAL-TRANSFER",
    "agentLogin": null,
    "queue": null
}`
For Type phone_numer
`{
    "endpointARN": null,
    "endpointId": null,
    "type": "phone_number",
    "name": null,
    "phoneNumber": "{phoneNumber}",
    "agentLogin": null,
    "queue": null
}`

**Comment by miaowing** [comment]
same problem

**Comment by vs-amzn** [comment]
Has this always been an issue for you? When did this start occurring?

**Comment by SanketK-25** [comment]
Not Sure as I was not using this method initially, Got a use-care last month where I thought this would help.

**Comment by seiyako** [comment]
This seems related to this request. https://github.com/amazon-connect/amazon-connect-streams/issues/258

Currently the information populated in the connection object is limited and it has been this way since beginning. We're tracking this issue in our backlog.
