### ISSUE TITLE
onEnded no disconnectReason provided

### ISSUE THREAD

**Issue by michael-proctor** [amazon-connect/amazon-connect-streams#877]
As per announcement in early 2021 [Amazon Connect now provides disconnect reason for Voice Calls & Tasks](https://aws.amazon.com/about-aws/whats-new/2021/02/amazon-connect-now-provides-disconnect-reason-voice-calls-tasks/)

This is available via the, [CTR](https://docs.aws.amazon.com/connect/latest/adminguide/ctr-data-model.html#ctr-ContactTraceRecord)

However, we still just get a [Contact](https://github.com/amazon-connect/amazon-connect-streams/blob/e3fa961fdd5b339670009557b702b0e7a179380c/src/index.d.ts#L1474) object for [onEnded event](https://github.com/amazon-connect/amazon-connect-streams/blob/e3fa961fdd5b339670009557b702b0e7a179380c/src/index.d.ts#L1533)

Can this please as urgency be expanded to provide the disconnectReason as this is common to understand the cause of the call finalization within our extension.

Is there anyway to we could find this reason within the state? I haven't been able to locate anywhere that stores this state within the API.

**Comment by andywang219** [comment]
Hey,

Could you open a support ticket with us? For these types of issues, we would need additional information such as agent logs, contact ids, etc.
