### ISSUE TITLE
Initialization Failed

### ISSUE THREAD

**Issue by offthewall123** [amazon-connect/amazon-connect-streams#878]
when tried to log into CCP, it displayed Initialization Failed, Try fixing your connection by logging out , and then logging on again. If you need help, contact your administrator.

It happens from time to time and will be fixed after refresh the page.

Why and in what scenario it will happen? Any solution to avoid this error?

**Comment by bretticus-mc** [comment]
We had an issue with a shared worker migration that was resolved. Please re-open if the issue persists.

**Comment by lgb861213** [comment]
> We had an issue with a shared worker migration that was resolved. Please re-open if the issue persists.

Could you describe in detail how you solved it?
