### ISSUE TITLE
Auto Login & Login pop screen freezes with Amazon connect streams

### ISSUE THREAD

**Issue by AdithSandeza** [amazon-connect/amazon-connect-streams#879]
I have developed my own CTI widget using amazon connect streams. 

Inside the initCCP object i have enabled auto login to true and login pop to close after the user authenticates. I tried it with both the methods (pop up window and redirecting to new tab),It pop up’s the credential page, but when i enter my credentials and try to login, the login screen freezes. 

If i refresh the page and login again, i am able to login correctly. 

If enter a wrong crrdential and hit the login, it notifies me that my credentials are wrong.

Why i am not able to login the first time when the tab or window pops up? The page gets frooze which is not the expected behaviour. Please let me know if i am missing some thing. 

Requesting, someone to help me if you have already faced this issue before. 

NOTE: My wiget’s iframe is within a iframe of a CRM tool. In my widget’s iframe attributes should i add any additional attribute? The CRM’s iframe is the parent frame to my widget thus i might not be able to control it.

**Comment by bretticus-mc** [comment]
Hello, is this still occurring? We had an issue with an upstream dependency that sounds like it is related to the problem you're describing.
