### ISSUE TITLE
Having trouble initializing the Streams API in a React app

### ISSUE THREAD

**Issue by becklin-haston** [amazon-connect/amazon-connect-streams#88]
Hello,

So, our organization is creating a custom CCP agent console in React. We're having a great deal of trouble importing the amazon-connect-streams script into our React project. Anyone here have any pointers for how we can continue with our React-powered CCP?

**Comment by jagadeeshaby** [comment]
- Ideal way here is to pull the package directly from NPM to get the benefits of Reacts optimizations (which is currently not available  - it's in our issue pipeline)
 
Few workarounds to try out 
- Loading library from git hub directly - https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly and import it within react. (you may need to configure the alias(https://webpack.js.org/configuration/resolve/) to load this from node modules)
- Loading the scripts dynamically - Ex - https://cleverbeagle.com/blog/articles/tutorial-how-to-load-third-party-scripts-dynamically-in-javascript

**Comment by chengkunkang** [comment]
@jagadeeshaby  any updates for the npm to get this lib?

**Comment by james-work-account** [comment]
Hi @becklin-haston - did you ever find a way to include the Streams API in your React app?

**Comment by james-work-account** [comment]
I found a way to integrate the bot in my React app - see #148. Not sure if it answers this issue but it might help.

**Comment by marcogrcr** [comment]
Now that `amazon-connect-streams` is [now distributed as an `npm` package in `npmjs.com`](https://www.npmjs.com/package/amazon-connect-streams), the following setup with [webpack](https://webpack.js.org/) works for me:

**package.json**

```json
{
  "name": "my-app",
  "version": "1.0.0",
  "scripts": {
    "bundle": "webpack --mode production",
    "server": "webpack-dev-server -w --config webpack.server.config.js"
  },
  "dependencies": {
    "amazon-connect-streams": "1.4.7",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  },
  "devDependencies": {
    "@babel/core": "7.9.6",
    "@babel/preset-env": "7.9.6",
    "@babel/preset-react": "7.9.4",
    "babel-loader": "8.1.0",
    "core-js": "3.6.5",
    "html-webpack-plugin": "4.3.0",
    "regenerator-runtime": "0.13.5",
    "webpack": "4.43.0",
    "webpack-cli": "3.3.11",
    "webpack-dev-server": "3.10.3"
  }
}
```

**.babelrc**

```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "corejs": { "version": 3 }
      }
    ],
    "@babel/preset-react"
  ]
}
```

**webpack.config.js**

```js
const path = require("path");

module.exports = {
  entry: "./src/index.jsx",
  module: {
    rules: [{ test: /\.jsx?$/, use: "babel-loader" }]
  },
  output: {
    filename: "app.js",
    path: path.resolve("dist")
  }
};
```

**webpack.server.config.js**

```js
const HtmlWebpackPlugin = require("html-webpack-plugin");

const config = require("./webpack.config");

module.exports = {
  ...config,
  devServer: {
    disableHostCheck: true,
    host: "0.0.0.0",
    https: true,
    overlay: true,
    port: 8000
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: "./src/index.html"
    })
  ]
};
```

**src/index.jsx**

```jsx
import "amazon-connect-streams";

import React, { useEffect } from "react";
import { render } from "react-dom";

const CCP_URL = "https://<instance>.awsapps.com/connect/ccp-v2";
const LOGIN_URL = "https://<your-saml-login-url>";
const REGION = "<your-region>"; // e.g. us-west-2

function App() {
  useEffect(() => {
    const container = document.getElementById("ccp");
    connect.core.initCCP(container, {
      ccpUrl: CCP_URL,
      loginUrl: LOGIN_URL,
      loginPopup: true,
      loginPopupAutoClose: true,
      region: REGION,
      softphone: {
        allowFramedSoftphone: true
      }
    });
  }, []);

  return <div id="ccp" style={{ width: "320px", height: "500px" }}></div>;
}

render(<App />, document.getElementById("app"));
```

**src/index.html**

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>My App</title>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>
```
