### ISSUE TITLE
[High Sev] Breaking Issue with Streams v2.14.2 and initApp()

### ISSUE THREAD

**Issue by taylanu** [amazon-connect/amazon-connect-streams#885]
## Description:
The `hasAnySearchParameter` function in `amazon-connect-streams/src/agent-app/agent-app.js` is currently assigned without being declared, which causes a `ReferenceError` in certain environments. To fix this issue, we should declare the variable before assigning the function to it.

### Current Code:
https://github.com/amazon-connect/amazon-connect-streams/blob/8e20f4fa6fab9dfbcbe7a5dc5f562f4cd866b6fa/src/agent-app/agent-app.js#L146-L149

```js
hasAnySearchParameter = function (url) {
  var regex = /[?&]?[^=?&]+=[^=?&]+/g;
  return regex.test(url);
}
```

### Updated Code

```js
var hasAnySearchParameter = function (url) {
  var regex = /[?&]?[^=?&]+=[^=?&]+/g;
  return regex.test(url);
}
```

### Explanation:
Declaring the variable `hasAnySearchParameter` using the `var` keyword before assigning the function to it will prevent the `ReferenceError` and ensure the code works as expected in all environments.

### Solution:
Refer to Pull 

**Testing Environment**
Operating System: Mac OS v14.5
NodeJS Version: 18.20.2 (LTS)
Package Manager: NPM

**Comment by andywang219** [comment]
Released version 2.14.3 which contains the fix!

Thank you!
