### ISSUE TITLE
Agent defaultOutboundNumber

### ISSUE THREAD

**Issue by prosunshining** [amazon-connect/amazon-connect-streams#89]
I tried to get defaultOutboundNumber with connect stream api, but it doesn't seem possible.
From the source of ccp inspected, I see this code

var ccp = angular.module("ccp", ["ccpModule", "phoneNumberModule"]);
....
ccp.constant("defaultOutboundNumber", "+1xxxxxxxxxx");

Does connect stream api support any like to get default outbound number of agent?

**Comment by RathoreKavita** [comment]
We currently don't support this feature. Please check our documentation, which will have announcements as we make updates.

**Comment by seiyako** [comment]
If you want to get the phone number of the agent's defaultOutboundQueue, please use `agent.getRoutingProfile()` and `agent.getEndpoints()`.

```
const agent = new connect.Agent();
const defaultOutboundQueueARN = agent.getRoutingProfile().defaultOutboundQueue.queueARN;
let defaultOutboundPhoneNumber;
agent.getEndpoints([defaultOutboundQueueARN], {
  success: (data) => {
    defaultOutboundPhoneNumber = data.endpoints[0].phoneNumber;
  }
});
```

Hope this helps.
