### ISSUE TITLE
The Amazon Custom CCP is losing audio.

### ISSUE THREAD

**Issue by dblkbox42** [amazon-connect/amazon-connect-streams#891]
During the calls the customer is no longer able to hear the agent after a short period on the call, Nor can the rep hears the customer, but when listening to the recording I can still hear the customer saying Hello Hello, but I can't hear the rep.  Is anybody else having the same or similar issue.

**Comment by oharez** [comment]
Have you reviewed the agents client logs? Anything notable for disconnect reason in trace record? Does the agent go into error status? I have had numerous agent audio issues- they pretty much are always config or hardware config issues on the agent side. If your agent is working from home, some ISP's for whatever reason have caused issues with connectivity - You should be able to see this in some form of RTC errors in the logs as well. If the logs are perfect, and there's still an audio stream being sent from the agent during those times, and the agent isn't muted then you can start looking for hardware issues, or a config problem, like trying to run two tabs in a browser that need microphone, some mic security setting, power saving setting. If it's a bluetooth device, have them use a wired mic for a bit to ensure there's no issue there.

**Comment by dblkbox42** [comment]
Thank you.  

    On Tuesday, June 25, 2024 at 11:12:02 AM CDT, oharez ***@***.***> wrote:  
 
 


Have you reviewed the agents client logs? Anything notable for disconnect reason in trace record? Does the agent go into error status? I have had numerous agent audio issues- they pretty much are always config or hardware config issues on the agent side. If your agent is working from home, some ISP's for whatever reason have caused issues with connectivity - You should be able to see this in some form of RTC errors in the logs as well. If the logs are perfect, and there's still an audio stream being sent from the agent during those times, and the agent isn't muted then you can start looking for hardware issues, or a config problem, like trying to run two tabs in a browser that need microphone, some mic security setting, power saving setting. If it's a bluetooth device, have them use a wired mic for a bit to ensure there's no issue there.

**Comment by bretticus-mc** [comment]
+1 to oharez. This sounds like a hardware issue. Please re-open if the issue persists

**Comment by dblkbox42** [comment]
Bretticus-MC
Besides the headset, What hardware can attribute to mulitple reps losing audio during their calls ?

**Comment by bretticus-mc** [comment]
If multiple agents then probably not. Are you using the [connect-rtc-js](https://github.com/aws/connect-rtc-js) library? How consistently does this happen? Is there any pattern for when this happens (like peak times)? Have you ran the [Connect Endpoint utility test](https://tools.connect.aws/endpoint-test/)?

**Comment by bretticus-mc** [comment]
Please open a ticket [here](https://aws.amazon.com/contact-us/?nc2=h_header). We'll need HAR files and CCP logs to troubleshoot furhter.
