### ISSUE TITLE
Authentication issue within Amazon Connect as third party app

### ISSUE THREAD

**Issue by MHamza8070** [amazon-connect/amazon-connect-streams#896]
I am facing issue in authentication of Amazon Connect within custom ccp, If open custom ccp in a third party app in Amazon Connect. If application is being opened in a browser directly, it works fine but if opens as 3p app in agent workspace, it gives error and login popup  stuck. What is the possible way to overcome this?

 
<img width="768" alt="Untitled" src="https://github.com/amazon-connect/amazon-connect-streams/assets/93217480/01b8fe0a-ed4e-43ed-b613-4f94d907af47">

**Comment by bretticus-mc** [comment]
Looks like missing sandbox attributes. Just to confirm my understanding, you're trying to open custom ccp in Connect's Agent Workspace that is <instance URL>/agent-app-v2?

**Comment by MHamza8070** [comment]
@bretticus-mc  Yes, I want to open the custom ccp in Connect's Agent workspace.

**Comment by bretticus-mc** [comment]
I see. Open a support ticket and we can route it to the Agent Workspace team.

https://aws.amazon.com/contact-us/?nc2=h_header

**Comment by arikrayi** [comment]
Hi @MHamza8070, just curious, have you ever resolved your issue? because i'm facing the same issue.

**Comment by MHamza8070** [comment]
Hi @arikrayi  Streams not supported in Third Party apps yet. You can use only available Agent Workspace SDK methods in 3P Apps.
