### ISSUE TITLE
I am getting the below error while compiling the application with Webpack

### ISSUE THREAD

**Issue by ammmarr** [amazon-connect/amazon-connect-streams#899]
I am getting the below error while compiling the application with Webpack
 
ERROR in ./node_modules/amazon-connect-streams/release/connect-streams.js 108:32
Module parse failed: Unexpected token (108:32)
You may need an appropriate loader to handle this file type.
|     }
|     const iframeIdSelector = `iframe[id='${appName}']`;
>     const iframe = containerDOM?.querySelector(iframeIdSelector) ||
|       document.getElementById(appName) ||
|       window.top.document.getElementById(appName);
 @ ./app/Dashboard/Dashboard.js 14:0-32
 @ ./app/Dashboard/index.js
 @ ./app/routes/asyncLoad.js
 @ ./app/routes/routes.js
 @ ./app/routes/index.js
 @ ./app/components/App/App.js
 @ ./app/components/App/index.js
 @ ./app/app.js
 @ multi ./node_modules/react-app-polyfill/ie11.js webpack-hot-middleware/client?reload=true ./app/app.js

_Originally posted by @SukheshEV in https://github.com/amazon-connect/amazon-connect-streams/issues/644#issuecomment-2199324033_

**Comment by beallc** [comment]
Can you please provide more information about your configuration or possibly a sample application that recreates the issue?

**Comment by seiyako** [comment]
What version of StreamsJS do you use? The version you're trying to compile with your app might not have the babel transpilation enabled yet thus the new JS syntax `?.` remains not transformed so your compilation failed. Can you try a newer version of StreamsJS?

**Comment by andywang219** [comment]
hello, we've enabled file transpilation to the latest streams release. Please see https://github.com/amazon-connect/amazon-connect-streams/releases/tag/v2.15.0
