### ISSUE TITLE
Manual log out does not trigger TERMINATED event

### ISSUE THREAD

**Issue by ajspetner** [amazon-connect/amazon-connect-streams#907]
When manually triggering logout [per the documentation](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#logging-out) as such:
```
fetch("https://<your-instance-domain>/connect/logout", { credentials: 'include', mode: 'no-cors'})
  .then(() => {
    const eventBus = connect.core.getEventBus();
    eventBus.trigger(connect.EventType.TERMINATE);
  });
```
The `TERMINATED` event is never triggered, contrary to the documentation.

**Comment by ajspetner** [comment]
@seiyako shouldn't this be labeled as a bug, since it is not working as per the documentation?

**Comment by hngan** [comment]
Yes, this is a known bug that we'll be fixing as part of introducing a new set of logout/login helper APIs. In the meantime, you can do a hack and replace `eventBus.trigger(connect.EventType.TERMINATE);` with `connect.core.getUpstream().sendUpstream(connect.EventType.TERMINATE)`. This will work as a temporary workaround, but I can't guarantee that this to be a permanent solution.

**Comment by alexgurr** [comment]
I don't believe this has been fixed, can we reopen this?
