### ISSUE TITLE
contact.toSnapshot().contactData.initiationMethod is null for Monitor and Barge-In scenario

### ISSUE THREAD

**Issue by richardwadsworth** [amazon-connect/amazon-connect-streams#910]
Hi

The contactData.initiationMethod attribute returned by contact.toSnapshot() while in the contact.onRefresh() event is always null in Monitor or Barge-in status.

The connection[type='agent'].monitorStatus correctly shows "SILENT_MONITOR" or "BARGE" in these states.  But initiationMethod is null.  I would expect initiationMethod to be aligned to https://docs.aws.amazon.com/connect/latest/adminguide/contact-events.html

thanks

**Comment by tannera926** [comment]
Thanks for bringing this to our attention, I'll bring this up with our partner teams. In the meantime, to determine if a connection is in monitor or barge status, I would recommend using the [isBarge](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#voiceconnectionisbarge) API and the [isSilentMonitor](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#voiceconnectionissilentmonitor) API.
