### ISSUE TITLE
 Agent mute button is stuck and wrongly showing unmute agent when agent is in a conference and silently monitored by a supervisor (duplicate of autoclosed #865)

### ISSUE THREAD

**Issue by Studodge** [amazon-connect/amazon-connect-streams#911]
This is a duplicate of https://github.com/amazon-connect/amazon-connect-streams/issues/865 (that was autoclosed at similar time that an update to the ticket had been promised -- ie July 31). Not sure how to "reopen" existing ticket -- so best option I could find was to duplicate the closed ticket. Please close this ticket if the original ticket can be re-opened.
----
When an agent is in conference and a supervisor starts silently monitoring the conference, the agent mute button is stuck and can't be toggled and even that it's showing the agent as unmuted, it's muted and can't be heard by any other participants.

Trying to toggle the button will return a success action but it's not doing anything. 
----
See https://github.com/amazon-connect/amazon-connect-streams/issues/865 for details orf original ticket

**Comment by andywang219** [comment]
Hi,

Could you provide steps on how to reproduce the issue and the mute status through the process? Is the agent muted prior to the manager / supervisor silently monitoring?

I ran a quick test where the agent was `unmuted` prior to the monitoring. When the supervisor monitors, the agent can still be heard and is still able to mute / umute.

**Comment by Studodge** [comment]
Apologies - this was confused between mute and hold issues. An internal ticket has been opened with Amazon to investigate the hold issue. Closing this ticket.
