### ISSUE TITLE
ability to remove callbacks that are no longer needed

### ISSUE THREAD

**Issue by mfulton26** [amazon-connect/amazon-connect-streams#915]
I need a way to remove callbacks registered with `connect.agent()`, `connect.contact()`, and any other callback based "subscriptions".

**Comment by bretticus-mc** [comment]
When you register a callback an event subscription object is returned. You can call unsubscribe() on the object to remove the callback. 

Example:
```
const eventSubscription = connect.contact(function(contact) {
    const contactId = contact.getContactId();

    console.log("New contact received with ContactId:", contactId);
});

eventSubscription.unsubscribe();
```

**Comment by mfulton26** [comment]
Oh, that is so nice @bretticus-mc! The TypeScript types state that `connect.contact()` is a `void` method. Can this be updated? My guess is there a good number of methods that support unsubscribing, but such isn't discoverable via the TypeScript types.

https://github.com/amazon-connect/amazon-connect-streams/blob/073ac34c49f06edf1220ec03fc2353777ac8d0ce/src/index.d.ts#L84

P.S. I cannot re-open this issue. I suspect I lack permissions to do so.
