### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by mfulton26** [amazon-connect/amazon-connect-streams#918]
Return type on `connect.contact()` and other subscribe methods is `void` instead of an object with an `unsubscribe()` method.

https://github.com/amazon-connect/amazon-connect-streams/blob/073ac34c49f06edf1220ec03fc2353777ac8d0ce/src/index.d.ts#L84

_Originally posted by @mfulton26 in https://github.com/amazon-connect/amazon-connect-streams/issues/915#issuecomment-2299210403_

**Comment by sandeep0009** [comment]
may you assign this to me i would like to work upon this
