### ISSUE TITLE
How to get the user logged in information using streams API

### ISSUE THREAD

**Issue by jahnavi310** [amazon-connect/amazon-connect-streams#920]
We are using a custom CCP in an iframe and have successfully setup SSO authentication via okta defining the relay state as our current web app - this works fine.

What we need is to know who is the current logged in user, right now the only way we can think of is reading the username of from the iframe, we are not able to decode the cookie since its a federated token and not a jwt token.

Does the stream API have any way of achieving this?

Thanks in advance

**Comment by L4MI4** [comment]
I believe that is handled via the agent.getConfiguration() method, you could attach it to any event handler, most preferably on agent init. You get both the name and username.

**Comment by tannera926** [comment]
Correct, [agent.getConfiguration()](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#agentgetconfiguration) returns the agent's name, username, and arn, as well as other details.
