### ISSUE TITLE
slack workflow is failing

### ISSUE THREAD

**Issue by mfulton26** [amazon-connect/amazon-connect-streams#925]
Whenever I report an issue or comment on an issue, I get notified about a failed slack workflow run.

https://github.com/amazon-connect/amazon-connect-streams/actions/workflows/slack.yml

If this workflow isn't needed anymore then can it be disabled/removed? (As I suspect it wasn't every working.) If not, can the errors be silenced, or the issue be fixed?

https://github.com/amazon-connect/amazon-connect-streams/blob/b8f213e6cde76cd1d57da07fec1b7f6804ca05be/.github/workflows/slack.yml#L27C30-L27C43

A fix might be fairly straight forward:

```patch
diff --git a/.github/workflows/slack.yml b/.github/workflows/slack.yml
index 3e02100..c764fb3 100644
--- a/.github/workflows/slack.yml
+++ b/.github/workflows/slack.yml
@@ -24,7 +24,7 @@ jobs:
       with:
         payload: |
           {
-            "issueUrl" : ${{ github.event.issue.issue_url }}
+            "issueUrl" : ${{ github.event.issue.url }}
           }
       env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

```

**Comment by vpogudina** [comment]
I've updated issue.issue_url to issue.url, thanks for pointing it out

**Comment by mfulton26** [comment]
> I've updated issue.issue_url to issue.url, thanks for pointing it out

It looks like run also failed. I think it is because the URL is not quoted so it isn't valid JSON.

**Comment by vpogudina** [comment]
Oh :( I've deleted the workflow since it seems it was never working properly.
