### ISSUE TITLE
Promise return types

### ISSUE THREAD

**Issue by mfulton26** [amazon-connect/amazon-connect-streams#926]
From what I can tell, all of the functions that receive callbacks of type `SuccessFailOptions` are all `void` returning functions. I'd much rather have these functions return `Promise`s (especially if not callbacks are passed in). Can this be supported?

https://github.com/amazon-connect/amazon-connect-streams/blob/b8f213e6cde76cd1d57da07fec1b7f6804ca05be/src/index.d.ts#L953

**Comment by tannera926** [comment]
This can't be supported currently. If you would like to submit a feature request, you can submit one to AWS support [here](https://aws.amazon.com/contact-us/?nc2=h_header).
