### ISSUE TITLE
log levels not working

### ISSUE THREAD

**Issue by mfulton26** [amazon-connect/amazon-connect-streams#929]
Even with the following code I still get undesired logs (e.g. INFO, LOG, etc.):

```js
const logger = connect.getLog();
logger.setLogLevel(connect.LogLevel.CRITICAL);
logger.setEchoLevel(connect.LogLevel.CRITICAL);
```

**Comment by tannera926** [comment]
This is a known issue, unfortunately setting the log level doesn't work. We have a backlog task to fix this.

**Comment by mfulton26** [comment]
@tannera926 is this a task/issue I can follow on GitHub to track progress or is it in a private issue tracking system? If not public, can we leave this one open until it is fixed?

**Comment by tannera926** [comment]
This isn't a task you can follow on Github. If you would like it to be prioritized, you can submit a feature request to support [here](https://aws.amazon.com/contact-us/?nc2=h_header).
