### ISSUE TITLE
How can I transfer to a quick connect when a call is rejected?

### ISSUE THREAD

**Issue by akhil-sq** [amazon-connect/amazon-connect-streams#940]
I am trying to build a flow where if an agent is rejecting the call, the call gets to their voicemail. There is only one agent in the queue and we don't want the same call to ring to them. 

I was not able to figure out how to send the call to voicemail but I thought if I can sent the call to a quick connect, I can link the quick connect to go to their voicemail.

Currently, I am unable to even figure out how to send the missed call or rejected call to a quick connect. Can someone help?

**Comment by hngan** [comment]
This isn't something that Streams can support. An agent cannot transfer a rejected contact through quick connect.

**Comment by akhil-sq** [comment]
Do you any recommendations on what can be done? Essentially I want a rejected call to go to voicemail instead of ringing them again.
