### ISSUE TITLE
`onLocalMediaStreamCreated` Type not found error. ^v1.5

### ISSUE THREAD

**Issue by peter-wd-1** [amazon-connect/amazon-connect-streams#941]
Please check `onLocalMediaStreamCreated` function type definition in  `@types/amazon-connect-streams": "^1.4.12`. 
I've checked that that 1.5v package has this function in compiled file but type does not.
My package installed:   "amazon-connect-streams": "^2.15.0",

**Comment by hngan** [comment]
Thank you for the call out. We'll add it back on the next Streams release.
